### ISSUE TITLE
Cannot start alpine:latest official container (error 500)

### ISSUE THREAD

**Issue by zahari** [kitematic/kitematic#1001]
alpine:latest

Windows 7 Professional SP1 64bit
Docker Toolbox 1.8.1b

Container does not finish downloading.
Screenshot: http://imgur.com/2wCFfZ9

**Comment by FrenchBen** [comment]
@zahari Do you have a link to the image you used?
If you look at the screenshot, it's not a problem with the container not finishing the download, but rather that the image you used has no  'default' commands associated with it. 

A command is usually passed to the container during creation which would indicate what the container needs to run.

**Comment by mchiang0610** [comment]
Merging with #1030

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (113/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:52026 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYAw-004LKq-2o
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:56:15 -0500
Date: Fri, 11 Sep 2015 16:56:17 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442015777;
	bh=IZOUAOfClIXkCxkHz2X3jMExSTPTcahz6R/YyRiNJeE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=wS3+S3T/ZYxeXCra3wxhyytsM+a02iLc9ip2IJwuj4mH9RHY4DhifPO7UJh34VRe7
	 pJdBQf/54tCIxX7X2odf0kSiWuFhkJJ0RS/nYVN9uv4OPM8CmH8IwZRhaBLn58mRMU
	 39qDY7RdC+CX8omJ+BeqN6EygTRQAcvn63J39u9U=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (114/100 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:51172 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYAw-004LKN-0W
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:56:15 -0500
Date: Fri, 11 Sep 2015 16:56:17 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442015777;
	bh=60DNKSPo2kB6jFE3nf7H+on+3zwIH2iLTmI6HPiHD5o=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ErIzbTU1arYt25xv+jeaeNXvAmCrkRDra7Ya0cN3VHGW+JAPNDvRRmUZBXegIm36U
	 PZqiwJuJBU3EUJ3BYju/OVrXxi72SiOvVCTLWwDj/dc+OFOYrg6ujQA9JBKWHQzVnT
	 1HQKj23kxL25uvWyDoxHMq9sorHKXs/qWbxaCmyc=
