### ISSUE TITLE
Network timedd out while trying to connect to GitHub

### ISSUE THREAD

**Issue by sputnik62** [kitematic/kitematic#1003]
I am on a very fast internet connection yet I get messages about network timeouts with DockerHub very frequently

**Comment by FrenchBen** [comment]
@sputnik62 Could it be some VM DHCP issues? Can you check the connectivity within the VM?
Can you create a gist of your VM logs? `~/.docker/machine/machines/default/default/Logs/VBox.log`

**Comment by mchiang0610** [comment]
@sputnik62 Thanks for this. I will pass this onto the Docker Hub team. 

Closing this because it's not a bug with Kitematic but rather a Hub bug.
