### ISSUE TITLE
Account is not Active

### ISSUE THREAD

**Issue by qianyiliushang** [kitematic/kitematic#1007]
when I install mysql from kinematic, it reports the error 
```
Error: Status 403 trying to pull repository library/mysql: "Account is not Active"
```

I wonder which account used here

**Comment by FrenchBen** [comment]
The account should be specified in the top left corner of the Kitematic app - There's a good chance you logged into the Hub for which you need to activate the account.

**Comment by mchiang0610** [comment]
@qianyiliushang Can you try to log out and log in again? Thanks! 

The problem should be fixed after. If not please reopen this issue. Thanks!

**Comment by qianyiliushang** [comment]
Now I cannot login hub via kitematic on my 2 macbooks(I can sign in hub with web site) it seems that I only successfully sign in after kitematic installed.

**Comment by mchiang0610** [comment]
@qianyiliushang It seems like you have not activated your Docker Hub account through the sign up email yet. 

Please try to log in again from hub.docker.com  

If you are still having trouble, please contact support@docker.com. They will help you with any Hub issues. 

Thank you!
