### ISSUE TITLE
ENOENT for ca.pem

### ISSUE THREAD

**Issue by mieciu** [kitematic/kitematic#1008]
Hi!

I was really enjoying Kitematic up to first problems with reaching the machine (after OS X reboot). I've decided to set up machine once again:

This is what I get now when firing up Kitematic
```
ENOENT: no such file or directory, open '/Users/<redacted>/.docker/machine/machines/default/ca.pem'
```
![kitematic](https://cloud.githubusercontent.com/assets/2097938/9683765/5f48916a-5313-11e5-9e27-4ec3be01f53e.png)

Indeed, there is no such file even if `<redacted>` stands for my username.
```
$ ls ~/.docker/machine/machines/default/
boot2docker.iso  config.json      default/         disk.vmdk        id_rsa           id_rsa.pub
```
 
Could you please tell me how could I get it back working?

**Comment by mieciu** [comment]
unfortunately VM deletion did not help

**Comment by FrenchBen** [comment]
What about under the machine certs:
`$ ls ~/.docker/machine/certs/`

Do you have a properly created certificate? If yes, you can re-generate the certificates for your VM via:
`docker-machine -D regenerate-certs default`

**Comment by mieciu** [comment]
Hi there, thanks a lot for a fast response!!

Unfortunately I wasn't patient enough and had my VirtualBox reinstalled, which solved my issue. If I manage to reproduce that behaviour, I'll definitely try  regenerating certs via `docker-machine`..

Let me close this issue for now :smile:

**Comment by FrenchBen** [comment]
@mieciu Glad you were able to solve it :+1:  - Sometimes re-creating the VM is easier than the above if the VM was brand new.

**Comment by joychugh** [comment]
@FrenchBen that worked :+1:

**Comment by benfavre** [comment]
@FrenchBen that worked :+1:

**Comment by jaycenca** [comment]
@FrenchBen Thanks，it worked.

**Comment by pradeepkumart** [comment]
Thanks , it worked
