### ISSUE TITLE
Cannot install Container

### ISSUE THREAD

**Issue by roolo** [kitematic/kitematic#1009]
Tag latest not found in repository docker.io/nacyot/javascript-node.js

**Comment by FrenchBen** [comment]
That's the correct behavior - If you look at the repository for that user on [Docker Hub](https://hub.docker.com/r/nacyot/javascript-node.js/tags/) you'll see that it doesn't have a 'latest' tag, but only a '0.10.29' tag

**Comment by roolo** [comment]
I don't think it is a good behavior. Why the application wants to install stuff which is not there.

I don't know how does it work under the hood

Scenarios

1. Kitematic does rely on *latest* tag. Why do I see repository which doesn't have it.

2. Owner of repo does define what is the installation place in history. How can owner define non-existent place in history.

**Comment by FrenchBen** [comment]
There was some early work to propose an alternate tag when 'latest' isn't available, but it's pretty slow. 
Kitematic uses `docker pull` behind the scene, which also fails if you don't specify the proper tag. 

Before clicking the 'create' button, you can click within Kitematic on the 3 circles 'ooo' and select the active tag that will be used to create the container.

**Comment by mchiang0610** [comment]
Merging with #572

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (104/100 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:47283 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaY6e-0048oi-HJ
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:51:49 -0500
Date: Fri, 11 Sep 2015 16:51:51 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442015511;
	bh=MgmaRZUhC8hDeTkZ/+rjFYT1Flm+qBh9l+rqoZbnnZU=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=E83Sx++u/fRq/GIHf+FCxFrYNjesDc65KFPQ0zpzMb5z6srUMafZr1+T2zJ1NIGr9
	 f0vY3XQuvMEBQDQqzLXmOsFbXbPvOfyVac5y3FxCKNYYbr1UxAsB5PesxZxk3l53P5
	 43DOIWIfzOaStZ3wGQ2euFTHjiGLX/jayqXdPxwY=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (105/100 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:32647)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaY6f-0048qi-WA
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:51:51 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=LDtxNb7HzcnEoldIer7rVOKpN9M=; b=Dz09h+Bhoaaj+HDb
	2z4Ks9A439sZIkcKfXCtKYZ/LavIw39jsUbGZMbKNqIy5gh6NQB/luS855UEyQsH
	uDQLvDM/0pv35q/Ey/RyklcDjro0jX/ZK5eBpX/fZsLXH26I4Fmf6BXLKLimRxFX
	0IopmlnXrPWkNEVYzhAQdhUl0fA=
Received: by filter0668p1mdw1.sendgrid.net with SMTP id filter0668p1mdw1.25860.55F369188
        2015-09-11 23:51:52.186292025 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id JWW75mnJT82X52YJhxLaFA
	for <greg@biomassiv.es>; Fri, 11 Sep 2015 23:51:52.342 +0000 (UTC)
Date: Fri, 11 Sep 2015 16:51:52 -0700
