### ISSUE TITLE
Unable to download images

### ISSUE THREAD

**Issue by mononokehime** [kitematic/kitematic#1011]
Hi there

I'm unable to download the following either through command line or kitematic.

Kitematic shows this error for sonatype/nexus:oss:
Error pulling image (latest) from docker.io/sebmartin/nexus, Untar re-exec error: write /mnt/sda1/var/lib/docker/graph/_tmp/c49263d2b77338690d2b4316ae992265992f1508ddf75d60ada2d9dda1f1e8a9/tar-data.json.gz: no space left on device: output:
(eom)
For larrycai/docker-openldap both command line and kitematic just hang at around 26%. I'm on OSX Yosemite and jsut installed kitematic.

**Comment by mononokehime** [comment]
Oh and I have plenty of space left on the drive

**Comment by mchiang0610** [comment]
@mononokehime Are you able to pull other images? If so, it could be a problem with that particular image. 

Let me know and we can help you from there.

**Comment by mchiang0610** [comment]
@mononokehime seems like a problem with that particular image. Closing for now. Feel free to reopen any time!

**Comment by mononokehime** [comment]
I'm sorry not to have replied. I never really solved the issue but it did go away. I think it was an unclean shutdown of kitematic or docker. I rebooted and everything was ok

All the best
Fergus 



On 11 Sep 2015, at 16:46, Michael Chiang <notifications@github.com> wrote:

@mononokehime seems like a problem with that particular image. Closing for now. Feel free to reopen any time!

―
