### ISSUE TITLE
When searching for an exact image name, it should be showed first

### ISSUE THREAD

**Issue by jpetazzo** [kitematic/kitematic#1012]
If I enter an exact image name, I think it should be displayed first in the search results.

See screenshot below:

![screen shot 2015-09-05 at 5 06 07 pm](https://cloud.githubusercontent.com/assets/171481/9701773/b32d7eb6-53f0-11e5-95f0-4c9039a366f8.png)

**Comment by FrenchBen** [comment]
Kitematic displays a similar search result as seen on the following page (not sure of the order preference):
https://hub.docker.com/search/?q=ipython%2Fnotebook&page=1&isAutomated=0&isOfficial=0&pullCount=0&starCount=0

**Comment by jpetazzo** [comment]
Duh, indeed. Do you think I should nag upstream?

**Comment by FrenchBen** [comment]
I'll probably add a similar 'sort' filter, which should help bump up a container with high star rating/download/etc.

I know the search is still being worked on, so it's probably being tweaked all the time.

**Comment by mchiang0610** [comment]
@jpetazzo Yes, Kitematic gives back whatever we are given through search of Hub. 

Closing this for now but will notify the Hub team. 

Thanks,
Michael
