### ISSUE TITLE
Make "access url" clickable in the container overview (pretty please!)

### ISSUE THREAD

**Issue by jpetazzo** [kitematic/kitematic#1013]
When going to the "ports" panel for a container, the mapped ports are clickable (and the default browser is used to open the link).

Could it also be the case for the default view? (The one shown below)

Thanks! <3

![screen shot 2015-09-05 at 5 12 14 pm](https://cloud.githubusercontent.com/assets/171481/9701780/4aba5eac-53f1-11e5-893f-099e15f49bf4.png)

**Comment by FrenchBen** [comment]
#feature - Add URL link to Home tab access url

#dibbs

**Comment by FrenchBen** [comment]
PR #1018 should fix this - As a side note it seems this container uses HTTPS, which isn't something that can be easily detected by Kitematic. 
You will still have to add https in front of the link once it's open and add an exception for a locally created cert.

**Comment by jpetazzo** [comment]
Nice, thanks! Yeah, I noticed about the HTTPS thing afterwards; but in that specific case I ended up passing the right env vars to disable HTTPS (since I didn't see the point of getting obnoxious warnings from my browser when connecting over an internal connection :-))

Thanks again!

**Comment by FrenchBen** [comment]
No problem :) - It was merged earlier by the team, which means it'll be part of the next release.

**Comment by mchiang0610** [comment]
Closing because it's merged.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (102/100 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:47644)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaY5h-0045x1-TO
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:50:51 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=LBPUbcx5EZjBMF/Bw3k+xyzVGjY=; b=CjfWfL6nQt+hK8FS
	82+Rqs6R0SerSvgGF86CJvZ8bGl4fRZTXNz0I7jolFEx3UsTQgCPw9RYmdUU0mrc
	yLlLc99JnS6D3Bfk7hFiNNBhbruGqsSV20IswhxprxqvDb0WKkQT2T+lOO35UkH/
	JLBvrhQ4odYGoQ2b0PE7e+71uNw=
Received: by filter0870p1mdw1.sendgrid.net with SMTP id filter0870p1mdw1.4880.55F368DB1E
        2015-09-11 23:50:51.348464941 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id hf8qLO2xQA-sDT09NcI_cQ
	for <greg@biomassiv.es>; Fri, 11 Sep 2015 23:50:51.517 +0000 (UTC)
Date: Fri, 11 Sep 2015 16:50:51 -0700

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (102/100 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:53240)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaY5h-0045x5-Q0
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:50:51 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=BvJh7IofbeVTLxdZfr2RwILE7VE=; b=ZXBjjX+HV+u5fHsc
	OUyTNCC2WTiNvKNqPX0fvo3JIEVbkLHj4mbBNG2ihkWoae8REDhM1BKdttWvAr/V
	Wuv9BcLWSkZ5G4UW+aSlMskQVWEoVwcNOLpHb3aHzyA0kOV/Ys3gXq66PiF5XUHI
	INRbwU9mOlcOatbhK4tqV9iYmtc=
Received: by filter0641p1mdw1.sendgrid.net with SMTP id filter0641p1mdw1.4625.55F368DB1E
        2015-09-11 23:50:51.830799961 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id -EgbhymIRluci_-XSoI7ow
	for <greg@biomassiv.es>; Fri, 11 Sep 2015 23:50:51.962 +0000 (UTC)
Date: Fri, 11 Sep 2015 16:50:51 -0700
