### ISSUE TITLE
Chinese User download image is so slow

### ISSUE THREAD

**Issue by hongdanyang1991** [kitematic/kitematic#1017]
It is so slow for Chinese Users to download docker images!

**Comment by FrenchBen** [comment]
@hongdanyang1991 What's your overall download speed? There shouldn't be any latency, unless you're behind a very specific network setup?

**Comment by 66beta** [comment]
Me too, **China Telecom** (Shanghai), **China Unicom** is better

Its network problem, not softerware's.

VPN 走起！

**Comment by mchiang0610** [comment]
@hongdanyang1991 @66beta Thanks for the feedback. Unfortunately we cannot fix network speed problems. 

Closing this for now. 

Thanks,
Michael

**Comment by Giszmo** [comment]
I'm not sure this is only a Chinese issue. Since half an hour I'm watching this, trying to download some 100MB. Here in Chile with my current ISP I download well seeded torrents at 8MB/s.:

````
Unable to find image 'gitlab/gitlab-runner:latest' locally
latest: Pulling from gitlab/gitlab-runner
````

On my server in Germany it also went lightning fast.
