### ISSUE TITLE
Image not found error

### ISSUE THREAD

**Issue by larsenmeta** [kitematic/kitematic#1019]
When attempting to create a new container from a private repo on docker hub I receive:

Error: image user/image:latest not found

The image is listed in the repository view in kitematic, 
and "docker pull user/image:latest" executes without error when run via the cli, so the image exists.

kitematic has been logged in and docker login has been successfully executed.

OSX 10.10.4

**Comment by FrenchBen** [comment]
The error is usually linked to the missing 'latest' tag, but if you were able to pull it via the CLI then it should work as expected.

Without having access to the image to replicate the issue it will be pretty difficult for me to replicate. Are you experiencing the same issue with public images?

Also can you take a screenshot of your Kitematic > About page?

**Comment by larsenmeta** [comment]
Thanks for the prompt response.  

Public images are working fine, it seems to only be private ones that generate this situation.  Unfortunately, I can't share the private images due to my NDA.  I'm not really sure how to help you replicate the issue.

I have easily been able to pull and run the image from the CLI (with and without the :latest tag), so I don't really need a solution.  I just wanted to let someone know I've received an error that didn't seem right.

Here is the "about" screenshot
![screenshot 2015-09-08 14 21 39](https://cloud.githubusercontent.com/assets/13213146/9747941/e9a838f4-5635-11e5-83af-6db28dc5e6a8.png)

Please let me know if there's any other info I can provide to help troubleshoot/debug.

**Comment by FrenchBen** [comment]
I'll do some qa on my end with private repo and see if I can replicate. For now we can probably tag it as a #bug

**Comment by mchiang0610** [comment]
Seems like the same problem as #1024. Closing to merge the issue
