### ISSUE TITLE
Kitematic Error while pulling Rails

### ISSUE THREAD

**Issue by aerodame** [kitematic/kitematic#1021]
Error pulling image (latest) from docker.io/library/rails, Driver aufs failed to create image rootfs 4a5e6db8c0693a16de88b7559ded7c1cb804018571b137e13abb1713ce6a71cf: open /mnt/sda1/var/lib/docker/aufs/layers/2c49f83e0b13f73bf3d276c9fe26ba9aa94d2a1614e866642b95cb0245d0cdab: no such file or directory

**Comment by mchiang0610** [comment]
@aerodame Seems like it's a problem with pulling 2 images at once. Please try again, and it should work. 

Thanks!
