### ISSUE TITLE
Kitematic seems not to use HTTP-Proxy

### ISSUE THREAD

**Issue by blue61** [kitematic/kitematic#1023]
obviously i can not get any image. i do see them all listed, though.

**Comment by blue61** [comment]
![unbenannt991](https://cloud.githubusercontent.com/assets/375567/9764210/26d1d8a6-570e-11e5-837b-414622f92047.PNG)

**Comment by mchiang0610** [comment]
@blue61 Thanks for the issue. Kitematic currently does not support proxies.

**Comment by mchiang0610** [comment]
closing this to merge with #321
