### ISSUE TITLE
cannot see private repo's in my org

### ISSUE THREAD

**Issue by michaelwilde** [kitematic/kitematic#1024]
Experiencing an issue with current released version of Docker Toolbox (Kitematic 0.7.6) where a user i've added to my team in my org on hub.docker.com--and the team has rights to a private repo--cannot see private repo's inside of Kitematic... i was hoping they'd appear in "My Repos" but they do not.  Help?

**Comment by FrenchBen** [comment]
Kitematic is up to 0.8.3, which is also what is provided in the Docker Toolbox - I would suggest uninstalling any previous versions and updating to the latest tools: [Docker Toolbox](https://www.docker.com/toolbox)

**Comment by michaelwilde** [comment]
Everyone I am testing with sees the same thing unless they are in owners group.  They are all on Docker Toolbox downloaded in the last week

Sent from Outlook<http://aka.ms/Ox5hz3>




On Thu, Sep 10, 2015 at 3:34 PM -0700, "FrenchBen" <notifications@github.com<mailto:notifications@github.com>> wrote:


Kitematic is up to 0.8.3, which is also what is provided in the Docker Toolbox - I would suggest uninstalling any previous versions and updating to the latest tools: Docker Toolbox<https://www.docker.com/toolbox>

**Comment by FrenchBen** [comment]
@michaelwilde If it's a recent Toolbox version then it shouldn't be the 0.7.6 you mentioned. 
On hub.docker.com - How do they view the repositories? 
Unfortunately I am not part of any ORG and can't see the same thing that you are.

If you want to add me to your ORG temporarily I'd be happy to look into it. =)

**Comment by michaelwilde** [comment]
Right. My version is behind, just like you said. But all of my colleagues on Docker toolbox from last week.  What's your docker Hub ID. (Frenchben?) I will add you to the org and to a group that has read or write on the repo

Sent from Outlook<http://aka.ms/Ox5hz3>

_____________________________

**Comment by FrenchBen** [comment]
should be just 'frenchben' - Thanks!

**Comment by michaelwilde** [comment]
ok.. you're in.  There will likely be a difference what you see in Web version of Docker Hub in the "Splunk" org, than what you see in Kitematic's "My Repos"..

**Comment by ysle** [comment]
+1 here as well.

**Comment by FrenchBen** [comment]
@michaelwilde Saw the invite come through, thank you for the help - 
@ysle @michaelwilde  I'll see if I can start debugging it today and provide a patch asap

**Comment by michaelwilde** [comment]
Word.  0.8.4 has same behavior btw.

-michael

Michael Wilde
Chief of Black Ops and White Lies
Office of Field Technology, Splunk
thewilde@splunk.com<mailto:thewilde@splunk.com>
(512) 524-9742<tel:(512)%20524-9742>

http://www.splunk.com<http://www.splunk.com/>

splunk >  a logfile is forever

On Sep 11, 2015, at 12:14 PM, FrenchBen <notifications@github.com<mailto:notifications@github.com>> wrote:


@michaelwilde<https://github.com/michaelwilde> Saw the invite come through, thank you for the help -
@ysle<https://github.com/ysle> @michaelwilde<https://github.com/michaelwilde> I'll see if I can start debugging it today and provide a patch asap

**Comment by michaelwilde** [comment]
It "will" work if you put your users in the "owners" group.. but of course we don't really want that, do we?

**Comment by FrenchBen** [comment]
@michaelwilde I see it - I think we lookup repos for the user, but don't check if the user belongs to an org. Adding them to the 'owners' essentially puts the repo under the user's repo list. 
Otherwise it needs to be looked up by Org. 

i.e. on hub.docker.com - I see my own repo. To view the private org repo, I need to use the dropdown and select the team which 'owns' the repo.

I'll see if I can simply loop through those in Kitematic.

**Comment by FrenchBen** [comment]
@michaelwilde I have a patch ready to go - but need 1 private repo created within the ORG to QA this. Let me know when you have it ready for me to try out.

@ysle If you're familiar with the build, I can push my current patch and you can assist with QA?

**Comment by michaelwilde** [comment]
Sure man...   You have a private repo.  You are in a group that has write access to it.  https://hub.docker.com/r/splunk/frenchbentest/

Go FrenchBen go!

**Comment by FrenchBen** [comment]
Thanks @michaelwilde  - PR https://github.com/kitematic/kitematic/pull/1038 should fix this:
![org-repo](https://cloud.githubusercontent.com/assets/3965324/9855034/f52078e2-5ad9-11e5-8fc9-21ff46acc5e9.png)

**Comment by jeffdm** [comment]
@michaelwilde this should be fixed in 0.8.5 (and part of the latest Docker Toolbox 1.8.2a). 

Thanks for the issue report, and to @FrenchBen for the great fix!

**Comment by ysle** [comment]
thanks!
