### ISSUE TITLE
Some libraries are not working with the new version of Node

### ISSUE THREAD

**Issue by saiberz** [kitematic/kitematic#1025]
I'm using:
node v4.0.0
npm  v2.14.2
OSX

Running npm install with I get this error:
>Loading "Gruntfile.js" tasks...ERROR
>Error: Cannot find module 'electron-prebuilt'

Looks like there is a problem with electron-prebuilt module

**Comment by FrenchBen** [comment]
As of right now the proper development stack is:
* Node v0.10.40
* NPM 1.4.28

This can easily be managed via `nvm` http://learn.bevry.me/node/install/

**Comment by saiberz** [comment]
Ok, sorry I didn't read it before I open the issue.
By the way it's working perfectly with 
- Node 0.12.7
- NPM 2.14.0

**Comment by FrenchBen** [comment]
@saiberz Node 0.12.7 kind of works - I think the issue is that the tests usually do not pass. Try to run `npm test`

**Comment by saiberz** [comment]
thanks @FrenchBen  , I'll take into account :+1:
