### ISSUE TITLE
Error creating the VM docker host.

### ISSUE THREAD

**Issue by alexandrev** [kitematic/kitematic#1027]
I'm facing issues when I want to run the setup and create the docker host VM. I get this message:

"C:\Program Files\Docker Toolbox\kitematic\resources\resources\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="C:\Users\<redacted>\disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed."

![image](https://cloud.githubusercontent.com/assets/947041/9798984/c197ff5e-5804-11e5-98dc-3904d2478331.png)

I don't know what to try. I try to delete the VM and start again but same problem appears.

Any help?

**Comment by FrenchBen** [comment]
@alexandrev There are couple of factors in Windows that could be causing this - Check the [Wiki](https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#kitematic-vm-stuck-at-99-or-cannot-pull-images) under the Windows section for possible fixes

**Comment by alexandrev** [comment]
Hi @FrenchBen, thanks for your fast anwser but I only find this section about known issues https://kitematic.com/docs/known-issues/ but nothing related to my problem. Could you be more specific? Thanks in advance

**Comment by FrenchBen** [comment]
@alexandrev the '[Wiki](https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#kitematic-vm-stuck-at-99-or-cannot-pull-images)' word above, as is this one, is a link - Just click it :)

**Comment by mchiang0610** [comment]
Closing to merge with #1029
