### ISSUE TITLE
docker.io not reachable

### ISSUE THREAD

**Issue by yogesh26** [kitematic/kitematic#1035]
I have tried few times to pull hello-world repo but all the times it times out with following message. Have been trying over the internet but couldnt get much info on this issue. I am running with 

Docker version 1.8.2, build 0a8c2e3

MacOS 10.10.4

Ping can reach any valid url but docker always returns time out.  
I will appreciate if someone can describe some solution.

Regards
Yogesh

**Comment by mchiang0610** [comment]
@yogesh26 Are you connected through Proxy or VPN? 

Sometimes this is caused by DNS errors as well.

**Comment by yogesh26** [comment]
Hi Mchiang I am completely unrestricted, no proxy or VPN.

**Comment by yogesh26** [comment]
This is my debugging effort to the problem I am facing while trying to 'docker pull xyz' . The error message it throws is "Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/base/images. You may want to check your internet connection or if you are behind a proxy." I am accessing the internet via my unrestricted phone internet.

**Comment by mchiang0610** [comment]
@yogesh26 Can you refresh your DNS, and give this a try again. 

Merging this with #1030 to help us collect more error reports there. 

Thanks!

**Comment by yogesh26** [comment]
Thanks MChiang, it worked indeed. I did flushed the cache using "sudo killall -HUP mDNSResponder". It cleaned the dns cache and "docker pull hello-world" worked immediately.

**Comment by nitsbobby** [comment]
I am not able to push my new docker image from IntelliJ Idea to my repository from my laptop. I am using my broadband high speed connection and there is no issue as I am able to login into my docker hub repository using docker login and it is successfully connecting. Also docker desktop installed on my laptop is not connecting to my docker hub account. The credential which I am using to connect from IntelliJ Idea Terminal and not working on connecting with docker desktop.
I am using Linux container format.
