### ISSUE TITLE
Bug with elasticsearch container

### ISSUE THREAD

**Issue by TheFlighteur** [kitematic/kitematic#1036]
Right now it seems that elestic search is not downloadable through kitematic.

**Comment by FrenchBen** [comment]
What version of Kitematic/toolbox are you using? Any screenshot of the issue, or just a never-ending download animation?

**Comment by FrenchBen** [comment]
I just create a new container without any issues - What are your network settings? Are you behind a firewall?
![elasticsearch](https://cloud.githubusercontent.com/assets/3965324/9854661/e81e1e58-5ad7-11e5-9cbd-4afcc2252b93.png)

**Comment by TheFlighteur** [comment]
The error told me that kitematic can't download the image, i'll retry later.

**Comment by mchiang0610** [comment]
@TheFlighteur This can be a temporary network issue. Please try again later. 

Merging this with #1030 as well. Can you provide more details / logs there? 

Thanks,
Michael
