### ISSUE TITLE
Error launching rethinkdb container 

### ISSUE THREAD

**Issue by wjimenez5271** [kitematic/kitematic#1039]
```
Error pulling image (latest) from rethinkdb, Driver aufs failed to create image rootfs 24926fb0be263b4568a2834abbeb0f436d3b9e437b21cc009c6adf2cefe289f7: open /mnt/sda1/var/lib/docker/aufs/layers/8c00acfb017549e44d28098762c3e6296872a1ca9b90385855f1019d84bb0dac: no such file or directory
```

**Comment by FrenchBen** [comment]
I would restart the VM - looks like it didn't start with the proper permissions.
`docker-machine restart default` should do the trick

**Comment by mchiang0610** [comment]
@wjimenez5271 Yes, it seems like the VM is not functioning correctly. 

Closing this but if the solution is not working out, please reopen this issue. 
Thanks!
