### ISSUE TITLE
pulling alpine images gets error 500

### ISSUE THREAD

**Issue by drakpz** [kitematic/kitematic#1040]
This is what I get if trying to pull alpine image:

server error
500
No command specified

**Comment by mchiang0610** [comment]
@drakpz Can you refresh DNS, and try it again?

**Comment by mchiang0610** [comment]
Merging with #1030

**Comment by drakpz** [comment]
done that, still no juice. Even tried with a different connection and triple flushed dns. no luck, same error. Same error as well from differente OSes (docker toolbox on osx and on win10).

**Comment by mchiang0610** [comment]
@drakpz Are you under VPN / proxy? It's a known issue if that's the case.

**Comment by drakpz** [comment]
Nope. No proxy nor vpn.

Piergiorgio Spagnolatti

Il giorno 15/set/2015, alle ore 23:39, Michael Chiang <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@drakpz<https://github.com/drakpz> Are you under VPN / proxy? It's a known issue if that's the case.

—
Reply to this email directly or view it on GitHub<https://github.com/kitematic/kitematic/issues/1040#issuecomment-140554631>.

AVVERTENZE LEGALI - I contenuti di questo messaggio, proveniente da un indirizzo di posta elettronica aziendale della Banca Popolare di Sondrio, e gli eventuali allegati possono essere letti e utilizzati, per esigenze lavorative, da chi opera alle dipendenze o per conto della stessa, o è comunque cointeressato nell'inerente relazione d'affari. Le dichiarazioni, ivi contenute, non impegnano contrattualmente la Banca Popolare di Sondrio se non nei limiti di quanto eventualmente previsto in accordi opportunamente formalizzati. Se il messaggio è stato ricevuto per errore ce ne scusiamo, pregando di segnalare ciò al mittente e poi di distruggerlo senza farne alcun uso poiché l'utilizzo senza averne diritto è vietato dalla legge e potrebbe costituire reato.

DATI SOCIETARI - BANCA POPOLARE DI SONDRIO - Società cooperativa per azioni - Fondata nel 1871
Sede sociale e direzione generale: I - 23100 SONDRIO SO - piazza Garibaldi, 16
Indirizzo Internet: http:[doppiabarra]www[punto]popso[punto]it - E-mail: info[chiocciolina]popso[punto]it
Iscritta al Registro delle Imprese di Sondrio al n. 00053810149, all'Albo delle Banche al n. 842, all'Albo delle Società Cooperative al n. A160536 Capogruppo del Gruppo bancario Banca Popolare di Sondrio, iscritto all'Albo dei Gruppi bancari al n. 5696.0 Aderente al Fondo Interbancario di Tutela dei Depositi e al Fondo Nazionale di Garanzia - Codice fiscale e partita IVA: 00053810149
Capitale sociale € 1.360.157.331 - Riserve € 833.958.444 (dati approvati dall'Assemblea dei soci del 18/04/2015).

N.B. I “filtri antivirus” e “antispam” in uso su molti sistemi di posta elettronica possono talvolta ritardare o impedire, in tutto o in parte, il recapito dei messaggi. In tali casi, salvo verifica di avvenuta ricezione, può essere necessario modificare i contenuti o le modalità d'invio.

**Comment by mchiang0610** [comment]
@drakpz there is no command specified in the specific docker image. 

May I ask what you are looking to do?
