### ISSUE TITLE
Network timed out

### ISSUE THREAD

**Issue by tapz** [kitematic/kitematic#1045]
Got this error, but the url works in a web browser...

Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/elasticsearch/images. You may want to check your internet connection or if you are behind a proxy.

Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/redis/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by FrenchBen** [comment]
Sounds like your VM can't connect - you can check this by going into the VM and trying to ping the above link:
`docker-machine ssh default`
`ping index.docker.io`

**Comment by tapz** [comment]
It finally succeeded to connect when I had added the container couple of times again.

**Comment by FrenchBen** [comment]
:+1: Good to hear - Closing this for now, but feel free to re-open it if you have any more issues.

**Comment by jpdesigndev** [comment]
I'm getting the same issues. I've tried many times.
