### ISSUE TITLE
系统休眠再开后，连不上，没法执行命令

### ISSUE THREAD

**Issue by aaqqxx** [kitematic/kitematic#1049]
系统休眠后，网络断开，不能执行命令，很难再次开始，需要重启电脑，有时重启电脑要好几次才可以连上

**Comment by FrenchBen** [comment]
@aaqqxx  请说英语 :)

Google translate:
"Sleep system, disconnected from the network, you can not execute the command, it is difficult start again, you need to restart the computer, restart the computer and sometimes several times before they can connect better"

Virtualbox does have some issues when waking up and making the proper connection - You shouldn't have to restart fully, you can simply execute the following in a command line:
`docker-machine restart default`

**Comment by mchiang0610** [comment]
@FrenchBen It seems like his docker machine instance doesn't work after waking his computer up from sleep mode. 

A known machine error.
