### ISSUE TITLE
Error creating the Docker Host VM in Windows 10 build 10547

### ISSUE THREAD

**Issue by alexandrev** [kitematic/kitematic#1050]
When I try to create the default virtual machine using Kitematic (or the Docker Quickstart Terminal) the machine is created but the network configuration is wrong. It tries to create and rename a lot of Host-Only Virtualbox Adapters every time I try to create the machine but never the configuration is right to start the machine.

![image](https://cloud.githubusercontent.com/assets/947041/9979940/6d7f4714-5f85-11e5-8276-060b40954f9d.png)

![image](https://cloud.githubusercontent.com/assets/947041/9979943/79cc0f02-5f85-11e5-879b-dab8f1aee33b.png)
![image](https://cloud.githubusercontent.com/assets/947041/9979944/8b9166d8-5f85-11e5-822a-c166db84c6c4.png)

If I change the network configuration of the machine using the Virtualbox GUI the machine starts but there is no connection with the docker client. Any help?

**Comment by Grabuge** [comment]
I have the same problem with Windows 10 10547. Network interface error when VM try to start ...
We will probably have to wait a new Virtualbox build. Well, after each insider build, my Docker is down :D .

**Comment by FrenchBen** [comment]
@alexandrev @Grabuge I would encourage you to take a look at the following thread which has some very good debug information as well as steps to get it up and running:
https://github.com/kitematic/kitematic/issues/1037

**Comment by mchiang0610** [comment]
@Grabuge Sorry about your experience so far. We are looking into this issue. 

Merging this with  #1029 and #1037 to reduce duplicates.
