### ISSUE TITLE
EHOSTDOWN and ETIMEDOUT when restarting an host

### ISSUE THREAD

**Issue by gpapin** [kitematic/kitematic#1051]
![capture d ecran 2015-09-21 a 11 31 51](https://cloud.githubusercontent.com/assets/3064311/9989891/62c8b948-6054-11e5-8c89-f3cbfc7bd598.png)

I wanted to use my local docker instance of mongoDB, is was supposed to be running but my application couldn't connect to it, so I decided to restart it, this it when the previous error occurred.

**Comment by FrenchBen** [comment]
Looks like your VM is down- From the command line issue:
`docker-machine restart default`

**Comment by gpapin** [comment]
It was most likely down, but the kinematic UI was reporting it as up. Everything is sorted now but I had to restart Kitematic to re-sync it properly

**Comment by mchiang0610** [comment]
@gpapin thanks. Merging this with #1030 for discussion there.
