### ISSUE TITLE
Install problem on mac book pro Yosemite 10.10.5

### ISSUE THREAD

**Issue by toddplesniak** [kitematic/kitematic#1052]
I get this message when trying to setup Kitematic on my mac book pro running Yosemite 10.10.5, Docker Kitematic 0.8.5 built with Docker Engine 1.8.2, Docker Machine 0.4.1 and Virtual Box 5.0.4

/opt/homebrew-cask/Caskroom/kitematic/0.8.5/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users/<redacted>/.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: Too many retries. Last error: Maximum number of retries (60) exceeded You will want to check the provider to make sure the machine and associated resources were properly removed.

then if I try to retry or delete and reinstall the unable to obtain IP address message appears.

Machine IP could not be fetched. Please retry the setup. If this fails please file a ticket on our GitHub repo.

**Comment by FrenchBen** [comment]
I would try to uninstall everything you've installed/configured via homebrew/cask and use the [Docker Toolbox](docker.com/toolbox) instead.

**Comment by toddplesniak** [comment]
actually the Docker Toolbox was what I have a problem with.

**Comment by mchiang0610** [comment]
@toddplesniak Thanks for this. It seems like this is a problem with Docker machine. 

One possible fix is to open virtualbox and remove the "default" VM (by using delete all files). Run the installer again after. 

If it's still not working, please comment in the main thread for this issue #1029 

Thanks!
