### ISSUE TITLE
Created a new Repo and tried to pull from Kitematic - Experiencing error message :Tag latest not found in repository docker.io/kmrkaya/kmrbotw

### ISSUE THREAD

**Issue by kmrkaya** [kitematic/kitematic#1054]
Created a new Repo and tried to pull from Kitematic - Experiencing error message :Tag latest not found in repository docker.io/kmrkaya/kmrbotw

**Comment by mchiang0610** [comment]
@kmrkaya does the image have the latest tag? If not, you will receive an error like that. Otherwise, the image may be having issues. 

If you are still having problems with this, please email support@docker.com for intense help 
Thanks!
