### ISSUE TITLE
Machine IP could not be fetched. Please retry the setup

### ISSUE THREAD

**Issue by cpuguy83** [kitematic/kitematic#1055]
Moved from docker/docker#16489, ping @acidhax
---

Using Kitematic, I get this error:
Machine IP could not be fetched. Please retry the setup.

If I Delete VM and Retry:

/Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users//.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed.

**Comment by acidhax** [comment]
Fixed:

Repaired Disk Permissions

**Comment by mchiang0610** [comment]
@cpuguy83 Thanks for this. This is part of the docker machine issue we have. Merging with it. #1029
