### ISSUE TITLE
unable to login on docker hub from kinematic 1.8.2a

### ISSUE THREAD

**Issue by smartinsightsfromdata** [kitematic/kitematic#1057]
I have a valid & working login on docker hub (browser access).

On the other hand I am unable to login from kinematic on my mac.

I try and the app lies there: no feedback  etc., doing apparently nothing.  Usually after a couple of minutes I kill it exasperated.

Any idea?

**Comment by mchiang0610** [comment]
@smartinsightsfromdata This may be a problem with your DNS. Can you try to clear your DNS cache? 

If problem persists, please email support@docker.com and they will be able to help you further. 

Thanks!
