### ISSUE TITLE
Kitematic error. connect ETIMEDOUT 192.168.99.100

### ISSUE THREAD

**Issue by arnfox** [kitematic/kitematic#1058]
Hi
I'm using Win 10. Virtualbox 5.0.5 (night build, as 5.0.4 official did not work with the Kitematic)
I'm installing Kitematic and it work well until my notebook fall asleep. After it awake it can't reach docker on Virtualbox (default) no more. After a while having 99% it throws
``` 
Cannot connect to the Docker Engine. Either the VM is not responding or the connection may be blocked (VPN or Proxy): connect ETIMEDOUT 192.168.99.100:2376
```

If I'm running windows shell and try "docker ps", I got
```
Cannot connect to the Docker Engine. Either the VM is not responding or the connection may be blocked (VPN or Proxy): connect ETIMEDOUT 192.168.99.100:2376
```
It start working well again only if I restart my laptop.

Any advice?

Best
Pavel

**Comment by mchiang0610** [comment]
@arnfox Thanks for this. This seems to be a networking issue that we are looking into. 

Merging with #1029 so we can discuss all the problems there to help troubleshoot this.
