### ISSUE TITLE
Attempt to delete a broken container failed with a strange message "no such container"

### ISSUE THREAD

**Issue by leo-from-spb** [kitematic/kitematic#1060]
Attempted to run a container. During download, an error occurred.
An attempt to delete it causes one more error: 

>no such container
>404
>no such id: fedora

**Comment by leo-from-spb** [comment]
Is it possible to somehow remove a broken container?

**Comment by mchiang0610** [comment]
@leo-from-spb Yes, it should be removed by restarting Kitematic. 

Regarding the 404 problem - I will merge this with the bug report that we've had. 

#1030 

Thanks!
