### ISSUE TITLE
Feature request - Change VM name ( " default " ) 

### ISSUE THREAD

**Issue by leo-from-spb** [kitematic/kitematic#1061]
Please allow to select name for the VM that Kitematic uses for dockers, and allow to rename the existent VM.

**Comment by mchiang0610** [comment]
@leo-from-spb Thanks for the suggestion

**Comment by FrenchBen** [comment]
Wouldn't the 'cfg' PR solve this for advance settings? https://github.com/kitematic/kitematic/pull/992

**Comment by mchiang0610** [comment]
@FrenchBen Yes, it would.

**Comment by d3v1an7** [comment]
Hi all, I guess this is a fairly edge case, but I'm creating a `dev` docker machine with a provisioning script on new machines -- the enforced creation of the `default` machine when opening Kitematic is a bit confusing, and if I remove it manually, it re-creates itself on subsequent opens of the app.
Is it possible to detect if a working docker machine already exists prior to creation of `default`? <3

**Comment by FrenchBen** [comment]
@d3v1an7 the above mentioned PR does just that - It looks for any preference of docker machine and uses that for Kitematic.

**Comment by FrenchBen** [comment]
@mmehta I believe this is what you were referring to - The new VM is now `default` instead of `dev`

**Comment by lusitania** [comment]
@FrenchBen I struggle with your comment
> It looks for any preference of docker machine and uses that for Kitematic.

I've installed the recent docker-toolbox 1.9.1f for Windows, named my host "docker" but kitematic still creates a "default" machine. What am I missing?

Best

**Comment by thiphariel** [comment]
Same here, on OS X 10.11.2, toolbox 1.9.1

**Comment by FrenchBen** [comment]
@thiphariel The default vm is always loaded - there is currently some discussion to get the VM selection, but no definite path to do so (see the wiki)

**Comment by vkartaviy** [comment]
@FrenchBen :+1:

It would be really great to have ability to select VM at the start of application.
