### ISSUE TITLE
server error 500 No command specified

### ISSUE THREAD

**Issue by BarryLevinson** [kitematic/kitematic#1063]
![screen shot 2015-09-24 at 3 52 27 pm](https://cloud.githubusercontent.com/assets/13556113/10073784/03b19fe2-62d4-11e5-890d-e47c5ca4c7c8.png)

Is there a problem on my end, or is the service down right now?

**Comment by mchiang0610** [comment]
@BarryLevinson Hi, this is a problem with the specific docker image - it did not specify how to run it when a container is created.
