### ISSUE TITLE
cannot download hello-world-nginx

### ISSUE THREAD

**Issue by alaskanson** [kitematic/kitematic#1066]
Error:
Get https://registry-1.docker.io/v1/repositories/kitematic/hello-world-nginx/tags/latest: dial tcp: lookup registry-1.docker.io: no such host

Host seems to resolve just fine and I can put the URL into my browser and get at least some result:
{"error": "Requires authorization"}

I have a user and can log in ok but this still doesnt work.

bash-3.2$ ping registry-1.docker.io
PING us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com (54.88.164.232): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

**Comment by alaskanson** [comment]
Neglected to mention this is on a Mac with Kitematic downloaded yesterday.

**Comment by mchiang0610** [comment]
@alaskanson Sorry about this. This seems like a problem with Docker hub. Please email support@docker.com for immediate support. 

Thanks!
