### ISSUE TITLE
Is Kitematic removing local volumes?

### ISSUE THREAD

**Issue by ianbytchek** [kitematic/kitematic#1068]
I searched the issues but didn't find this exact problem reported, though it seems it's mentioned in a few places. When I manually run a container with files / folders mapped as volumes via `docker run` and then remove the container using the :x: button in Kitematic's UI, the local files / folders that were mapped get deleted. I'd go insane if not the time machine… This looks serious, no?

**Comment by mchiang0610** [comment]
@ianbytchek 

Kitematic will not remove your local folders. However, for the files created by Kitematic inside the kitematic folder, we may remove upon deletion. 

Could we get a little more detail on your use case to try to address this issue?

**Comment by ianbytchek** [comment]
Hey @mchiang0610, take this for instance. I have the following files in the following folder:

![image](https://cloud.githubusercontent.com/assets/1086845/10117206/70bf852a-6457-11e5-9a73-541ab7567d9e.png)

I would then start a docker container.

```sh
volume_dir=~/Kitematic; \
absolute_volume_dir=$(cd $volume_dir && pwd); \
docker run -d \
    --publish '80:80' \
    --publish '443:443' \
    --name 'haproxy' \
    --volume "$absolute_volume_dir/haproxy/haproxy.cfg:/docker/configuration/haproxy.cfg" \
    --volume "$absolute_volume_dir/haproxy/ssl:/docker/ssl" \
    ianbytchek/haproxy
```

Then remove this container inside Kitematic.

![image](https://cloud.githubusercontent.com/assets/1086845/10117233/08174ad4-6458-11e5-8083-0b9b00b429f5.png)

Which deletes every local file and folder mounted as a volume:

![image](https://cloud.githubusercontent.com/assets/1086845/10117228/e404f132-6457-11e5-8879-e0e2ed28ea12.png)

**Comment by mchiang0610** [comment]
@ianbytchek Sorry about that. 

It's in the kitematic folder and using the container name so Kitematic deletes it upon deleting the particular container. 

Changing the location should solve this for now.

**Comment by ianbytchek** [comment]
Thanks man, I'll give that a go!
