### ISSUE TITLE
https proxy

### ISSUE THREAD

**Issue by memeinstigator** [kitematic/kitematic#1071]
When kinematic is tying to download this https://index.docker.io/v1/repositories/library/ubuntu-upstart/images, it is not using the https_proxy value set in the shell before starting the kitematic. I am unable to download any images

Steps - mac Terminal:
export https_proxy=http://proxy:port
open Kitematic.app/

![screen shot 2015-09-28 at 4 22 44 pm](https://cloud.githubusercontent.com/assets/5017652/10149126/2ec6444a-65fd-11e5-8e0f-41bedd183acc.png)

**Comment by mchiang0610** [comment]
@memeinstigator sorry for this. Docker machine that's used doesn't currently support Proxies.

**Comment by mchiang0610** [comment]
#1031 Merging with the rest of the proxy / VPN error reports.

**Comment by FrenchBen** [comment]
@memeinstigator What you're missing is that the download happens within the VM, not the terminal you've opened and set the proxy to.
Check out the wiki section, at the bottom of it, there are steps to add proxy settings to the VM:
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#add-proxy-settings-to-vm
