### ISSUE TITLE
The machine 'boot2docker-vm' is already locked by a session

### ISSUE THREAD

**Issue by fyddaben** [kitematic/kitematic#1072]
every time i open a new terminal,it will run

```
VBoxManage startvm boot2docker-vm --type headless
```

and i dont know where i config this command

and when i open a second terminal ,it will tell me 
```
The machine 'boot2docker-vm' is already locked by a session
```

**Comment by FrenchBen** [comment]
Check your `.bashrc` or `.profile` within your home directory - Something may have been added from the original boot2docker install.

**Comment by fyddaben** [comment]
i have no .profile. and my .bashrc have nothing  . i dont know why vboxmanage must auto start.fuck

**Comment by FrenchBen** [comment]
What about under System Preferences > Users & Group > Login Items ?

**Comment by mchiang0610** [comment]
@fyddaben Thanks for reporting. Kitematic / installs through Docker Toolbox uses 'default' VM instead of boot2docker-vm. 

This must be a customization you've made with your default terminal. 

A quick temporary solution might be to open Kitematic and click the "Docker CLI" button at the bottom left of the interface. This will open up a terminal for you to use. 

Hope this helps. Thanks.

**Comment by fyddaben** [comment]
when i type
```
bash --login -x
```
it turns out
```
+ VBoxManage startvm boot2docker-vm --type headless
VBoxManage: error: The machine 'boot2docker-vm' is already locked by a session (or being locked or unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 592 of file VBoxManageMisc.cpp
+ '[' -x /usr/libexec/path_helper ']'
++ /usr/libexec/path_helper -s
```


is virtualbox need config somewhere?

**Comment by mchiang0610** [comment]
@fyddaben Thanks. 

If you wish to use the boot2docker-vm as you have scripted, you can open up VirtualBox. There you should see boot2docker-vm. Right click on it, and remove it. (make sure to select "Delete All Files". 

If you are not wishing for that to come up, please remove the scripts that you've set.

**Comment by fyddaben** [comment]
ok . i change bash to zsh.and the problem should be sloved .i will close it .thx.
