### ISSUE TITLE
I can't connect all evening

### ISSUE THREAD

**Issue by steven-st-james** [kitematic/kitematic#1073]
I'm having issues connecting to download containers

**Comment by nVitius** [comment]
You won't get any help if you don't provide more details about the issue you're getting. Steps taken, error messages, etc.

**Comment by mchiang0610** [comment]
@steven-st-james Could you provide more details? 

Docker Hub was available. In the past, users have had problems when they are in VPN / Proxy environments or when they have a custom DNS that wouldn't resolve docker hub. 

Closing this for now to keep the issues clean. Please reopen it with more information if you continue to have problems with it.
