### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by starlight0405** [kitematic/kitematic#1074]
https://index.docker.io/v1/repositories/library/ubuntu/images: net/http: TLS handshake timeout

**Comment by FrenchBen** [comment]
Are you behind a proxy? Could you share details of your network setup?

**Comment by samhe** [comment]
+1
I encounter the same issue when running behind a proxy.

**Comment by FrenchBen** [comment]
@samhe Did you look at the info in the wiki? You can try to update some of the VM proxy settings:
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#add-proxy-settings-to-vm

**Comment by mchiang0610** [comment]
Closing because we are aware of this issue as per @FrenchBen's post.
