### ISSUE TITLE
After the El Capitan upgrade, the virtual box startup stuck at 99%

### ISSUE THREAD

**Issue by vicary** [kitematic/kitematic#1078]
From VirtualBox the VM can boot into CLI and it has an IP of `192.168.99.103`, but Kitematic doesn't know that.

After that I brutally removed all VMs in VirtualBox, it's not helping either.

If I restart Kitematic with the VM already booted, it prompts about the inability to fetch machine IP, which always happens at 42%.

![screen shot 2015-10-02 at 7 03 01 pm](https://cloud.githubusercontent.com/assets/85772/10245245/484b0796-6938-11e5-836d-9d0f99cca129.png)
![screen shot 2015-10-02 at 7 03 14 pm](https://cloud.githubusercontent.com/assets/85772/10245244/484978cc-6938-11e5-98b1-fd55af67c557.png)
![screen shot 2015-10-02 at 7 03 57 pm](https://cloud.githubusercontent.com/assets/85772/10245252/5f4c6282-6938-11e5-94a4-c5f175017ee0.png)

**Comment by FrenchBen** [comment]
I plan on doing a clean upgrade to my system over the weekend and will do QA. 
Can you provide the following output details:
`docker-machine ls`
`docker-machine env default`
`docker-machine ip default`

**Comment by vicary** [comment]
No, even docker-machine does not know that it's already started. It stuck here forever.

```
$ docker-machine start default
Starting VM...
```

Without a properly connecting VM, these commands are expected to fail.
```
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL   SWARM
default            virtualbox   Timeout
$ docker-machine env default
Unexpected error getting machine url: exit status 255
$ docker-machine ip default
exit status 255
```

**Comment by yourtion** [comment]
I updated to 10.11.1 beta and VirtualBox 5.0.6, but still stuck at 99%.

**Comment by brandentimm** [comment]
I had this same error with the latest beta on El Cap, but it worked after doing "Delete VM and Retry Setup".

**Comment by vicary** [comment]
Interesting enough, the "Delete VM and Retry Setup" was not working in the last few days, but it worked today. Maybe I was not waiting long enough, not sure about it.

Since Kitematic never properly started, I cannot run docker-machine upgrade in the mean time.

VirtualBox version is still 5.0.4.

**Comment by FrenchBen** [comment]
@vicary kitematic isn't the issue here, but rather a bad VM (when you ran the start, no URL was shown) - You should be able to delete the VM and re-create it. 
`docker-machine rm default`
`docker-machine -D create --driver virtualbox --virtualbox-memory "2048" default`

The above should output a LOT of debug info which may help us debug possible installation issue. Please create a gist.github.com of the log if the VM doesn't get created properly.

**Comment by vicary** [comment]
The problem with re-creation before is because of my removal of the VMs from the VirtualBox interface instead of `docker-machine rm`, when I did that again from docker CLI it all works no problem. It should be a VirtualBox issue, closing this.

**Comment by FrenchBen** [comment]
@vicary Makes sense, as machine cleans up a few additional things - Good to see you got this resolved :+1:
