### ISSUE TITLE
Kitematic is giving issue after restarting machine

### ISSUE THREAD

**Issue by Passion4Architecture** [kitematic/kitematic#1081]

**Comment by Passion4Architecture** [comment]
When i try to open it through Docker CLI windows, it shows the following error: 
An error occurred trying to connect: Get https://127.0.0.1:2375/v1.20/images/json: dial tcp 127.0.0.1:2375: ConnectEx tc
p: No connection could be made because the target machine actively refused it.

**Comment by FrenchBen** [comment]
It looks like the IP is incorrect for the URL - Are you clicking the Docker CLI within Kitematic or directly tried to connect via command line?

**Comment by mchiang0610** [comment]
@Passion4Architecture Thanks. Seems like the virtual network had a problem. Please open virtualbox remove the "default" vm by using delete all files (assuming you don't have files in it). And then run Docker toolbox again. 

Hope that helps
