### ISSUE TITLE
Network timed out while trying to connect to https://index.docker.io/v1/repositories/kalilinux/kali-linux-docker/images. You may want to check your internet connection or if you are behind a proxy.

### ISSUE THREAD

**Issue by C3sPO** [kitematic/kitematic#1082]
Not sure why, but I can't install images. My internet works fine.

**Comment by FrenchBen** [comment]
Are you behind a proxy? Some VM have trouble connecting/downloading images when the machine is setup behind a proxy.

**Comment by C3sPO** [comment]
I got it to work by shutting off Little Snitch. The command prompt and kitematic weren’t flagging any outgoing requests with littlesnitch so it took me a while to look there, but shutting it down totally let the connection through. Weird one.


On October 5, 2015 at 11:54:02 AM, FrenchBen (notifications@github.com) wrote:

Are you behind a proxy? Some VM have trouble connecting/downloading images when the machine is setup behind a proxy.

**Comment by FrenchBen** [comment]
Thanks for the update - Closing it as this is resolved.
