### ISSUE TITLE
kinematic docker status download

### ISSUE THREAD

**Issue by fthamura** [kitematic/kitematic#1084]
in docker, we have status download progress

why can I get in kinematic?

right now I got 500 after waiting download big file from docker hub.

i wish can become next version feature.

NB: linux version also ;)

**Comment by mchiang0610** [comment]
@fthamura depending on which images, there is a progress bar. 

Regarding the 500 error you are getting, please try refreshing your DNS, and make sure you are not in a VPN or proxy environment
