### ISSUE TITLE
Volume management in Windows

### ISSUE THREAD

**Issue by yarmenti** [kitematic/kitematic#1085]
Hey guys,

I do not understand how volumes works in Windows. Actually I think that when downloading a container, kitematic should ask the user if (s)he wants to create (and where) a volume if present in the Dockerfile.

Because, now it does not work properly, at least in Win.

Cheers,

**Comment by FrenchBen** [comment]
@yarmenti Not all images are created equally and a mapped volume isn't always declared, which makes it difficult for Kitematic to know the proper location to map. 

What image did you download/setup and having trouble configuring a volume for?

**Comment by yarmenti** [comment]
I tried an openldap one (osixia/openldap) but when running the container, the folders were not created by default. Moreover, when enabling them, I had some errors due to missing config in that volumes.

I don't know how Kitematic is written but if a Dockerfile is mandatory, maybe one should check if some volumes are available inside it, and thus, a popup would then open to ask if Kitematic must enable the volume and then create the Kitematic/<container_name>/volumes and then start the container mapping them.

But thank you for the answer, I hope it could help to improve things :)

**Comment by FrenchBen** [comment]
Kitematic does check for volumes detailed in the Dockerfile, when you map the volume to a local folder, there is no copy of the internal data to that folder. 
If you look under Settings > Volumes you'll see that both folders in the Dockerfile are shown:
![volume](https://cloud.githubusercontent.com/assets/3965324/10287242/ee6c4be8-6b5f-11e5-9635-8fc53a7fd498.png)


It's assumed that you're mapping it to over-write the image settings/setup.

**Comment by yarmenti** [comment]
Ok, thanks I understood.
Would it be possible to first create the mapping local / container and then run the container (for the first time at least)?
So that the internal modifications could be saved to the host, and if we want to kill the container, we could still have a configured container for the image.

**Comment by FrenchBen** [comment]
@yarmenti Not sure if I understand the request? You mean map the volume during the first start? 
When you map the volume Kitematic actually deletes and re-creates the container in the background.

**Comment by yarmenti** [comment]
Ok, so this is weird:

- when the mapping is not set, the container works properly.

- when I enable it, if what you say ils correct, it should also work because tarting from zero. But it doesn't seems to, as the container ils broken saying that files are missing in the mounted volumes.

Weird... :/

**Comment by FrenchBen** [comment]
@yarmenti I'm not too familiar with the openldap image - Perhaps a required config file is needed in those folders?
Maybe check the content of the folders within the container and have a similar config in your volume folder?

**Comment by FrenchBen** [comment]
#closing since no feedback provided over 15+ days - Please comment back on here if needed

**Comment by donders** [comment]
I hope I understand correctly that I cannot manage a container's volume if there is no volume configuration in the origin's dockerfile.

Does that mean that there is no way to manage a container's volume from Kitematic's GUI if I cannot access the dockerfile, for example from `ibmcom/websphere-traditional`?

**Comment by Chrisdowson** [comment]
Has this feature been added yet?
