### ISSUE TITLE
Hangs starting VM

### ISSUE THREAD

**Issue by hlship** [kitematic/kitematic#1086]
I had a number of problems installing Docker Toolbox, documented here:

https://github.com/docker/docker/issues/16685

I'm now having an issue where I launch Kitematic, and it brings up the "Starting Docker VM" screen.

This quickly advances to 98%, but has stopped.

![kitematic](https://cloud.githubusercontent.com/assets/52660/10288904/75c1e5cc-6b50-11e5-944b-01ca78e85ce1.png)

Meanwhile, it looks like the Docker VM is actually up and running:

```
10:56:07 hship> docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                           NAMES
090c95277185        mongo:latest        "/entrypoint.sh mongo"   3 days ago          Up 3 days           0.0.0.0:32769->27017/tcp        mongo
a99106c05f12        redis:latest        "/entrypoint.sh redis"   3 days ago          Up 3 days           192.168.99.100:6379->6379/tcp   redis-3
~
10:58:11 hship>
```

Quitting Kitematic and restarting brings back the starting screen, which then fails:

![kitematic](https://cloud.githubusercontent.com/assets/52660/10288959/bc355dcc-6b50-11e5-8e79-f3759a249eb8.png)

I haven't tried either option yet, as the VM does still seem to be running, and I have some work to do :-).

My environment is a recent fresh install of OS X 10.10.5.

**Comment by mchiang0610** [comment]
@hlship Sorry about your experience so far, and thank you for letting us know. 

This is usually a problem when we fail to connect with the VM (mainly attributed to Virtualbox networking issues). Are you currently connected through a VPN or Proxy? 

We have a broader discussion of this in thread #1029. Hope you don't mind me merging this in there as well. 

Again, thank you so much for helping!
