### ISSUE TITLE
Error downloading official fedora image

### ISSUE THREAD

**Issue by nitingupta910** [kitematic/kitematic#1089]
using Kitematic 0.8.5

**Comment by mchiang0610** [comment]
@nitingupta910 Thanks for reporting. Are you connected via VPN / proxy? Make sure to check DNS. 

As this is a problem with Docker Hub, can you email support@docker.com for immediate support? 

Hope this helps! Thanks

**Comment by nitingupta910** [comment]
Thanks for your reply.
I was not connected to VPN/proxy.  I could instead download ubuntu image and that's running find. Since that's all I needed to proceed with work, I would close this issue for now.
