### ISSUE TITLE
Error pulling image (latest) from docker.io/bigdatauniversity/spark, HTTP code 401

### ISSUE THREAD

**Issue by satya42cse** [kitematic/kitematic#1090]
HI Tried to download bigdatauniversity/spark so many times, even i reinstalled the kitematic and my os too. still am getting "Error pulling image (latest) from docker.io/bigdatauniversity/spark, HTTP code 401" Error. Please help me to download this file.

**Comment by satya42cse** [comment]
I tried to download that image from :satyaforu user id.

**Comment by FrenchBen** [comment]
Are you logged in to the DockerHub when this happens? Did you confirm your email after signing up for DockerHub?

**Comment by satya42cse** [comment]
Hi,
I did and downloaded other images files.Science i cant able to download it.
i format the my os and tried to download it again. download stops some
where and it stuck there , after some time it showing above error.

On Wed, Oct 7, 2015 at 9:46 AM, FrenchBen <notifications@github.com> wrote:

> Are you logged in to the DockerHub when this happens? Did you confirm your
> email after signing up for DockerHub?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/issues/1090#issuecomment-146217113>
> .
>



-- 
Satya Cheetirala

**Comment by FrenchBen** [comment]
If some images work while others don't it could be a simple connectivity issue which unfortunately isn't something we can fix.

**Comment by mchiang0610** [comment]
@satya42cse Please contact support@docker.com
