### ISSUE TITLE
Log-in forbidden when username contains non alphanumeric chars.

### ISSUE THREAD

**Issue by ignasi35** [kitematic/kitematic#1091]
For users where username is an e.mail the validation of the username on the login from prevents logging in completely because the username contains '@' and '.'

**Comment by ignasi35** [comment]
I'm not sure what are the actual validation requirements re the username. ATM they seem to restrict usernames to 'lowercase', 'letters and numbers' and '4-30 in length'.

**Comment by ignasi35** [comment]
Maybe a whitelist of accepted characters should be used.

**Comment by FrenchBen** [comment]
I don't think DockerHub allows email for username? your username should be whatever you used for DockerHub.

**Comment by ignasi35** [comment]
Then I think the error is on dockerhub. I just logged in using both "username@gmail.com" and "username". Thanks for the quick response.

**Comment by FrenchBen** [comment]
username is the preferred way - Interesting that DockerHub allows you to login with both.
