### ISSUE TITLE
File not found MAPR cent66

### ISSUE THREAD

**Issue by webspiderc** [kitematic/kitematic#1092]
![github_mapr_docker_control](https://cloud.githubusercontent.com/assets/7650877/10363228/f275cd8a-6de5-11e5-805e-8903b4b1f43c.png)
![github_mapr_docker_data](https://cloud.githubusercontent.com/assets/7650877/10363229/f27755a6-6de5-11e5-86e0-a97cf0581fab.png)

**Comment by FrenchBen** [comment]
This isn't really a 'true' issue, the tag 'latest' doesn't exist for that image, as seen here:
https://hub.docker.com/r/maprtech/mapr-data-cent66/tags/

If you select the proper tag available, then it will all work - Closing in favor of https://github.com/kitematic/kitematic/issues/572
