### ISSUE TITLE
Unable to pull docker images - Getting timedout error

### ISSUE THREAD

**Issue by vmnamburu** [kitematic/kitematic#1100]
I am using Docker toolset on Windows. Trying to pull a docker image and getting the following error (both in Gitbash and Kitematic)

Network timed out while trying to connect to https://index.docker.io/v1/repositories/bigdatauniversity/spark/images. You may want to check your internet connection or if you are behind a proxy.

But I am able to open the same link in a browser.
![github_spark_docker_image_dwnld_issue](https://cloud.githubusercontent.com/assets/11724569/10410967/793cc97c-6f71-11e5-86ce-7c8e781fccaa.jpg)

**Comment by FrenchBen** [comment]
@vmnamburu The timeout happens within the VM; making the connection test within your browser only confirms that your main computer is connected, but it's possible that the VM lost its connection.

Are you behind a proxy? If so, check out the wiki: https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#add-proxy-settings-to-vm
I would also suggest a complete restart - Virtualbox's network daemon can sometimes be finicky.

**Comment by mchiang0610** [comment]
Hub is also having some maintenance work being performed. Please check: https://status.docker.com/ 

Thanks!
