### ISSUE TITLE
Kitematic Early Linux support - Boot2Docker Error: Cannot connect to the Docker daemon. The daemon is not running: connect ENOENT /var/run/docker.sock

### ISSUE THREAD

**Issue by miguelqvd** [kitematic/kitematic#1101]
Hi,

I've installed Kitematic Early Linux support  on my Ubuntu where I also have configured a boot2docker VM. I've all the env vars configured:

export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_CERT_PATH=/home/maq/.docker/machine/certs
export DOCKER_TLS_VERIFY=1
export DOCKER_IP=192.168.99.100

docker-machine & docker-compose work fine and I can interact with my VM.

Kitematic for linux is always asking for docker daemon running on my host and because of that I suspect it doesn't take into account docker env vars and it doesn't manage docker in the VM.

I would like to get Kitematic running against docker in my boot2docker VM with my Ubuntu host.

Any ideas?

![image](https://cloud.githubusercontent.com/assets/5271855/10411021/a91e95fe-6f57-11e5-9773-8abb31df1b38.png)

**Comment by FrenchBen** [comment]
@miguelqvd The Early support for Linux is actually made to NOT create a VM and why the above error exists. 
You should be installing the Docker daemon directly on your ubuntu workstation, which Kitematic will then connect to.
The above `export` commands are useless as the early Linux support doesn't look for a VM at all. 

You can checkout the Ubuntu install how-to at the following url: https://docs.docker.com/installation/ubuntulinux/

**Comment by miguelqvd** [comment]
Thank you for your reply, which make really a lot of sense. However I need to ask how might I mange docker environments that are not installed in my local linux machine. I'm thinking for example about administrating digital ocean VMs. I think Kitematic has a lot of potential and it should support this feature which is already available for windows and mac through env vars.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (104/100 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:58664 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZmS3u-003D7Z-Mo
	for greg@biomassiv.es; Wed, 14 Oct 2015 14:50:11 -0500
Date: Wed, 14 Oct 2015 12:50:09 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1444852209;
	bh=xBHgliJikVM7NjBc/JAhsTxCKkpKFBjPaZMmBfAKb7o=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=1v4dHaCa6lPWQIGnnAiBg0ftU//Yo1cDU0frSfaB3gygxvaqc5ObwepXdCHqKrJNM
	 E8fJleVgYYsG9lF4qx2UOeHHcdaWOFg2Rg4pbFNZiochsvPAVDA28NaD6JOfWwORjl
	 rDU5UdLQo0i7/uYKP93rMVfBy26iy54vEWODz+sE=
