### ISSUE TITLE
Error: Status 403 trying to pull repository kitematic/hello-world-nginx: "Account is not Active"

### ISSUE THREAD

**Issue by lengruyi** [kitematic/kitematic#1105]
Error: Status 403 trying to pull repository kitematic/hello-world-nginx: "Account is not Active"

**Comment by mchiang0610** [comment]
Hi, 

Currently we are performing a maintenance on Docker Hub. Please check: 
https://status.docker.com/ 
If you are continuing to have problems with Docker Hub, please email support@docker.com for immediate response.
