### ISSUE TITLE
kernel panic

### ISSUE THREAD

**Issue by mcandre** [kitematic/kitematic#1106]
Summary:

The first time I run Kitematic, it crashes my Mac.

Trace:

https://gist.github.com/mcandre/7ef03027fa10ada902db

System:

* Kitematic 0.8.7
* DockerToolbox 1.8.3
* brew cask 0.57.0
* brew 0.9.5
* Mac OS X El Capitan 10.11
* 15" mid-2012 MacBook Pro

**Comment by FrenchBen** [comment]
Looks like Virtualbox didn't play nice with your airport card drivers. Brew shouldn't be in there as Docker Toolbox does all of the work of installing the tools for you. 

Can you confirm your Virtualbox version? As of 10/02/2015 Virtualbox release 5.0.6 which has a kernel panic fix added: https://forums.virtualbox.org/viewtopic.php?f=1&t=73652

**Comment by mcandre** [comment]
Lol, I'm using VirtualBox 5.0.6!

```
$ brew cask info virtualbox
virtualbox: 5.0.6-103037
VirtualBox
https://www.virtualbox.org
/opt/homebrew-cask/Caskroom/virtualbox/5.0.6-103037 (4 files, 87M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/virtualbox.rb
==> Contents
  /Applications/VirtualBox.app/Contents/MacOS/VBoxManage (binary)
  /Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless (binary)
  VirtualBox.pkg (pkg)
```

**Comment by FrenchBen** [comment]
@mcandre If you're up for it - you can try their test builds, see if it solves your problem?
https://www.virtualbox.org/wiki/Testbuilds

**Comment by FrenchBen** [comment]
Closing due to no further details provided
