### ISSUE TITLE
encountered during container pull  

### ISSUE THREAD

**Issue by 0fffh** [kitematic/kitematic#1107]
Error pulling image (latest) from docker.io/library/python, Driver aufs failed to create image rootfs 20b348f4d5682b697d2f456322c97d916bafb65f6c4436697209ac1ec0f1803f: open /mnt/sda1/var/lib/docker/aufs/layers/8b49fe88b40b6c09bbe751e9b235d1919e704ae1765a304226047bd0b203b3fe: no such file or directory

**Comment by FrenchBen** [comment]
Seems that your VM is having some issues - I would shutdown kitematic and reboot the vm:
`docker-machine restart default`

**Comment by mchiang0610** [comment]
This can potentially be a hub problem - hub had some maintenance performed on it. It should be all back to normal. 

check status.docker.com, and if you are continuing to have problems, please email support@docker.com
