### ISSUE TITLE
Tag latest not found in repository docker.io/centurylink/cluster-deploy Not Installed

### ISSUE THREAD

**Issue by vineetsitm09** [kitematic/kitematic#1110]
Hello ,

Please help me to solve this issue.

Tag latest not found in repository docker.io/centurylink/cluster-deploy

Regards-
Vineet Yadav

**Comment by FrenchBen** [comment]
@vineetsitm09 if you look on the Docker Hub you'll notice that the tag doesn't exist:
https://hub.docker.com/r/centurylink/cluster-deploy/tags/

Simply click on the `ooo` next to the image name in Kitematic then select the appropriate tag you'd like to use.

**Comment by vineetsitm09** [comment]
Thanks



On Wed, Oct 14, 2015 at 10:04 PM, FrenchBen <notifications@github.com>
wrote:

> @vineetsitm09 <https://github.com/vineetsitm09> if you look on the Docker
> Hub you'll notice that the tag doesn't exist:
> https://hub.docker.com/r/centurylink/cluster-deploy/tags/
>
> Simply click on the ooo next to the image name in Kitematic then select
> the appropriate tag you'd like to use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/issues/1110#issuecomment-148108640>
> .
>



-- 

*Thanks and Regards*


* Vineet Yadav MSP UIDAI Project *
