### ISSUE TITLE
Enter a passphrase

### ISSUE THREAD

**Issue by WebAndCow** [kitematic/kitematic#1113]
Hi,

When i click on the "Docker CLI" button (bottom left), it opens a new window in the terminal with this :

```
Initializing new SSH agent...
succeeded
Enter passphrase for /Users/{user}/.ssh/id_rsa:
```

It's only the first time i click on it.

When i close the window terminal, and click again (without typing a passphrase before) on the "Docker CLI" button, i don't see anymore the message above and it works normally.

System:

Kitematic 0.8.7
Mac OS X 10.9.5
iMac 21,5" 2013

**Comment by FrenchBen** [comment]
Docker CLI shouldn't be doing anything special with SSH keys - Are you sure you didn't have some recent terminal `.bashrc` changes?

**Comment by WebAndCow** [comment]
Yes, i copied a Github gist, to set-up ssh-agent to deploy with ssh 

```
# Set up ssh-agent
SSH_ENV="$HOME/.ssh/environment"

function start_agent {
    echo "Initializing new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi
```

I think it's the origin of the problem, but i need those lines to deploy in ssh.

Do you have any idea to fix this problem ?

Thanks

**Comment by FrenchBen** [comment]
There is nothing to fix, the code you pasted is what created / generated the key for you. Once the key has been generated then you should be fine. 
Either way this is not a Docker CLI issue #closing but feel free to comment as needed
