### ISSUE TITLE
Error message: ENOENT: no such file or directory, open 'C:\Users\<redacted>\ca.pem'

### ISSUE THREAD

**Issue by jcampon** [kitematic/kitematic#1117]
Hi,

I have this issue with DockerToolbox-1.8.3.exe for Windows 7

I think the problem is that in some parts the VM is referred as "dev" whereas in some other parts (like the real physical path where the VM files are stored, etc) is referred as "default"

What I've done is just regenerate the certificates using the proper VM name and it now works!

Run from the Windows command line:

    Microsoft Windows [Version 6.1.7601]
    Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
    
    C:\Program Files\Docker Toolbox>docker-machine regenerate-certs -f dev
    Regenerating TLS certificates
    Error: Host does not exist: dev
    
    C:\Program Files\Docker Toolbox>docker-machine regenerate-certs -f default
    Regenerating TLS certificates
    
    C:\Program Files\Docker Toolbox>

And that will do the trick!

**Comment by FrenchBen** [comment]
If you had previous versions of Kitematic/VM installed, is possible that errors could've been generated. Moving forward all VM are created with the name of 'default' - It looks like your last command worked and got your up and running. I'll close this for now but feel free to re-open it if the issue happens again.

**Comment by rwatts3** [comment]
How long did the command take for you ?
I'm running around 10 minutes with it just sitting at this screen. 

```
C:\Program Files\Docker Toolbox>docker-machine regenerate-certs -f default
Regenerating TLS certificates
```

**Comment by FrenchBen** [comment]
@rwatts3 Can you try to run it with some debug info?
`docker-machine -D regenerate-certs -f default`
