### ISSUE TITLE
Problem persists while pulling and starting docker containers ETIMEDOUT Error

### ISSUE THREAD

**Issue by ynagarjuna1995** [kitematic/kitematic#1122]
ETIMEDOUT connect 192.168.99.100:2376

Intended docker container to pull is [here](https://hub.docker.com/r/strongloop/node/)
this error arises even with other operations too..[Starting a container,Pulling a Container]

I have restarted the host VM on windows using 
``` docker restart default ```

But same error persists for clear understanding I am attaching the pictures below

Technical Details :
Operating System : Windows 10 
Toolbox Version : 1.8.3 

![image](https://cloud.githubusercontent.com/assets/5663901/10564618/6036f552-75d8-11e5-92c8-709a4d64847d.png)

![image](https://cloud.githubusercontent.com/assets/5663901/10564669/ce70f3f0-75d9-11e5-86f1-e98d389c7b07.png)

**Comment by mchiang0610** [comment]
@ynagarjuna1995 are you connected using proxy / VPN? This is usually a DNS problem with virtualbox.

**Comment by ynagarjuna1995** [comment]
@mchiang0610  No I am not using any VPN/Proxy 

The problem persists even when I try to start my Containers.
