### ISSUE TITLE
Problem caused becuase of Sudden Power Failure : cannot connect to the docker engine either VM is not responding or connection blocked by VPN ETIMED out error

### ISSUE THREAD

**Issue by ynagarjuna1995** [kitematic/kitematic#1123]
I have encountered this after a sudden power failure when I started the system again and start trying to use  docker hangs for sometime trying to set the 
>Environment Variables for the host machine

Technical Details :
Operating System : Windows 10
Toolbox Version : 1.8.3

![image](https://cloud.githubusercontent.com/assets/5663901/10564813/66177eae-75df-11e5-9137-0e9a23ab24ff.png)

**Comment by ynagarjuna1995** [comment]
Issue resolved after restarting my entire operating system windows 10 

Please fix or suggest any solutions in case  these kind of issues arises.

>Same problem persists when I keep my System in Sleep Mode without properly closing/stop/Shutdown docker deamon or Host machine

**Comment by mchiang0610** [comment]
@ynagarjuna1995 are you connected via VPN / proxy?

**Comment by ynagarjuna1995** [comment]
@mchiang0610  I am not using any VPN /Proxy

**Comment by mchiang0610** [comment]
@ynagarjuna1995 This is a problem with VirtualBox causing the VM to not respond. 

Merging with #1029
