### ISSUE TITLE
500 error downloading fedora:latest

### ISSUE THREAD

**Issue by mgoodhand** [kitematic/kitematic#1124]
I attempted to download the official Fedora image using Kitematic 0.8.7 on OSX 10.11 (El Capitan). I got

```
server error 
500 
No command specified
```

**Comment by mchiang0610** [comment]
This seems like the fedora image doesn't specify how to run the container. Please use the command line to run it with the proper switches. 

Thanks!

**Comment by mgoodhand** [comment]
Yep, that works (`docker run -it fedora bash`). Thanks.
