### ISSUE TITLE
docker.io/jboss/wildfly server misbehaving

### ISSUE THREAD

**Issue by gabrielvega** [kitematic/kitematic#1129]
$ docker pull jboss/wildfly
Using default tag: latest
Pulling repository docker.io/jboss/wildfly
Error while pulling image: Get https://index.docker.io/v1/repositories/jboss/wildfly/images: dial tcp: lookup index.docker.io on 200.44.32.10:53: server misbehaving

**Comment by mchiang0610** [comment]
@gabrielvega are you getting this error on the command line as well? 

Please email support@docker.com for immediate support. We really care about the experience of our Docker Hub.

**Comment by gabrielvega** [comment]
Yes, from command line. 

Ok, let me email them.

Thanks!
