### ISSUE TITLE
Problem in creating a container on windows

### ISSUE THREAD

**Issue by vinaydate** [kitematic/kitematic#1134]
Host OS: Windows 10
Tried to create container from image 'nodejs-webpack'. Each time, the window title says 'nodejs-webpack' Downloading. But the contents of 'Home' tab are :
> ETIMEDOUT
> ETIMEDOUT
> connect
> 192.168.99.100
> 2376

**Comment by mchiang0610** [comment]
@vinaydate Thanks for contacting us. This seems like a DNS issue. Are you running this in a proxy or VPN environment? As this relates to Docker Hub, we want to provide you with fast responses -> Please email support@docker.com for fast help. 

Merging this issue with #1030 

Thanks! 
Michael
