### ISSUE TITLE
windows: docker: command not found( docker not added to path)

### ISSUE THREAD

**Issue by Rykka** [kitematic/kitematic#1136]
Running with mingw64 with this problem,
Solved with adding 'C:\Program Files\Docker Toolbox' to $PATH

**Comment by FrenchBen** [comment]
This is more of a toolbox issue than kitematic - Would you mind re-creating this issue within the toolbox hub?
https://github.com/docker/toolbox/issues

**Comment by Rykka** [comment]
done.

**Comment by FrenchBen** [comment]
:+1:
