### ISSUE TITLE
Add volume from OSX

### ISSUE THREAD

**Issue by fabdelgado** [kitematic/kitematic#1139]
It should be able to add volume to the container. With only certain I could map a folder on my OS X.

**Comment by FrenchBen** [comment]
Depending on the image that you're using, the [volume directive](https://docs.docker.com/reference/builder/#volume) may not have been declared, thus it doesn't show up in Kitematic. 

For all images that have the `VOLUME` in their dockerfile, you will be able to map a folder. There's a pending PR #722,  that needs to be update, but would allow you to map volumes even when one wasn't declared in the Dockerfile.
