### ISSUE TITLE
Can't Download geoffd/hhvm-nginx-mongo-base from Kitematci

### ISSUE THREAD

**Issue by pcruse3** [kitematic/kitematic#1140]
Hi,

I am trying to use geoffd/hhvm-nginx-mongo-base, but I get this error:

`Tag latest not found in repository geoffd/hhvm-nginx-mongo-base`

Any idea how to fix?

**Comment by mchiang0610** [comment]
@pcruse3 it seems like it's a problem with the repo ( wasn't tagged with latest (https://hub.docker.com/r/geoffd/hhvm-nginx-mongo-base/tags/ ) ) 

You can try to select the particular tag through kitematic (latest being 1.0.1) 

Hope this helps. 

Thanks
