### ISSUE TITLE
Error : Stderr: Error creating machine: exec: "VBoxManage":

### ISSUE THREAD

**Issue by Ternoc** [kitematic/kitematic#1142]
I try to lunch kitematic on Windows 10 (64bit) and I get this error : 
i don't find how to fix this
Thanks.
![2015 10 26 14 52 24](https://cloud.githubusercontent.com/assets/11840322/10730582/2f9a8d68-7bf1-11e5-9fd4-15e177f11c84.png)

```
D:\Program Files\kitematic\resources\resources\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Error creating machine: exec: "VBoxManage": executable file not found in %PATH% You will want to check the provider to make sure the machine and associated resources were properly removed.
```

**Comment by FrenchBen** [comment]
Did you install it via the [Docker Toolbox](https://www.docker.com/toolbox)?

**Comment by Ternoc** [comment]
Yes

**Comment by FrenchBen** [comment]
Did you uncheck VirtualBox install? Can you confirm that it was installed properly?

**Comment by Ternoc** [comment]
Yes, I unistalled Docker, kitematic and Virtual Box and reinstalled the whole thing

**Comment by FrenchBen** [comment]
Can you check your Env vars and post them here?
It should also have the Docker toolbox path defined:
![windows env](https://cloud.githubusercontent.com/assets/251292/10656552/adaedb20-7834-11e5-8881-d5402d3fee37.png)

**Comment by Ternoc** [comment]
I resolved the problem by installing Docker Toolbox on the OS SSD

**Comment by FrenchBen** [comment]
:+1: Good to hear this was resolved.
