### ISSUE TITLE
Make Kitematic use VMware Fusion if available

### ISSUE THREAD

**Issue by sammcj** [kitematic/kitematic#1147]
Kitematic doesn't detect that VMware Fusion is installed and tries to install or use Virtualbox.

Boot2Docker works with VMware Fusion, so i it seems it's just the Kitematic interface that needs updating.

- It is not recommended to install both VMware Fusion and Virtualbox at the same time.
- As to why individuals may not want to run Virtualbox - it has several major IO performance and networking issues and well, there's Oracle... (Not that VMware are saints either mind you, but at least their desktop virtualisation performs well and is stable).
- VMware Fusion is widely deployed in many organisations that run OSX.

**Comment by beni05** [comment]
Apple Pay encrypts any credit/debit cards added to the passbook app on supported Apple devices. Apple Pay assigns a device-specific tokenized credit card number called a DPAN that Braintree will use to process transactions securely.??

**Comment by sammcj** [comment]
> Apple Pay encrypts any credit/debit cards added to the passbook app on supported Apple devices.  Apple Pay assigns a device-specific tokenized credit card number called a DPAN that Braintree will use  to process transactions securely.??

@beni05 I think you commented on the wrong issue.

**Comment by beni05** [comment]
• Use only the button artwork provided by Apple.
• Apple Pay payment buttons must always invoke the
Apple Pay payment sheet.
• Set up Apple Pay buttons must always initiate the
setup sequence.
• Select a button height that is equal in size or larger
than other checkout buttons.
• Select the logo-only version of the button for use
within a non-English interface.
• Use the same version of the button for both portrait
and landscape formats.
• Select a button color option that provides sufficient
contrast to the surrounding background,,

**Comment by FrenchBen** [comment]
@sammcj It's not a question of detecting VMware or another VM-like provider, but rather the ability to provide open-source/free VM management software. 
There was an attempt to add some config to Kitematic in order to support the different driver/providers, but it's a bit of hack: https://github.com/kitematic/kitematic/pull/1108

Allowing the user to select a VM that's been registered with docker-machine would be the way to go. I may create a PR for something like that.

**Comment by FrenchBen** [comment]
Closing with future PR in mind
