### ISSUE TITLE
How to set the icon for a repo?

### ISSUE THREAD

**Issue by michaelwilde** [kitematic/kitematic#1148]
Not really a bug/issue, but how does one set the icon for a repo, so there is something other than the whale?   Recommended repo's all have cool icons... i'd like my own pub/privates to have their own icons too.  How to do i do that?

**Comment by FrenchBen** [comment]
Currently this is setup in a hard-coded way, where the 'recommended' images have an `img` entry defined, that is then pulled from the web:
https://kitematic.com/recommended.json

Ideally this would be a feature of the repo that you're using, where an icon could be added.

**Comment by michaelwilde** [comment]
That would be really sweet... maybe even in the build or push step?  Or heck have it a feature of registry / hub / DTR as long as Kite can view it.

**Comment by FrenchBen** [comment]
If it's in Hub, Kitematic would be able to use it. 
You can open up a ticket for it here:
https://github.com/docker/hub-feedback

**Comment by FrenchBen** [comment]
Closing this in favor of an issue opened with Hub :)

**Comment by michaelwilde** [comment]
Hey ben.. i just opened up hub issue. https://github.com/docker/hub-feedback/issues/431

**Comment by FrenchBen** [comment]
Thanks @michaelwilde I believe it's an up and coming feature. The issue just makes sure there is more leverage for it to happen sooner ;)
