### ISSUE TITLE
Support for containers that do not expose ports.

### ISSUE THREAD

**Issue by jeffdm** [kitematic/kitematic#115]
Right now Kitematic doesn't provide much support for containers run with a TTY-only interface, or any containers that don't expose ports.

**Comment by BKreisel** [comment]
Any news on this feature? I'd be very interested in a solution that spawns a shell/cli to interact with

**Comment by jeffdm** [comment]
Support for CLI-only containers will be in Kitematic 0.5.

**Comment by BKreisel** [comment]
Thanks. Great work so far!

**Comment by jeffdm** [comment]
0.5 includes support for containers without open ports.
