### ISSUE TITLE
.8.7 not starting Docker VM after upgrade 

### ISSUE THREAD

**Issue by linit01** [kitematic/kitematic#1159]
Using Kitematic after upgrading to 8.7 on OSX my Docker VM will not boot.  I have tried deleting it and having it recreated but get same error, Machine IP could not be fetched.  Any others having this issue and know the fix?

**Comment by FrenchBen** [comment]
Did you use the Docker Toolbox to install everything?

**Comment by linit01** [comment]
Yes I did. I got it working again when I noticed that my version of VirtualBox was out of date.  After upgrade I was able to use the app again.

**Comment by linit01** [comment]
Yes I did. I got it working again when I noticed that my version of VirtualBox was out of date.  After upgrade I was able to use the app again.

**Comment by FrenchBen** [comment]
:+1:  Can you close the issue since it is now resolved?
