### ISSUE TITLE
Error pulling image (latest) from docker.io/sequenceiq/spark, Untar re-exec error: exit status 1: output: write /usr/java/jdk1.7.0_51/jre/lib/amd64/libjfxwebkit.so: no space left on device

### ISSUE THREAD

**Issue by guoziyan** [kitematic/kitematic#1162]
Error pulling image (latest) from docker.io/sequenceiq/spark, Untar re-exec error: exit status 1: output: write /usr/java/jdk1.7.0_51/jre/lib/amd64/libjfxwebkit.so: no space left on device

**Comment by FrenchBen** [comment]
Looks like you ran out of disk space. How big is your hard drive?

**Comment by guoziyan** [comment]
Thanks! But I find the reason may be the bad internet connection.  I'm  live in China.  So there are some  difficulties in visit some sites.

**Comment by FrenchBen** [comment]
Very likely yes - A stable/good connection is assumed and having intermittent connections will cause some issues.
Closing this for now.
