### ISSUE TITLE
roadmap feature request: view tweak to support for multiple docker-machine and/or docker

### ISSUE THREAD

**Issue by a1exus** [kitematic/kitematic#1171]
I'm running few docker-machines, digitalocean, getcarina and local. It'd be very useful to interact with all of docker-machine via Kitematic and not just local docker-machine.

Is that something that can be considered for future roadmap?

**Comment by FrenchBen** [comment]
Hi @a1exus It is something that's been discussed previously as seen in the wiki, under machine management:
https://github.com/kitematic/kitematic/wiki/Machine-Management
