### ISSUE TITLE
How to setup dm.basesize

### ISSUE THREAD

**Issue by jardakiss** [kitematic/kitematic#1173]
Hello, 

is there any chance how to set the "dm.basesize" option when Kitematic starts the docker daemon, pelase?

Thanks

**Comment by FrenchBen** [comment]
@jardakiss Since this seems to be a 1 time operation that can be done on the VM directly, there isn't much use for Kitematic to have this implemented. 
http://docs.docker.com/engine/reference/commandline/daemon/
