### ISSUE TITLE
Show the number of pulls/downloads like docker hub

### ISSUE THREAD

**Issue by aadrian** [kitematic/kitematic#1175]
Please show the number of downloads/pulls like docker hub does. The number of "stars" does not help that much when searching for an image candidate.

**Comment by FrenchBen** [comment]
Would something like this be good enough?
![show-pull-count](https://github-cloud.s3.amazonaws.com/assets%2F3965324%2F10957508%2Fd3ad799a-8319-11e5-97a8-9f724c4665c9.png)

**Comment by aadrian** [comment]
> Would something like this be good enough?

Yes! That would be fantastic! :).
