### ISSUE TITLE
Error when installing minecraft

### ISSUE THREAD

**Issue by tribet84** [kitematic/kitematic#1176]
Every time I try to install the minecraft container I got this error

**Comment by FrenchBen** [comment]
Do you have the actual error?

**Comment by tribet84** [comment]
ETIMEDOUT
ETIMEDOUT
connect
192.168.99.100
2376

**Comment by tribet84** [comment]
I restarted my laptop and now it works... ANyway

**Comment by FrenchBen** [comment]
:+1: When in doubt restart ;)
