### ISSUE TITLE
Unable to start a container on Kitematic

### ISSUE THREAD

**Issue by abov** [kitematic/kitematic#1178]
After rebuilding the db (docker-compose build), then starting the containers (docker-compose up), I get this error message in iterm:

Creating api_db_1...
Creating api_api_1...
Cannot start container 2efe68861fe1e76550659f05b46c3e718e4c432cdbfb3fe14ef83b3da88690a2: Cannot link to a non running container: /api_db_1 AS /api_api_1/api_db_1

End

Then, I tried starting the containers in Kitematic (created after running docker-compose up) and here is the first error message:

[ERROR] InnoDB: Failure of system call pwrite(). Operating system error number is 28.
InnoDB: Error number 28 means 'No space left on device'.
InnoDB: Some operating system error numbers are described at
InnoDB: http://dev.mysql.com/doc/refman/5.6/en/operating-system-error-codes.html

**Comment by FrenchBen** [comment]
Can you share your docker-compose file?

**Comment by abov** [comment]
It seems I've branched off of a failed branch. Just rebuilt the db from another branch and received no errors.

**Comment by FrenchBen** [comment]
:+1:
