### ISSUE TITLE
Installing git during Kitematic installation

### ISSUE THREAD

**Issue by egorzot** [kitematic/kitematic#1184]
I already have git installed in C:\Program Files (x86)\Git.
During Kitematic installation it's impossible to unselect "git installation".
So, is it going to install the different copy of git in its own directory or it will try to reinstall my git? Won't it cause any errors? Won't it damage my git files?

**Comment by FrenchBen** [comment]
Can you open this within https://github.com/docker/toolbox as this section is for Kitematic related issues only.
Thanks!
