### ISSUE TITLE
How to change the vboxnet network

### ISSUE THREAD

**Issue by sirkkalap** [kitematic/kitematic#1185]
I will have to use 192.168.50.0/24 for VirtualBox host network, because company VPN splits only this network and terrorizes all other networks.

On boot2docker this was easy: https://gist.github.com/sirkkalap/ccaac0d307ef8da08c2d

However with the new toolchain I am totally lost.

**Comment by nathanleclaire** [comment]
There is a machine option `--virtualbox-hostonly-cidr` which you might be able to use.

**Comment by sirkkalap** [comment]
Thanks. I will use that.
