### ISSUE TITLE
Question: Why volumes only can be specified if they are under the Users directory (Windows)

### ISSUE THREAD

**Issue by alexandrev** [kitematic/kitematic#1192]
I'm using Kitematic for Windows, and when I try to specify the host path for a VOLUME sentence in my docker container, I'm getting this error:

![image](https://cloud.githubusercontent.com/assets/947041/11016767/98c686e6-858a-11e5-9827-8e0327a10294.png)

If I specify a folder inside my User folder, everything is OK. But I don't understand that kind of restriction. Even more, in the Windows system, when I can have different volumes mounted with different folders and it has no sense to be restricted to your User folder.

Why is that reason and could be change for next versions at least in Windows systems? Maybe if you have to be sure that the user has full access, we can restrict the Owner of the folder or something like that...

What do you think? 

Thanks!!

**Comment by mchiang0610** [comment]
@alexandrev Thanks for reporting this. We will pass this on to the Docker machine team for a fix. 
cc/ @nathanleclaire

**Comment by alexandrev** [comment]
Thanks @mchiang0610, If I could do more, please let me know. I'm here to help in everything I can.

**Comment by mchiang0610** [comment]
@alexandrev Can you provide us logs / your windows version as well for us to reproduce this?

**Comment by alexandrev** [comment]
The windows version is windows 10 build 10586. Please, tell me which logs
you want and I'll provide it to you.

Thanks,

**Comment by FrenchBen** [comment]
@alexandrev The reason behind this is linked to the VM - When the Virtualbox is created it mounts the folders within your `Users` directory, which makes it the only folder available to the containers.
You're getting the error due to this restriction and you were probably trying to mount folders outside of the `Users` path

**Comment by alexandrev** [comment]
I know the error, as you said is because i'm trying to mount a volume from
another folder but why is the reason for this restriction?

Could I personalize the folder that it is mounted inside the vm?? Any way
to customize these options?

**Comment by FrenchBen** [comment]
@alexandrev In theory you could add more folders to the VM - It's impossible for us to know what folders are available or unavailable, but the `Users` directory will always be there. There isn't a straight-forward way for us to check what folders have been mounted by the user within the VM; We added the check within the code to make sure that we could read/write to the folder.

Most developers will work out of their user folders/desktop and thus never see this restriction. Feel free to create a PR that allows for greater flexibility :)

**Comment by alexandrev** [comment]
OK, I want to try it. We can close this question because now I know the
reason of the message.

Thank you all for the time you spend answering this question :)

**Comment by FrenchBen** [comment]
:+1: You're welcome!
