### ISSUE TITLE
problem with docker pull

### ISSUE THREAD

**Issue by geoHeil** [kitematic/kitematic#1195]
Hi kitematic does not support downloading from https://hub.docker.com/r/andypetrella/spark-notebook/ as the tags cannot be selected.

only the cli with something like this docker pull andypetrella/spark-notebook:0.6.2-SNAPSHOT-scala-2.10.4-spark-1.5.1-hadoop-2.7.1 works

**Comment by mchiang0610** [comment]
Hi @geoHeil  You can select the tags by clicking the "..." button. 

![image](https://cloud.githubusercontent.com/assets/3325447/11023144/46cfef62-8625-11e5-9443-ace1aaeb868d.png)

Hope that helps.
