### ISSUE TITLE
We're sorry. There seem to be an error: Error pulling image for china user.

### ISSUE THREAD

**Issue by zming619** [kitematic/kitematic#1203]
i live in china，

kitematic error msg:
Error pulling image (latest) from docker.io/library/memcached, Server error: Status 0 while fetching image layer (575489a51992d5d30976ff5ba7f7eabdc134acfb51c79ff48883089009594e64)

**Comment by FrenchBen** [comment]
Unfortunately if you're behind a proxy or have network issues, as often seen in China, you may run into some issues.

**Comment by zming619** [comment]
it should be a network problem, thank you very much for your responses
