### ISSUE TITLE
Error recreating the container after a change in the volume local path 

### ISSUE THREAD

**Issue by alexandrev** [kitematic/kitematic#1205]
When I have a container running and I want to change the local folder in one of the volume definition, the container stop and try to restart (as I think it is the normal behavior) but cannot do it because there are a port collision and I get this error:

![image](https://cloud.githubusercontent.com/assets/947041/11102935/c8902d7c-88bf-11e5-9ba8-f7321e25c6a3.png)

When this happens  I cannot operate with the container (I cannot start it again or remove it or do anything with it). My only choice is to restart the kitematic application and it's gone for once.

This doesn't happen all the times but usually (80%) and I don't see the port is occupied (no LISTEN or WAIT when I do a netstat inside the VM)

**Comment by FrenchBen** [comment]
Did you pull the latest master? Some of the port binding logic was updated recently. 
Is the image private or can I get it from docker hub in order to replicate this?

**Comment by alexandrev** [comment]
Yeah, I test it from the master. To reproduce that error I used a private
dockerfile but I'm going to try to reproduce with a public one so you can
test it too.

I'll keep you posted.

-- Sent from my mobile phone. Please excuse any typo.

**Comment by alexandrev** [comment]
I haven't been able to reproduce this error with different public repos (I tried with the hello-ngnix, tutum/centos and rabbitmq) so I'm pretty sure that the problem is with the private dockerfile I'm using and no with the program. So, I'm closing the issue now.

Thanks a lot anyway!!

**Comment by FrenchBen** [comment]
:+1:
