### ISSUE TITLE
docker-run fails to pull image with certificate error on Windows 7

### ISSUE THREAD

**Issue by luispollo** [kitematic/kitematic#1207]
Trying to setup docker on Windows 7 for the first time using the Docker Toolbox. Getting the following error trying to run the hello-world image:

$ docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: x509: certificate is valid for FG3K6C3A15800002, not index.docker.io

$ docker --version
Docker version 1.9.0, build 76d6bc9

I get the same error on Powershell, Bash or Kitematic. I'm behind a corporate proxy and have both the http_proxy and no_proxy environment variables set to allow docker to connect to the internet, but avoid using the proxy for my Docker VM in VirtualBox.

**Comment by FrenchBen** [comment]
@luispollo Did you follow the guide for the proxy settings?
https://github.com/kitematic/kitematic/wiki/Common-Proxy-Issues-&-Fixes

I may have not read your last sentence properly - Did you setup the VM with the proper proxy settings or you did not?
It looks like your proxy is modifying the certificate which is causing some issues

**Comment by luispollo** [comment]
Thanks @FrenchBen! I had missed exporting the env variables inside the VM. Thanks for the link! 
I'm not sure what's the right channel to suggest this, so I'll write it here, but it would be great to add a pointer to this kind of troubleshooting information in the main Docker documentation, since this will affect every type of installation behind corporate firewalls, which I'm guessing is pretty common. In my previous experience with container environments (using LXC), getting these nitty gritty details of the networking setup right inside the corporate network was by far our top cause of issues with developer environments.

**Comment by FrenchBen** [comment]
:+1: Glad you were able to get this resolved @luispollo
