### ISSUE TITLE
bug: Cannot connect to the Docker daemon. Is the docker daemon running on this host? Ubuntu 14.04

### ISSUE THREAD

**Issue by hasanmehmood** [kitematic/kitematic#1219]
Hello Everyone!
I am facing the same issue, I have installed docker on Ubuntu 14.04 64 bit. I have did everything to make this error remove but failed.

     hassan@hassan-Inspiron-3420:~$ docker run hello-world
     Cannot connect to the Docker daemon. Is the docker daemon running on this host?

     hassan@hassan-Inspiron-3420:~$ docker version
     Client:
     Version:      1.9.0
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   76d6bc9
     Built:        Tue Nov  3 17:43:42 UTC 2015
     OS/Arch:      linux/amd64
     Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Any help on this issue will be highly appreciated, Thanks.

**Comment by FrenchBen** [comment]
Did you follow the instructions found on https://docs.docker.com/engine/installation/ubuntulinux/

**Comment by hasanmehmood** [comment]
@FrenchBen Thanks man, problem solved :+1: 
Previously I followed these steps and got the error, http://docs.docker.com/linux/step_one/
