### ISSUE TITLE
Reloading the UI makes the VM stats go away

### ISSUE THREAD

**Issue by Jellyfrog** [kitematic/kitematic#122]
`⌘+R` makes the stats go away:
![screenshot 2014-12-02 23 12 47](https://cloud.githubusercontent.com/assets/759887/5271965/c55d7750-7a78-11e4-8f13-9950cc7d6dd5.png)

**Comment by jeffdm** [comment]
This was fixed in a previous version. CMD + R is no longer available as a hotkey. Since the UI automatically updates upon any changes there shouldn't be a reason to refresh.

Thanks for the bug report!
