### ISSUE TITLE
dataiku

### ISSUE THREAD

**Issue by Abramrm** [kitematic/kitematic#1224]

**Comment by FrenchBen** [comment]
Closing not enough information provided

**Comment by Abramrm** [comment]
Mister,

I did not understood the message you sent me. I installed DSS on my
computer in order to be part of the DataScience Challenge organized by
Datalyo, in Lyon, France.
After installing DSS I subscribe on your website in order to activate the
program. How can I get the activation number ?

Thank you in advance,

Abram Rojas

Le mercredi 18 novembre 2015, French Ben <notifications@github.com> a
écrit :
