### ISSUE TITLE
Feature Request: Third-party docker registries integration

### ISSUE THREAD

**Issue by alexandrev** [kitematic/kitematic#1225]
Nowadays Kitematic lives with the images we can pull from the Docker Hub. Ok, that's not exactly true because any other image we can build inside our environment we can manage it inside our Kitematic but you know what I mean.

Docker Hub is the main source of images, that's true and it has no point to argue about that, but more frequently in each company are creating their own registries with their own images and custom environments and in Kitematic we are not providing an easy way to integrate with these kind of registries. 

So, my idea is to provide a way to integrate with third-party system the same way we do with the Docker Hub registry, so any person inside a company can pull images from their registry (or even push it from there).

What do you think about this feature? Do you think it is worth it?

Best regards,

**Comment by dannc** [comment]
I believe what you're discussing is already asked for in issue #232.  The gating issue with that being that docker private repos do not include search functionality as does e.g DockerHub and Docker Trusted Repository, so that image repositories would not be "discoverable."  Third-party registries might even have their own custom search mechanisms as well.

**Comment by alexandrev** [comment]
Hi @dannc , many thanks for your information. I wasn't awared that there wasn't any standard form to query or search inside a private repository. So, I guess with that information that implement a feature like the one I'm request is not a very feasible task.

**Comment by dannc** [comment]
You might want to validate with @FrenchBen, who already make a PR for this feature, only to find out that at least the private registries didn't contain the search feature.  Don't really know about 3rd party ones like Quay.io, etc.

**Comment by FrenchBen** [comment]
Closing in favor of #210
