### ISSUE TITLE
Docker links not working after upgrading to 1.9

### ISSUE THREAD

**Issue by marceloschmidt** [kitematic/kitematic#1227]
I'm running Kitematic on Mac OSX, El Capitan. After upgrading Docker to 1.9 and Kitematic to 0.9.3, the links are not automatically available for the containers.
I'm running a mongo container and a rocketchat/rocket.chat one. Rocket.Chat cannot access the mongo instance using the container name as it used to before. Was this by design? How does Kitematic deal with links between containers?

TIA

**Comment by alexandrev** [comment]
Kitematic doesn't deal with links between container that's the job of the docker daemon itself.

**Comment by marceloschmidt** [comment]
Yeah, I found out there were lots of requests for linking via Kitematic. I'm closing this.

**Comment by marceloschmidt** [comment]
Thanks
