### ISSUE TITLE
The container does not start on Windows 7 behind proxy

### ISSUE THREAD

**Issue by xaircore** [kitematic/kitematic#1230]
Error while pulling image: Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp 54.172.178.86:443: connection refused

**Comment by alexandrev** [comment]
Could be posible that you are behind any kind of firewall or proxy? If it's the case, you should try to read this documentation where it explains to you how to proceed: https://github.com/kitematic/kitematic/wiki/Common-Proxy-Issues-&-Fixes . Please, come back to us if it that's not helping you to solve your issue.

**Comment by xaircore** [comment]
@alexandrev Thank you, it worked
