### ISSUE TITLE
Cannot install from active repo

### ISSUE THREAD

**Issue by markmaunu** [kitematic/kitematic#1236]
Hello I am trying to install cuckoo sandbox from the repo below 
https://hub.docker.com/r/jgajek/cuckoo-docker/

I get the error below:

Tag latest not found in repository docker.io/jgajek/cuckoo-docker

Any help provided to get this installed wold be great thanks.
Mark

**Comment by FrenchBen** [comment]
This is a non-issue, if you look at the tags available for that repo, you'll see that there isn't a 'latest' tag.
Prior to creating the container based on that image, simply select a different tag from within Kitematic:
![image](https://cloud.githubusercontent.com/assets/3965324/11345653/4f794f9c-91cd-11e5-9fb9-50f25926043f.png) - Click the 3 dots 'ooo'
![tag-select](https://cloud.githubusercontent.com/assets/3965324/11345658/5b9216e2-91cd-11e5-82ea-58af0c7e742d.png) - Click select tag
![tag-list](https://cloud.githubusercontent.com/assets/3965324/11345661/60edb5b0-91cd-11e5-80b2-ffd1c4789765.png) - Click the tag of choice
