### ISSUE TITLE
Add support for --tls-san command line argument of Docker Machine

### ISSUE THREAD

**Issue by ChrisPearce** [kitematic/kitematic#1239]
The --tls-san command line argument appears to be have been merged ( https://github.com/docker/machine/pull/2356) and targeted for milestone 0.5.2 of Docker Machine.

This adds the ability to add extra SANs to all server-side certificates generated by docker machine.

It would be very useful if there was a way that this command line argument could be set and used when Kitematic uses Docker Machine for creation.

**Comment by FrenchBen** [comment]
@ChrisPearce We currently don't have any machine 'tools' within Kitematic, but it would be good to see it better integrated. 
IMHO for most cases, the --tls-san option wont be needed, but if it is, it's simple enough to re-create the VM via the command line. 
Closing this until a proper machine tool is integrated within Kitematic - Added the feature request to the wiki on Machine management:
https://github.com/kitematic/kitematic/wiki/Machine-Management
