### ISSUE TITLE
allow url/ports to be copied to the clipboard or clicked on in kitematic.

### ISSUE THREAD

**Issue by rayarachelian** [kitematic/kitematic#1240]
Under the "Home" tab for each container, Kitematic shows IP addresses and ports for each container under "IP and Ports" as docker port and address url.

It would be useful if these were turned into clickable URLs, (they're already shown as URLs) or if they were at least capable of being selected and copied to the clipboard.

![image](https://cloud.githubusercontent.com/assets/13457566/11351750/7a8c6528-9206-11e5-8828-31a42c8420c9.png)

**Comment by FrenchBen** [comment]
This feature has actually been implemented, but a few additional changes are in the pipeline prior to being a proper release. 
You should now see an output similar to:
![access-url](https://cloud.githubusercontent.com/assets/3965324/11352270/4a70b72e-91f0-11e5-894f-28c1a591642d.png)
With the ip:port combo as a selectable area.
