### ISSUE TITLE
TERM environment variable not set

### ISSUE THREAD

**Issue by roncanepa** [kitematic/kitematic#149]
Fresh install of Kitematic v.0.4.3 and the "example master" from https://kitematic.com/docs/building-an-image/ .   Edit to add:  OS is Yosemite 10.10.1

After building the image, creating+starting a container, and then clicking the "terminal" icon, I get a terminal session but all commands fail with: "TERM environment variable not set"

I've seen elsewhere online that the "clear" in the passed shell command "clear && [...]"  can sometimes cause this issue.

**Comment by jeffdm** [comment]
Thanks!

Should be fixed in 0.5, but feel free to re-open.
