### ISSUE TITLE
Kitematic suspends my boot2docker vm when I quit

### ISSUE THREAD

**Issue by programmerq** [kitematic/kitematic#154]
Normally, I interact with boot2docker directly or from scripts. If I open kitematic, it does use my existing boot2docker VM, but when I quit Kitematic, my boot2docker VM is suspended. This is disruptive to my workflow.

**Comment by jeffdm** [comment]
Thanks Jeff! We've heard this a lot, there needs to be a better default & way to configure this.

**Comment by jeffdm** [comment]
Fixed in 0.5! This was turned off by default but can be re-enabled in the app settings.
