### ISSUE TITLE
Error: Boot2Docker SSH key doesn't exist.

### ISSUE THREAD

**Issue by ianwalter** [kitematic/kitematic#155]
When I open Kitematic I get the following error:

Error: Boot2Docker SSH key doesn't exist. Fix by removing the existing Boot2Docker VM and re-run the installer. This usually occurs because an old version of Boot2Docker is installed.

1. I don't have boot2docker installed
2. There aren't any VMs in Virtual Box (other than a couple I created with Vagrant)

Any ideas on how I can fix this?

**Comment by jeffdm** [comment]
Interesting and thank you for posting the issue!

Boot2Docker comes packaged with Kitematic. Upon loading it should create ssh keys similar to `~/.ssh/id_boot2docker`. It seems like this didn't happen. Do any of the following work:

- Re-run Kitematic
- Remove `~/.boot2docker` if it exists.
- Download boot2docker (`brew install boot2docker` and `boot2docker init`)

I hope this helps! I'll try running this in a blank vm to reproduce.

Thanks again

**Comment by ianwalter** [comment]
Looks like that worked, thanks!

**Comment by jeffdm** [comment]
Good to hear. Which step fixed it? Did you need to resort to installing boot2docker with brew?

Thanks!

**Comment by ianwalter** [comment]
Yup, I had to install boot2docker, run `boot2docker init`, and restart Kitematic.

**Comment by jeffdm** [comment]
Good to know. The detection for an existing Boot2Docker setup must be broken.

Thanks Ian!

**Comment by jeffdm** [comment]
Fixed in 0.4.5
