### ISSUE TITLE
First letter of each line in logs being cut off

### ISSUE THREAD

**Issue by ianwalter** [kitematic/kitematic#156]
Here's an example of what I'm seeing:

`lling MySQL ...`

When it should be:

`=> Installing MySQL ...`

Maybe we can stop slicing the log line here:
https://github.com/kitematic/kitematic/blob/master/meteor/client/lib/apputil.js#L121

If I do that, I see a bunch of lines with a seemingly random character. Wrapping the `Apps.update` call with this condition seems to work:
```js
if (line.length > 8) {
```

**Comment by jeffdm** [comment]
Hi - thanks for the issue!

This is because we incorrectly parse the stream returned by the Docker remote API's logs API. Will fix in 0.5.

**Comment by jeffdm** [comment]
Fixed in 0.5
