### ISSUE TITLE
UX suggestions

### ISSUE THREAD

**Issue by nathanleclaire** [kitematic/kitematic#190]
- Always display icons together with text, and vice versa.  Right now it seems in the top buttons the text only shows up on hover, IMO it should just show all the time.

- Make it so that when you hover over something clickable (e.g. the web view), the mouse pointer coverts to the "pointer" (the little glove with the pointer finger).  I like the color change, but this cursor change on hover is the universal idiom for "I can be clicked and it will do something!"  In CSS this rule is something like 

```css
a:hover {
    cursor: pointer;
}
```

if I recall correctly.

I think I had one more, so I'll post if I remember it.

**Comment by nathanleclaire** [comment]
Oh yes, I remembered the last one.  In any case where you're displaying something that goes `host => container` e.g. volumes and ports, make sure that you get the order consistent with what Docker displays (it always is `host => container`).

**Comment by Elesant** [comment]
Thanks for the suggestions @nathanleclaire! :)

**Comment by nathanleclaire** [comment]
:+1:

**Comment by mchiang0610** [comment]
- Made buttons more obvious, and there are tooltips on hover
