### ISSUE TITLE
run binaries from resources path without copying to host 

### ISSUE THREAD

**Issue by pandrew** [kitematic/kitematic#205]
Kitematic seems to copy docker and docker-machine binaries to the host system. I use multiple docker and machine binaries in my path and i am worried theres a conflict between the two. Also i don`t want to fill my hdd with stuff that i don't know is being put there. It would be great if there is some notification of what is being installed. However by looking at the code it looks as if it runs from resources?:

```
  command: function () {
    return path.join(process.cwd(), 'resources', 'docker-machine-' + this.version());
  },```

**Comment by jeffdm** [comment]
The app is entirely self-contained except for:
- Downloading & Installing VirtualBox if you don't have it already
- Copying the latest `docker` and `docker-machine` binaries to `/usr/local/bin` _for convenience_. But I agree this isn't very transparent.

We'll make this more clear on the download page. Thoughts? Thanks for the issue!

**Comment by mchiang0610** [comment]
@pandrew assuming this is okay. Closing for now. Please re-open if you'd like more information. 

Thanks!
