### ISSUE TITLE
Error with development version

### ISSUE THREAD

**Issue by razmo** [kitematic/kitematic#219]
I would like to contribute to this project but i got some error when i run "npm start"

![screen shot 2015-03-05 at 11 56 50](https://cloud.githubusercontent.com/assets/1369214/6503608/d6a6ef10-c32e-11e4-9ee4-e095edb947a7.png)

Anyone have the same issue ?

**Comment by jeffdm** [comment]
Just pushed a change to fix this - sorry about that. Pull & try again and it should work!
