### ISSUE TITLE
Non-Zero Exit - No IP address found 4: eth1 / Error creating machine

### ISSUE THREAD

**Issue by schmunk42** [kitematic/kitematic#221]
Even after removing Library/Application Support/Kitematic and VM.

```
/Applications/Kitematic (Beta).app/Contents/Resources/app/resources/docker-machine-0.1.0 create -d virtualbox --virtualbox-memory 2048 devreturned non zero exit codetime="2015-03-05T20:35:14+01:00" level="info" msg="Creating SSH key..." time="2015-03-05T20:35:14+01:00" level="info" msg="Creating VirtualBox VM..." time="2015-03-05T20:35:23+01:00" level="error" msg="Error creating machine: exit status 1" time="2015-03-05T20:35:23+01:00" level="warning" msg="You will want to check the provider to make sure the machine and associated resources were properly removed." time="2015-03-05T20:35:23+01:00" level="fatal" msg="Error creating machine" 
/Applications/Kitematic (Beta).app/Contents/Resources/app/resources/docker-machine-0.1.0 create -d virtualbox --virtualbox-memory 2048 devreturned non zero exit code
```

**Comment by jeffdm** [comment]
This is a tough bug. It's usually due to an error in VirtualBox. The following command may fix this:

```
docker-machine rm -f dev
```

Then running Kitematic again. If it persists, try installing the latest VirtualBox and trying again. This should clear out the error.

This has happened to a couple people now, so I'm eager to know what works. Please let me know! Thanks for filing the issue.

**Comment by schmunk42** [comment]
Tried `rm`, VBox update and `rm` again.... without luck

First error:

```
Could not reach the Docker Engine inside the VirtualBox VM
```

I tried to create the dev machine manually

```
Kraftbuch:~ tobias$ docker-machine create -d virtualbox --virtualbox-memory 2048 dev
INFO[0005] Creating SSH key...                          
INFO[0005] Creating VirtualBox VM...                    
INFO[0016] Starting VirtualBox VM...                    
INFO[0016] Waiting for VM to start...                   
ERRO[0070] Error creating machine: No IP address found 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:75:bf:20 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe75:bf20/64 scope link 
       valid_lft forever preferred_lft forever
 
WARN[0070] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0070] Error creating machine 
```

Any ideas how to work around the interface issue?
I'll now try to build `docker-machine` from master ...


Semi-related: https://github.com/docker/machine/issues/237

**Comment by jeffdm** [comment]
Are you on a VPN? What's the output if you run `docker-machine create -d virtualbox --virtualbox-memory 2048 dev -D`  (with the -D flag)?

**Comment by jeffdm** [comment]
Another thing to try:

`rm -rf ~/.docker/machine/machines/dev`

**Comment by schmunk42** [comment]
Nope. I traced it down to the line in `docker-machine` even tried to patch on master there.
All without luck :(

Here's the issue: https://github.com/docker/machine/issues/721

**Comment by schmunk42** [comment]
Workaround available: https://github.com/docker/machine/issues/721#issuecomment-77481245

**Comment by stevengssns** [comment]
Fyi, the workaround mentioned above didn't fix it for me. However, a bit further down the same thread I found one that did.

https://github.com/docker/machine/issues/721#issuecomment-88340886

**Comment by mchiang0610** [comment]
@timothyjlaurent suggested: https://github.com/kitematic/kitematic/issues/379#issuecomment-94086601

**Comment by SDavis1813** [comment]
Hi Guys-

Hoping someone can help... Trying to install/use VirtualBox and E-VIDENT on MacBook.  I have a VB icon on desktop now.  Went through steps of installing Evident, but wont run. IM NOT A PROGRAMER! Just a PhD student trying to wade through programing jargon that is making my brain hurt!! What am I doing wrong?? Any guidance appreciated!!

**Comment by mchiang0610** [comment]
@SDavis1813 Is this on Kitematic / Docker related.

**Comment by mchiang0610** [comment]
Merging with #1029
