### ISSUE TITLE
Enabling vm shutdown preference when quitting Kitematic does not work all the time. 

### ISSUE THREAD

**Issue by kangman** [kitematic/kitematic#235]
When I close kitematic the Virtualbox VM is still running even thought I have enabled Kitematic to shutdown the VM upon quit.

**Comment by mchiang0610** [comment]
+1

**Comment by maxx** [comment]
+1

**Comment by ninuxio** [comment]
+1

**Comment by jeffdm** [comment]
The code for shutting down the VM was refactored in 0.5.11 and after a bunch of testing I couldn't reproduce this. Marking it as closed for now, but feel free to reopen.

**Comment by padyx** [comment]
I can still reproduce this issue (Docker toolbox 1.9, Windows 7 x64) on every shutdown.
Shall I open a new issue @jeffdm or can we reopen this one?

**Comment by RVN-BR** [comment]
+1... windows 10 latest docker toolbox... Still there.... it just stays "powered on" in virtualbox admin...

**Comment by FrenchBen** [comment]
@RVN-BR if you get the latest release from this repo, it should be fixed. Toolbox needs to be updated
