### ISSUE TITLE
Feature request - additional functionality in UI

### ISSUE THREAD

**Issue by johnzan** [kitematic/kitematic#237]
Hi,

I'd really like to be able to get more information on the image(s) listed in both the default view and the search results. 

For example, I'd love to be able to click on the tile (that represents the image, is 'tile' the correct term for this?) and be presented with the information currently available for the image in the docker hub, or even cooler, see the contents of the dockerfile, with the option to save the dockerfile to my system and (optionally) open it with my editor

Good work chaps, really like what I see so far.. 

Regards,
J.

**Comment by mchiang0610** [comment]
@johnzan Clicking docker image name on the tile will now bring you to Docker Hub, where you can see more information about that particular image. 

If that particular docker image has more content on Docker Hub, you'll be able to see it there. 

Thanks!

**Comment by johnzan** [comment]
Brilliant, thanks :+1:
