### ISSUE TITLE
Integration with boot2docker

### ISSUE THREAD

**Issue by globexdesigns** [kitematic/kitematic#238]
Any plans to integrate kitematic with an existing boot2docker VM instead of creating a new VM?

**Comment by mchiang0610** [comment]
We're defaulting to the machine VM right now. VM is called dev in virtualbox

**Comment by stefanfoulis** [comment]
I'd be interested in this feature as well. I have a lot of stuff setup in boot2docker and also rely on the default boot2docker IP for some convenience DNS entries.
It would be awesome if kitematic could just be pointed to an existing docker api endpoint. Even if it is just some hidden option somewhere.
