### ISSUE TITLE
Feature Request - search and install from a private repository

### ISSUE THREAD

**Issue by funkytaco** [kitematic/kitematic#239]
I'd like to be able to install from our local, private repository. For example, maybe go into Advanced Settings and change the repo you search to a local url, i.e. https://docker.example.com:5000/v1/search

**Comment by eoglethorpe** [comment]
+1. It looks awesome but makes it pretty impractical for me to use without being able to access my private repos

**Comment by mchiang0610** [comment]
Private repos are part of our roadmap. Thanks!

**Comment by mchiang0610** [comment]
Duplicate request. See #232.  ( https://github.com/kitematic/kitematic/issues/232 )
