### ISSUE TITLE
Kitematic setup fails if used behind a proxy

### ISSUE THREAD

**Issue by riemers** [kitematic/kitematic#240]
On mac on a proxy setup, the kitematic doesn't give a proper error that it cannot find an internet connection. Only if you run the commandline you will see it is trying to reach the api or something. (So http_proxy vars might need to be set etc, in order for it to work?)

Anyways, just feedback, since the button suggested that in kitematic ;)

**Comment by jeffdm** [comment]
This should be fixed in [0.5.18](https://github.com/kitematic/kitematic/releases/tag/v0.5.18) as we no longer need to download boot2docker.iso

**Comment by MatthiasLohr** [comment]
Hey,

not sure if it's really fixed. I have to use (setup) Kitematic behind a proxy, but i'm getting this error:

```
getaddrinfo ENOTFOUND github.com
github.com:443
```

Any idea?

**Comment by MatthiasLohr** [comment]
When defining http_proxy/https_proxy variables:

```
tunneling socket could not be established, cause=write EPROTO
```

**Comment by mchiang0610** [comment]
@MatthiasLohr Are you seeing this error if just installing Docker machine from command line?

**Comment by MatthiasLohr** [comment]
I'm seeing the first error while trying to install Kitematic app started via finder in a proxy environment.

The second error occurs on calling the setup with ```http_proxy=... https_proxy=... open Kitematic.app```.

**Comment by mchiang0610** [comment]
@MatthiasLohr It seems like the proxy is not giving you access to GitHub (where Kitematic may pull data).

**Comment by MatthiasLohr** [comment]
The proxy has no problem with GitHub... i can use GitHub via proxy in Google Chrome and Firefox...

Maybe an authentication problem? I configured the proxy URL with credentials (http://username:password@123.456.789.0:8080/). Does Kitematic use this credentials?

**Comment by mchiang0610** [comment]
@MatthiasLohr Thanks for the update. This should be a Docker machine problem. We're looking for a fix.

**Comment by mchiang0610** [comment]
Merging with #1031 and #1029

**Comment by FugDev** [comment]
https://github.com/kitematic/kitematic/issues/1031#issuecomment-139749024

**Comment by mchiang0610** [comment]
If anyone still has problems with this on Mac or Windows 10+, please contact me at mchiang@docker.com.

We are working on something to help address this issue.

**Comment by schergr** [comment]
Not sure if its the same problem, but I'm just started running the docker beta for Windows, and get the following error.  Any 

![image](https://cloud.githubusercontent.com/assets/59206/15043272/8ba7a9a8-1299-11e6-9bc5-8044db35b928.png)

**Comment by FrenchBen** [comment]
@schergr Some recent changes in networking broke it - Currently working on a fix which should be released Monday. 

Thanks

**Comment by Opticcenter** [comment]
Error  in version 0.10.3 
![Error 0.10.3](http://c2n.me/3y3fMdI.png)


``

**Comment by FrenchBen** [comment]
@Opticcenter with the Release of Docker for Mac/Windows, we check the native install first - If that isn't there, you have the ability to move forward and use the virtualbox installation instead.

**Comment by punix81** [comment]
hy , I've same error on ubuntu 17.04 !

**Comment by paesjoaopaulo** [comment]
Have a solution for this issue?

**Comment by dbipin05** [comment]
Hi,
I'm new to Docker Windows. I'm using windows 7 on my corporate machine and I tried all the ways mentioned in all the blogs but no success yet.
When I run Docker Quickstart terminal I see the below

![image](https://user-images.githubusercontent.com/36712422/36733552-f8ec52ba-1b9e-11e8-95ea-312e6a1fb7c2.png)

And when I run Kitematic I see the below error
![image](https://user-images.githubusercontent.com/36712422/36733419-90784018-1b9e-11e8-9612-b602e6cab9b8.png)

My machine specifications are:
Lenovo Thinkpad, Windows 7 Enterprise 64bit

Kindly let me know what can i do to resolve this please!

**Comment by dbipin05** [comment]
Hi,
I'm new to Docker Windows. I'm using windows 7 on my corporate machine and I tried all the ways mentioned in all the blogs but no success yet.
When I run Docker Quickstart terminal I see the below


![image](https://user-images.githubusercontent.com/36712422/36733781-a8bf4ca6-1b9f-11e8-9f19-b7df05d225b0.png)


And when I run Kitematic I see the below error

![image](https://user-images.githubusercontent.com/36712422/36733797-b1ddfed6-1b9f-11e8-96d6-61b0d6dd0c9c.png)


My machine specifications are:
Lenovo Thinkpad, Windows 7 Enterprise 64bit

Kindly let me know what can i do to resolve this please!

**Comment by Avdhoot01** [comment]
I too am facing the same issue where I am not able to login to dockerhub.

![image](https://user-images.githubusercontent.com/42203142/44079648-4062a80e-9fc7-11e8-94da-5b09d7ccc520.png)

Can someone please help ?

**Comment by punix81** [comment]
You must configure http-proxy.conf .

On ubuntu  edit/create  /etc/systemd/system/docker.service.d/http-proxy.conf
like this : 

            [Service]
            Environment="http_proxy=http://your.proxy:your.port"
            Environment="https_proxy=http://your.proxy:your.port"
            Environment="no_proxy=127.0.0.1, localhost, your.no_proxy"
            ExecStart=
            ExecStart=/usr/bin/dockerd --dns 131.102.100.110 --dns 131.102.37.142 --dns 8.8.8.8 --dns 8.8.4.4 -H fd://

**Comment by praveendait** [comment]
if you are facing this in windows: in command prompt go to kitematic exe location. then do following
set set HTTP_PROXY=http://UN:PWD@host:port
set set HTTPS_PROXY=http://UN:PWD@host:port [note the same here]
then run kitematic.exe, it should work.
