### ISSUE TITLE
Get error when using cli

### ISSUE THREAD

**Issue by destec** [kitematic/kitematic#241]
I'm now using the lastest version of Kitematic and I create a new redis container from the reconmended page. I think it runs smoothly without any error because every thing looks pretty awesome. But the question is when I opened the terminal(not by clicking the button on the top but the origin terminal of OS X) and ran a basic command: `docker stats redis` I got an error: 
> FATA[0000] Post http:///var/run/docker.sock/v1.17/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

So would you please help me with that?

**Comment by Elesant** [comment]
Hi @destec 

Just to confirm the issue. Are you still getting the same error after clicking the Docker terminal button?
![image](https://cloud.githubusercontent.com/assets/559953/6625658/a02a6d38-c8ae-11e4-84f9-f89779483611.png)

**Comment by notduncansmith** [comment]
I had the same problem a few minutes ago. Appending this to your `~/.bash_profile` may help: `$(boot2docker shellinit &>/dev/null)`

**Comment by destec** [comment]
@Elesant Thanks for your reply, I think I missed the button you mentioned. I tried that one and all worked fine.

**Comment by jeffdm** [comment]
Awesome to hear @destec! This seems fixed - closing.
