### ISSUE TITLE
Issue with docker-machine create on npm start

### ISSUE THREAD

**Issue by yakovkhalinsky** [kitematic/kitematic#243]
Steps I follow to reproduce the error:
1) git clone the repo
2) run `npm install`
3) run `npm start`
   - here I had a problem where it couldn't find the `docker-machine` binary in the `resources` directory
   - I solved that my manually copying it from my `/usr/local/bin`

4) reran `npm start` to get the error in the attached image

![image](https://cloud.githubusercontent.com/assets/646086/6625846/b98fa228-c946-11e4-833a-7610ffa9b2be.png)

I'm not sure if there is any dependancy on a particular node version, but I have tried this on both 0.10 and 0.12 versions.

**Comment by jeffdm** [comment]
Thank for the issue.

It looks like this version of docker-machine is not the same as the one Kitematic downloads on `npm install`.

Would it be possible to clone the repo, run `npm install` and paste the output here?

**Comment by yakovkhalinsky** [comment]
@jeffdm this is what I get is I do a fresh clone then, `npm install` and `npm start`

![image](https://cloud.githubusercontent.com/assets/646086/6633409/3a654358-c99c-11e4-9094-a85aefea4a04.png)

**Comment by yakovkhalinsky** [comment]
this is all I see in the `resources` directory

![image](https://cloud.githubusercontent.com/assets/646086/6633422/651d007c-c99c-11e4-90e2-b2f0d15b586d.png)

**Comment by yakovkhalinsky** [comment]
Was able to resolve this by manually doing a wget of the docker machine and naming it to `docker-machine-0.1.0-kitematic-0.5.10` as well as doing a `chmod +x` on it

**Comment by yakovkhalinsky** [comment]
I tried something a little differrent:
1) did a clean `git clone`
2) ran `npm install`
3) checked `resources` for docker-machine -- no docker-machine binary
4) ran `npm install` a second time
5) checked `resources` and docker-machine is now present

weird :monkey_face:

**Comment by jeffdm** [comment]
Fixed this on master. Sorry about that - the initial `npm install` would accidentally remove `docker-machine` after downloading it.
