### ISSUE TITLE
Support container start and stop

### ISSUE THREAD

**Issue by rsheldon** [kitematic/kitematic#250]
Currently it looks like you can really only:

* Create a container
* Delete a container
* Restart a container

Seems like being able to start/stop containers would be very useful. I don't want to have to search for a container and create a new one every time I want to start and use it. 

I often use docker to try out some new app/version, or to spin up a dev environment when I need it. However I want to be able to stop a container and restart it later - not recreate it. Stopped containers should be visible in the container list in the UI (left sidebar in current UI).

**Comment by jeffdm** [comment]
Hi there! Right now stopped containers are visible (if you run `docker stop <container>`) they'll grey out. That said there's currently no way to stop them via the interface - added a label.

Thanks for the issue :smiley:

**Comment by pborreli** [comment]
:+1: for the stop button

**Comment by kematzy** [comment]
+1  definitely need start / stop / suspend type button(s)

**Comment by tehsphinx** [comment]
+1

**Comment by dstroot** [comment]
Wow - I just thought I was an idiot an could not find the stop button.  Would be very welcome to have one!

+1

**Comment by maleghast** [comment]
+1 for a stop button as well - love the app btw ;-)

**Comment by hrwebasst** [comment]
+2
1 for each start and stop ;)

**Comment by alisamar** [comment]
+1

**Comment by Telemakhos** [comment]
+1000

Guys this is a severe UX flaw... I've spent 20 minutes in the GUI looking for the stop button before starting to google the solution... who doesn't immediately look for stop/play buttons? xD Hope you fix it ASAP

**Comment by jeffdm** [comment]
@Telemakhos thanks for the note!!

**Comment by kevinrook** [comment]
+1

**Comment by jontayesp** [comment]
+1

**Comment by jernejz5** [comment]
+1

**Comment by JoeWoo** [comment]
+1

**Comment by drathier** [comment]
+1

**Comment by xsenechal** [comment]
+1

**Comment by jeffdm** [comment]
Quick update, work in progress here: #433

**Comment by mchiang0610** [comment]
We have added the container stop button. Thanks!
