### ISSUE TITLE
UI on 11" Macbook Air does not fit

### ISSUE THREAD

**Issue by wadedog** [kitematic/kitematic#253]
The UI's default size does not fit height wise on an 11" Macbook Air.

The height go the window cannot be adjusted to be shorter so the window always goes behind the dock.

![screen shot 2015-03-13 at 10 44 16 am](https://cloud.githubusercontent.com/assets/70641/6630515/f69f6140-c96d-11e4-8bd6-7394c67baa99.png)

**Comment by jeffdm** [comment]
Thanks for filing an issue about this!
