### ISSUE TITLE
Cisco Anyconnect VPN Collision

### ISSUE THREAD

**Issue by jeffdm** [kitematic/kitematic#254]
Cisco Anyconnect seems to completely block access to the Kitematic VM. They both use the subnet 192.168.0.0/16.

We'll need a way to access the VM through port mapping or to change the IP addresses used by machine to create the VMs.

**Comment by retr0h** [comment]
Could we simply rely on local port forwarding (similar to the way `vagrant ssh` works)?  That always works for me, I start running into problems, when using host_only on 192.168/16 ranges.

**Comment by jpapejr** [comment]
You can alleviate the problem with AnyConnect by disconnecting from the VPN and running a command like so 

sudo route -nv add -net 192.168.99 -interface vboxnet0

I used the instructions here http://apple.stackexchange.com/questions/126164/how-to-make-custom-routes-survive-reboots as a means to do this on reboot (Mac specific). Otherwise, you'll have to do this command each time to reboot your machine .

**Comment by jeffdm** [comment]
In case this helps:

**reproduce:** `sudo route -nv remove -net 192.168.99`

**fix:** `sudo route -nv add -net 192.168.99 -interface vboxnet0`

**Comment by mchiang0610** [comment]
bringing discussion from https://github.com/kitematic/kitematic/issues/290 here as well

**Comment by mchiang0610** [comment]
Merging with #1031

**Comment by Juchar** [comment]
Hi, I stumble accross the same problem over here. Somehow I do not get it working.

Would it be possible that someone provides the equivalent windows command?

Unix:
 `sudo route -nv add -net 192.168.99 -interface vboxnet0`

Windows:
`?`

What I tried:
`route -4 -p ADD 192.169.99.0 mask 255.255.255.0 169.254.249.64 metric 1`
where **169.254.249.64** is the IP-Address of the network adapter that is used by the virtualbox VM.

**Comment by mchiang0610** [comment]
If anyone still has problems with this on Mac or Windows 10+, please contact me at mchiang@docker.com.

We are working on something to help address this issue.

**Comment by EasyAsABC123** [comment]
@mchiang0610 tried to email you but that isn't an email anymore.
