### ISSUE TITLE
Docker image overview could show image sizes

### ISSUE THREAD

**Issue by eschnett** [kitematic/kitematic#255]
I am looking at the Docker image view that allows me to create a new container. This overview could show for each image also its size.

For example, I've heard that the Debian image is "leaner" than the Ubuntu image. I'd like to see in how far this is true, and comparing sizes would help me.

**Comment by jeffdm** [comment]
Thanks for creating an issue. This definitely makes sense.

(Also, it's incredible to see someone from the Perimeter institute trying out Kitematic :)

**Comment by eschnett** [comment]
Thank you... While we are a theoretical physics institute, many people here need to run some software, and this should be as easy as possible. Thus I'm investigating Docker and related tools.

**Comment by mchiang0610** [comment]
@eschnett This is a really good suggestion. Unfortunately, the Hub API does not give Kitematic that information. 

Closing this for now.
