### ISSUE TITLE
changing volumes reverts to original on restart

### ISSUE THREAD

**Issue by geddski** [kitematic/kitematic#256]
1. change volume location to another directory
2. restart container
3. see that the volume you changed is right back to the original.

**Comment by jeffdm** [comment]
Thanks for the issue. This is an important one - working on a fix that will be rolled out soon.

**Comment by geddski** [comment]
indeed! Thanks for the quick response.

**Comment by geddski** [comment]
@jeffdm any update on this? Kinda can't use kitematic until this one is addressed.

**Comment by jeffdm** [comment]
Closed in #340. Cutting a release for 0.5.11 later today.

**Comment by geddski** [comment]
Nice! Thanks
