### ISSUE TITLE
VM not closed cleanly when kitematic is configured to shutdown the VM on exit

### ISSUE THREAD

**Issue by outofjungle** [kitematic/kitematic#257]
The "DEV" virtualbox VM was still running after the kitematic was closed even when the setting "shutdown linux VM on closing kitematic" was checked.

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by ChrisChinchilla** [comment]
If it's any help I found that unchecking and rechecking the box fixed this.

**Comment by ninuxio** [comment]
@ChrisChinchilla same here but it's a one time fix. if you reopen kinematic and close it again the vm stay ON

**Comment by ninuxio** [comment]
duplicate with #235 ?

**Comment by jeffdm** [comment]
This is a duplicate of #235, thanks @ninuxio
