### ISSUE TITLE
Warn before installing VirtualBox on first run

### ISSUE THREAD

**Issue by seanfisher** [kitematic/kitematic#262]
I was surprised when I opened the app and it immediately started installing virtual box without asking. I would suggest a dialog box on first run explaining the setup process with an OK and cancel button.

Super slick though, nice job.

**Comment by mchiang0610** [comment]
Thanks for sending in this. This is something that's been asked a lot. We will have improve on this in the next couple of versions.

**Comment by zacharybrady** [comment]
#dibs

**Comment by mchiang0610** [comment]
@seanfisher We now tell the user we are installing VBox
