### ISSUE TITLE
Shared folders/Volumes do not mount if /Users/ is on a separate volume.

### ISSUE THREAD

**Issue by kayhtee** [kitematic/kitematic#265]
Trying the hello-world-nginx. There seems no link between website_files in the conainer and the given host directory. Am I missing something? Do I need to enable file sharing in my system preferences?
kitematic 0.5.10

Kimtee

**Comment by jeffdm** [comment]
Thanks for the issue. It should be on by default.

The website_files directory can be found under `~/Kitematic/<container name>/`. Are the files there?

**Comment by kayhtee** [comment]
No, no files there. Even ~/Kitematic/.. was not created during installation. 
I'm on Mac OS X 10.9.5 (but this shouldn't  matter). I had Virtualbox (4.3.22r9823) installed before too

**Comment by jeffdm** [comment]
Can you post a screenshot of Kitematic with the `hello-world-nginx` container selected?

Thanks!

**Comment by kayhtee** [comment]
That what I see: clicking on website_files is without reaction (since it doesn't exist)
![screenshot_hello-world-nginx](https://cloud.githubusercontent.com/assets/11136504/6653892/fb288bf2-caa2-11e4-972a-f5e8e9707445.png)

**Comment by jeffdm** [comment]
Thanks for the screenshot! Does creating a 2nd `hello-world-nginx` container work?

**Comment by kayhtee** [comment]
Yes, it creates a hello-world-nginx-2

**Comment by jeffdm** [comment]
Great - does the shared directory work for this second container?

**Comment by kayhtee** [comment]
No, the Kitematic folder is not created rsp inserted

**Comment by kayhtee** [comment]
![bildschirmfoto 2015-03-14 um 23 42 39](https://cloud.githubusercontent.com/assets/11136504/6653903/e2095754-caa3-11e4-8a40-4e0cfc08128a.png)

**Comment by kayhtee** [comment]
My Users directory is linked to another Volume, could this be the source of the issue? everything else works with this config

**Comment by jeffdm** [comment]
Ah! I see. We use VirtualBox shared folders under the hood, which may not work with /Users/ in a separate Volume.

**Comment by kayhtee** [comment]
Ok, thanks a lot.  
will try to change my config rsp create a new user on the main Volume

**Comment by jeffdm** [comment]
Awesome, thanks so much! Also, try to make sure to hit the green button on GitHub when commenting, otherwise the issue keeps being closed :smiley:!

**Comment by kayhtee** [comment]
thank you so much, you are right: after creating new user on same volume (no linking) it works fine. 
Now finally I can hit the close button :-)

**Comment by ve3** [comment]
installed this https://hub.docker.com/r/kitematic/hello-world-nginx/
and website_files could not from anywhere both host os, vm os.
can't test anything just install and watch default page.

**Comment by FrenchBen** [comment]
@ve3 Did you mount them within your /Users path?

**Comment by ve3** [comment]
@FrenchBen There is no instruction how to do it. I install this from Kitematic which is GUI but, I map folder from there but not found.

**Comment by FrenchBen** [comment]
You click the volume button and mount it on your desktop for example.

**Comment by inuwas** [comment]
![untitled](https://user-images.githubusercontent.com/12743152/29171675-382e6fde-7dd5-11e7-8373-dacbebeff5d3.jpeg)
I am having the same issue sharing files with my ubuntu installation on Kitematic. Please see the attached image. 
![hello](https://user-images.githubusercontent.com/12743152/29171872-ec0dc68a-7dd5-11e7-9b11-9d85ec52f950.jpeg)

**Comment by 1and1get2** [comment]
+1 same issue also on beta (0.17.1)
