### ISSUE TITLE
terminal button open empty terminal 

### ISSUE THREAD

**Issue by ttwthomas** [kitematic/kitematic#268]
Terminal button open empty terminal when you have a port defined in you ssh client config ('Port xx' in ~/.ssh/config)
An easy fix would be to add '-p22' in the command line here 
https://github.com/kitematic/kitematic/blob/643d705d2d376dd79186990b2196ec9110cdc1a1/src/ContainerDetailsSubheader.react.js#L110

**Comment by jeffdm** [comment]
Thanks for the issue! Feel free to create a PR or we'll get around to this soon!

**Comment by jeffdm** [comment]
Fixed in #297.

Thanks for this @ttwthomas !
