### ISSUE TITLE
Kitematic on The Changelog!

### ISSUE THREAD

**Issue by adamstac** [kitematic/kitematic#272]
Howdy from The Changelog.

Congrats on joining the Docker mothership!

We'd love to get y'all on the show sometime soon.

I'm guessing you've heard of the show, but if not -- The Changelog is a podcast covering what's fresh and new in open source. Listen to the show here http://thechangelog.com/podcast/ or here http://5by5.tv/changelog

Looking forward to talking to y'all!

Adam, EIC

**Comment by jeffdm** [comment]
Definitely interested! Can't find your email, but please shoot me a msg: jmorgan@docker.com! Would love to chat.

Thanks!
