### ISSUE TITLE
Problem downloading atlassian/stash docker

### ISSUE THREAD

**Issue by tcorral** [kitematic/kitematic#274]
There is a problem downloading the docker in atlassian/stash. I tried to install jenkins and it worked.

**Comment by robtec** [comment]
@tcorral Hey, at what point did it fail? did it show the percentage circle?

**Comment by tcorral** [comment]
The first time I tried it shown the percentage circle and it arrives to 12%
but the next times I tried (even restarting the application) it doesn´t
shown the percentage circle and then the error is shown.


2015-03-14 13:25 GMT+01:00 Rob Powell <notifications@github.com>:

**Comment by jeffdm** [comment]
Thanks for the issue. Is it possible your connection was cut partially through the download? (Stash is a larger image)?

Side note: stash has a small issue now where it runs as the `stash` user, which cannot access the host-mounted volume that Kitematic creates.

**Comment by mchiang0610** [comment]
Merging with #1030
