### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by olegafx** [kitematic/kitematic#275]
Something is wrong with Atom Helper. It uses too much energy. Even Mac’s fans starts working.

Install new app, create default Nginx container and… thats it.

OSX 10.10.2
Kitematic 0.5.10
system’s node 0.10.35

![activity_monitor__applications_in_last_8_hours_](https://cloud.githubusercontent.com/assets/867546/6651933/afe798a8-ca6c-11e4-9e52-ee800df71d99.png)

**Comment by jeffdm** [comment]
Thanks for the issue! Will investigate

**Comment by jpapejr** [comment]
Having the same issue with Kinematic and consequently Atom.io for the same issue:

high cpu burn on the atom_helper processes which, in turn, translates into high energy impact.

**Comment by goldibex** [comment]
I can also confirm this issue, with nothing but a Redis image open.

**Comment by jeffdm** [comment]
Thanks! Good to know @goldibex as this isn't from the web preview for web containers

**Comment by jontayesp** [comment]
:+1: 

I have the same issue running a single ubuntu-upstart.

**Comment by marcmorel** [comment]
Same here ... What's the use of Atom Helper ?
Great app btw :stuck_out_tongue_winking_eye:

**Comment by jpapejr** [comment]
I think the Atom Helper is here because the kitematic ui is build on the same foundation as the Atom node.js editor.

**Comment by jeffdm** [comment]
@jpapejr thats right- though it still shouldn't be hogging a bunch of CPU. Will take a look at this

**Comment by jpapejr** [comment]
That'd be awesome. I want to use Atom but I love my battery life and cpu cycles more. :)

**Comment by olegafx** [comment]
You've found the source of problem?

**Comment by jeffdm** [comment]
@olegafx not yet. I assume it's something related to the following:
- The web preview
- Background work being done (need to investigate)
- Chromium in general tends to be a bit of a battery hog

**Comment by mchiang0610** [comment]
Discussion here: https://discuss.atom.io/t/atomhelper-high-cpu-usage/2553

**Comment by douglasmiranda** [comment]
When I start the kitematic the fan go crazy and even the process VBoxHeadless consumes more CPU.

I'm using dockertoolbox

**Comment by mchiang0610** [comment]
Merging with #867
