### ISSUE TITLE
No errors if image fails to launch

### ISSUE THREAD

**Issue by ahwulf** [kitematic/kitematic#276]
I downloaded the default ubuntu image. It doesn't run and when I force it to restart it just gives up, no errors, no information, nothing. Does Kite have a log file somewhere? Is there someway to know what is going on?

**Comment by jeffdm** [comment]
Try the `ubuntu-upstart` [image](https://registry.hub.docker.com/_/ubuntu-upstart/) on DockerHub. The regular `ubuntu` image is mainly used as a base image for other containers.

Hope this helps!
