### ISSUE TITLE
Setup should migrate an existing boot2docker vm.

### ISSUE THREAD

**Issue by jeffdm** [kitematic/kitematic#277]
Waiting on a change upstream in [docker-machine](https://github.com/docker/machine/) before implementing this.

**Comment by chiedojohn** [comment]
Thanks Jeff! Interested to see how this goes!

**Comment by nikom** [comment]
Have there been any news about using the existing boot2docker vm with kitematic in the meantime?

**Comment by roncanepa** [comment]
searched for this issue and pulled it up specifically to request the same as @nikom

**Comment by mchiang0610** [comment]
Toolbox does this now.
