### ISSUE TITLE
Ability to handle old boot2docker etc installs

### ISSUE THREAD

**Issue by kematzy** [kitematic/kitematic#278]
Trying out Kitematic the first time was a bit of a pain-in-the-*** as it kept on getting stuck on existing boot2docker stuff.

I only managed to get things working after I had spent time clearing away all old stuff AND downloading and reinstalling VirtualBox separately.

Please provide some hand-holding for others going forward.

**Comment by jeffdm** [comment]
Sorry to hear that. Thanks for going through all of that to get Kitematic running.

Any idea on where it got stuck in setup? Kitematic shouldn't be interfering with an existing Boot2Docker setup as we use docker-machine. Did the app error (and turn red?) What ended up working?

Thanks for the issue!

**Comment by kematzy** [comment]
Thanks for your quick feedback.

This is a screenshot of the the/one error. (not 100% sure)

It made no difference if I clicked "Retry Setup" or "Delete VM and Retry Setup" buttons.

Perhaps you could log what goes on in the background and expose that similar to the log in the running container. It could help understand what went wrong.


![screenshot 2015-03-14 23 40 09](https://cloud.githubusercontent.com/assets/6571/6654056/09acf016-cae7-11e4-8b82-9060befcd942.png)

**Comment by jeffdm** [comment]
Can you reach `https://api.github.com/repos/boot2docker/boot2docker/releases`?

The biggest cause of this seems to be `docker-machine` not being able to download the latest version of boot2docker.

Do you know if you're behind a proxy or any kind of VPN?

Thanks!

**Comment by kematzy** [comment]
Hi Jeff,

I'm not behind any proxy or VPN, and I can reach the above URL. 

However, I run [Little Snitch](http://www.obdev.at/) which may have interfered with the process without giving any signs.

My normal process when trying new apps is to "allow once" on any remote requests that I consider "OK" and "allow forever" on any requests to "trusted" sources (such as github.com). It's possible that I just accepted "allow once" on the "api.github.com" request without realising it. 

As I said above, a log could / would have identified this problem (provided you logged the failure to connect).  Perhaps the log output could be presented after clicking a simple "folder triangle toggle" type button? That way it's there but not cluttering up your beautiful UI.

Anyway, thanks for your work on Kitematic and I look forward to future versions with more bells & whistles.

**Comment by imod** [comment]
I have the exact same problem - for now I did not try to remove my existing installs (e.g. boot2docker) so if you need me to look at any specific logs, please let me know.

**Comment by jeffdm** [comment]
@imod @kematzy thanks, and sorry for the delay.

Running the following on the command line and posting the logs for the 2nd command would help debug this enormously. 

- `docker-machine rm -f dev`
- `docker-machine -D create -d virtualbox dev`

**Comment by imod** [comment]
@jeffdm please find the logs at http://pastebin.com/4hGURTZW

...it seems there is when calling VirtualBox, as the first part of the log just shows the usage of the VBoxManage command...

**Comment by jeffdm** [comment]
From https://forums.virtualbox.org/viewtopic.php?f=11&t=43487, it seems to be a permissions error with VirtualBox. What is the output of the following? (if you don't mind providing it):

- `ls -ld /Applications`
- `ls -ld /Applications/VirtualBox.app`

**Comment by imod** [comment]
sure, no problem...

```
elongatus:/ domi$ ls -ld /Applications
drwxrwxr-x@ 117 root  staff  3978 Apr  6 09:04 /Applications
elongatus:/ domi$ ls -ld /Applications/VirtualBox.app
drwxr-xr-x  3 root  admin  102 Aug 29  2014 /Applications/VirtualBox.app
elongatus:/ domi$ 
```

**Comment by mchiang0610** [comment]
Not sure if this fixes it: https://github.com/kitematic/kitematic/releases/tag/v0.5.27-intel-nic

Can someone test it out if you are running into this issue?

**Comment by imod** [comment]
unfortunately it does not fix the issue...

![screen shot 2015-05-26 at 08 10 20](https://cloud.githubusercontent.com/assets/543297/7806235/c8c8f5ba-037e-11e5-9963-4b361d95ab90.png)

**Comment by mchiang0610** [comment]
Merging with #1029
