### ISSUE TITLE
cannt launch the kitematic

### ISSUE THREAD

**Issue by yuwang88** [kitematic/kitematic#280]
When I run the app with  "npm start" command,the error message showed up like below:

mkdir -p /usr/local/bin && rm -f /usr/local/bin/docker-machine && cp /Users/yuwang/Desktop/cocos2dx/kitematic/resources/docker-machine-0.1.0-kitematic-0.5.10 /usr/local/bin/docker-machine && rm -f /usr/local/bin/docker && cp /Users/yuwang/Desktop/cocos2dx/kitematic/resources/docker-1.5.0 /usr/local/bin/docker returned non zero exit code stdout: stderr:cp: /Users/yuwang/Desktop/cocos2dx/kitematic/resources/docker-machine-0.1.0-kitematic-0.5.10: No such file or directory

and I found that there was no file called "docker-machine-0.1.0-kitematic-0.5.10" under kitematic/resources file.

**Comment by jeffdm** [comment]
Thanks for the issue.

A change was committed to master earlier today that fixed downloading the
docker-machine binary on `npm install`. If you pull master and run `npm
install` does this still happen?

**Comment by jeffdm** [comment]
Closing this for now since it's fixed on master. Feel free to reopen
