### ISSUE TITLE
How to use docker-machine instead of local vbox ?

### ISSUE THREAD

**Issue by runseb** [kitematic/kitematic#284]
Hi, another newbie question here. I am not seeing any options through the UI to use docker-machine ?
Nothing in the docs as well.
Any hints ?

**Comment by mchiang0610** [comment]
Hi @runseb, Kitematic automatically uses Docker Machine underneath. 

Closing this for now. If you have further questions feel free to open this again! Thx :)

**Comment by runseb** [comment]
ok @mchiang0610 . So let me be a bit more precise. How can I use Kitematic to manage containers on a remote Docker host. I don't see an option to switch from a machine virtual box driver to say a digital ocean one ?

**Comment by mchiang0610** [comment]
@runseb It's not supported right now. Sorry. 

There is a feature request for it here: https://github.com/kitematic/kitematic/issues/117

**Comment by runseb** [comment]
gotcha thanks
