### ISSUE TITLE
Better handling of Registry errors

### ISSUE THREAD

**Issue by hagzag** [kitematic/kitematic#286]
I got this error message, now that blocks managing other containers I instantiated.
Using MACOSX 10.10.2, Kitematic 0.5.10 Beta
![image](https://cloud.githubusercontent.com/assets/194057/6666538/08ae9b6c-cbee-11e4-8118-09f1d9a3b4dd.png)

**Comment by mchiang0610** [comment]
@hagzag  Are you using Kitematic within a VPN environment / proxy?

**Comment by westondeboer** [comment]
same Mac OS X 10.10.3, Kitematic 0.5.10 Beta

**Comment by connaryscott** [comment]
Ditto for me, no vpn, just an error suggesting it.

**Comment by lisajill** [comment]
Same problem

**Comment by hxtpoe** [comment]
Everytime I'm trying to add container tleyden5iwx/couchbase-server-3.0.1 I have the same issue.

    [3597:0318/192538:INFO:CONSOLE(79)] "Error: HTTP code is 500 which indicates error:
     server error   - No command specified", source:   
    /Users/hxtpoe/works/kitematic/build/ContainerHome.react.js (79)

**Comment by scanferla** [comment]
+1

**Comment by mchiang0610** [comment]
@scanferla Did you just see this error pop up in the newer build?

**Comment by scanferla** [comment]
Yes, I’ve just installed it. But it seems that I can use that image just fine, from the command line.
