### ISSUE TITLE
Logs only showing every 2nd entry

### ISSUE THREAD

**Issue by mattsoutherden** [kitematic/kitematic#288]
Version: 0.5.10

For some reason I am only seeing every 2nd log entry from ```docker logs -f *container*``` shown in the Logs pane.

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by mattsoutherden** [comment]
Hi, I've not been able to reproduce the same error on my home machine with a fresh install of 0.5.10. I will try and debug some more on my work machine tomorrow.

**Comment by mattsoutherden** [comment]
OK, I can now replicate it. It happens when running a container with interactive tty. e.g.

```docker run -it -p 80:80 nginx```

Refreshing the browser resulting every 2nd request showing up in the Logs pane, whereas ```docker logs -f``` shows every entry.

```docker run d -p 80:80 nginx``` and ```docker run -d -p 80:80 nginx``` work as expected.

I was trying out Kitematic whilst developing a new container, hence the interactive.

**Comment by jeffdm** [comment]
Thanks @mattsoutherden. I repro'd this - working on a fix.
