### ISSUE TITLE
docker/virtualbox plus vpn equals poison?

### ISSUE THREAD

**Issue by connaryscott** [kitematic/kitematic#290]
Not sure, but I tried boot2docker a while ago.  setup a container and all was good.  Started a vpn and then stopped it.  Then tried to back into boot2docker, never worked again.  Saw lots of workarounds that did not look very pleasant especially when you are trying to explain it to a developer/newbie type.  Nto sure if that situation is present in my case here when I tried kitematic for the first time and got this error:

There was a problem connecting to the Docker Engine in the VirtualBox VM.   This could be caused because this Mac is currently connected to a VPN, blocking access to the VM.  If the issue persists, please file a ticket ou our GitHub repo.

(annoying typed out as I could not copy/paste this error :( )

Thanks,

Chuck Scott

**Comment by jeffdm** [comment]
Thanks for the issue. Sorry you had to type the error.

**Comment by mchiang0610** [comment]
Merging this into https://github.com/kitematic/kitematic/issues/254
