### ISSUE TITLE
Default Jekyll image is stuck at "Connecting to Docker Hub"

### ISSUE THREAD

**Issue by erlend-sh** [kitematic/kitematic#293]
I've tested other images and they all download successfully and I've gotten some of them running, but the recently added official [jekyll/jekyll](https://registry.hub.docker.com/u/jekyll/jekyll/) image doesn't even get to the download stage.

cc: @envygeeks

**Comment by envygeeks** [comment]
Can you try now @erlend-sh I had my build server start tagging stable as latest too, before we did not provide latest and it could be that it was searching for latest and not finding it.

**Comment by erlend-sh** [comment]
Download works now, cheers!
