### ISSUE TITLE
syntax error near unexpected token `Beta'

### ISSUE THREAD

**Issue by amulyas** [kitematic/kitematic#299]
/Users/XXXXXX/Downloads/Kitematic (Beta).app/Contents/Resources/app/resources/docker-machine-0.1.0-kitematic-0.5.10 create -d virtualbox --virtualbox-memory 2048 dev returned non zero exit code

on command line
XXXXX:Downloads XXXXX$ /Users/XXXXX/Downloads/Kitematic (Beta).app/Contents/Resources/app/resources/docker-machine-0.1.0-kitematic-0.5.10 create -d virtualbox --virtualbox-memory 2048 dev
-bash: syntax error near unexpected token `Beta'

**Comment by jeffdm** [comment]
Thanks for the issue! Out of curiosity, is there a space in your user name? (XXXXXX here)

**Comment by amulyas** [comment]
Hi jeff,  no but its a numeric username like
 123456789

**Comment by amulyas** [comment]
here is the real text 

/Users/502393292/Downloads/Kitematic (Beta).app/Contents/Resources/app/resources/docker-machine-0.1.0-kitematic-0.5.10 create -d virtualbox --virtualbox-memory 2048 dev returned non zero exit code

**Comment by jeffdm** [comment]
Thanks! Appreciate the extra info :smiley:

Does renaming the app to Kitematic.app happen to work for now?. Sorry about that.

**Comment by amulyas** [comment]
nope 
SFO1502393292A:Downloads 502393292$ /Users/502393292/Downloads/Kitematic.app/Contents/Resources/app/resources/docker-machine-0.1.0-kitematic-0.5.10 create -d virtualbox --virtualbox-memory 2048 dev
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0xa52735)
	/usr/src/go/src/pkg/runtime/panic.c:520 +0x69
runtime.goenvs()
	/usr/src/go/src/pkg/runtime/os_darwin.c:88 +0x62
runtime.schedinit()
	/usr/src/go/src/pkg/runtime/proc.c:164 +0x76
_rt0_go()
	/usr/src/go/src/pkg/runtime/asm_amd64.s:91 +0x114

/Users/502393292/Downloads/Kitematic.app/Contents/Resources/app/resources/docker-machine-0.1.0-kitematic-0.5.10 create -d virtualbox --virtualbox-memory 2048 dev returned non zero exit code

**Comment by jeffdm** [comment]
From https://github.com/boot2docker/boot2docker/issues/397 it seems that running:

`unset DYLD_INSERT_LIBRARIES`

May help.  Thoughts?

**Comment by amulyas** [comment]
I uninstalled boot2docker and unset the variable restarted mac .. no help I have go programming language installed too

**Comment by jeffdm** [comment]
@amulyas does this work with 0.5.18 (latest release of KM)? It shipped with a new version of machine - might be worth a try.

Thanks!

**Comment by amulyas** [comment]
I will try now my friend

**Comment by jeffdm** [comment]
@amulyas thanks, let me know how it goes!

**Comment by mchiang0610** [comment]
@amulyas Assuming this is fixed. If you are still having this issue, please re-open.
