### ISSUE TITLE
Cache logs between container switches for better performance.

### ISSUE THREAD

**Issue by boopathi** [kitematic/kitematic#301]
When switching between containers, if there's too much logs, the rendering takes a while, and leads to a bad experience.

Is it possible to clear the logs ? If its not, this will be a nice feature to have.

**Comment by jeffdm** [comment]
I think this can be greatly improved by caching the log data. The problem is that right now it fetches all container logs on every switch. This could take a lot of time for logs that have 1000s of lines.

**Comment by wyattjoh** [comment]
This is essentially crippling my experience. I run mongo in a docker container that has lots of tests run against it. Every connection causes a few lines in the log, which means after a few hours of testing, if I click on the mongo container, it has to reload a few thousand lines of logs, which hangs the entire interface for a few minutes!

**Comment by jeffdm** [comment]
@wyattjoh thanks for the feedback. Prioritizing this - logs need to be fast. Sorry about the bad experience.
