### ISSUE TITLE
Error - Failing to connect to Docker Engine

### ISSUE THREAD

**Issue by andrewvalentine** [kitematic/kitematic#302]
"There was a problem connecting to the Docker Engine in the VirtualBox VM. This could be because this Mac is currently connected to a VPN, blocking access to this VM."

No VPN currently connected. Issue persists following restart of network adapter, restart of Kitematic and boot cycle of Mac.
![screen shot 2015-03-17 at 22 20 49](https://cloud.githubusercontent.com/assets/5181124/6698811/418d0a3e-ccf4-11e4-903e-8a05549e94e9.png)

**Comment by jeffdm** [comment]
Thanks for the issue!

Does:
- Removing the `dev` VM through VirtualBox
- Restarting Kitematic

work?

**Comment by andrewvalentine** [comment]
Hi Jeffrey,

Thanks for your response. I resolved this by:

- Connecting and disconnecting my VPN client (Junos Pulse)
- Restarting Kitematic and successfully downloading and running CentOS VM

Confirmed resolved following reboot. Not sure why the one instance of
connecting/disconnecting the VPN fixed it, but bugs with Junos Pulse don't
surprise me any more...

Thanks!

Andrew

On 18 March 2015 at 04:19, Jeffrey Morgan <notifications@github.com> wrote:

> Thanks for the issue!
>
> Does:
>
>    - Removing the dev VM through VirtualBox
>    - Restarting Kitematic
>
> work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/issues/302#issuecomment-82733075>.
>



-- 
Andrew Valentine
P: 07828 045095

**Comment by lostinplace** [comment]
I'm having the same issue, though restarting the app and closing Junos Pulse doesn't seem to help

**Comment by lostinplace** [comment]
I killed junos entirely, docker-machine removed the dev image and created a new one

search for an image:  select scratch official, start installing, receive the following:

![image](https://cloud.githubusercontent.com/assets/645413/6925278/5ab9221e-d7ac-11e4-9145-bf19e1e47a91.png)

now I can't delete the image,  running docker images yields:

````
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              511136ea3c5a        21 months ago       0 B
````

everything's frozen until I kill kitematic and the VM

**Comment by lostinplace** [comment]
This also persists through reboot

**Comment by lostinplace** [comment]
````
➜  ~  docker-machine create -d virtualbox dev
INFO[0000] Creating SSH key...
INFO[0000] Creating VirtualBox VM...
INFO[0008] Starting VirtualBox VM...
INFO[0008] Waiting for VM to start...
INFO[0040] "dev" has been created and is now the active machine.
INFO[0040] To point your Docker client at it, run this in your shell: $(docker-machine env dev)
➜  ~  $(docker-machine env dev)
➜  ~  docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
➜  ~
````

**Comment by mchiang0610** [comment]
@lostinplace There are 2 issues here - 

1. Problem connecting to Docker Engine 

2. If that worked, the base image - CentOS - will not run as Kitematic doesn't support running base images (not given instructions on how to run it). - This part of the issue will be merged with https://github.com/kitematic/kitematic/issues/485

**Comment by mchiang0610** [comment]
Should be fixed. 

These logs might be useful for #1029 as well.. will merge.

**Comment by megamindbrian** [comment]
This is not fixed, still getting errors.
