### ISSUE TITLE
No abort when downloading from Docker Hub?

### ISSUE THREAD

**Issue by FredrikHedman** [kitematic/kitematic#303]
When I tried to download a container (tinycore-python) the interface of Kitematic (0.5.10) is stuck and there is no obvious way to abort the operation except deleting the container.

It would be helpful to have a cancel/abort button...

**Comment by thaJeztah** [comment]
Docker itself doesn't currently support cancelling a "pull", so that will have to be implemented first. There are some pull-requests to work on that, but I'm not sure which release it will be in.

Perhaps some interface/GUI improvements can be made to prevent the "interface" from being stuck.

**Comment by FredrikHedman** [comment]
A "^C" certainly works;)...anyhow I now understand the current limitation, but iterfacewise it would be helpful if one could cancel a download.
