### ISSUE TITLE
Link to user support forum in README broken

### ISSUE THREAD

**Issue by nathanleclaire** [kitematic/kitematic#310]
Noticed that https://forums.docker.com/c/kitematic (listed in the README) doesn't lead anywhere useful.

**Comment by jeffdm** [comment]
Thanks!

**Comment by tukushan** [comment]
#dibs

**Comment by tukushan** [comment]
https://forums.docker.com/c/kitematic links to the correct location, there's just very few posts yet :)

**Comment by nathanleclaire** [comment]
This was broken when I tried, looks fixed now... Cheers
