### ISSUE TITLE
Can't click anything

### ISSUE THREAD

**Issue by davidhq** [kitematic/kitematic#311]
latest beta version downloaded from the site yesterday

This happens: (clicking around, nothing happens): http://cl.ly/image/232M1X2c1i3T

I'm on OSX Mavericks

**Comment by jeffdm** [comment]
Thanks for the issue.

**Comment by DigitalRogues** [comment]
I have a similar state when starting the app, it appears its loading tons and tons of logging from the selected machine and it's basically freezing the UI.

**Comment by jeffdm** [comment]
@DigitalRogues Thanks, I think we'll need paging for the logs. Looking into this
