### ISSUE TITLE
Why is the Docker CLI binary packaged with and required by Kitematic?

### ISSUE THREAD

**Issue by domderen** [kitematic/kitematic#312]
Hi,

I saw in: https://github.com/kitematic/kitematic/blob/master/util/deps thet you are downloading Docker CLI as a project dependency. Could you tell me what is the reason of this, when you have Docker Machine right now, and as far as I saw, you are using dockerode to connect to docker host?

I am asking about it coz I am thinking about changes required to set up this project on Windows, and Docker CLI would be one of the things to get rid of.

**Comment by jeffdm** [comment]
Thanks for creating the issue, and wow, thank you so much for looking into what it would take for Windows.

It's mainly for the 'Open Docker Terminal' button in-app (see below):
![screen shot 2015-03-20 at 6 17 32 pm](https://cloud.githubusercontent.com/assets/251292/6763156/314f765c-cf2e-11e4-87f2-e94b82962c9e.png)

Note: on startup Kitematic copies `docker` and `docker-machine` to `/usr/local/bin`.

Right now we could get away with changing this button to run something like: `docker-machine ssh dev`

**Comment by domderen** [comment]
Hey,

Thanks for getting back to me. That's good to know. I can prepare a pull request later on to loose Docker CLI dependency. This is the only constraint against porting it to Windows as there is no Docker CLI for Windows.

I was able to start the application on windows and get past the SetupStore initialization, by disabling the installation of VirtualBox for now, and preparing the required VM using machine by hand. The app was able to connect it the docker in the VM using docker-machine for Windows,and query for containers.

Unfortunately I found an issue next, when the app is trying to use react router to navigate to containers view. The error is the same as described here: http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined but the solution provided here didn't work for me. I assume this is a react issue, so I tried upgrading dependencies to newest version of react, but it caused other issues. I assume this is because there were some breaking changes in react 0.13.

Anyway, I will try to fix the issue later on, and get the whole application running on Windows, and when that's done, I will look into porting SetupStore for Windows. It would be great if you could mention all places in the app that highly depend on the MacOS environment.

**Comment by StefanScherer** [comment]
@domderen I've played with `docker-machine.exe` on Windows last week. I additionally downloaded `docker.exe` CLI that is also pre-built on dockerproject.com.

Assuming [Chocolatey](https://chocolatey.org) we can install VirtualBox and `curl` with two little steps. I have made all these steps in a good old `cmd.exe` shell:

```cmd
λ cinst virtualbox
λ cinst curl
```

Then download `docker-machine.exe` and `docker.exe` 

```cmd
λ curl -L -o docker-machine.exe https://github.com/docker/machine/releases/download/v0.1.0/docker-machine_windows-amd64.exe
λ curl -L -o docker.exe https://master.dockerproject.com/windows/amd64/docker.exe
```

Now create a VirtualBox dev machine:

```cmd
λ docker-machine create -d virtualbox dev
```

And here comes my favorite for `cmd.exe` shells: Translate the unix'ish environments printed by `docker-machine` and set it as environment variables in a plain Windows shell:

```cmd
λ for /f "tokens=2" %i in ('docker-machine env dev') do set %i
```

We are almost up and running. But the `docker.exe` (nightly build) already uses protocol version 1.18, but talking to a docker host we need version 1.17 for docker 1.5.0 hosts.

This could be done with a little trick:

```cmd
λ sed -ibak -b docker.exe -e 's/1.18/1.17/g'
```

And now you can do something like
```
λ docker logs
λ docker images
```

Maybe this helps.

**Comment by thaJeztah** [comment]
@StefanScherer that's pretty nifty. I like the env-vars trick. Have you suggested this trick in the Machine repo? Perhaps they're interested in that part.

Also

/cc @ahmetalpbalkan because I think he was working on the Chocolatey parts in Docker

**Comment by StefanScherer** [comment]
@thaJeztah thanks for the reminder. I've found docker/machine#732 and shared my experience there, too.

**Comment by domderen** [comment]
Wow, that is great! I was actually using git-bash to run everything so far, but it might be a good idea to port it with chocolatey in mind. I will try to run the project fully, with premade virtualbox VM, and share some working code. Next probably some branch with Windows SetupStore to have a setup for this environment.

**Comment by thaJeztah** [comment]
@StefanScherer thank! Just saw it coming by in my notifications

**Comment by ahmetalpbalkan** [comment]
@thaJeztah Hi folks, we are planning to bundle `docker.exe` with Boot2Docker windows installer and will be also distributing as a separate package on Chocolatey/OneGet. The first Chocolatey package will go out sometime like Tuesday with 1.6.0-rc1.

**Comment by domderen** [comment]
Hey, thanks :) But I am still wondering if it is necessary to integrate docker.exe here, when we have docker-machine ssh command? Can anyone tell me of any added benefits?

**Comment by ahmetalpbalkan** [comment]
@domderen SSH is not the recommended way to connect to the machines. "machine env machinename" sets the env for docker CLI. Read more or watch here: https://blog.docker.com/2015/02/announcing-docker-machine-beta/ Also one of the implicit goals of docker project is to make people manage servers without SSHing to them. :-)

**Comment by domderen** [comment]
Hey, this sounds reasonable. I'll have that in mind and try to prepare a version that is using docker.exe to open a docker command prompt ;)

**Comment by jeffdm** [comment]
Great timing @ahmetalpbalkan! Awesome!

@domderen that sounds great. Thanks for the work so far :)

**Comment by domderen** [comment]
Hey @jeffdm, thanks :) A little update on my side about the windows port. Main points:

DONE
* I recreated the deps and reset scripts for windows to install and remove external dependencies. They are written in powershell, coz my CMD skills really suck, and I am not sure if some steps could be done in CMD without at least invoking the PS commands. I was able to loose Chocolatey dependency though, which required administrator rights, so right now the whole setup can be done without admin rights.
* I've updated the SetupStore and SetupUtil to prepare the application for windows, including the downloading and installation of VirtualBox. As mentioned before, it is done without Chocolatey, so it still might be a little shaky.
* Updated the list of directories used by the app, to proper Windows paths, so the docker and docker-machine binaries are placed on the user's directory. This might not be the best place for them, but it is a start.
* I noticed that docker-machine's boot2docker image, does not automatically share Users directory with the VM, so I created a workaround and invoke a VirtualBox command to do it manually during the VM initialization step in the SetupStore. This is a strange one though coz the regular boot2docker does that automatically. Maybe this is an issue to be raised in the docker-machine repo.
* I've rewritten a bit parts of code responsible for opening URLs or drive paths, and added an extra dependency node package called "open" which supports different platforms out of the box, so opening links and paths should now work on all platforms.

So basically now it should be possible to clone the repo, install npm deps, download app deps using the PS script, start the application in development mode, have VirtualBox installed and VM initialized, and next it should be possible to create a new container with files shared from the windows host.

AWAITS
* File sharing and selecting directories in the app is flaky on windows, it still needs some magic to work properly. It works with the directory that is attached on container creation, but it is not possible yet, to change the default dir. Also the naming for the local directory in the container's settings should be changed, coz it is called "Mac Folder", so it is not really friendly for different platforms :)
* Opening a separate terminal with docker CLI is not available yet. I haven't started working on this one, as I am not sure how to simulate the same behavior on windows, mostly because I don't fully understand what the "terminal" script file is doing.
* Application deploy in gulp file, is not ready for deploying windows version. I wanted to leave it as the last piece.
* Testing if any of my changes don't break any of the Mac functionality. Unfortunately I don't have access to Mac, so I am only testing the app on Windows, so I don't know if I didn't break anything.
* The whole windows setup needs some proper testing. I tested it so far on Windows 7 and Windows 8, but I am sure I didn't try all possible dependencies' configurations.

I think that's mostly it for now. If anyone is interested in this, the branch I am working on is available at: https://github.com/domderen/kitematic/tree/win_client

I am also thinking of send a pull request with the current changes, as a separate branch here, just to let other people participate in the work. What do you guys think about it?

**Comment by jeffdm** [comment]
@domderen this is incredible. Thanks for the writeup. Please feel free to create a PR. I've made a `windows` branch if this helps https://github.com/kitematic/kitematic/tree/windows

**Comment by ahmetalpbalkan** [comment]
BTW boot2docker installer for 1.6.0-rc2 is ready. Please see if the problems persist there or not, if so please open an issue in boot2docker repos and cc me so we can fix for 1.6. (here's a dropbox link, distributed under no warranty) https://www.dropbox.com/s/s15m3lgccjzpw9v/boot2docker-installer-1.6.0-rc2.exe?dl=0

**Comment by jeffdm** [comment]
@ahmetalpbalkan awesome, I'll take this for a spin!

@domderen just walked through the code on your branch. This looks amazing so far. Please do make a PR! :smiley:

**Comment by domderen** [comment]
@ahmetalpbalkan I downloaded the installer you provided, and preformed a clean install of Boot2Docker. I than ran `boot2docker.exe init` and it downloaded this iso: https://github.com/boot2docker/boot2docker/releases/download/v1.5.0/boot2docker.iso I am not sure if this is the newest version you had in mind?

I later ssh'ed to the VM, and checked that the c/Users share was correctly connected there. But as I mentioned mi my previous comment, boot2docker was never an issue, it always connected the shared folder properly. The problem is with docker-machine, when I create a new VM with virtualbox driver. it says it uses the boot2docker iso as well, but it doesn't share the c/Users folder with the VM.

@jeffdm Good to hear that, I'll prepare a pull request later on.

**Comment by ahmetalpbalkan** [comment]
@domderen hmm it's not supposed to download anything as ISO is already in the installer. Could be a temporary issue as ISO/b2d cli are not tagged on official repos. Will be probably fixed once release goes out in a week.

**Comment by ahmetalpbalkan** [comment]
@domderen ok I took a look at the installer, it seems like if you have leftovers from the previous version it uses the old ISO somehow.

- uninstall b2d.
- delete `%USERPROFILE%\.boot2docker`
- delete `c:\program files\boot2docker for windows` (if still exists)
- open virtualbox, delete boot2docker-vm with its files.
- install with the link above.
- do the first run with `boot2docker start` link on the Desktop or Start Menu.
- it will put you in a prompt where you can run `docker ps`, and it's 1.6.0-rc2.

**Comment by domderen** [comment]
@ahmetalpbalkan I did follow your steps, and I did get 1.6 version, and I ssh'd to the boot2docker image, and I saw that the /c/Users share was there by default, as with previous versions of boot2docker image.

But does docker-machine uses exactly the same boot2docker image? If so, maybe there is something wrong with the virtualbox driver inside the docker machine? Coz docker-machines virtualbox VMs do not have this /c/Users share set up by default on windows.

**Comment by ahmetalpbalkan** [comment]
cc: @ehazlett for docker-machine related questions. I believe docker-machine (on Windows) uses Hyper-V to boot a boot2docker ISO.

**Comment by domderen** [comment]
@ahmetalpbalkan Hyper-V? You mean apart from VirtualBox? Coz it uses VirtualBox for sure.

**Comment by ehazlett** [comment]
Yes you can use hyperv with machine on windows instead of virtualbox. It's
not as tested but I would love to work together to get it there :)

**Comment by ahmetalpbalkan** [comment]
@domderen ah I totally forgot about the fact that VirtualBox driver also works on Windows. :) My bad.

**Comment by domderen** [comment]
@ahmetalpbalkan so is the virtualbox driver for docker-machine using a different version of boot2docker.iso? Coz it doesn't automatically create a shared folder on windows, and I am not sure where to raise an issue.

Also I saw that the newest version of Boot2Docker that you provided has the Docker CLI integrated. Where do you plan to install the Docker CLi binary by default? I guess Kitematic should try to use the same directory for storing the Docker CLI an Docker-Machine binaries.

**Comment by ahmetalpbalkan** [comment]
@domderen I will be installing docker cli binary next to boot2docker cli binary. (C:\program files\boot2docker for windows\docker.exe) I suggest opening a new issue on boot2docker/boot2docker repo to ask b2d related questions. You can cc tianon/svendowideit there.

**Comment by jeffdm** [comment]
Closing since windows is released with docker.exe :smiley:
