### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jschiffer** [kitematic/kitematic#313]
"/Applications/Kitematic (Beta).app/Contents/Resources/app/resources/docker-machine-0.1.0-kitematic-0.5.10 create -d virtualbox --virtualbox-memory 2048 dev returned non zero exit code"

Hope this is useful.

**Comment by jeffdm** [comment]
It is. Thanks for the issue!

Would it be possible to run the following on the command line and show the result? It will run the same command but in Debug mode.

`docker-machine -D create -d virtualbox dev`

Thanks

**Comment by jeffehobbs** [comment]
I get it too. 
```
ERRO[0000] Error creating machine: Machine dev already exists 
WARN[0000] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0000] Error creating machine  
```

**Comment by HungoHung** [comment]
I meet the exactly same issue as described by jschiffer and see the exactly same output as described by jeffehobbs.

Here is the way I fix the issue:

1. Close kitematic and make sure there is no process left (check activity monitor)
2. Download virtualbox from oracle.
3. After install virtualbox, launch virtualbox and I found one running instance called dev.
4. Stop that instance and remove it.
5. Re-launch kitematic and let the installation process go again. (This time it finish successfully).

**Comment by michalharakal** [comment]
I'm having also this problem. Maybe this helps. My machine is behind corporate firewall, where an setup for proxy is required like this:

    export https_proxy=http://xxx:xxx 

Running docker-machine with debug in command line creates following error:

    ERRO[0000] Error creating machine: Machine dev already exists
    WARN[0000] You will want to check the provider to make sure the machine and associated resources     were properly removed.
    FATA[0000] Error creating machine

**Comment by nhamiltonrally** [comment]
I also have the same issue presenting the same error messages. I've tried the above fixes with no success. Any other suggestions?

**Comment by jeffdm** [comment]
@michalharakal thanks for the info - Kitematic needs better support for a proxy environment.

@nhamiltonrally if you run `docker-machine -D create -d virtualbox dev`, what's the output?

**Comment by nhamiltonrally** [comment]
Same as above:
ERRO[0000] Error creating machine: Machine dev already exists 
WARN[0000] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0000] Error creating machine

**Comment by knice** [comment]
I am experiencing the same error. I followed @HungoHung's advice (close Kitematic, check Activity Monitor for running machines and quit them, then check VirtualBox to remove all machines). I even removed `~/.docker` to have clean slate. Then I ran: `docker-machine -D create -d virtualbox dev`

Which resulted in a new machine being created, but an error occurred when the machine was being configured. Here are the last few lines of that command:

```bash
DEBU[0020] STDERR:                                      
DEBU[0020] executing: /usr/bin/VBoxManage startvm dev --type headless 
DEBU[0020] STDOUT: Waiting for VM "dev" to power on...
VM "dev" has been successfully started.
 
DEBU[0020] STDERR:                                      
INFO[0020] Waiting for VM to start...                   
DEBU[0051] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 53343 -i /Users/raknight/.docker/machine/machines/dev/id_rsa docker@localhost sudo hostname dev && echo "dev" | sudo tee /var/lib/boot2docker/etc/hostname 
ERRO[0051] Error creating machine: exit status 255      
WARN[0051] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0051] Error creating machine
```

**Comment by jonatrey** [comment]
I tried the workaround from @HungoHung, but it did not work.

Here is my output from the comment {code}docker-machine -D create -d virtualbox dev{code}:

{code}
DEBU[0006] STDERR:
DEBU[0006] executing: /usr/bin/VBoxManage modifyvm dev --firmware bios --bioslogofadein off --bioslogofadeout off --natdnshostresolver1 on --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 8 --memory 1024 --acpi on --ioapic on --rtcuseutc on --cpuhotplug off --pae on --synthcpu off --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd
DEBU[0006] STDOUT:
DEBU[0006] STDERR:
DEBU[0006] executing: /usr/bin/VBoxManage modifyvm dev --nic1 nat --nictype1 virtio --cableconnected1 on
DEBU[0006] STDOUT:
DEBU[0006] STDERR:
DEBU[0006] executing: /usr/bin/VBoxManage modifyvm dev --natpf1 ssh,tcp,127.0.0.1,50790,,22
DEBU[0006] STDOUT:
DEBU[0006] STDERR:
DEBU[0006] executing: /usr/bin/VBoxManage list hostonlyifs
DEBU[0006] STDOUT:
DEBU[0006] STDERR:
DEBU[0006] executing: /usr/bin/VBoxManage hostonlyif create
DEBU[0006] STDOUT:
DEBU[0006] STDERR: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory

VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg*, int, int*)" at line 68 of file VBoxManageHostonly.cpp

ERRO[0006] Error creating machine: exit status 1
WARN[0006] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0006] Error creating machine
{code}

**Comment by jeffdm** [comment]
Thanks for the logs - seems like VBox may not have installed properly. Which version of VirtualBox are you running @jonatrey

**Comment by jonatrey** [comment]
I was running VBox 4.2.0, installed a long time ago. I now upgraded my VBox to 4.3.26 and everything is working fine.

**Comment by jeffdm** [comment]
Great to hear. Looks like Virtualbox had a missing device under /dev/ or something. Going to close this for now.

**Comment by knice** [comment]
For anyone else who comes across this issue: I still had problems launching Kitematic 0.5.13 after upgrading VirtualBox to 4.3, but a restart solved the issue.

**Comment by jeffdm** [comment]
Great to hear. Thanks for the info @knice!

Interesting, it seems that sometimes the VirtualBox kernel extensions aren't properly loaded.

**Comment by kylemclaren** [comment]
Uninstalling Virtualbox then restarting Kitematic solved this for me...

**Comment by kylemclaren** [comment]
I had to manually remove the machine:

`cd ~/.docker/machine/machines && rm -rf dev`

**Comment by etburke** [comment]
Manually removing the machine worked for me.

**Comment by kylemclaren** [comment]
Awesome @etburke :+1:

**Comment by TrentBrown** [comment]
Thanks, kylemclaren. Manually removing the "dev" machine directory fixed this problem for me, too. Odd that deleting the "dev" instance via the VirtualBox GUI left this directory behind...

**Comment by solthoth** [comment]
Hey guys, may be late to the party, but a common trend I see on issues is that if the virtual image that docker is creating in virtualbox is using 50% or more of the host's memory (RAM) then VB will not allow the instance to start up. By default I see that the ISO uses 2GB and if my box has 4GB VB sees this as an issue. Upgrading to 6GB+ fixes the issue 100% of the time for me (this is for both virtual machines and physical computers).
