### ISSUE TITLE
Mysql container [help]

### ISSUE THREAD

**Issue by lvegerano** [kitematic/kitematic#315]
I downloaded the mysql container and every time I tried to start the logs say: 
```
error: database is uninitialized and MYSQL_ROOT_PASSWORD not set
  Did you forget to add -e MYSQL_ROOT_PASSWORD=... ?
```
Asking around I was told to check the Dockerfile but could not find one. Any ideas?

Thanks.

**Comment by mchiang0610** [comment]
@lvegerano You should be able to use the 'settings' pane in Kitematic to set the MYSQL_ROOT_PASSWORD environment variable. 

Hope this helps. Closing the issue for now, but if you are still having trouble, please do open it again. 

Thanks
