### ISSUE TITLE
make the "open terminal" button bigger

### ISSUE THREAD

**Issue by plentz** [kitematic/kitematic#317]
https://kitematic.com/docs/using-docker-cli/
https://github.com/kitematic/kitematic/issues/251#issuecomment-78720257

I think that these two images already explains that we have a problem :)

maybe put it above the container list?

**Comment by mchiang0610** [comment]
@plentz Thanks for submitting this. We'll review these requests as we make the next versions. 

Thanks

**Comment by jeffdm** [comment]
Also feel free to make a quick sketch up of what you'd imagine this looking like. We'd love to see it.

**Comment by plentz** [comment]
I suck at design :)

![i suck at design](https://cloud.githubusercontent.com/assets/4867/6773755/9a4e5746-d0f4-11e4-8e1c-e354bd533995.png)

maybe the icon could be the same as the other icons with just an `>_` and "open terminal at the right. and we move the "+" sign to the side of the "new container" link.

**Comment by jeffdm** [comment]
This pic great for getting your idea across. Thanks. cc @Elesant.

**Comment by alcastaneda** [comment]
#dibs

**Comment by mchiang0610** [comment]
We are increasing the size of the terminal button in 0.6
