### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by domderen** [kitematic/kitematic#319]
Hi,

Could someone else please try to load the application on Windows? I am trying to start the app, and it does load. I managed to get the dependencies running, and I am not modifying the Setup scripts to download and install everything by itself. I prepared the dependencies powershell script which downloads the docker and docker-machine binaries, and modified the application code to use them. I also modified the code so it could find the VBoxManage binary and manage VirtualBox on windows. It is still missing a step of installing VirtualBox on it's own, so you need to install VirtualBox yourself, but other than that the application should start.

And now here comes the problem. When I run the application it seems that the app starts with two instances of react. I see two instances of 

```javascript
"Download the React DevTools for a better development experience: http://fb.me/react-devtools", source: c:\Users\dderen\Documents\GitHub\kitematic\node_modules\react\lib\React.js (143)
```

in the console log, and later when react tries to do anything connected with components it fails with error:

```javascript
"TypeError: Cannot read property 'firstChild' of undefined", source: file:///C:/Users/dderen/Documents/GitHub/kitematic/build/Main.js (47)
```

And the stacktrace points to react sources.

I debugged a bit more, and at application startup it seems that react is loaded twice, once by the kitematic app itself, and once by react-router, even though it was already loaded.

I tested this on Mac as well, and there is no issue, react is loaded only once, by the kitematic app. It is not loaded by react-router (I mean require command just takes the existing instance, instead of trying to initialize a new one). I also tested it on two different Windows boxes (one with Win 7 and one with Win 8.1), and the issue persists on both.

I would appreciate any help with this issue, and I have a problem even finding the root cause of it. I am not sure if it is connected with the Atom-Shell, or with react or with react-router or what...

Can anyone else test this setup on Windows as well to see if the behavior is reproducible globally?
My branch with windows changes is available at: https://github.com/domderen/kitematic/tree/win_client

Thanks in advance!

**Comment by domderen** [comment]
Hey, the issue was solved by my friend @KamilSzot. He found out that the usage of 

```html
<script src="Main.js"></script>
```

in Index.html causes the issue. I changed the setup to be

```html
<script src="Startup.js"></script>
```

and added new file Startup.js which has the following content

```javascript
require('./Main');
```

And now the application works as expected. I will confirm that it also works on Mac, and prepare a pull request to fix the issue.

**Comment by jeffdm** [comment]
Sorry for the delay in getting back. I've been following your work on Windows - this is awesome!

Feel free to drop by #kitematic on IRC or our [gitter channel](https://gitter.im/kitematic/kitematic) if you'd like to chat. I'm going to take your branch for a spin soon!

**Comment by domderen** [comment]
Hey, I think this issue thread can be closed now, as the PR has need merged.

**Comment by jeffdm** [comment]
Awesome, closing! Thx @domderen !

**Comment by radum** [comment]
I have the same issue with the latest version of kitematic downloaded just now.

The app opens nothing is shown in the window and in the console I get the same errors:

```
[7172:0511/202022:INFO:CONSOLE(48)] "Warning: owner-based and parent-based contexts differ (values: `undefined` vs `function (props, context)
```

What am I missing?

Removing the react router require removes the error but ...

**Comment by radum** [comment]
Just did what @domderen suggested and now it's fine. I'm a total noob for not understanding why but still why is this happening?

**Comment by domderen** [comment]
This issue was found and documented by my friend @KamilSzot here: https://github.com/atom/electron/issues/1289

Though to be honest the error message that you presented is unknown to me, I don't remember anything like that.
