### ISSUE TITLE
Allow for 'more details' on images overview

### ISSUE THREAD

**Issue by ChrisChinchilla** [kitematic/kitematic#320]
Many images need some extra information or parameters to be correctly installed, for example MariaDB.

Whilst Kitematic doesn't currently support setting any of these values when creating a container, it might be a good idea to allow users to click through and read the full documentation of an image so they are aware of a potential issue and don't install containers that wont work.

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by mchiang0610** [comment]
Clicking on image names in Kitematic will bring the user to Docker Hub, where they can find more information.
