### ISSUE TITLE
Ability to set Http/Https proxy settings for Kitematic

### ISSUE THREAD

**Issue by nickos168** [kitematic/kitematic#321]
Trying to start a Docker VM through the Kitematic UI and when it reached 99% is stops, after some time it timeouts. 

I am doing this at work and we have a proxy, so my guess this is causing the problem. At home this worked fine. Is there a way to setup Http/Https proxy settings?

**Comment by jeffdm** [comment]
Thanks for the issue!

There is no current way to do this at the moment, or at least that I know of. Thanks for coming by the IRC channel.

**Comment by nickos168** [comment]
Any workarounds?

**Comment by stardot1701** [comment]
Try this...
1) Open Terminal.  
2) Change directory to location of Kitematic App
3) type the following, replacing the proxy info with your own...

 http_proxy=http://proxyhost:proxyport https_proxy=http://proxyhost:proxyport open Kitematic\ \(Beta\).app/

Good luck!

**Comment by jenslauterbach** [comment]
Really would like to set a proxy too. I have the same problem like @nickos168.

**Comment by dobsiin** [comment]
I have the same problem trying the kitematic 0.7 alpha on windows.
I am sitting behind a corporate proxy.

**Comment by glenti** [comment]
Try installing cntlm to get nl authentication to corporate proxy

**Comment by guydavis** [comment]
Just tried with cntlm, which I verified works well for Firefox using proxy of localhost:3128.  I can't get the Windows Kitematic Alpha to install however.  It gives error about being unable to being unable to:

    Get https://api.github.com/repos/boot2docker/boot2docker/releases: dial tcp 192.30.252.138:443:   
    ConnectEx tcp: No connection could be made because the target machine actively refused it.

I tried by first setting Windows env vars (for my user) of http_proxy and https_proxy to http://localhost:3128.  As well, I then tried stardot1701's suggestion of using them on CMD shell.  Same error. 

Solving this proxy install roadblock would go along way to speeding adoption amongst big corps.  I can start getting our developers, then testers, and even management making use of our software in Docker containers, but only if the Docker (Kitematic) install on Windows is trivial.

**Comment by rikkuness** [comment]
Surely the issue isn't entirely at the kitematic layer, I'd expect it needs setting inside the boot2docker VM so that docker engine can use it to communicate with Docker Hub?

**Comment by gengyong** [comment]
on windows, you can just add variable setting "http_proxy" to system environment, it works perfectly.

**Comment by mchiang0610** [comment]
Merging with #1031

**Comment by mchiang0610** [comment]
If anyone still has problems with this on Mac or Windows 10+, please contact me at mchiang@docker.com.

We are working on something to help address this issue.

**Comment by brokosz** [comment]
@mchiang0610 - still no dice on Mac. I sent you an email.

**Comment by Trakkasure** [comment]
I am also having issues. Running behind a draconian proxy. Nothing gets through without checking into that damn thing.

**Comment by mikedevita** [comment]
another here with issues behind corporate NTLM bluecoat proxy...

**Comment by blackfyre** [comment]
@mchiang0610 
I'm also having issues with this, although I'm a mobile worker (half time in office, another half out of office), with no access to my env variables on windows 10...
Wouldn't it be simpler to set this in the app? or read it from Docker?

**Comment by eldelmoniorojo** [comment]
I have set cnltm to use my corporate proxy using ntlm authentication and also set HTTP_PROXY and HTTPS_PROXY before run Electron (Kitematic binary file) from command line

 export 'HTTP_PROXY=http://localhost:8080'
export 'HTTPS_PROXY=http://localhost:8080'
 /Applications/Docker/Kitematic\ \(Beta\).app/Contents/MacOS/Electron
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

and it works!!
I hope it can help you!!

**Comment by tjwebb** [comment]
By following advice from @eldelmoniorojo and others, I am able to log in to my docker account via Kitematic, but I am not able to download any images. I get the following error:

```
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
```

![screen shot 2017-08-23 at 4 29 15 pm](https://user-images.githubusercontent.com/1009114/29636886-4e75dcc8-8820-11e7-9ee4-41b60df59ad7.png)

Is there additional configuration that might help me solve this?

**Comment by eldelmoniorojo** [comment]
1. Try to update docker versión. There was some problems related to dns resolutions.
2. try setting your dns to google 8.8.8.8 (this could solve your problems)
3. Cross your fingers.

**Comment by kvlahromei** [comment]
Switching the DNS doesn't work for people at enterprises. The network settings are propagated via DHCP and IT will kill you, if you tweak the offical settings.

I confirm the bug for kitematic 17.0 (toolbox 17.07).

**Comment by aseempatni** [comment]
I'm also facing the same issue. kitematic 0.17.2 Docker for Mac 18.06.0

**Comment by johnschult** [comment]
This is my working setup on macos...
```
alias kitematic="open /Applications/Kitematic.app/"
```
If your terminal has `http_proxy` and `https_proxy` set and you run your alias `kitematic` from there it will work.

**Comment by macosxgeek** [comment]
It's working for me with Terminal:

http_proxy=http://some.address.here open Kinematic.app

I can see it's reaching the specified proxy host. The problem is with SSL Certificate. When the app launches I'm getting:

"unable to get local issuer certificate"

Basically I have the required cert and it's added to the Keychain. Is there a way to use it with Kinematic? (I mean the certificate I have) ?

**Comment by eldelmoniorojo** [comment]
Try setup also https_proxy too using same value http_proxy

**Comment by 42force** [comment]
Hi, 
what was the solution for this? it seems setting the proxy does not work.

Thank you,
