### ISSUE TITLE
Can't setup/start first VM: 'Error: connect ECONNREFUSED'

### ISSUE THREAD

**Issue by kevinSuttle** [kitematic/kitematic#324]
First install. 
Beta Version 0.5.10. 
OSX 10.10.2 14C1514.

Caveat: I'm on unfamiliar wifi (Rackspace Docker Birthday Event)

![screen_shot_2015-03-23_at_6_39_27_pm](https://cloud.githubusercontent.com/assets/95672/6793027/ee1cb488-d18c-11e4-92fc-f07ed5bd8efb.png)

**Comment by jeffdm** [comment]
Thanks for the issue! Sorry to hear the setup didn't finish. Does retrying happen to work?

Jeff

**Comment by kevinSuttle** [comment]
Let me retry now that I'm home. I tried again during the initial setup—both deleting the VM and not—but no dice.

**Comment by kevinSuttle** [comment]
Now, the application itself doesn't complete start up. 
I opened up dev tools and found this. Uninstalled and and reinstalled several times. 

![screen shot 2015-03-24 at 12 07 59 am](https://cloud.githubusercontent.com/assets/95672/6796082/0cec9b6c-d1ba-11e4-922d-0cd8f3369222.png)
![screen shot 2015-03-24 at 12 08 18 am](https://cloud.githubusercontent.com/assets/95672/6796083/0ceccb32-d1ba-11e4-950d-78964b93b9aa.png)

**Comment by kevinSuttle** [comment]
Rebooted. And now it works. `¯\_(°.°)_/¯`

![screen shot 2015-03-24 at 12 19 52 am](https://cloud.githubusercontent.com/assets/95672/6796157/af5f2d28-d1bb-11e4-8aef-5066937ccecb.png)

**Comment by morex87** [comment]
same error found
I have tried to reboot with no results yet.. any solution with the beta?
command line tools package for osx is needed?

here is my setup setup:
osx 10.10.2
kinematic (beta)  0.5.10

![kitematic_error](https://cloud.githubusercontent.com/assets/4439704/6871571/48a7ecc2-d482-11e4-8389-0e38e58cf274.png)
