### ISSUE TITLE
docker-machine-0.1.0.-kitematic-0.5.10 spinning out of control

### ISSUE THREAD

**Issue by maxx** [kitematic/kitematic#327]
docker-machine-0.1.0.-kitematic-0.5.10 attempts to exhaust an entire cpu thread, all available memory, and increases open files until it hits the system limit.  Before I realized what was going on, this actually caused some corruption in my system plist files (for example, I had to regenerate input plist in OSX due to the OS corrupting it as a result of way too many open files).

Interface sits at "Starting Docker VM" at 99%.

As a side note, I also have the issue of the VirtualBox VM never shutting down when kitematic is stopped -- so these may be related.

I will try to gather more data next time this occurs.

**Comment by jeffdm** [comment]
Hi there, thanks for the issue. Really sorry that this is occurring. It definitely looks to be something related to VirtualBox, with `docker-machine` possibly hanging and opening a bunch of files.

This issue seems familiar so I'll try to reproduce it on my side as well.

**Comment by maxx** [comment]
I've been trying to reproduce this today too .. 

It only seems to happen after a high uptime .. I saw lots of dynlib errors when I sampled the process in activity monitor.. Unfortunately I didn't get to copy those in time.

I had recently done a major homebrew overhaul, upgrading nearly everything in /usr/local. Would there be any dependencies on anything in there?

**Comment by maxx** [comment]
Also, my virtualbox is 4.3.26 r98988, but the same issue also occurred on a previous version.

**Comment by WangWenchao** [comment]
I met this problem today too,  any fixed?

**Comment by pomahtuk** [comment]
Rebooted, updated almost everything from home-brew and still getting this issue. If you are interested in any details - i could post them here.

**Comment by jeffdm** [comment]
Thanks! 

@pomahtuk could you run the following commands to re-create the VM and see what's causing the error?

- `docker-machine rm -f dev`
- `docker-machine -D create -d virtualbox dev`

Thanks!

**Comment by pomahtuk** [comment]
@jeffdm sorry for so long response time, but here is my output:

```
DEBU[0010] STDERR:
INFO[0010] Waiting for VM to start... 
DEBU[0042] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 57201 -i /Users/ilovriakov/.docker/machine/machines/dev/id_rsa docker@localhost sudo hostname dev && echo "dev" | sudo tee /var/lib/boot2docker/etc/hostname
ERRO[0043] Error creating machine: exit status 255
WARN[0043] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0043] Error creating machine
```

**Comment by jeffdm** [comment]
@pomahtuk thanks!

`Exit status 255` errors should be fixed in the next release of Kitematic which will include `docker-machine` 0.2.0

That said, as a temporary solution I've found (will wipe all docker / vms):
- Remove any VirtualBox VMs
- Remove the `~/.docker` directory
- `docker-machine -D create -d virtualbox dev`

**Comment by mchiang0610** [comment]
@maxx  @WangWenchao  @pomahtuk 
Consolidating with https://github.com/kitematic/kitematic/issues/236 

We are testing out a pre-release that should fix this problem! Do you mind giving it a try?

https://github.com/kitematic/kitematic/releases/download/v0.5.27-intel-nic/Kitematic-0.5.27-intel-nic.zip

Let me know if you are still running into the issue after.

**Comment by maxx** [comment]
I forgot to mention I never had this issue again after 0.5.27.
