### ISSUE TITLE
i don't download centos image,why?

### ISSUE THREAD

**Issue by shubo83** [kitematic/kitematic#328]
![image](https://cloud.githubusercontent.com/assets/3070621/6796323/f9e91f0a-d22b-11e4-811b-ff5cb035293d.png)

**Comment by mchiang0610** [comment]
@shubo83 It seems that Kitematic isn't getting a response from VirtualBox. Can you try force quitting both Virtualbox and Kitematic, and starting them again?

**Comment by wind-rider** [comment]
Even restarting the computer does not help...

**Comment by jeffdm** [comment]
Thanks for the issue.. sorry you're hitting this error.

Does removing the `dev` VirtualBox VM work? Would it be possible for you to check if it's running?

**Comment by mchiang0610** [comment]
@shubo83 Do you mind trying again with the latest Kitematic? It should be fixed. If not please re-open this issue. Thanks!
