### ISSUE TITLE
Hovering over settings sends request to container:80

### ISSUE THREAD

**Issue by boopathi** [kitematic/kitematic#333]
![screenshot 2015-03-26 03 29 50](https://cloud.githubusercontent.com/assets/294474/6836526/c38d6acc-d368-11e4-9592-7dec7e4c3175.png)

Hovering over the Kitematic settings at the bottom left corner sends http request to container port 80 to update the view under `Home`.

Is this intended ? I think this shouldn't happen.

**Comment by Elesant** [comment]
Thanks for reporting the issue! @boopathi
