### ISSUE TITLE
How can i stop a running a container without the command line ?

### ISSUE THREAD

**Issue by ugerkmannbartels** [kitematic/kitematic#335]
Hey,
great work ! But i missing a easy way to stop a running container ?

Maybe i overlook something.
![screenshot_26_03_15_09_11](https://cloud.githubusercontent.com/assets/11660846/6842429/3f459c0a-d398-11e4-9741-eb5a1b6f3db9.jpg)

**Comment by jeffdm** [comment]
Thanks for the issue. This is a duplicate of #250. Closing for now. Thanks for the image, though :+1:
