### ISSUE TITLE
Create CentOS Docker Fails with VPN error

### ISSUE THREAD

**Issue by gcstang** [kitematic/kitematic#338]
This keeps failing and I have no VPN, others are working correctly for example the hello-world-nginx.

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by wind-rider** [comment]
I have the same issue - hello-world-nginx works, but spksrc from Synocommunity fails.

Also - after trying spksrc, hello-world-nginx also doesn't work anymore.

**Comment by mchiang0610** [comment]
Merging with #1031

**Comment by mchiang0610** [comment]
If anyone still has problems with this on Mac or Windows 10+, please contact me at mchiang@docker.com.

We are working on something to help address this issue.
