### ISSUE TITLE
Editing Container Ports

### ISSUE THREAD

**Issue by kameshsampath** [kitematic/kitematic#344]
Is there a way to edit container ports i.e. Docker Port to OS Port mapping, right now I dont see the Kitematic UI is allowing it.

Steps to reproduce it:

* Create a new contaier from Kitmatic UI - e.g. postgres
* Once the Server is booted you will see that you can't edit or change the Ports

**Comment by jeffdm** [comment]
Thanks for the issue! There's currently no way to edit the ports. I'll label this as a feature :)

**Comment by DominicBoettger** [comment]
One example:

You have five developers using kitematic. On every kitematic runs a mongodb container. This container will have another port on every workstation. So every developer has another configuration. I thought i solved it running manually from commandline but after clicking restart in the interface the configuration was removed.
Is it correct that the container will be dropped when clicking restart? This is a nightmare!

**Comment by jontayesp** [comment]
:+1:

**Comment by agorski** [comment]
:+1:

**Comment by andrestc** [comment]
This is indeed a great feature. +1.

**Comment by brunowego** [comment]
+1

**Comment by d-oliveros** [comment]
How are we supposed to use kitematic, if the port keeps changing every time you start a service? There's no way we can use this if the port is not fixed or configurable.

**Comment by virtualirfan** [comment]
+1

Frankly, kitematic is unusable without this "feature".

**Comment by furlongm** [comment]
+1

**Comment by sergioamim** [comment]
+1

**Comment by piti118** [comment]
+1

**Comment by mgcnrx11** [comment]
+1

**Comment by wallclockbuilder** [comment]
+1

**Comment by goushijie** [comment]
+1

**Comment by goushijie** [comment]
And I look forward to it.

**Comment by pahanini** [comment]
+1

**Comment by mathieukempe** [comment]
+1

**Comment by giodegas** [comment]
+1

**Comment by giodegas** [comment]
also, having by default the port numbers corresponding to the ones in the docker file would be a nice option.
I usually started a container with:

    docker run -d -p 5000:5000  -p 6000:6000/udp <image>

**Comment by paulfeaviour** [comment]
+1

**Comment by FrenchBen** [comment]
As of Kitematic v0.8.4 you can edit ports for containers if you're unhappy with the port it uses

**Comment by giodegas** [comment]
I am now testing Kitematic 0.9.3. 
Changing the TCP port works. I can communicate with the internal process via TCP.
Unfortunately, changing the UDP port it does not. The internal process listening to the UDP port stops responding.
Apparently the iptables rules in the docker-VM are not properly regenerated.
The only way to use the UDP port is not changing anything, so the iptables rules do not change.

**Comment by giodegas** [comment]
Actually for my applications the best would be that by default the container should externally espose the port number indicated in the Dockerfile with the EXPOSE command, if they are greater that 1024 without changing to the 32768 range.
This is how Docker works on Linux without Kitematic.
Also UDP ports are not shown,in the summary, ( see #438 ) so my process is unreachable even with an unchanged ports setup.

**Comment by ssi-praveen-marothu** [comment]
Cant add same TCP & UDP ports.  If there is an existing TCP port , then adding the same port as UDP is overwriting the TCP port.
