### ISSUE TITLE
Get current docker IP via command line

### ISSUE THREAD

**Issue by caarlos0** [kitematic/kitematic#345]
Let's say I don't want to open a new terminal via Kitematic, but rather set the `DOCKER_HOST` in my current terminal.

I looked into the code but didn't found a way of doing this. Is it possible? Can we add such feature?

**Comment by DieterReuter** [comment]
Just use `docker-machine env dev` to display the settings of your current Docker Host. Or you can use directly in your bash shell the command `$(docker-machine env dev)` and all settings will be done for you.

Here is a short example:
```
docker-machine env dev
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=/Users/dieter/.docker/machine/machines/dev
export DOCKER_HOST=tcp://192.168.59.103:2376
```

**Comment by caarlos0** [comment]
Nice!

Many thanks @DieterReuter !
