### ISSUE TITLE
Windows version of Kitematic

### ISSUE THREAD

**Issue by domderen** [kitematic/kitematic#347]
Current progress is visible at: https://github.com/kitematic/kitematic/pull/339

The status list:

- [x] I recreated the deps and reset scripts for windows to install and remove external dependencies. They are written in powershell, coz my CMD skills really suck, and I am not sure if some steps could be done in CMD without at least invoking the PS commands. I was able to loose Chocolatey dependency though, which required administrator rights, so right now the whole setup can be done without admin rights.
- [x] I have removed the pre and post install scripts from package.json as this is really discuraged by the NPM docs, and instead moved them to gulpfile. This also allowed me to port those scripts for Windows platform.
- [x] I've updated the SetupStore and SetupUtil to prepare the application for windows, including the downloading and installation of VirtualBox. As mentioned before, it is done without Chocolatey, so it still might be a little shaky.
- [x] Updated the list of directories used by the app, to proper Windows paths, so the docker and docker-machine binaries are placed on the user's directory. This might not be the best place for them, but it is a start.
- [x] I noticed that docker-machine's boot2docker image, does not automatically share Users directory with the VM, so I created a workaround and invoke a VirtualBox command to do it manually during the VM initialization step in the SetupStore. This is a strange one though coz the regular boot2docker does that automatically. Maybe this is an issue to be raised in the docker-machine repo.
- [x] I've rewritten a bit parts of code responsible for opening URLs or drive paths, and added an extra dependency node package called "open" which supports different platforms out of the box, so opening links and paths should now work on all platforms.
- [x] Ability to open a CMD window with Docker env variables set up, and docker on the path.
- [x] Tested the application setup process on WIndows 8.1 and it works as expected.
- [x] File sharing and selecting directories in the app is flaky on windows, it still needs some magic to work properly. It works with the directory that is attached on container creation, but it is not possible yet, to change the default dir. Also the naming for the local directory in the container's settings should be changed, coz it is called "Mac Folder", so it is not really friendly for different platforms :)
- [x] Application deploy in gulp file, is not ready for deploying windows version. I wanted to leave it as the last piece.
- [x] Testing if any of my changes don't break any of the Mac functionality. Unfortunately I don't have access to Mac, so I am only testing the app on Windows, so I don't know if I didn't break anything.
- [x] Probably some graphical changes to the app window itself to make it more Windows like :)
- [x] Adding support for ssh terminal in ContainerSubHeader.
- [x] Keyboard shortcuts support on Windows.
- [x] Running reset scripts from the gulp task (npm run reset).
- [ ] Auto updates
- [x] Installer & Distribution

**Comment by jeffdm** [comment]
Added:
+ Auto updates
+ Installer & Distribution

to the list.

**Comment by StefanScherer** [comment]
I just stumbled upon AppVeyor as a CI server for Windows in the Chocolatey project.

Perhaps this is a useful service to build the Windows verison of Kitematic: http://www.appveyor.com

**Comment by jeffdm** [comment]
@StefanScherer thanks! Awesome. This will be huge for any integration testing we need to do. Unit tests usually run in Linux on CircleCI and just test each JS class independently and mock the rest.

**Comment by jeffdm** [comment]
@domderen So far so good, I checked off `Testing if any of my changes don't break any of the Mac functionality` after some extensive testing.

**Comment by domderen** [comment]
@jeffdm Great! And in terms of unit tests, I guess we can add a few of them with mocked process.platform equal to 'win32'. Maybe add such point to the list?

**Comment by jeffdm** [comment]
Status update: Merged the initial PR @domderen with a few tweaks to make sure Mac still works.

**Comment by jeffdm** [comment]
Status update: Windows alpha launched last friday! Everything done on this list except for auto updates.

@domderen this foundational work was critical to getting an initial version of Windows shipped last week. I wanted to say a huge thanks for the contributions. Many Windows users around the world are running containers for the first time!

Going to close this for now in favor of an issue only for windows auto-updates.

**Comment by nuest** [comment]
I have a working build for my Kitematic fork with AppVeyor, maybe this helps someone:

https://github.com/nuest/kitematic/blob/model-ui/appveyor.yml

**Comment by StefanScherer** [comment]
@nuest Impressive! Thanks for sharing.
