### ISSUE TITLE
Enable API URL

### ISSUE THREAD

**Issue by DaspawnW** [kitematic/kitematic#348]
In new version of IntelliJ IDEA 14.1 is support for Docker. For use it is important to enable API URL.
What about this for Kitematic?

**Comment by jeffdm** [comment]
Thanks for the issue.

To help me understand this better, can you point to an IntelliJ tutorial or similar? Are you looking for how to get the Docker Remote API URL that Kitematic uses?

**Comment by Jirapong** [comment]
I think this is what @DaspawnW mention - http://blog.jetbrains.com/idea/2015/03/docker-support-in-intellij-idea-14-1/

**Comment by jeffdm** [comment]
Ah! Ok. Thanks @Jirapong

**Comment by Jirapong** [comment]
So, I believe that if forward the Remote API URL port 2375 or 2376 on the "dev" VM manually it should work? 

May be this is good to be an option on the VM Settings?

**Comment by DaspawnW** [comment]
Thank you, @Jirapong. I think this is what I mean.

Sorry for my late answer.

**Comment by jeffdm** [comment]
Wow! Thanks for the help @Jirapong !

Intellij doesn't work with an engine URL over TLS?

**Comment by Jirapong** [comment]
I believe they do also. However, On OSX there is issue with curl library that not allow --cert and --key. see reference at https://github.com/boot2docker/boot2docker/issues/573 . I'm working on the solution to allow TLS.

**Comment by Jirapong** [comment]
OK. On connecting with TLS. I put everything in my blog post at https://github.com/kitematic/kitematic/issues/348

**Comment by jeffdm** [comment]
@Jirapong awesome. Thanks for the blog post!

**Comment by mchiang0610** [comment]
@Jirapong  Thanks for the blog. 

Assuming the information solves the issue. Closing this issue for now. Please re-open if you feel the need to. :)
