### ISSUE TITLE
Cannot start any debian container.

### ISSUE THREAD

**Issue by Koxzi95** [kitematic/kitematic#350]
I can start any other containers but Debian containers don't seem to be responsive. When created they just stop immediately and I cannot run or restart them. The log also stays empty.

**Comment by jeffdm** [comment]
Thanks for the issue!

This is because the debian container is usually meant to be used as a base image and doesn't have a CMD specified in the Dockerfile. In Kitematic it just runs nothing.

Flagged this as a bug since Kitematic should provide a better UI/UX response for this case.

**Comment by Koxzi95** [comment]
Makes sense, a UI prompt would be fantastic. Learning docker so wondered what was wrong!

**Comment by wcandillon** [comment]
I'm having the same issue. Is there an ubuntu container we can use with kitnematic?

**Comment by jeffdm** [comment]
For now `ubuntu-upstart` is an ubuntu image that should work with Kitematic: https://registry.hub.docker.com/u/library/ubuntu-upstart/

That said, the base images should all still work with Kitematic. Leaving this open for now

**Comment by wcandillon** [comment]
@jeffdm thks a lot! I was able to find an ubuntu image that works

**Comment by jeffdm** [comment]
Great to hear, @wcandillon !
