### ISSUE TITLE
Kitematic hangs

### ISSUE THREAD

**Issue by claytantor** [kitematic/kitematic#354]
![image](https://cloud.githubusercontent.com/assets/407854/6946787/94664acc-d857-11e4-8d35-7ee2771f00d5.png)

when trying to remove images the app hangs and becomes unresponsive.

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by mchiang0610** [comment]
@claytantor This issue should be fixed in the newer version of Kitematic. Please re-try. 

If the issue still exists, please let us know! Thanks
