### ISSUE TITLE
Kitematic shows fatal error when attempting to create a container from `scratch`

### ISSUE THREAD

**Issue by lostinplace** [kitematic/kitematic#355]
I go to create a new image from https://registry.hub.docker.com/_/scratch/

No VPN software running

![image](https://cloud.githubusercontent.com/assets/645413/6950091/6df8dfd8-d886-11e4-83e4-f570dd0df5bc.png)

This happens with a lot of other images as well, although some work just fine

**Comment by jeffdm** [comment]
Thanks for the issue,

The Docker engine complains if you try to run scratch, but it seems that Kitematic treats the error as a fatal error and stops. Instead it should just show a similar warning.
