### ISSUE TITLE
Kitematic crashes on first run and complains about Atom Framework

### ISSUE THREAD

**Issue by cusspvz** [kitematic/kitematic#357]
report:
```
Process:               Kitematic (Beta) [68237]
Path:                  /Applications/Kitematic (Beta).app/Contents/MacOS/Kitematic (Beta)
Identifier:            com.kitematic.kitematic
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Kitematic (Beta) [68237]
User ID:               502

Date/Time:             2015-04-02 15:41:05.169 +0100
OS Version:            Mac OS X 10.10.2 (14C1510)
Report Version:        11
Anonymous UUID:        3D0F422E-8473-C00D-EE9A-0D30A26AA91B

Sleep/Wake UUID:       0F295AB9-35DA-40DE-A37A-C5568A83FC83

Time Awake Since Boot: 640000 seconds
Time Since Wake:       2000 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Atom Framework.framework/Atom Framework
  Referenced from: /Applications/Kitematic (Beta).app/Contents/MacOS/Kitematic (Beta)
  Reason: no suitable image found.  Did find:
	/Applications/Kitematic (Beta).app/Contents/MacOS/../Frameworks/Atom Framework.framework/Atom Framework: file too short

Binary Images:
    0x7fff62415000 -     0x7fff6244b837  dyld (353.2.1) <65DCCB06-339C-3E25-9702-600A28291D0E> /usr/lib/dyld

```

**Comment by jeffdm** [comment]
Thanks for the issue!

Interesting - first time seeing this. Does re-downloading Kitematic work?

**Comment by cusspvz** [comment]
Actually I was unable to use **Kitematic** because it crashes every time I try to open it.
Have you deployed a new release on its website since yesterday? If not, that happens with latest available version.

**Comment by jeffdm** [comment]
Thanks for the update :smiley: 

From this thread: https://discuss.atom.io/t/dont-work-with-mac-osx-10-9-2/6019/3

It seems that atom-shell based apps only work if you unzip them using the `Archive Utility`. Does unzipping the app this way work?

**Comment by cusspvz** [comment]
WHAAAATTT?? Thats crazy, but... it worked! I feel dumb now, unzipping using the `Archive Utility` fixed it! Is it maybe related with symlinks or case sensitive?

Well, at least this issue should help someone. Thanks for the tip @jeffdm !

**Comment by jeffdm** [comment]
No reason to feel dumb! Seems like a silly bug upstream with Atom. Glad we got it working :smiley:. Sadly, it also occurs with some CLI-based unzip tools. It definitely will help others :smiley:
