### ISSUE TITLE
Ability to load one's own Dockerfiles to create containers

### ISSUE THREAD

**Issue by niieani** [kitematic/kitematic#366]
This would be a great feature when developing and often rebuilding or testing Dockerfiles. It would be awesome if one could simply drag&drop a Dockerfile onto Kitematic, which would build it and create a  container from it. Perhaps having a list of locally built Docker packages would be useful too.

**Comment by kpsmith** [comment]
Yes please. Is there a way to accomplish this today without uploading the Dockerfile to docker hub?

**Comment by jeffdm** [comment]
Thanks for the issue! This is a great idea (re the drag and drop).

**Comment by notthetup** [comment]
:+1:

**Comment by jontayesp** [comment]
:+1:

**Comment by prussiap** [comment]
hmm so there is no way to load a local dockerfile or point a downloaded image to use your local Dockerfile and rails app?

**Comment by jeffdm** [comment]
@prussiap not currently, sorry. Containers can only be pulled and created via DockerHub for now.

Keep an eye out for work around this soon!

Going to close this since it's a duplicate of #296. Thanks!!!

**Comment by amiracam** [comment]
sorry, late to the party, but is there a way of loading a local container , specifically one that cloned via "commit" on one machine and then copied to another target machine ?

**Comment by FrenchBen** [comment]
@amiracam See our docs on export and import:
https://docs.docker.com/engine/reference/commandline/import/
