### ISSUE TITLE
Skip install button

### ISSUE THREAD

**Issue by RepublicOfAppsLLC** [kitematic/kitematic#368]
Hi,

I already have docker, boot2docker and Virtualbox installed.  In fact they're currently running containers that I don't want to disturb.

I started Kinematic but it's trying to re-install these things and I don't want that.  I just want to use Kinematic to view and maybe manipulate containers.

Please add a "skip install" button and please do not automatically start the install.  This should be a user-controlled action in both cases.

Thanks!

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by nickfan** [comment]
+1

**Comment by jeffdm** [comment]
Going to close this for now since we now detect if VBox exists and automatically skip it
