### ISSUE TITLE
Ability to connect to a private Docker Hub

### ISSUE THREAD

**Issue by msabramo** [kitematic/kitematic#375]
I have an internal Docker Hub with images that are specific to my company and I am wondering if I could deploy them with Kitematic.

**Comment by jontayesp** [comment]
:+1:

**Comment by jontayesp** [comment]
Duplicate: #210.

**Comment by jeffdm** [comment]
Thanks for creating the issue

@jontayesp Thanks!

Moving the discussion over to #232
