### ISSUE TITLE
error FATA[0000] Couldn't read ca cert... when running docker logs

### ISSUE THREAD

**Issue by funkytaco** [kitematic/kitematic#378]
I removed boot2docker, and I understand that Kitematic copies the docker binary to the OS. I'd like to know if this log entry is from boot2docker or kitematic?

`FATA[0000] Couldn't read ca cert /Users/myuser/.boot2docker/certs/boot2docker-vm/ca.pem: open /Users/myuser/.boot2docker/certs/boot2docker-vm/ca.pem: no such file or directory`

**Comment by funkytaco** [comment]
More info:

    $ which docker
    /usr/local/bin/docker

    $ echo $DOCKER_CERT_PATH
    /Users/myuser/.boot2docker/certs/boot2docker-vm

So it looks like Kitematic doesn't check the docker certificate path. This path doesn't exist:
    stat /Users/myuser/.boot2docker/certs/boot2docker-vm/
    stat: /Users/myuser/.boot2docker/certs/boot2docker-vm/: stat: No such file or directory

**Comment by funkytaco** [comment]
It looks like `docker-machine` has the settings needed:
    > docker-machine env dev
    export DOCKER_TLS_VERIFY=1
    export DOCKER_CERT_PATH=/Users/lgonzalez/.docker/machine/machines/dev
    export DOCKER_HOST=tcp://192.168.99.100:2376


    > docker logs
    FATA[0000] Couldn't read ca cert /Users/lgonzalez/.boot2docker/certs/boot2docker-vm/ca.pem: open /Users/lgonzalez/.boot2docker/certs/boot2docker-vm/ca.pem: no such file or directory 

    So then I ran:
    > $(docker-machine env dev)
    > docker logs              
    docker: "logs" requires 1 argument. See 'docker logs --help'.
So, it looks like docker logs works again.

This works fine, until I close my terminal window, so I'll set it in my profile for now.

**Comment by mchiang0610** [comment]
@funkytaco This is really weird. Are you still having this issue running the latest Kitematic?

**Comment by funkytaco** [comment]
I had boot2docker installed first. I then installed Kitematic. I then uninstalled the boot2docker manually. I didn't think Kitematic was using boot2docker directory files in any fashion.

Not sure how to duplicate exactly at this point. I've not had the issue recur.
