### ISSUE TITLE
Volumes not working on Mac Pro

### ISSUE THREAD

**Issue by Jerry49Taylor** [kitematic/kitematic#380]
I'm running OS X Yosemite 10.10.3 on my MacPro and Kitematic is not opening the website folder in Finder for me. This works on my MacbookPro running same version of OS X.

There's no Kinematic folder in my homed directory on the Mac Pro so maybe that's the problem. Could it be because the Users area is mounted on the second HD and not the system HD?

**Comment by mchiang0610** [comment]
@Jerry49Taylor Are you still having this problem with the updated Kitematic?

**Comment by mchiang0610** [comment]
@Jerry49Taylor Assuming it's okay for now. Please re-open this issue if you are still having problems.
