### ISSUE TITLE
Kitematic didn't automatically update the VM

### ISSUE THREAD

**Issue by timothyjlaurent** [kitematic/kitematic#392]
Installed kitematic -- when I try to run anything:

```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
FATA[0000] Error response from daemon: client and server don't have same version (client : 1.18, server: 1.17)
```

:(

**Comment by timothyjlaurent** [comment]
This may have been related to 2 kitematic windows being open -- working now

**Comment by jeffdm** [comment]
@timothyjlaurent Hi there. Sorry about that. Glad it's fixed now.

It looks like Kitematic didn't update an existing VM you had properly but did update the binaries in `/usr/local/bin`. If you run `docker-machine upgrade` manually it should work.
