### ISSUE TITLE
OSX Yosemite Kitematic doesn't install 

### ISSUE THREAD

**Issue by crislar** [kitematic/kitematic#394]
This is the dump it shows on the install screen. 
C

/Applications/Kitematic (Beta).app/Contents/Resources/app/resources/docker-machine-0.2.0 create -d virtualbox --virtualbox-memory 2048 dev returned non zero exit code stdout:time="2015-04-18T12:09:01+01:00" level="info" msg="Creating SSH key..." time="2015-04-18T12:09:03+01:00" level="info" msg="Creating VirtualBox VM..." time="2015-04-18T12:09:30+01:00" level="error" msg="Error creating machine: exit status 1" time="2015-04-18T12:09:30+01:00" level="warning" msg="You will want to check the provider to make sure the machine and associated resources were properly removed." time="2015-04-18T12:09:30+01:00" level="fatal" msg="Error creating machine" stderr:

**Comment by jeffdm** [comment]
@crislar Thanks for the issue. I'm very close to reproducing this but in the meantime I'll group this with #295. Closing for now, and feel free track the progress on that issue!

Jeff

**Comment by crislar** [comment]
will do thanks for the rapid feedback!
Christian

Jeffrey Morgan wrote:
> @crislar <https://github.com/crislar> Thanks for the issue. I'm very
> close to reproducing this but in the meantime I'll group this with #295
> <https://github.com/kitematic/kitematic/issues/295>. Closing for now,
> and feel free track the progress on that issue!
> 
> Jeff
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/issues/394#issuecomment-94181982>.
> 

-- 
Christian de Larrinaga
FBCS, CITP, MCMA
-------------------------
@ FirstHand
-------------------------
+44 7989 386778
cdel@firsthand.net
-------------------------
