### ISSUE TITLE
Kitematic with laptop on the move

### ISSUE THREAD

**Issue by fac2003** [kitematic/kitematic#395]
I installed an image while my laptop was connected to an ethernet cable. Things worked well. I was able to use the image. When I disconnected and took the laptop to another location, I used wifi. Starting kitematic at the new location yielded this error:

![kitematic-redacted](https://cloud.githubusercontent.com/assets/1728407/7220320/ab12c9b6-e690-11e4-83fd-f049bcddb60c.png)

Looks like kitematic "remembered" I was on an ethernet adapter before and failed to switch to wifi, or something.

I was able to recover by clicking on the second link (delete and retry), but I think the issue should not happen in the first place.

**Comment by mchiang0610** [comment]
@fac2003 

Does the error still occur if you restart Kitematic?

**Comment by mchiang0610** [comment]
@fac2003 Assuming you're not running into this problem anymore. Closing this issue for now, please re-open if you are still having this issue. 

Thanks!
