### ISSUE TITLE
Feature request - Infinite scrolling (pagination) for list of images from Docker Hub

### ISSUE THREAD

**Issue by jeffdm** [kitematic/kitematic#411]
Search results are limited to one page.

**Comment by mchiang0610** [comment]
Feature request - Infinite scrolling (pagination) for list of images from Docker Hub

**Comment by TeckniX** [comment]
This is not really complete, as I keep getting some odd responsde from the registry API when requesting additional pages, but I think I'm on the right track:

https://github.com/TeckniX/kitematic/tree/infinite-scrolling

**Comment by FrenchBen** [comment]
This is now in place
