### ISSUE TITLE
A way to manually check for updates

### ISSUE THREAD

**Issue by jeffdm** [kitematic/kitematic#412]
Needs some UX discussion. Possible implementation is via the menu:

`Kitematic` => `Check for Updates...`

A dialog pops up saying `No updates available` or `Update to the latest?`

**Comment by sandcastle** [comment]
I'd love to see this - ideally with the update requiring no further interaction after clicking `Update to the latest?`

**Comment by tsugliani** [comment]
Agreed, an embedded auto update system would be greatly appreciated. :+1:

**Comment by mchiang0610** [comment]
Closing to support Toolbox / using the auto-updater inside Kitematic.
