### ISSUE TITLE
Docker CLI returns "Forbidden" errors

### ISSUE THREAD

**Issue by mconigliaro** [kitematic/kitematic#417]
I'm new to docker, so I'm pretty lost. I installed kitematic via `brew cask install kitematic`, and now I'm trying to run the commands I'm seeing in tutorials (e.g. https://kitematic.com/docs/using-docker-cli/), but I always get this forbidden error:

```
$ docker run -d -P redis
FATA[0000] An error occurred trying to connect: Post https://192.168.99.100:2376/v1.17/containers/create: Forbidden
```

```
$ docker info
FATA[0000] An error occurred trying to connect: Get https://192.168.99.100:2376/v1.17/info: Forbidden
```

**Comment by jeffdm** [comment]
@mconigliaro thanks for the issue

It looks like the cask hasn't been updated yet to the [latest version (0.5.18)](https://github.com/kitematic/kitematic/releases/tag/v0.5.18). Does downloading this version any trying again work?

**Comment by mconigliaro** [comment]
I figured it out. My local Squid cache was getting in the way. Thanks for the help!
