### ISSUE TITLE
Feature request - Docker Hub Enterprise (DHE) support 

### ISSUE THREAD

**Issue by JohnMurray** [kitematic/kitematic#421]
It would be nice if this has support for docker enterprise.

**Comment by jeffdm** [comment]
@JohnMurray thanks for the issue1

**Comment by mchiang0610** [comment]
@JohnMurray Can you provide more details regarding this? By Docker Enterprise, I'm assuming you mean Docker Hub Enterprise support? 

What are the particular features you are looking for?

**Comment by mchiang0610** [comment]
Closing because DHE changed into DTR. DTR support will come.
