### ISSUE TITLE
Build own Dockerfile

### ISSUE THREAD

**Issue by gkawka** [kitematic/kitematic#427]
Hi,
i have serious problem to register in Kitematic my custom local Dockerfile container. When I run it doesn't appear in Kitematic list. What should I do or can you give me some advice. I saw on your kitematic/example repo there was a link to docs about creating custom image but i've got 404.

**Comment by jeffdm** [comment]
@gkawka Hi there, thanks for the issue.

Here's that missing doc link: https://kitematic.com/docs/using-docker-cli/

Is the image you built tagged?

**Comment by gkawka** [comment]
d'oh! No it wasn't and now its working pretty well :) Thanks very much

**Comment by jeffdm** [comment]
@gkawka Good to know! Thanks again!
