### ISSUE TITLE
Running Kitematic through Corporate SOCKS proxy fails

### ISSUE THREAD

**Issue by imjacobclark** [kitematic/kitematic#430]
Attempted to run Kitematic though a corporate SOCKS proxy today, I wasn't able to pull any container images from the Dockerhub and as a result wasn't able to use Kitematic.

Might be worth investigating Proxy settings through the Kitematic interface, or documentation on how to get around proxy issues.

**Comment by TeckniX** [comment]
How do you usually pull docker images from Dockerhub? This is more than a Kitematic issue, but should also affect your normal docker CLI

**Comment by jeffdm** [comment]
@imjacobclark @TeckniX curious to hear the answer to this too! It would help us debug why this is failing for Kitematic :smiley:

**Comment by mchiang0610** [comment]
@imjacobclark Are you having the same problem on normal docker CLI?

**Comment by mchiang0610** [comment]
Merging with #240
