### ISSUE TITLE
feature idea: link for downloaded images/containers to related docker docks

### ISSUE THREAD

**Issue by simiula** [kitematic/kitematic#431]
Once downloaded, to set params you have to find on docker site where is located that image...
for example I got apache-php, but I cannot figure out how to get into the www folder...
Can be nice to have the info button that link directly to that container docs. If too difficult for all containers user-made, maybe can be just for the official containers.

**Comment by TeckniX** [comment]
There should be a 'webfile' mapped to the container. You can then go into that folder to add your www files. 
See the Kitematic site about [Managing volumes](https://kitematic.com/docs/managing-volumes/)

**Comment by mchiang0610** [comment]
See @TeckniX's PR for container linking: 
https://github.com/kitematic/kitematic/pull/479

**Comment by mchiang0610** [comment]
@simiula It's been passed onto the Docker official images team. Closing this issue for now. 

Thanks!
