### ISSUE TITLE
suggestions: stop single container

### ISSUE THREAD

**Issue by simiula** [kitematic/kitematic#432]
Using Mac it is to develop things, can be nice to easy start/stop single containers.

**Comment by TeckniX** [comment]
Please look through the issues before posting - This is a duplicate of (https://github.com/kitematic/kitematic/issues/426) and has been added to the list of features

**Comment by jeffdm** [comment]
Closing for now! In fact, @TeckniX  added this feature just recently! It shipped as part of 0.5.20+. Many thanks to him!
