### ISSUE TITLE
No download progress for registry v2

### ISSUE THREAD

**Issue by dickensian** [kitematic/kitematic#435]
Offer a progress indicator for all steps when a loader is shown (including downloading images), or even better the ability to toggle open a console view so we can see what's going on (for those of us who care).

**Comment by jeffdm** [comment]
@dickensian before migration to v2 registry all images used to show progress. We need to update Kitematic to better support v2 progress. Work on this soon.

**Comment by mchiang0610** [comment]
@dickensian Merging this with the feature request of better progress bars for Kitematic using the v2 registry api. 

See: https://github.com/kitematic/kitematic/issues/512 

Closing this for now. Thanks for submitting!
