### ISSUE TITLE
Shell detection - question/enhancement?

### ISSUE THREAD

**Issue by TeckniX** [kitematic/kitematic#444]
I can't seem to get a default terminal prompt with `bash` as the default. 
The code shows the shell being a variable set at command `$SHELL` but I can't tell where that is referenced? I tried to set an environment variable of `SHELL` with a value of `/bin/bash` but that didn't help.

* How is the shell variable set?
* How do I change it?

**Comment by jeffdm** [comment]
Is this for the `terminal into container` button near the top of the app? or the system-wide shell created clicking the bottom-left button?

**Comment by TeckniX** [comment]
This is for the terminal into container button near the top of the app.

**Comment by jeffdm** [comment]
Ah I see. For that button we default to `sh` but should probably use `$SHELL` instead (if it works). Some barebone containers don't come with `bash`

**Comment by TeckniX** [comment]
It makes sense, but would be nice to over-write it with a simple $SHELL environment under the settings, as I believe it to be the purpose. I now see the command needed in the code :tired_face: 

I've added a PR that reads the 'SHELL' environment and pushes that to the terminal container command
