### ISSUE TITLE
Wait for another image download shows up when there's no other download

### ISSUE THREAD

**Issue by Elesant** [kitematic/kitematic#445]

**Comment by jeffdm** [comment]
This occurs for all downloads, whether its waiting or not. Problem is, there's no way to differentiate.

Closing for now since I don't think there's anything we can do about this.

**Comment by sibprogrammer** [comment]
What is the solution or workaround for this problem?
After incorrect shutdown of notebook (due to battery) I can't download any new box using kitematic.

**Comment by reneolivo** [comment]
This is happening to me and there are no solutions! It's stuck like that for life....
