### ISSUE TITLE
dial unix /var/run/docker.sock: no such file or directory

### ISSUE THREAD

**Issue by sja87** [kitematic/kitematic#448]
I like your Kitematic client.

![bildschirmfoto 2015-04-28 um 17 57 32](https://cloud.githubusercontent.com/assets/4973582/7374015/27dff932-edd0-11e4-9ccd-72c3e8feb857.png)

Now I want to start with docker in Terminal. But when I pull a new image I see the following error:

![bildschirmfoto 2015-04-28 um 17 54 46](https://cloud.githubusercontent.com/assets/4973582/7373921/ac60f46e-edcf-11e4-96ac-7465907bda2e.png)

I found the Issue #261 but $(docker-machine env dev) not fix my problem.

![bildschirmfoto 2015-04-28 um 17 56 48](https://cloud.githubusercontent.com/assets/4973582/7373986/fee985b6-edcf-11e4-991b-ef1f962b982e.png)

**Comment by mchiang0610** [comment]
Hi, 

Thanks for this. If you use `docker pull centos` instead of `sudo pull centos` it should work. 

Let me know if it's not working. Thanks!

**Comment by sja87** [comment]
Thanks it works!

![bildschirmfoto 2015-04-29 um 09 20 47](https://cloud.githubusercontent.com/assets/4973582/7386167/0872d322-ee51-11e4-85ce-c4fd433f2a03.png)
