### ISSUE TITLE
UI not updated on delete

### ISSUE THREAD

**Issue by cpuguy83** [kitematic/kitematic#449]
When you remove the currently selected container the logs UI is not updated, so even though I've removed it, it's still showing logs from that container.

**Comment by cpuguy83** [comment]
See screenshot, shows redis is the container I was looking at (and removed while it was selected) even though postgres is selected.
If I actually go and click the postgres container it does update the main UI.

![screen shot 2015-04-28 at 12 52 05 pm](https://cloud.githubusercontent.com/assets/799078/7375275/6e538418-eda5-11e4-9579-4cdab3685ca1.png)

**Comment by mchiang0610** [comment]
Hi Brian, @cpuguy83 

Thanks for sending this in. Do you have a way to reproduce this? I am trying to reproduce this on our side. 

Thanks

**Comment by cpuguy83** [comment]
@mchiang0610 

1. Run 2 containers
2. Select one of the containers
3. Delete the currently selected container (press the X next to it's name)

**Comment by mchiang0610** [comment]
Should be fixed now. Thanks!
