### ISSUE TITLE
Language localization for documentation

### ISSUE THREAD

**Issue by llitfkitfk** [kitematic/kitematic#451]
In the past couple of days, DockOne, which is a docker community from China, has translate the kitematic Documentation to Chinese version. So, I hope add the [Chinese Documentation](http://dockone.io/article/254) to the https://kitematic.com/docs/

**Comment by mchiang0610** [comment]
@llitfkitfk Good suggestion! Our documentation should allow localization for different languages.

**Comment by mchiang0610** [comment]
@SvenDowideit What do you think on this, especially when we are planning to merge KM docs into Docker docs?

**Comment by mchiang0610** [comment]
@llitfkitfk Docs moving to docs.docker.com will close this for now.
