### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by johncokos** [kitematic/kitematic#453]
- [ ] 1. Make the buttons in the lower left more visible and obvious.

- [ ] 2. The idea that you can't use your regular terminal without first clicking the whale icon to set the env isn't easily discoverable.  Can we somehow set the environment on kitematic start so that this is not required?

- [ ] 3. The view/restart/stop/terminal buttons in the top of the running container don't really feel or act like buttons.  In UAT, I've been watching  users hammer them repeatedly because they don't get any immediate feedback.  Perhaps they should disable after click, and then re-enable after their task is done?

- [ ] 4. Similar to the previous suggestion, clicking restart should give some visual indication as to when the process has actually completed.  Without live logs, you really can't tell when you're ready to go.

- [ ] 5. Editable port mappings would be great.'

- [ ] 6. It would be cool if you could magically save container settings (like mounts, ports, etc) for reuse.  It's a common use case for people to delete and redownload their containers.  They seem to be getting frustrated at having to set all that back up again each time.

**Comment by Elesant** [comment]
Thanks for the great suggestions! @johncokos

**Comment by mchiang0610** [comment]
@johncokos 

Separating these UI suggestions into individual issues.  (closing this one)

https://github.com/kitematic/kitematic/issues/506
https://github.com/kitematic/kitematic/issues/507
https://github.com/kitematic/kitematic/issues/508
https://github.com/kitematic/kitematic/issues/509
https://github.com/kitematic/kitematic/issues/493
https://github.com/kitematic/kitematic/issues/510
