### ISSUE TITLE
500 server error with container rpi-raspbian

### ISSUE THREAD

**Issue by thorstensiefert** [kitematic/kitematic#454]
Hi,
i tried to download the above named container several times....
Always getting the Message: "500 server error - cannot start container rpi-raspbian [8] System error: exec format error." 
ask for remedy.
Thx

**Comment by TeckniX** [comment]
There are quite a few rpi-raspbian projects available on dockHub - Can you provide a link to the one you used?

**Comment by thorstensiefert** [comment]
I tried this one: https://registry.hub.docker.com/u/resin/rpi-raspbian/

**Comment by thorstensiefert** [comment]
I tried this one:
https://registry.hub.docker.com/u/resin/rpi-raspbian/ <https://registry.hub.docker.com/u/resin/rpi-raspbian/>

**Comment by thorstensiefert** [comment]
I think I found the problem: Wrong architecture...  My fault! Sorry! Thx for your help!

**Comment by jeffdm** [comment]
No worries! Thanks @TeckniX , @thorstensiefert ! Will close for now.
