### ISSUE TITLE
Error pane sticks around indefinitely 

### ISSUE THREAD

**Issue by mcgain** [kitematic/kitematic#455]
![screen shot 2015-04-29 at 5 11 56 pm](https://cloud.githubusercontent.com/assets/193744/7401529/f111f5c2-ee92-11e4-81dc-a8cd981729dd.png)

If a container errors out, the "An error occurred:" pane will not go away, despite changing containers or even deleting the one that failed.

**Comment by jeffdm** [comment]
This is a bug I can reproduce - thanks for the issue!

**Comment by mchiang0610** [comment]
Fixed
