### ISSUE TITLE
New interface

### ISSUE THREAD

**Issue by groverz** [kitematic/kitematic#460]
Cool software :+1:. No Ip address for new interface :).

https://yadi.sk/i/wn1EY-hLgMbba

**Comment by TeckniX** [comment]
@groverz I'm not sure if I understand the issue? the IP that you see is mapped to your VM, which holds the docker containers. That IP should be static. Your site should respond to: 192.168.99.100:32786 also

**Comment by groverz** [comment]
Sorry for my English. It is bridge to local netwok(+1 enterface). 

eth0 - in
eth1 - 192.168.99.100
+ eth2 - dhcp

This minor flaws. Сonvenient to find all ip interface

**Comment by TeckniX** [comment]
My question is why the need for the brige to be displayed? 
eth1 is already correctly assigning the IP needed to view the container's wordpress install.

**Comment by groverz** [comment]
+eth3 - bridge wifi. It is wokr bridge.
Worpres shown for clarity.

Specify where all the interfaces it is convenient not to climb into the console.
