### ISSUE TITLE
UI shows stop button on stopped containers if KM starts with VM off

### ISSUE THREAD

**Issue by jeffdm** [kitematic/kitematic#465]

**Comment by TeckniX** [comment]
Having trouble replicating this one. Here are my steps:

* Start Kitematic
* Once Kitematic window is up, issue: `VBoxManage controlvm dev savestate`
* Check VM is off `VBoxManage list runningvms`
* Check container window buttons (I get the proper start button)

**Comment by mchiang0610** [comment]
This issue should be fixed. Cannot reproduce.
