### ISSUE TITLE
500 error reported while downloading a container

### ISSUE THREAD

**Issue by verdurin** [kitematic/kitematic#466]
I tried running the official Fedora 21 container via Kitematic and a 500 server error - no command specified was reported, even though elsewhere in the application, the container was still listed as 'downloading'.

This is with Kinematic 0.5.23 on OS X 10.10.3.

**Comment by verdurin** [comment]
This has also happened with a CentOS container.

**Comment by TeckniX** [comment]
Please provided the DockHub links to the containers you were trying to download, so that we can replicate the issue.

Thanks!

**Comment by Elesant** [comment]
@verdurin Sorry about that! It's an known issue that images that don't have a starting command will cause an error in Kitematic. See https://github.com/kitematic/kitematic/issues/230

@TeckniX Thank you so much for helping out! :)

**Comment by TeckniX** [comment]
No problem @Elesant

**Comment by jeffdm** [comment]
Duplicate of #436, will close for now, look out for a fix soon!

Thanks all!
