### ISSUE TITLE
Unresponsive GUI

### ISSUE THREAD

**Issue by JC1738** [kitematic/kitematic#467]
It appears as more docker containers are run the slower, slower the GUI gets to the point it becomes unresponsive and it's difficult to then go through and delete the containers via the UI.

**Comment by TeckniX** [comment]
How may containers do you have running? (aka steps to repeat)

**Comment by JC1738** [comment]
They are all stopped, but at time for slow down, there were 30 stopped containers

**Comment by jeffdm** [comment]
Thanks for this!

**Comment by mchiang0610** [comment]
@JC1738 should be fixed now. Can you try if you are still having the issue? (If so please re-open). 

The upcoming v0.6 should again provide some performance enhancements.
