### ISSUE TITLE
Error after downloading an image

### ISSUE THREAD

**Issue by devnieL** [kitematic/kitematic#468]
![image](https://cloud.githubusercontent.com/assets/1231888/7439870/52ee4438-f057-11e4-855c-b142f946080a.png)

Hi, I had a problem after downloading this image : https://github.com/QuantumObject/docker-dspace , I think that the problem starts when kitematic tries to install it.

Thanks for kitematic !

**Comment by jeffdm** [comment]
@devnieL hi there thanks for the issue, and sorry about the frustrating error message

This is the same cause as #436 , will close for now and keep out for a fix soon!

**Comment by jeffdm** [comment]
@devnieL thanks for the issue!

I was able to successfully download & run this image. It seems like an error occurred at:
- API calls to the registry
- The daemon could not be reached

If you try again does it work? In VirtualBox, is the `dev` VM up and running?

**Comment by devnieL** [comment]
I don't know what happened but after restarting kitematic, it's ok 
![image](https://cloud.githubusercontent.com/assets/1231888/7443227/29cdc0ce-f101-11e4-9686-6001379e15a2.png)

Thanks !

**Comment by jeffdm** [comment]
@devnieL good to know, thanks.
