### ISSUE TITLE
Error - creating container (Kitematic fails to connect with VM)

### ISSUE THREAD

**Issue by rogueleaderr** [kitematic/kitematic#469]
Sorry to be a bit unhelpful but I just downloaded Kitematic on OSX Yosemite, tried to start a new container, and got this rather cryptic error:

![kitematic_and_new_issue_ _kitematic_kitematic_and_ _george s_linernotes_tasks_-_low_energy_songs_are_not_low_energy_enough_-_asana](https://cloud.githubusercontent.com/assets/1051233/7447355/8d3d3a26-f1ac-11e4-880d-895109cbf066.png)

I had previous started one container by clicking "start in command line" and then had manually shut down the "dev" machine that was open in Virtualbox when I wanted to install Boot2Docker, so perhaps that's related?

**Comment by jeffdm** [comment]
Hi @rogueleaderr, thanks for the issue

Is the Virtualbox VM running?

**Comment by rogueleaderr** [comment]
I just manually started the dev vm inside of virtualbox and Kitematic 
still showed the error screen (though the little cloud icon "ubuntu" on 
the left was flashing so maybe the download had actually resumed.

I then tried closing and reopening kitematic and now it appears to be 
working.

**Comment by simple-task** [comment]
I had the same issue on my mac. I noticed that this happens if you already have virtual box installed on your machine.

I unstalled Virtual box locally and restarted kitematic. That did the trick for me. Hope that helps.
Ram Peri

**Comment by jeffdm** [comment]
Thanks for the info, looking into this

**Comment by mchiang0610** [comment]
Moving duplicate issues into this one 
Issues: 
https://github.com/kitematic/kitematic/issues/482 
https://github.com/kitematic/kitematic/issues/487

**Comment by mchiang0610** [comment]
Should be fixed now.
