### ISSUE TITLE
Kitematic fails to assign a port

### ISSUE THREAD

**Issue by iangcarroll** [kitematic/kitematic#470]
Kitematic seems to fail to assign a port in some cases; sometimes rebooting the app works, sometimes not.

I'm on OS X 10.10.

![screen shot 2015-05-03 at 7 43 42 pm](https://cloud.githubusercontent.com/assets/1280719/7447525/bd0b8ecc-f1cc-11e4-849b-3b61decc7fb8.png)

**Comment by iangcarroll** [comment]
Note: I'm spawning these from the command line.

**Comment by iangcarroll** [comment]
Running it with `-P` fixed it, sorry.

**Comment by jeffdm** [comment]
No worries! Thanks for the issue @iangcarroll :smiley:
