### ISSUE TITLE
Cgroups configuration

### ISSUE THREAD

**Issue by Garito** [kitematic/kitematic#471]
Hi!
I need to limit the amount of RAM memory a container uses
As I read, this is achieved with cgroups in Docker so I'm wondering if it is possible to config this issue with kinematic and if so how

Thanks a lot!

**Comment by TeckniX** [comment]
Cgroups is actually used to monitor usage, but I don't believe it's memory usage. Any changes to the memory is setup within the container, so you can do it by simply clicking the terminal button within the container window. 

http://serverfault.com/questions/620653/monitoring-cpu-and-memory-usage-of-docker-containers-on-centos-7

**Comment by Garito** [comment]
What about the -m option of the run command?

**Comment by TeckniX** [comment]
Then you're talking about passing an extra option to docker run, not using cgroups ;) - I believe this will be an added/future enhancement

**Comment by Garito** [comment]
Just don't care how...
I'm trying to start a MongoDB database in my old laptop and it uses 2GB of memory even with and empty mongo (only local database)

So can't work at all

**Comment by TeckniX** [comment]
@Garito understood.
For the time being do this:
* Open VirtualBox App (not kitematic)
* Change the default memory of the 'dev' image to 1GB (default is the 2GB)
* Save all

You have now limited the virtualbox image that runs your container to the 1GB ram size, which your container will not be able to go beyond

**Comment by Garito** [comment]
Nice!
Seems to work

**Comment by TeckniX** [comment]
:+1:

**Comment by Garito** [comment]
Thanks a lot!!!
