### ISSUE TITLE
Added features: Links and Runtime

### ISSUE THREAD

**Issue by TeckniX** [kitematic/kitematic#476]
I've started a quick branch for runtime memory settings and linking containers.
Some of the early work can be seen here:

https://github.com/TeckniX/kitematic/tree/link_container

Any feedback is appreciated.

Couple of notes:
- Linking Containers: This will only take effect if the container you are linking to is running (otherwise it clears the entry)
- Runtime memory: It should save the settings in local memory, which is then merged with the container settings. Additionally all values are in MB, so entering 1 in the setting will set it to 1MB

**Comment by mchiang0610** [comment]
Hey @TeckniX, just wanted to say thanks for this! Saw the pull request. Super cool. 

One thing I might add is auto-complete when linking containers. :)

**Comment by TeckniX** [comment]
Good idea - I'll get that going! Is there a preferred package for typeahead?

**Comment by mchiang0610** [comment]
@TeckniX Sorry for the late reply. We don't currently have a typeahead but maybe this? 
https://github.com/fmoo/react-typeahead 

What do you think?

**Comment by TeckniX** [comment]
@mchiang0610 That's exactly what I used in my container linking pull - Redoing it all now that Kitematic has moved towards a flux-like design. :+1: #learningcurve

**Comment by mchiang0610** [comment]
@TeckniX Super sorry about that. :) I think for the longer term, the flux-like design will help.

**Comment by TeckniX** [comment]
Not sweating it, I've learnt a boat load of stuff just by helping here, so thank you for that!

**Comment by mchiang0610** [comment]
@TeckniX Thanks! I'm beginning to add better labels to the issues, and cleaning them up. Going to start using the help wanted labels for top priority 'install' / starting Kitematic issues.

**Comment by TeckniX** [comment]
Awesome! I'll keep an eye on it. Going through the Alt library doc and I'll get started on the linking of containers again

**Comment by mchiang0610** [comment]
@TeckniX Where are you located? Would love to send you Kitematic stickers - if you want of course. :)
