### ISSUE TITLE
404 error - Unable to download more images / open containers 

### ISSUE THREAD

**Issue by HintikkaKimmo** [kitematic/kitematic#477]
Hi, earlier tried to download docker image for rethinkDB which failed with 404. Now kinematic is stuck with the error and I am unable to download or open any new docker containers with it.

**Comment by jeffdm** [comment]
Thanks for the issue! In the meantime restarting Kitematic will fix this.

**Comment by mchiang0610** [comment]
@HintikkaKimmo I'm assuming this issue has been resolved by restarting Kitematic. 

Closing the issue for now. Please re-open if you are still having the issue. Thanks!

**Comment by adlermedrado** [comment]
I tried here and it's not working. I can't download containers.

**Comment by HintikkaKimmo** [comment]
Hi,

On my side this is closed. For other reasons I updated from OSX Mavericks to Yosemite and never had the error again. 

I could actually load the same containers directly from docker directory so when error happened I opened this issue.

**Comment by adlermedrado** [comment]
Thank you @HintikkaKimmo. I'll do some more testings and if it's the case, I'll open a new issue.
Best,

**Comment by mchiang0610** [comment]
@adlermedrado Are you still having issues? Can you give it another try? There was a server error on Docker's side today, and it's now fixed.

**Comment by adlermedrado** [comment]
I tried now and it worked well.
Thank you.

**Comment by mchiang0610** [comment]
Awesome!
