### ISSUE TITLE
Is there a command to set up environment variables? (like boot2docker shellinit)

### ISSUE THREAD

**Issue by mikew** [kitematic/kitematic#478]
When using boot2docker our team added this line to our `.bashrc` files

```bash
boot2docker status &> /dev/null && boot2docker shellinit
```

and now we are trying

```bash
init-kitematic () {
  export DOCKER_HOST=tcp://192.168.99.100:2376
  export DOCKER_CERT_PATH=~/.docker/machine/machines/dev
  export DOCKER_TLS_VERIFY=1
}

init-kitematic
```

but are a little wary of the hardcoded IP. Is there an equivalent to `boot2docker shellinit` in Kitematic?

**Comment by TeckniX** [comment]
I believe that the IP will always be the same, if you look at boot2docker, they do the same thing, where the IP is always hardcoded within their install/setup.
As you may know, it's all done via VBox, and kitematic uses the exact same iso as boot2docker to create the VBox. The IP difference is to make sure it's not conflicting with an existing boot2docker IP.

Once the VBox is created there's really no reason for it to change or get a different IP.

**Comment by mchiang0610** [comment]
@mikew 
The equivalent would be `docker-machine env dev`
