### ISSUE TITLE
Error - creating container (Kitematic fails to connect with VM)

### ISSUE THREAD

**Issue by diegodfsd** [kitematic/kitematic#482]
I'm trying download the image arch:latest and something went wrong, but no message with error was showed and I have no way to try again the download.

My mac is running with OS X Yosemite version 10.10.3

My Kitematic is like this:
![screen shot 2015-05-08 at 10 25 21 pm](https://cloud.githubusercontent.com/assets/705799/7548058/6ebaeff2-f5d1-11e4-97b4-d73f5f70fddf.png)

**Comment by mchiang0610** [comment]
@diegodfsd can you try: 

1. Remove the container and restart Kitematic 
2. Create it again

This usually happens when Kitematic can't contact the VM.

Let me know if you are still having trouble.

**Comment by diegodfsd** [comment]
@mchiang0610 I tried with another image and everything worked good, but the original problem yet need be solved. How I've said I think the Kitematic need show some error message to user and it needs offer one way to the user retry the operation.

**Comment by mchiang0610** [comment]
Closing this one to consolidate duplicate issues. 
See https://github.com/kitematic/kitematic/issues/469

**Comment by mchiang0610** [comment]
@diegodfsd I agree Kitematic needs to show errors better. In this case, Kitematic lost contact with the VM. (Kitematic did not get a response back)
