### ISSUE TITLE
stops at 99%

### ISSUE THREAD

**Issue by alistairwalsh** [kitematic/kitematic#483]
![image](https://cloud.githubusercontent.com/assets/5056954/7548310/46fe86ba-f647-11e4-97bb-16d2889af6e9.png)
Kitematic startup tops at 99%

**Comment by ehlersd** [comment]
+1  I'm seeing the same problem.

**Comment by emerick42** [comment]
I had this problem too, and solved it by simply deleting the "dev" virtual machine created by Kitematic. **You will lose all your configured containers**.

```
$ VBoxManage list vms
"dev" {698b51bc-ff9d-401e-a87f-957d613e6b60}

$ VBoxManage unregistervm dev --delete
```

If you have the error `VBoxManage: error: The machine 'dev' is already locked by a session (or being locked or unlocked)`, there is another process currently accessing this VM. You may still have Kitematic running. Also you should kill the `docker-manage 0.2.0` process using your task manager (which is a subprocess spawn by Kitematic to create the VM).

**Comment by alistairwalsh** [comment]
Thanks for the guidance.




I got 

>> VBoxManage: error: Cannot unregister the machine 'dev' while it is locked




When I tried your suggestion.




I found I had to 




>> VBoxManage controlvm dev poweroff




before I could





>> VBoxManage unregistervm dev —delete




check if dev is still running with




>> VBoxManage list runningvms

















—

**Comment by mchiang0610** [comment]
@alistairwalsh @ehlersd @emerick42 

We are testing out a pre-release that should fix this problem! Do you mind giving it a try?

https://github.com/kitematic/kitematic/releases/download/v0.5.27-intel-nic/Kitematic-0.5.27-intel-nic.zip

Let me know if you are still running into the issue after.

Also consolidating this issue with https://github.com/kitematic/kitematic/issues/236

**Comment by ux8mz** [comment]
@mchiang0610 Hi, I has the same problem, version 0.5.27 from official page.
Btw, I had this issue when first installed Kitematic then I deleted the VM and restarted both VirtualBox & Kinematic, after everything was good. Now I started it again and got this problem. 
![2015-05-27 02 30 33](https://cloud.githubusercontent.com/assets/9370383/7825699/dd0d85e6-0418-11e5-8cd2-653a4d8952fc.png)
