### ISSUE TITLE
Setup Error: Machine does not exist

### ISSUE THREAD

**Issue by gunjan5** [kitematic/kitematic#484]
Downloaded Kitematic for the first time, and as I open it (after asking for my mac's password) it gives me this error: 
![image](https://cloud.githubusercontent.com/assets/5966968/7549680/c81ffc2c-f5f4-11e4-8d03-b64669ef3107.png)

I tried clicking on "Retry Setup" and "Delete VM and Retry Setup" but no luck. 

I already have Virtualbox installed and had boot2docker VM on it before installing Kitematic, so after getting this error, I also deleted the boot2docker VM from VirtualBox and retried, but no luck.

I'm on a macbook pro OS X 10.9.5, NO VPN

**Comment by fuwaneko** [comment]
Same here, OS X 10.10.3.

**Comment by Kesarion** [comment]
Having the issue as well, OS X 10.10.3.

**Comment by DannyvanderJagt** [comment]
I had the same error but somehow I fixed (for now).

I googled and found this page: https://kitematic.com/docs/known-issues/. It said that I should try  `docker-machine rm -f dev` (in terminal) but I got these two errors:  (Kitematic app was shutdown at this point!)
`ERRO[0000] Error removing machine dev: Host does not exist`
`FATA[0000] There was an error removing a machine. To force remove it, pass the -f option. Warning: this might leave it running on the provider.`

After that I tried to second command from the page: `docker-machine create -d virtualbox dev`
The command tried to start the VM but it got stuck at `Waiting for VM to start...`. (even after 10 minutes)
After that I closed the terminal and opened the Kitematic app. Nothing had changed, still the same error. I did run to second command again and this time it worked and I got these two info statements:

`NFO[0055] "dev" has been created and is now the active machine.`
`INFO[0055] To point your Docker client at it, run this in your shell: eval "$(docker-machine env dev)"`

When I did open the Kitematic app I got the same error but I clicked the 'retry setup' button but that didn't fix it. Finally I clicked the 'Delete VM and Retry Setup' button and the app started the reinstall everything. Everthing is working now and the Kitematic app is working.

I hope this helps in fixing the bug, if there are any questions let me know.

**Comment by fuwaneko** [comment]
@DannyvanderJagt It did help. But in my case, second command succesfully launched VM in VBox and Kitematic started normally after that.

**Comment by gimbo** [comment]
Same here, OSX 10.9.5, Kitematic 0.5.24

**Comment by jeffdm** [comment]
This bug was introduced in 0.5.24 but fixed in 0.5.25, sorry about that.
