### ISSUE TITLE
Error - creating container (Kitematic fails to connect with VM) 

### ISSUE THREAD

**Issue by sasanksunkara** [kitematic/kitematic#487]
After downloading the kitematic I started to create a container using recommended image of hello-world-nginx..it took a while and says "An error occurred".

**Comment by hashir** [comment]
same

**Comment by mchiang0610** [comment]
@sasanksunkara can you try: 
1. Remove the container and restart Kitematic 
2. Create it again 

This usually happens when Kitematic can't contact the VM.

**Comment by mchiang0610** [comment]
duplicate of #482. Please comment there; https://github.com/kitematic/kitematic/issues/482
