### ISSUE TITLE
Container Create button behavior is unclear since it also runs

### ISSUE THREAD

**Issue by jeffdm** [kitematic/kitematic#495]
The `Create` button on Kitematic images also _runs_ containers, which may startle many users.

**Comment by mchiang0610** [comment]
Currently, we are focusing Kitematic on making the process of pulling / creating / running containers really easy, hence some abstraction where the "create" button in kitematic pulls the docker image, creates a docker container, and then runs it. 

This is a valid comment, just not ready. Please re-open if there is a need.
