### ISSUE TITLE
document what versions of tools are installed

### ISSUE THREAD

**Issue by SvenDowideit** [kitematic/kitematic#496]
release notes, but also to let the 'installer' know before it happens, what things would be updated / changed, and what wouldn't.

i have an older version of vbox installed, and didn't know if kitematic was going to update it - it didn't.

but it did replace everything else, including things i didn't realise.

(I'm thinking its good to update for most users, but we do need to tell them and give them a chance to back out.)

**Comment by mchiang0610** [comment]
@SvenDowideit This is completely valid. We created a docs label for this!

**Comment by mchiang0610** [comment]
In release notes now.
