### ISSUE TITLE
Paused containers don't have an unpause

### ISSUE THREAD

**Issue by SvenDowideit** [kitematic/kitematic#499]
i'm not sure if restart means that you're going to unpause the container, or do what I really expect - `docker restart`

I think kitematic needs an `unpause` button, which suggests a `pause` :/

**Comment by SvenDowideit** [comment]
and the container list should really make a paused container look different to a stopped one.

**Comment by mchiang0610** [comment]
@SvenDowideit We have the start button that unpauses the container.

**Comment by avindra** [comment]
@mchiang0610  can you clarify?

I don't see any unpause button here. All I see is "Stop" and "Restart"

(using `0.13 RC4`) : 

<img width="894" alt="screen shot 2016-12-31 at 2 13 16 pm" src="https://cloud.githubusercontent.com/assets/126848/21578955/5b522f30-cf63-11e6-9fb5-b794a0a60b08.png">
