### ISSUE TITLE
The Volumes UX assumes that volumes are directories

### ISSUE THREAD

**Issue by SvenDowideit** [kitematic/kitematic#500]
They can also be files.

Specifically, I bind mount `/var/run/docker.sock` and `/usr/local/bin/docker` into a container.

on the Container summary screen, these show as `usr` and `var`, which is weird.

**Comment by mchiang0610** [comment]
@SvenDowideit Thanks for this feedback. How do you think we can make the experience better for files?

**Comment by mchiang0610** [comment]
Merging with #1032
