### ISSUE TITLE
container creation timeout.

### ISSUE THREAD

**Issue by SvenDowideit** [kitematic/kitematic#503]
I have a container sitting at `connecting to hub` - probably because my DSL died.

there needs to be a timeout telling me what has and hasn't happened, and what cleanup step i should OK.

i may have made another container, or i may want this one to retry.

**Comment by mchiang0610** [comment]
@SvenDowideit  @jeffdm  Adding to this: 

To prevent a repeat of the stuck at 99% error, we should have a hard timeout if KM receives no response within a certain timeframe. ( 1 min might be a good start)

**Comment by mchiang0610** [comment]
Merging with #1029
