### ISSUE TITLE
Installing Kitematic won't enable users to use regular terminal without using the Whale button 

### ISSUE THREAD

**Issue by mchiang0610** [kitematic/kitematic#507]
Installing Kitematic won't enable users to use regular terminal without using the terminal in Kitematic (Whale button) 

Great suggestion by: @johncokos

**Comment by peteruithoven** [comment]
For OS X, couldn't the following line be automatically added to `~/.bash_profile`?
``` bash
eval "$(docker-machine env dev)"
```

**Comment by jeffdm** [comment]
Shipped in 0.7

**Comment by jeffdm** [comment]
@peteruithoven Good suggestion: we let users opt-in for that currently but perhaps we can find a good way to add it automatically to their shell profile.
