### ISSUE TITLE
UX - Buttons don't feel like buttons due to lack of feedback

### ISSUE THREAD

**Issue by mchiang0610** [kitematic/kitematic#508]
Great suggestion by @johncokos: 

In UAT, I've been watching users hammer them repeatedly because they don't get any immediate feedback. Perhaps they should disable after click, and then re-enable after their task is done?

**Comment by mchiang0610** [comment]
Adding @Elesant in for discussion.

**Comment by mchiang0610** [comment]
Merging discussions in here for button feedback.

**Comment by nathanleclaire** [comment]
Suggestion, use these: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

It drives me batty that the cursor doesn't become `cursor: pointer;` when I hover over buttons (User: OK... can I click these?), and `cursor: progress;` could indicate that something is happening after they click it.

**Comment by mchiang0610** [comment]
@nathanleclaire Thanks for that note. 

The reason for not using custom cursors is due to us trying to have a more native experience. (Ie. when you hover over Mac OS icons, your cursor will not change.) 

This suggestion is more for providing feedback to the users when the button is depressed (ie. changing colors or feel of the button being depressed). 

Super good suggestions though. 

cc: @Elesant 

In v0.6 we are enhancing this - already complete.

**Comment by nathanleclaire** [comment]
Ah, so at first I was convinced I was right, but I looked it up: https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Pointers.html

The `cursor: pointer;` is reserved for URL links.  So, I am wrong ;D
