### ISSUE TITLE
UX - Restart button should have visual feedback

### ISSUE THREAD

**Issue by mchiang0610** [kitematic/kitematic#509]
Suggestion by @johncokos

Clicking restart should give some visual indication as to when the process has actually completed. Without live logs, you really can't tell when you're ready to go

**Comment by TeckniX** [comment]
Would cycling the Start/Stop button be good enough?

**Comment by mchiang0610** [comment]
@TeckniX That would suffice as the first step. 

I think what @johncokos want is to know when the container is up and running && the software inside has started as well.

**Comment by jeffdm** [comment]
Fixed in 0.5.26

**Comment by mchiang0610** [comment]
@johncokos, Kitematic provides live logs. 

We are going to go with the assumption that if the container is up and running, that's what Kitematic will report. 

If the program written provides logs, Kitematic will live stream it. 

Feel free to re-open the issue if anyone feels there is something that can be done better here.

**Comment by johncokos** [comment]
This is more of UI thing that I'm asking for ... the buttons don't "visually click".  They don't depress, change colors, or give any indication that something is happening.  Generally, you would expect them to grey out after click, and then go blue again after whatever process they kicked off is done.  Our users in UAT are claiming that they "don't feel like buttons"  This may seem nit-picky, but if you watch a non technical person work with the app, they will hammer the restart button over and over expecting something to happen.  In reality, the container is restarting 50 times.  To them, nothing has happened.

**Comment by mchiang0610** [comment]
@johncokos I see what you mean now.

**Comment by mchiang0610** [comment]
@johncokos this should be improved in the upcoming version of Kitematic (v0.6)

**Comment by mchiang0610** [comment]
Fixed in 0.5.27
