### ISSUE TITLE
Bug - Fails to open docker from command line with proxy set

### ISSUE THREAD

**Issue by vangdfang** [kitematic/kitematic#514]
In Kinematic 0.5.26, I found with a proxy set in my environment (including http_proxy and https_proxy), I would get an error when attempting to open the docker command line from within Kinematic.  Running Boot2Docker's package manually showed me that it sets a NO_PROXY environment variable with the VM's IP, and doing this manually while specifying the remainder of the command line Kinematic attempts results in docker commands working as expected.  For example, this works:

```
NO_PROXY=192.168.99.100 DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_CERT_PATH=/Users/<redacted>/.docker/machine/machines/dev DOCKER_TLS_VERIFY=1 docker ps
```

Omitting NO_PROXY results in:
```
FATA[0000] An error occurred trying to connect: Get https://192.168.99.100:2376/v1.18/containers/json: Service Unavailable
```

**Comment by vangdfang** [comment]
Workaround, a la #261 -- add the following to .profile:

```
eval "$(docker-machine env dev)"
export NO_PROXY=$(echo $DOCKER_HOST | sed 's/tcp:\/\/\([^:]*\).*/\1/')
```

**Comment by mchiang0610** [comment]
@vangdfang Thanks for submitting the workaround as well.

**Comment by mchiang0610** [comment]
Merging with #1031

**Comment by jduprey** [comment]
I had the same problem
export NO_PROXY=$(echo $DOCKER_HOST | sed 's/tcp:\/\/\([^:]*\).*/\1/')

Fixed.

**Comment by mchiang0610** [comment]
If anyone still has problems with this on Mac or Windows 10+, please contact me at mchiang@docker.com.

We are working on something to help address this issue.

**Comment by anthony-o** [comment]
On Windows 7, in a bat, one can do this (with MSYS2 `usr\bin` in the `PATH`, in order to have `sed`):
```
for /f %%i in ('echo %DOCKER_HOST% ^| sed "s/tcp:\/\/\([^:]*\).*/\1/"') do set NO_PROXY=%%i
```
