### ISSUE TITLE
By what date would kitematic be available on windows? waiting desperately.

### ISSUE THREAD

**Issue by pucchur** [kitematic/kitematic#515]

**Comment by mchiang0610** [comment]
@pucchur We are targeting the end of June. 

That being said, we are planning to have public tests early June, would you like to take part in that? 

If so, would I be able to know what you are planning to do with Kitematic? (specific use cases?) 

Thanks! 
mchiang@docker.com 

PS. Closing this issue for now. Feel free to answer me via comments or email me. :)

**Comment by pucchur** [comment]
thanks for the details @mchiang0610, I am attempting to build a microservices styled architecture accounting software ...after researching tools like panamax, shipyard and docker I found kitematic to be the most developer friendly while trying on my friends Macbook that's why eagerly looking forward to the availability almost everyday.

**Comment by pucchur** [comment]
@mchiang0610 is the early stage windows version available now?

**Comment by mchiang0610** [comment]
@pucchur Not yet. There is a windows branch that is being actively worked on, but it may be broken at times as it's in heavy development. Thanks!
