### ISSUE TITLE
Failing to connect to Docker-machine instance on VBox

### ISSUE THREAD

**Issue by kostonstyle** [kitematic/kitematic#517]
Hi all  
When I run `docker version` command on terminal, I've got the error message:
```
Developers-MBP:~ user$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
FATA[0000] Get http:///var/run/docker.sock/v1.18/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```
Thanks  for help

**Comment by mchiang0610** [comment]
@kostonstyle 

I'm assuming you are running this from your Mac terminal. If so you will need to first run

```
eval "$(docker-machine env dev)"
```
Then it should all work.  

To make things easy, Kitematic has a Whale button that you can use without having to remember that (or script that). 

![image](https://cloud.githubusercontent.com/assets/3325447/7740142/a3ba8588-ff21-11e4-96a7-ee91ad4071c1.png)

**Comment by mchiang0610** [comment]
Hope this helps! Closing the issue for now.

**Comment by kostonstyle** [comment]
@mchiang0610 I pressed on Whale button to start the terminal and this error occurs.

**Comment by mchiang0610** [comment]
@kostonstyle Sorry about that.  Do you mind going into virtualbox and removing the "dev" VM, and also restart Kitematic to automatically create it again?

**Comment by mchiang0610** [comment]
@kostonstyle Do you have a script in your bash shell?

**Comment by mchiang0610** [comment]
Another user had this issue: 

Try: docker-machine regenerate-certs dev

**Comment by ryanmaclean** [comment]
Can confirm the same issue with recent build from Mac terminal, using the whale button found on the lower left hand corner of the Kitematic UI. In my case, "eval "$(docker-machine env dev)" did the trick!

**Comment by mchiang0610** [comment]
Should be fixed with latest toolbox
