### ISSUE TITLE
Bug - Kitematic crashes after opening on Yosemite 10.10.3

### ISSUE THREAD

**Issue by epavlenko** [kitematic/kitematic#518]
When I start Kinematic my MacBook Pro 13" Early 2015 always crashes and restarts automatically.
Mac OS Yosemite 10.10.3 (14D136).
Tried with Kitematic-0.5.25 and Kitematic-0.5.27.

**Comment by mchiang0610** [comment]
@epavlenko Can you help get Kitematic logs? 

```
cd  your directory
./Kitematic\ \(Beta\).app/Contents/MacOS/Kitematic\ \(Beta\) 
``` 
That should run Kitematic with logs.

**Comment by epavlenko** [comment]
@mchiang0610 I was unable to generate a text file or a screenshot, so here are photos of my screen when I run Kinematic as you showed.
![img_2701](https://cloud.githubusercontent.com/assets/7733819/7743446/96077f04-ffa3-11e4-8bd8-b182497cc4fc.jpg)
![img_2702](https://cloud.githubusercontent.com/assets/7733819/7743447/99181488-ffa3-11e4-9905-ab1dd16163bd.jpg)

**Comment by mchiang0610** [comment]
@epavlenko It seems to be running well. Does KM get stuck at 2%? (The logs you are showing seem all good)

**Comment by epavlenko** [comment]
@mchiang0610 my computer always goes to kernel panic at that moment

**Comment by mchiang0610** [comment]
@epavlenko One of the older version of KM may have a bug that caused that. Are you running the latest Kitematic? (Mind also checking if you are running the latest virtualbox? ) 

Thanks, and sorry about the experience so far.

**Comment by epavlenko** [comment]
@mchiang0610 Thanks. I removed my virtualbox and computer stopped crashing.
But now it's stuck on 99%.
There is nothing new in log: 
> $ ./Kitematic\ \(Beta\).app/Contents/MacOS/Kitematic\ \(Beta\) 
> [1929:0521/115348:INFO:renderer_main.cc(200)] Renderer process started
> [1927:0521/115349:INFO:CONSOLE(109)] "Download the React DevTools for a better development experience: https://fb.me/react-devtools", source: /Users/eugene/Downloads/Kinematic/Kitematic (Beta).app/Contents/Resources/app/node_modules/react/lib/React.js (109)

![screenshot 2015-05-21 11 56 22](https://cloud.githubusercontent.com/assets/7733819/7745365/42aafdd0-ffb3-11e4-815d-d5b3c25b158c.png)

**Comment by mchiang0610** [comment]
@epavlenko Ah. Good. Do you mind trying this version of Kitematic? It should fix that issue. Let me know if it doesn't. 

https://github.com/kitematic/kitematic/releases/tag/v0.5.27-intel-nic

(Note: this is a pre-release build that we are using to test the getting stuck at 99% bug)  Reference this issue: https://github.com/kitematic/kitematic/issues/236

**Comment by mchiang0610** [comment]
Closing this issue in favor of that issue now. (since it's the same) https://github.com/kitematic/kitematic/issues/236
