### ISSUE TITLE
Start-up stops at 99% - IP: 192.168.99.100 is not in the cert's list: 192.168.99.101

### ISSUE THREAD

**Issue by dev-guy** [kitematic/kitematic#519]
This guaranteed to happen if I reboot and run Kitematic again. Dropping dev and recreating it works; however, I would like to avoid the productivity loss of reinstalling containers every time I reboot.

Cannot connect to the Docker Engine. Either the 
VM is not responding or the connection may be
blocked (VPN or Proxy): Hostname/IP doesn't 
match certificate's altnames: "IP: 192.168.99.100 is
not in the cert's list: 192.168.99.101"

**Comment by mchiang0610** [comment]
@dev-guy We are testing out a pre-release that should fix this problem! Do you mind giving it a try? 

https://github.com/kitematic/kitematic/releases/download/v0.5.27-intel-nic/Kitematic-0.5.27-intel-nic.zip 

Let me know if you are still running into the issue after.

**Comment by mchiang0610** [comment]
Also consolidating this issue to: https://github.com/kitematic/kitematic/issues/483

**Comment by ynagarjuna1995** [comment]
![image](https://cloud.githubusercontent.com/assets/5663901/10790868/b7edd416-7dab-11e5-995f-4c990dd2eb2c.png)

I have the same problem how ever if I reinstall everything seems to be fine ..But again I will face the issue 

Waste of time 

Please fix the the issue

**Comment by FrenchBen** [comment]
@ynagarjuna1995 It looks like you had multiple machines setup at some point - Whenever the certs above appears, you can always regenerate the certs via: `docker-machine regenerate-certs default`

**Comment by peter-mw** [comment]
i have the same error 

`IP: 192.168.99.100 is not in the cert's list: 192.168.99.101`

![image](https://cloud.githubusercontent.com/assets/5698247/13438396/86352b4c-dff1-11e5-8753-b6bf86ee2d44.png)

**Comment by HimaniSinghai** [comment]
Thanks

**Comment by ccaspanello** [comment]
@peter-mw Thank you for that command.  Saved me from blowing away my VM and starting from scratch.  You rock!

**Comment by Happpy** [comment]
@peter-mw Thank you for the command, also saved my work

**Comment by peter-mw** [comment]
hi, i'm glad it worked, but credit for the command goes to @FrenchBen

**Comment by kimmuzafar** [comment]
It saved my day! Cheers..

**Comment by heliortf** [comment]
Really really thanks +1

**Comment by dinesh1gore** [comment]
Thanks! It really helped.
