### ISSUE TITLE
Tab links doesn't feel like they are clickable (add hover?)

### ISSUE THREAD

**Issue by Elesant** [kitematic/kitematic#538]
![screen shot 2015-05-26 at 4 08 36 pm](https://cloud.githubusercontent.com/assets/559953/7825415/8770e8c8-03c1-11e5-826b-9e460006a8a5.png)

**Comment by TeckniX** [comment]
Not sure when it was added, but it looks like a hover state exists in the latest master code:

![filter-hover](https://cloud.githubusercontent.com/assets/33699/7841875/87ffa084-046d-11e5-82dd-dad2083b65e8.png)

**Comment by Elesant** [comment]
@TeckniX ah thanks, sry I did a PR to fix this but forgot to close the issue after :p
