### ISSUE TITLE
Docker Engine and VirtualBox VM blocking

### ISSUE THREAD

**Issue by bradbergeron-us** [kitematic/kitematic#547]
Was not able to debug this...
![image](https://cloud.githubusercontent.com/assets/8945799/7833375/589593dc-0434-11e5-8f1f-b63418fec724.png)

**Comment by TeckniX** [comment]
@bradbergeron-us Would you mind doing the following to help us debug it?

* Restart the Kitematic app
* Click on View > Toggle DevTools
* Click on the `Console` tab within the DevTools
* Copy and paste all the information from that window as a gist, or as a comment here.

Thanks!

**Comment by bradbergeron-us** [comment]
## Did not See the response in time before I had patched it myself

#### My Solution
1. Restart Kitematic Application
2. Uninstall Virtual Box via Oracle
3. Restart OSX

**Comment by TeckniX** [comment]
:+1: 
Please do share any issues you run across with any steps to re-create them.

**Comment by mchiang0610** [comment]
Should be fixed with latest Docker Toolbox

Just in case, merging with #1029
