### ISSUE TITLE
Can't start containers

### ISSUE THREAD

**Issue by mansolo** [kitematic/kitematic#553]
Hi,

I have downloaded and installed Kinematic on my MBP. I can pull down simple containers but for centos, ubuntu, redis, mariadb, etc. I am not able to start the container via UI or CLI. I don't get any logs or other error messages that can help troubleshoot the problem. I also don't see any knob to increase/adjust system resources allocations, in case that is the reason why it is not working. Any suggestions?

Thanks.

**Comment by mchiang0610** [comment]
@mansolo Hi, redis and mariadb should work (mariadb will require some configuration). 

Ubuntu and CentOS should not work as they are base images and are not supported in Kitematic. 

If you are looking to run Ubuntu, please try the Ubuntu-upstart one. 

Thanks!
