### ISSUE TITLE
error requesting and image over proxy

### ISSUE THREAD

**Issue by jammer76** [kitematic/kitematic#559]
pulling an image over proxy doesn't works perhaps a new configuration parameter can help

**Comment by mchiang0610** [comment]
Hi @jammer76 Kitematic / Docker-machine currently do not play well with proxies at the moment. It's a known issue that we are aware of. 

Were you able to get through installing Kitematic through a proxy?

**Comment by azizur** [comment]
I am getting same error. Unable to pull docker images behind proxy.

**Comment by mchiang0610** [comment]
Merging with #1031

**Comment by mchiang0610** [comment]
If anyone still has problems with this on Mac or Windows 10+, please contact me at mchiang@docker.com.

We are working on something to help address this issue.
