### ISSUE TITLE
Unable to download grafana/grafana image? (HTTP 404)

### ISSUE THREAD

**Issue by victorhooi** [kitematic/kitematic#567]
I'm on OSX 10.10.4.

I have installed Kitematic (Beta - version 0.6.0) via Homebrew cask.

I'm trying to install the grafana/grafana image and I get the the following error:

![screenshot 2015-05-31 06 28 12](https://cloud.githubusercontent.com/assets/243499/7900694/5657772a-075e-11e5-8bba-4e51bbd1325b.png)

Is there any way to get more details about what's going on?

As far as I'm aware, the grafana/grafana image does exist on Docker Hub:

https://registry.hub.docker.com/u/grafana/grafana/

**Comment by jeffdm** [comment]
Thanks for the issue!

Is the VM up and running? Often this error will show if the Docker engine cannot be reached.

**Comment by victorhooi** [comment]
Very strange - it seems to have been an intermittent thing, because when I tried 30 minutes later, it seemed to work fine...

Sorry I can't reproduce it =(. Happy if you want to close the ticket, and we can re-open if it recurs?

**Comment by mchiang0610** [comment]
@victorhooi Closing this issue for now. Please do reopen it if you see it again! 

Thanks!
