### ISSUE TITLE
Container list never loads

### ISSUE THREAD

**Issue by abstractinventions** [kitematic/kitematic#575]
When launching kinematic the container list page simply sits there spinning and never loads.
![screenshot 2015-06-02 22 15 51](https://cloud.githubusercontent.com/assets/4849265/7935525/034a67d6-0975-11e5-833f-2e9f2f59ee29.png)

I've tried typing search terms in the search box as well.

However, when adding an image via the cmd line, it appears to the right.

I assume this is hitting a server somewhere and not getting a response - any idea of the query it is running that I could test via curl or such?

**Comment by rshmelev** [comment]
same issue with me...

**Comment by jeffdm** [comment]
Merging with #576
