### ISSUE TITLE
Kitematic stuck at loading 

### ISSUE THREAD

**Issue by numanoids** [kitematic/kitematic#576]
Bug https://github.com/kitematic/kitematic/issues/353 appears to have resurfaced. I'm unable to get kitematic to load up any images. CLI working fine for searching and pulling after I modified the VBox settings to --natdnsproxy1 off --natdnshostresolver1 off

**Comment by SkiftCreative** [comment]
getting the same issue here. fresh install.

osx 10.10.3

**Comment by TeckniX** [comment]
@numanoids @SkiftCreative There's a small issue with the actual Docker repo from which Kitematic captures info about the different containers.

This should be resolved soon, thanks for your patience!

**Comment by numanoids** [comment]
Thank you for the update!

**Comment by jeffdm** [comment]
Apologies - working on a fix for this.

For now KM recommended repos are disabled but soon they'll be back.

**Comment by jeffdm** [comment]
Should be fixed now.

**Comment by numanoids** [comment]
Yep, thanks for the fast turnaround!

**Comment by abstractinventions** [comment]
yes, works for me.  Thanks for the quick response.

**Comment by abstractinventions** [comment]
spoke too soon...although I was able to browse the images, I couldn't download any - keptrecieving a404.

I fixed it via `vboxmanage modifyvm dev --natdnsproxy1 off --natdnshostresolver1 off` as seen in #353
