### ISSUE TITLE
Redis: 404

### ISSUE THREAD

**Issue by gcobr** [kitematic/kitematic#578]
I am new to Kitematic, and I tried to create a container for Redis, but I got an HTTP 404 error saying: No such image: redis:latest (tag:latest).

**Comment by mchiang0610** [comment]
@gcobr Can you restart Kitematic? It should hopefully fix this issue. 

It works on my end, and cannot reproduce. 

If you are still running into problems, please let me know, and re-open the issue. 

Thanks!

**Comment by gcobr** [comment]
I did restart it, twice. However, the error persists.

Em ter, 2 de jun de 2015 às 19:43, Michael Chiang <notifications@github.com>
escreveu:

**Comment by mchiang0610** [comment]
@gcobr Are you connecting through proxy or VPN? It could be blocking your connection to Docker Hub.

**Comment by sirioz** [comment]
Same error here. 404 trying to pull many images. Restarted. Nothing changed.

**Comment by joewhite86** [comment]
In my case disabling my companies VPN helped.

**Comment by mchiang0610** [comment]
@sirioz @gcobr 
Looks like many users are having this issue: 
(Temp fix is there) 
https://github.com/kitematic/kitematic/issues/588 

Merging the two threads.
