### ISSUE TITLE
Basic uninstall script

### ISSUE THREAD

**Issue by tijn72** [kitematic/kitematic#58]
Using the following to do the full uninstall of Kitematic

its clunky but might help others that need to do repeated uninstall / installs 

```bash
#!/bin/sh
set -e
CUR_DIR=$(pwd)
cd /tmp

curl -o vbuninstall.sh http://www.virtualbox.org/svn/vbox/trunk/src/VBox/Installer/darwin/DiskImage/VirtualBox_Uninstall.tool
chmod u+x vbuninstall.sh

#see issue 57 - Kitematic doesnt kill the background VBox processes
pkill VBox

./vbuninstall.sh

sudo route delete -net 172.17.0.0 -netmask 255.255.0.0 -gateway 192.168.60.103
sudo rm -rf ~/Library/Application\ Support/Kitematic
sudo rm /Library/LaunchAgents/com.kitematic.route.plist
sudo rm -rf /Applications/Kitematic.app

cd $CUR_DIR
```

**Comment by jeffdm** [comment]
Fixed in 0.5. Just remove the `Kitematic.app` file and the `~/Users/<username>/Library/Application\ Support/Kitematic` directory and you're done.

If you want to completely wipe everything (Kitematic, VirtualBox, all your VMs) you can use `./util/reset`
