### ISSUE TITLE
Kitematic high utilization of system resources

### ISSUE THREAD

**Issue by UnquietCode** [kitematic/kitematic#580]
We have experienced significant performance gains simply by closing the Kitematic UI while leaving the VM running. (A best guess would be that the log aggregation and other stats collection is eating up resources even when the UI is hidden.) This isn't actually impacting our development process, it just seems suspicious and worth reporting. Thanks!

**Comment by mchiang0610** [comment]
@UnquietCode Thanks for reporting this. May we know what containers you were running?

**Comment by mchiang0610** [comment]
Merging with #867
