### ISSUE TITLE
jenkins show up as 404 when I try to start it

### ISSUE THREAD

**Issue by d3ming** [kitematic/kitematic#581]
Repro:
1. Start up kitematic
2. Search for the jenkins container
3. Start it

Result:
An error occured: HTTP code is 404 which indicates error: no such container...

**Comment by jeffdm** [comment]
Thanks for the issue

Can you check the logs for any issue: `cmd+alt+i then click Console`

**Comment by d3ming** [comment]
No errors in console.  I did find that this occurs to me in general when I try to add any container.  This was off of a fresh install on OSX 10.10.3

I do have docker and boot2docker installed separately as well

**Comment by cdtweb** [comment]
Hi, I did a fresh install of Kitematic on OSX 10.10.3 as well and am getting the same error message on any container that I try and install. I am also seeing nothing in the console.

**Comment by jeffdm** [comment]
404 usually means the image pull failed so the image cannot be found. The error message definitely needs to improve.

Taking a look.

**Comment by jeffdm** [comment]
Also, if you click the `Docker CLI` button and then try `docker run jenkins`, does it work? What is the error?

**Comment by Cordobo** [comment]
See my comment here: https://github.com/kitematic/kitematic/issues/584#issuecomment-108435576
It looks like the "404 image not found" is an issue with too many redirects in VirtualBox.
HTH

**Comment by mchiang0610** [comment]
Same as https://github.com/kitematic/kitematic/issues/588  

Temp workaround is there. (Merging threads) 

Thanks!

**Comment by vinit7533** [comment]
while installing jenkins we are getting HTTP Status 404 - /
