### ISSUE TITLE
Anyone seen this?

### ISSUE THREAD

**Issue by dstroot** [kitematic/kitematic#582]
![screen_shot_2015-06-02_at_7_57_01_pm](https://cloud.githubusercontent.com/assets/1438457/7951916/5db6ea72-0962-11e5-885e-3e2599cbbcb1.png)

Just started after installing most recent build.  :(

**Comment by jeffdm** [comment]
Thanks for the issue. Are there any errors in the console? `cmd+alt+i` then click `Console`

**Comment by dstroot** [comment]
Actually self inflicted - recopied the app and restarted my box and all is well

**Comment by jeffdm** [comment]
Good to hear!
