### ISSUE TITLE
can't download minecraft

### ISSUE THREAD

**Issue by flyhawk007** [kitematic/kitematic#584]
HTTP code is 404 which indicates error: no such container - No such image: kitematic/minecraft:latest (tag: latest)

**Comment by Cordobo** [comment]
This solved the problem of having too many redirects (see console output) and worked for me on OSX 10.10 with VirtualBox 4.3.28:

1. Open "Virtual Box  > Settings > Network > Host-only-networks"
2. Select "vboxnet0" and klick on the screw driver (ohhh, the irony...)
3. Select DHCP-Server and uncheck the checkbox from "Activate Server".
4. Accept with "OK".
5. Restart Kitematic.

HTH
Cordobo

**Comment by mchiang0610** [comment]
@Cordobo Thanks for this. We are looking into this issue. 

A temp fix is here: 
https://github.com/kitematic/kitematic/issues/588 

Merging the issue there.
