### ISSUE TITLE
After installing kitematic, all I got is this

### ISSUE THREAD

**Issue by adlermedrado** [kitematic/kitematic#585]
![kitematic](https://cloud.githubusercontent.com/assets/172623/7960533/abde1214-09d7-11e5-9d48-2d00399682a9.png)

**Comment by adlermedrado** [comment]
Virtualbox was installed, a Virtualbox VM was created but nothing more happened.

**Comment by adlermedrado** [comment]
I ran the commands below and it solved the problem:
`
docker-machine rm -f dev
docker-machine create -d virtualbox dev
`

**Comment by mchiang0610** [comment]
Thanks @adlermedrado, it's a problem we have connecting to Docker Machine
