### ISSUE TITLE
Trying to install any new container generates 404 in Kitematic

### ISSUE THREAD

**Issue by cousine** [kitematic/kitematic#587]
Also if I try to manually do it through the CLI, I get too many redirects

    FATA[0003] Get https://registry-1.docker.io/v1/repositories/kunickiaj/elasticsearch-head/tags: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: too many redirects

**Comment by cousine** [comment]
just an update, I've ssh'ed into the docker machine and added 8.8.8.8 to /etc/resolv.conf, which fixed the problem, but I suspect this is a dirty fix however its a functioning workaround till a fix is available.

**Comment by mchiang0610** [comment]
@cousine Thanks for this. We are noticing many 404 errors, and are looking into this. (Will be merging all the issues to a central one).

**Comment by mchiang0610** [comment]
Closing this in favor of: https://github.com/kitematic/kitematic/issues/588
