### ISSUE TITLE
Bug - Creating a container results in 404 error 

### ISSUE THREAD

**Issue by mchiang0610** [kitematic/kitematic#588]
This is to converge all the 404 issues we are getting in Kitematic. 

**Temp fix:** (Note: it only worked for some users)
1. Open Docker CLI through Kitematic 
![image](https://cloud.githubusercontent.com/assets/3325447/7965592/5a3d5c3e-09d3-11e5-9392-a9bfb02c8a01.png)

2. In the command prompt that is opened type in: 
`docker-machine ssh` 

3. `sudo su` to give sudo access for the next promp

4. `echo "nameserver 8.8.8.8" > /etc/resolve.conf`  This changes the name server to use Google's at 8.8.8.8 (please feel free to use another one if you have a preference). 

-----------------
For debugging purposes: 

Accessing through command line may result in: 
`FATA[0003] Get https://registry-1.docker.io/v1/repositories/kunickiaj/elasticsearch-head/tags: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: too many redirects` 
(In reference to: https://github.com/kitematic/kitematic/issues/587 )

**Comment by mchiang0610** [comment]
Comment from @cordobo in previous thread in case anyone would like this:

UPDATE:
Changing the GUESTS network from "NAT" to "Bridge" in Virtual Box worked as fine, although Kitematic wasn't able to startup (hanging at 99%). Switching back to "NAT" made Kitematic available again.

ORIGINAL COMMENT:
This solved the problem of having too many redirects (see console output) or getting a "404 image not found" and worked for me on OSX 10.10 with VirtualBox 4.3.28:

Open "Virtual Box > Settings > Network > Host-only-networks"
Select "vboxnet0" and klick on the screw driver (ohhh, the irony...)
Select DHCP-Server and uncheck the checkbox from "Activate Server".
Accept with "OK".
Restart Kitematic.
HTH
Cordobo

**Comment by iSashaCH** [comment]
echo "nameserver 8.8.8.8" > /etc/resolv.conf

**Comment by d3ming** [comment]
Thanks, this workaround worked for me!

**Comment by gcobr** [comment]
I've been using this nameserver for a long time, and it didn't solve the HTTP 404 problem.

I also think that if it were a DNS problem, we wouldn't get an actual HTTP status code.
Receiving an HTTP status code means that the name resolution phase of the request worked perfectly and that the request hit the server as expected. In turn, the server sent back an HTTP response saying that the requested resource was not found.

**Comment by mchiang0610** [comment]
@gcobr @d3ming @iSashaCH 

There was a DNS switch on Docker's side. It should be fixed. If not, please flush DNS. 

`sudo discoveryutil mdnsflushcache;sudo discoveryutil udnsflushcaches;say flushed` 

Please comment here if you are having problems. Otherwise, I will close this issue tomorrow. 

Thanks!

**Comment by simondean** [comment]
Opening the VirtualBox app and restarting the Kitematic VM resolved it for me. This was only after I'd realised that quiting the Kitematic app doesn't stop the VM

**Comment by mchiang0610** [comment]
@simondean Glad it's working for you now. :)

If you'd like Kitematic to stop the VM upon closing -> please go into Kitematic settings and check that box. The reason we don't stop the VM is because if we shut it down, you'd have to start it up again if you need to use Docker via command line.
