### ISSUE TITLE
Findability and official images

### ISSUE THREAD

**Issue by kevinSuttle** [kitematic/kitematic#589]
Exercise: try to find the official Node image in the Kitematic UI.

https://registry.hub.docker.com/_/node/

It's not listed in the "recommended" images and searching for 'node' doesn't return the official image. Am I missing something?

**Comment by mchiang0610** [comment]
@kevinSuttle 

If you search it should appear within Kitematic: 

![image](https://cloud.githubusercontent.com/assets/3325447/7966345/5049db58-09d8-11e5-9bcf-ae240c0548ac.png)

Closing this for now. Please do re-open if you are still not seeing it listed.

**Comment by kevinSuttle** [comment]
Weird. It was only showing Strongloop's before. It's there now. Perhaps it was the upgrade from 0.6.1 to 0.6.3 that fixed it. Anyway, thanks for looking into it @mchiang0610.
