### ISSUE TITLE
"certificate not trusted" Error When Logging In

### ISSUE THREAD

**Issue by bennythomps** [kitematic/kitematic#590]
I'm trying to launch a new image with Kitematic 0.6.3, but when trying to log in I receive a "certificate not trusted" error. If I try to skip logging in, I get an error saying "There was an error contacting Docker Hub".

![screen shot 2015-06-03 at 1 26 16 pm](https://cloud.githubusercontent.com/assets/6827467/7968144/772619d2-09f4-11e5-9032-473a0c0dfefb.png)

**Comment by mchiang0610** [comment]
@bennythomps Thanks Benny, I'm looking into this issue.

**Comment by bennythomps** [comment]
It's worth mentioning I'm behind a corporate proxy that self-signs all certificates.

**Comment by mchiang0610** [comment]
@bennythomps That makes sense. We cannot trust the corporate proxy. 

We should give you the option to though, or doing some other activities to guide the user.

**Comment by bennythomps** [comment]
Seems like the main culprit is the Docker Hub SSL configuration?

![screen shot 2015-06-04 at 8 47 26 am](https://cloud.githubusercontent.com/assets/6827467/7985441/63399050-0a96-11e5-8672-89a7d1e4e320.png)

**Comment by TeckniX** [comment]
Weird it's showing as a proper SHA256 for me..

![cert](https://cloud.githubusercontent.com/assets/33699/7991229/a9d55156-0ac4-11e5-977b-615b20a4281e.png)

**Comment by mchiang0610** [comment]
@bennythomps Can you click on the lock - and get the certificate information? (It can be possible that the network you are on is redirecting) 

I am getting the correct certificate like @TeckniX as well.

**Comment by daagar** [comment]
@bennythomps gets the 'wrong' cert I believe because of the corporate proxy having altered the certificate. Somehow, we need to be able to add the correct cert chain to Kitematic so internal proxy servers can be trusted.

**Comment by Carl4** [comment]
@bennythomps, That's how my corporate proxy mangles CERTS too. Is there a way to tell Kitematic to ignore SSL? Isn't it great how our corporate security posture causes us to disable security.

Better yet, where can I add my corporate Cert Authority to Kitematic?

**Comment by mchiang0610** [comment]
@Carl4 We don't support proxies / VPNs yet. We are aware and have plans to fix it

**Comment by mchiang0610** [comment]
Merging with #1031

**Comment by mchiang0610** [comment]
If anyone still has problems with this on Mac or Windows 10+, please contact me at mchiang@docker.com.

We are working on something to help address this issue.

**Comment by ghzhou** [comment]
Still have this problem as of today. I am on Win10.
