### ISSUE TITLE
hello-world-nginx 404 error

### ISSUE THREAD

**Issue by cosbor11** [kitematic/kitematic#592]
1. Installed app on OSX 10.10.3 using this command: brew cask install kitematic
2. Setup application
3. Created new Docker account
4. Clicked the 'Create' button on the first item on the Recommended list which is 'hello-world-ngix'
ISSUE: failed to get image from the hub (see error message in screenshot)

![screen shot 2015-06-03 at 6 02 04 pm](https://cloud.githubusercontent.com/assets/4424093/7974771/c045faa8-0a1a-11e5-923f-e329f981bb2a.png)

**Comment by cosbor11** [comment]
Everything worked fine when creating a debian container

**Comment by jeffdm** [comment]
Thanks for the issue,

If you click on the `Docker CLI` button and try this on the command line:

`docker pull kitematic/hello-world-nginx`

does it work?

**Comment by yeagerm** [comment]
I have the same problem as the OP. I can login to Docker site from the Kinematic app. When I run the Docker CLI and 
docker pull kitematic/hello-world-nginx

I get:
bash-3.2$ docker pull kitematic/hello-world-nginx
Pulling repository kitematic/hello-world-nginx
FATA[0000] Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp: lookup index.docker.io on 127.0.0.54:53: read udp 127.0.0.54:53: connection refused

**Comment by jeffdm** [comment]
It seems like you're using a local DNS server, maybe try:

`echo "8.8.8.8" > /etc/resolv.conf`

**Comment by yeagerm** [comment]
Ok, works now when I turned off DNScrypt and was using OpenDNS IPs, and put in 8.8.8.8 as a fallback.

**Comment by mchiang0610** [comment]
Good to hear. Closing this issue for now. Please re-open if you are still running into this problem. 

Thanks!
