### ISSUE TITLE
django official container connection timeout

### ISSUE THREAD

**Issue by scmjohns** [kitematic/kitematic#594]
Getting a timeout error trying to pull this container.

connect ETIMEDOUT 192.168.99.100:2376

**Comment by mchiang0610** [comment]
@scmjohns Can you click on the Docker CLI button within Kitematic? 

and run these 2 commands

`docker info`

and 

`docker-machine -D ls` 

Would love to see the logs from that. 

Thanks,
Michael

**Comment by scmjohns** [comment]
The issue itself seems to have resolved itself so I cannot replicate it to produce logs. I was able to download the django container but so far unable to run it. I did run the nginx container without issue.

**Comment by mchiang0610** [comment]
@scmjohns That's awesome to know. I will close this issue for now. If you run into it again, please feel free to reopen it, and we can troubleshoot from there. 

Thanks!

**Comment by scmjohns** [comment]
Thanks @mchiang0610
