### ISSUE TITLE
Binaries not copying to PATH

### ISSUE THREAD

**Issue by kylemclaren** [kitematic/kitematic#602]
The docs state that:
>It copies the docker and docker-machine binaries to /usr/local/bin for convenience.

But, this never happened and I had to manually move the binaries over...

**Comment by TeckniX** [comment]
What are the permissions on your `/usr/local/bin` folder?

**Comment by jeffdm** [comment]
We no longer copy the binaries to keep the app self-contained. Sorry the docs were out of date - I've just updated them

There's a new menu item to copy the binaries to PATH, under `Kitematic => Install Docker Commands`

![screen shot 2015-06-05 at 10 57 06 am](https://cloud.githubusercontent.com/assets/251292/8011891/a82dd384-0b71-11e5-8af4-fe2231236cc1.png)

**Comment by kylemclaren** [comment]
Nice, thanks @jeffdm...
