### ISSUE TITLE
Docker CLI throws "No such file or directory" if DOCKER_CERT_PATH variable contains spaces

### ISSUE THREAD

**Issue by mtjoseph** [kitematic/kitematic#606]
FYI. Running 0.6.3

Steps:
1. Open Kitematic
2. Click "DOCKER CLI"

Last login: Mon Jun  8 12:44:23 on ttys005
bash -c "export PATH='/Volumes/Macintosh HD/Users/zazu/Downloads/Archive/Kitematic (Beta).app/Contents/Resources/app/resources:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' clear && DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_CERT_PATH=/Volumes/Macintosh HD/Users/zazu/.docker/machine/machines/dev DOCKER_TLS_VERIFY=1 $SHELL"
~ ❯❯❯ bash -c "export PATH='/Volumes/Macintosh HD/Users/mtjoseph/Downloads/Archive/Kitematic (Beta).app/Contents/Resources/app/resources:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' clear && DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_CERT_PATH=/Volumes/Macintosh HD/Users/zazu/.docker/machine/machines/dev DOCKER_TLS_VERIFY=1 $SHELL"
bash: HD/Users/mtjoseph/.docker/machine/machines/dev: No such file or directory
~ ❯❯❯  

The workaround is to delimit "DOCKER_CERT_PATH" environment variable with single quote, e.g.
DOCKER_CERT_PATH='/Volumes/Macintosh HD/Users/zazu/.docker/machine/machines/dev'
and manually run command in a shell environment.

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by mchiang0610** [comment]
@mtjoseph merging with #1029
