### ISSUE TITLE
Crate not working

### ISSUE THREAD

**Issue by vyasmanish** [kitematic/kitematic#607]
Cannot pull Crate in docker

**Comment by TeckniX** [comment]
What is the exact name of the Crate that you're trying to build?
As you can see https://registry.hub.docker.com/search?q=crate there are quite a few. 

Also provide any screenshot/error encountered.
Thanks!

**Comment by mchiang0610** [comment]
merging this with: https://github.com/kitematic/kitematic/issues/626
