### ISSUE TITLE
have to log out and log back in to see docker hub content

### ISSUE THREAD

**Issue by sputnik62** [kitematic/kitematic#612]
When I start Kitematic I always get a message that says "problem connecting to docker hub". If I sign out and sign back in docker hub content become visible again

**Comment by jeffdm** [comment]
Just fixed in 0.6.4, sorry about that.

Thanks for the issue!

**Comment by sputnik62** [comment]
Just checked out v0.6.4 and it is working indeed. Thanks for a blazing fast reply.
