### ISSUE TITLE
Can Kitematic do a build from a Dockerfile

### ISSUE THREAD

**Issue by ronnieserr** [kitematic/kitematic#614]
Hi,

Please recommend the best way to build an image from a Dockerfile using Kitematic on Mac OS.

Thanks,

Ronnie

**Comment by mchiang0610** [comment]
@ronnieserr Hi Ronnie, 

If you have a dockerfile locally, please click on the Docker CLI button in the bottom left corner of Kitematic, and then do the docker build and docker run commands. 

The result should show in Kitematic after. Thanks!

**Comment by mchiang0610** [comment]
There is a feature request for this feature: https://github.com/kitematic/kitematic/issues/574 

Closing this thread to merge the conversation over to the other.
