### ISSUE TITLE
no such container404 opencpu/rstudio:latest (tag:latest)

### ISSUE THREAD

**Issue by markebrown** [kitematic/kitematic#617]
trying to use kitematic to use the opencpu/rstudio image and I got this error.

**Comment by TeckniX** [comment]
This is a known issue and already added as a needed feature:
https://github.com/kitematic/kitematic/issues/572

**Comment by mchiang0610** [comment]
@markebrown Hmm, this one in particular seem to have the latest tag. 

I was able to get the error as well - however it was a problem on the Docker Hub side, and it should be fixed now. 

Can you try again? Thanks!

**Comment by mchiang0610** [comment]
merging this with: https://github.com/kitematic/kitematic/issues/626
