### ISSUE TITLE
OVF file not available to open Kitematic as an appliance in Virtual Box

### ISSUE THREAD

**Issue by santoshkulkarni** [kitematic/kitematic#625]
Hi,

I use Virtual Box quite often and install new appliances using the .OVF file. In Kitematic there is no OVF file available. Can anyone please help with the installation step of Kitematic? Surprisingly, there is no proper documentation for installation or am I missing something?

Thanks,

**Comment by TeckniX** [comment]
@santoshkulkarni you should be able to simply download the zip file from the latest release.
Currently https://github.com/kitematic/kitematic/releases/download/v0.6.6/Kitematic-0.6.6.zip then copy the App to your `Applications` folder

**Comment by jeffdm** [comment]
Thanks @TeckniX.

Going to close this but feel free to re-open if you're still stuck after downloading the zip file.
