### ISSUE TITLE
BUG: 404 on hello-world-nginx

### ISSUE THREAD

**Issue by SpokeyWheeler** [kitematic/kitematic#626]
I tried to download the hello-world-nginx container repeatedly but it fails with a 404. Ghost worked fine, I haven't tried any others.

MacBook Air 13inch, Early 2014
Mac OSX Yosemite 10.10.3

Let me know if you need anything else.

**Comment by TeckniX** [comment]
@SpokeyWheeler What happens if you click on the `Docker CLI` button (bottom left) and type in the terminal:
`docker pull kitematic/hello-world-nginx`

Can you copy&paste the out put of that?

**Comment by SpokeyWheeler** [comment]
Of course, that works fine.

-- 
Regards
Spokey

**Comment by benwu7** [comment]
same problem

**Comment by mchiang0610** [comment]
@SpokeyWheeler @benwu7 Unfortunately 404 error message in Kitematic can mean all sorts of different errors. We are working on a new update that will output better errors to help troubleshoot with this.

**Comment by mchiang0610** [comment]
merging this with issue https://github.com/kitematic/kitematic/issues/626

**Comment by mchiang0610** [comment]
Merging with #1030

**Comment by k0377** [comment]
I still have an issue with jenkins and kitematic https://github.com/docker/toolbox/issues/270
