### ISSUE TITLE
Install makes it to 99% and hangs

### ISSUE THREAD

**Issue by jacquesroy** [kitematic/kitematic#633]
On a MacAir OS/X Yosemite 10.10.3
I tried re-instlling and got the same thing.

**Comment by jeffdm** [comment]
Hi there, thanks for the issue;

Can you try the following, in-app via the menu:

`Kitematic (Beta) > Install Docker Commands`

Then in a terminal:

`docker-machine -D create -d virtualbox dev`

What's the output of this command?

**Comment by jacquesroy** [comment]
I can't find the docker-machine command.
I tried again the installation and I get:

Cannot connect to the Docker Engine. Either the VM is not responding or the connection may be blocked (VPN or Proxy): connect EHOSTUNREACH 192.169.99.100:2376 - Local (192.168.99.1:49519(

**Comment by joelmoss** [comment]
I have this same issue. Running the above `docker-machine` command returns...

```
Error creating machine: Machine dev already exists
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

**Comment by codepuppet** [comment]
I wish someone had some insight into this as it is extremely annoying to remove the vm and re-build all the images each time Kitematic is updated.

**Comment by DJviolin** [comment]
Same on Windows, install hangs at 99%.

**Comment by jeffdm** [comment]
@DJviolin would it be possible to provide an image of the error?  Thanks!

**Comment by DJviolin** [comment]
![vagolap02](https://cloud.githubusercontent.com/assets/5021728/8260274/b8db1fc8-16c2-11e5-9f19-ca34f787e6fe.png)

It's in hungarian... What is says: it's detected IP address collision with an another computer on the network. But I only see this message when I try to install Kitematic. More details in the Event Viewer.

If you know what to look for in the event viewer, please tell me.

**Comment by pandrew** [comment]
Still ip address conflict issue on 0.7.3 on Windows 7.

**Comment by jeffdm** [comment]
Thanks @pandrew! Closing in favor of #386
