### ISSUE TITLE
no such container404No such image: ches/kafka:latest (tag: latest)

### ISSUE THREAD

**Issue by reorx** [kitematic/kitematic#635]
When creating a kafka container on my MacBook Pro, OSX 10.10.3, I got this error:

`no such container404No such image: ches/kafka:latest (tag: latest)`

![screen shot 2015-06-15 at 13 38 04](https://cloud.githubusercontent.com/assets/405972/8153687/e01722f6-1363-11e5-948b-b281979635bd.png)

I have tried redis container in recommended page, which worked fine, but all the kafka in search result could not been created, all stopped on this error, please help, and if anything I can do to provide more information for debugging, I would be very glad to participate.

**Comment by TeckniX** [comment]
What happens when you issue `docker pull ches/kafka:latest` from the command line?
You can click on the `Docker CLI` image in the bottom left of Kitematic to issue the above command

**Comment by mchiang0610** [comment]
merging this with: https://github.com/kitematic/kitematic/issues/626

**Comment by reorx** [comment]
Pull from command line works fine, but the error in kitematic kept happening.

The problem now solved, it seems caused by the “Unverified” label at top right corner, and after I have verified my email address, everything goes well again. Like #625 said, brainless 404 error is bad for bug reporting, which should be fixed in highest priority.
