### ISSUE TITLE
Failed to fetch container

### ISSUE THREAD

**Issue by orlangur87** [kitematic/kitematic#636]
![screen shot 2015-06-15 at 12 22 18 pm](https://cloud.githubusercontent.com/assets/1624643/8156903/10000812-1359-11e5-8808-d865f616685a.png)

**Comment by orlangur87** [comment]
tried echo "8.8.8.8" > /etc/resolv.conf and that
![screen shot 2015-06-15 at 12 25 53 pm](https://cloud.githubusercontent.com/assets/1624643/8156978/8ec7707c-1359-11e5-9ea3-8fb50c3174d6.png)

**Comment by orlangur87** [comment]
by the way, I tried hello-world-nginx container and it works well
![screen shot 2015-06-15 at 12 27 36 pm](https://cloud.githubusercontent.com/assets/1624643/8157029/e8e2c2c8-1359-11e5-8d95-c73feaf64157.png)

**Comment by TeckniX** [comment]
if `docker pull` can't do it, then your repository isn't setup properly or is empty?

I found your test repo here: https://registry.hub.docker.com/u/orlangur/test/ but don't see any tags or info for it.
If you look at the Kitematic Nginx, it has the proper info: https://registry.hub.docker.com/u/kitematic/hello-world-nginx/tags/manage/

I created an empty repo and get the exact same error (aka you probably created an empty repo)
https://registry.hub.docker.com/u/tecknix/testing/

**Comment by mchiang0610** [comment]
Merging this issue with #626
