### ISSUE TITLE
non-zero exit (docker-machine)

### ISSUE THREAD

**Issue by mannickutd** [kitematic/kitematic#643]
The installation fails with this message
Mac OS 10.10.3 (14D136)
![screen shot 2015-06-16 at 09 36 14](https://cloud.githubusercontent.com/assets/1556623/8179016/6afd49de-140b-11e5-8435-0f413e53919c.png)

The same issue exists with docker-machine.

**Comment by mchiang0610** [comment]
@mannickutd Are you connected through VPN?   

Mind opening up virtualbox and removing the dev VM in it. Please restart Kitematic again after. 

Thanks

**Comment by mannickutd** [comment]
Hi Michael,

I am not connected through a VPN but I do have VPN software installed on
the machine.

I removed the dev VM and restarted but got the same problem.
I have no problems with docker, and boot2docker.

Thanks

Nick

**Comment by mchiang0610** [comment]
@mannickutd Thanks Nick. This is likely a conflict between boot2docker and docker-machine. 

cc/ @nathanleclaire to see if he wants any specific logs to help us continue to troubleshoot this.

**Comment by nathanleclaire** [comment]
This is with Machine rc3 right?

**Comment by mchiang0610** [comment]
@nathanleclaire Judging by this created 2 days ago. Yes, it would be with Machine RC3. 

@mannickutd Can you confirm which version of Kitematic you are running?

**Comment by mannickutd** [comment]
The different versions of the library are below

Last login: Thu Jun 18 08:21:37 on ttys003

Nicholass-MacBook-Air:~ nicholasstaples$ docker-machine -v

docker-machine version 0.2.0 (8b9eaf2)

Nicholass-MacBook-Air:~ nicholasstaples$ docker -v

Docker version 1.5.0, build a8a31ef

Nicholass-MacBook-Air:~ nicholasstaples$ boot2docker -v

Boot2Docker-cli version: v1.5.0

Git commit: ccd9032

**Comment by mchiang0610** [comment]
merging with #1029
