### ISSUE TITLE
no such container404

### ISSUE THREAD

**Issue by bargulg** [kitematic/kitematic#644]
When trying to create a container from blalor/centos, I get an error: no such container404No such image: blalor/centos:latest (tag:latest)
Also, some spaces are missing in that message - it should be: no such container 404 No such image: blalor/centos:latest (tag:latest)
or: no such container: 404 No such image: blalor/centos:latest (tag:latest)

**Comment by bargulg** [comment]
When i pick an exact version, not latest, I get: server error500No command specified

**Comment by mchiang0610** [comment]
@bargulg It appears that image is a base container. Since it doesn't give Kitematic the commands necessary, you'll have to start it via command line. 

Try the Docker CLI button on Kitematic (bottom left)

**Comment by bargulg** [comment]
@mchiang0610 that explains error 500, but not error 404

**Comment by mchiang0610** [comment]
@bargulg 404 means Kitematic had trouble pulling. (We shouldn't display a 404 error in the future. We put most errors into 404 state but doesn't print out the actual error. This will be corrected in the future builds.

**Comment by mchiang0610** [comment]
merging this with issue https://github.com/kitematic/kitematic/issues/626

**Comment by RVN-BR** [comment]
When I try to install MySQL I get a 404 in kitematic, and this on terminal:

```
bash-3.2$ docker pull mysql
latest: Pulling from mysql
a16207605ac6: Download complete 
a16207605ac6: Error downloading dependent layers 
ea994adb8f5e: Downloading [===========>                                       ] 1.801 MB/8.069 MB
b9a671861279: Download complete 
a58de78a6a7f: Download complete 
12724ce38086: Download complete 
6875e56d8c4c: Layer already being pulled by another client. Waiting. 
6bafb24bd6c1: Pulling fs layer 
6bafb24bd6c1: Download complete 
4d217892bcfe: Download complete 
b741ec2037b8: Download complete 
96f8e8f069ed: Download complete 
9eefddb060bc: Download complete 
9eefddb060bc: Error pulling image (latest) from mysql, Driver aufs failed to create image rootfs a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757: open /mnt/sda1/var/lib/docker/aufs/layers/c12da83ee7c184e35558b5cc8953b1f1035c8c232bda7ff0a4ba53ead3dad337: no such file or directory a4ba53ead3dad337: no such file or directory 
c12da83ee7c1: Download complete 
FATA[0021] Error pulling image (latest) from mysql, Driver aufs failed to create image rootfs a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757: open /mnt/sda1/var/lib/docker/aufs/layers/c12da83ee7c184e35558b5cc8953b1f1035c8c232bda7ff0a4ba53ead3dad337: no such file or directory 
bash-3.2$ 
```

docker pull redis works, I get "image is up to date", but when I try to install in kitematic I get server 500 as per below: 
![image](https://cloud.githubusercontent.com/assets/1218902/8211905/495f9d1a-14ef-11e5-8b56-8eceeca301c0.png)

any ideas?
