### ISSUE TITLE
Feature Request show favorite/starred repos

### ISSUE THREAD

**Issue by mainiak** [kitematic/kitematic#646]
Hi.

Now when we can configure Kitematic with Docker Hub account and start containers from our own images - could it be possible to list our starred images and have it as extra filter - beside all/recommended/my-repositories?

`https://hub.docker.com/u/<user>/starred`

**Comment by mchiang0610** [comment]
@mainiak Thanks for the feature request. 

Kitematic currently allows you to use your Docker Hub account and start containers from your own images.

**Comment by oliveirarodolfo** [comment]
:+1:

**Comment by cosmin-harangus** [comment]
:+1:

**Comment by ChrisPearce** [comment]
:+1:

**Comment by mchiang0610** [comment]
Moving into #1032
