### ISSUE TITLE
Official Mongo Image - no such container 404No Such image: mongo:latest (tag: latest)

### ISSUE THREAD

**Issue by melbourne2991** [kitematic/kitematic#648]
When trying to download the official mongodb image I get this error

`no such container 404No Such image: mongo:latest (tag: latest)`

Please not "404No", there is no space in between the two (very minor issue but worth mentioning).

**Comment by jeffdm** [comment]
Thanks for the issue,

Can you open a docker CLI and run `docker pull mongo`. What's the output of this?

**Comment by mchiang0610** [comment]
merging this with issue https://github.com/kitematic/kitematic/issues/626
