### ISSUE TITLE
Ubuntu container internet connection

### ISSUE THREAD

**Issue by alihalabyah** [kitematic/kitematic#651]
Ubuntu containers are not connected to the internet, for example I can't install packages using the `apt-get` or even `ping` a specific website, any ideas?

**Comment by mchiang0610** [comment]
@alihalabyah It's working for me. Are you connected through VPN / proxy? 

Which specific image did you try?  (I tested it on the official ubuntu-upstart image)

**Comment by marcosscriven** [comment]
I had a similar issue, and found this: https://github.com/boot2docker/boot2docker/issues/365

I thus had to ssh in directly to the ```boot2docker``` container, and start up the docker container manually,  with the ```--net=host``` option. After that I was able to access the network.
