### ISSUE TITLE
Dragging Kitematic window in Windows will cause the size of Kitematic to be larger than screen 

### ISSUE THREAD

**Issue by mchiang0610** [kitematic/kitematic#656]
Dragging window will cause the size of Kitematic Windows to be larger than screen. 

Tested on: Windows 8.1 Pro x64 
Device: Surface Pro 3 

Tested on: Windows 8 x64 
Device: Lenovo Yoga 

How to get out: press 'esc' button

**Comment by jeffdm** [comment]
Should be fixed in #659 but reopen if not
