### ISSUE TITLE
Install - hello world test failed

### ISSUE THREAD

**Issue by mfkilgore** [kitematic/kitematic#660]
OS X 10.10.3.  First install and test resulted in the following screen;

![image](https://cloud.githubusercontent.com/assets/586666/8240030/b6535c70-15b4-11e5-86b5-bcc60eb1b258.png)

No further information.  All I was trying to do was the simple hello world test as my first test.

**Comment by jeffdm** [comment]
If you open a Docker CLI (button in bottom left of Kitematic) and type `docker pull kitematic/hello-world-nginx` what does it show?

Thanks for the issue

**Comment by mfkilgore** [comment]
Seems to find it --

bash-3.2$ docker pull kitematic/hello-world-nginx
latest: Pulling from kitematic/hello-world-nginx

4a130ef69fe4: Pull complete 
c625faf066a6: Pull complete 
fc986ab7f61e: Pull complete 
72d0fb19f9f7: Pull complete 
0fa122787541: Pull complete 
e015d7d3cb2d: Pull complete 
5888470cecdf: Pull complete 
2e646a716c11: Pull complete 
97f9de5b4601: Pull complete 
99b3ac4b2ecc: Pull complete 
df781af04f51: Pull complete 
fc3c122e2641: Pull complete 
fa8fefb0eecc: Pull complete 
fa9a3bb406d3: Already exists 
Digest: sha256:ec0ca6dcb034916784c988b4f2432716e2e92b995ac606e080c7a54b52b87066
Status: Downloaded newer image for kitematic/hello-world-nginx:latest

**Comment by mfkilgore** [comment]
Once pulled from the command line it is loaded in UI correctly...  I have repeated the same error and correction by manual pull with a different repostitory

**Comment by jeffdm** [comment]
I see. Thanks. Are you logged into Docker Hub via Kitematic?

**Comment by mfkilgore** [comment]
I might not be, I had a problem when logging in initially and might have skipped that step.  Let me restart the app and try again to see if logging in fixes it.

**Comment by jeffdm** [comment]
@mfkilgore I don't think it will make a big difference. Interesting. It must be a bug in the downloading code. I'll take a look now.

Thanks for all the help

**Comment by jeffdm** [comment]
@mfkilgore one more question - if you reproduce the error and then open the logs (`cmd+alt+i`) are there any errors in the console?

**Comment by mfkilgore** [comment]
Not sure if this is what you are looking for command cmd+alt+i opens the dev tools  and the console has - 192.168.99.100
/Applications/Kitematic (Beta).app/Contents/Resources/app/node_modules/react/lib/warning.js:48 Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.


I did not see a way to open the logs

**Comment by jeffdm** [comment]
That's what I was looking for - though there's no obvious error there. Thanks @mfkilgore . I'm diving into the code.

**Comment by specialbrand** [comment]
I'm running into the same 404 error when creating the hello-world-nginx container and tried running the `docker pull` command but I'm getting the following:

bash-3.2$ docker pull kitematic/hello-world-nginx
Pulling repository kitematic/hello-world-nginx
FATA[0000] Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp: lookup index.docker.io on 127.0.0.54:53: read udp 127.0.0.54:53: connection refused

**Comment by TeckniX** [comment]
@specialbrand can you follow that link:
https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images

And show us what you see?

**Comment by specialbrand** [comment]
Here's the output when I load the link:

bash-3.2$ curl https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images
[{"checksum": "", "id": "a7b9e066970255b48c0bff37ef1a02a279e2719d7698b030223d613ae321dce9"}, {"checksum": "", "id": "4058ef6c015a4613547878fa20902aa56aabd0fcd18b91161c5bf72a0c2fe24a"}, {"checksum": "", "id": "3bfcaaf4d8787061834c3dbfc9b77266d5e623878abf4b0cd2415f48546cf1fb"}, {"checksum": "", "id": "bc424c43016dc6448bfccae19dd8907fef84319d00bf23bca590617b85f13f8f"}, {"checksum": "", "id": "0b5d7f6cba2303f89dd4cba2045b666beecde1320f0d11479cac81f7f84fe4d5"}, {"checksum": "", "id": "a43700d76143669c996155314fba457ab1551a70f3361fa69c96df7eec962be3"}, {"checksum": "", "id": "1b60d2e211aca503c63eabe2b6ecaa3cca2fd01929cd29017cb8da4e7ae58ea0"}, {"checksum": "", "id": "0aba4154f362add6abe6a7c99f38293a2fdd8fabe3ee41af71d7a120337a4bcd"}, {"checksum": "", "id": "f1e4b95ebfb99b3a0f7cda585fff1fd4eaf33567843b372509a2f2fc854fa80e"}, {"checksum": "", "id": "e81098a79be004cdba61b06dfddd5a660e85a9da7421f10ff2618f696da55178"}, {"checksum": "", "id": "a4a833076723bf23ad293fbe82aa4188ff8c360fcd4b9e362e27645d5c63cbd2"}, {"checksum": "", "id": "6b7fe669ab6a219767a2216d55520dde01b4dff054d83ce0562a09c29b9810fa"}, {"checksum": "", "id": "c9b01cd390e66fef39f6f0b7f987f1a7654d7df929c17aae7fb1e0989f03ccb7"}, {"checksum": "", "id": "8cac09617af241a1f3acd4ac35f2d969fa639b86b7d92710e6399b1b5906a8bf"}, {"checksum": "", "id": "569c9516192e1f96f669ab695b2edeeefa8a88f10291943f4e467a2823579d0b"}, {"checksum": "", "id": "780d9eacc4a901bf652596a75158e5eed080766f70b482d8199ecced0f2287a0"}, {"checksum": "", "id": "bf0030a6926ad5ddc80cdd2deece2cadadf75e969272878a2daa5b2745e5aa30"}, {"checksum": "", "id": "a008714f24c1705855a6fd81597d7b0847124b6fca296b0f8f4a813c92acd39c"}, {"checksum": "", "id": "565f9d5c809886e6bc57af26146070f0a6fb460d3bcbc54216abeacbf5fd5d0a"}, {"checksum": "", "id": "27a401359ee0da2164d3e5a8f0ad38350210c7dda5a0b070474791c1064948ae"}, {"checksum": "", "id": "31ad069430dd7fe855301b91f266acf9adb0b29bf5c6286ae6404e7854bd373a"}, {"checksum": "", "id": "fb36def7ade2875b990e89315badf66b207174dd9485e17f5eb382f8413063b7"}, {"checksum": "", "id": "7510eb19501f18a4160486ebbb1f33d643cefa9f798d0e8e59a7166b6f3a834d"}, {"checksum": "", "id": "f636c327f56786b3c63a5988bf6cfa39566fcb0b84bba8924dd6cb2e6f08bd2b"}, {"checksum": "", "id": "67cafa78ed91d67c11a8e955e43a488439aa24f359d3e639af3480cda83e7ca0"}, {"checksum": "", "id": "2c93cfcb7728d3b8e54ae75f4cbaeed90132c1b470086a87d1823fc16817a009"}, {"checksum": "", "id": "8c7153e6bfb65e72ee71bfefeed1ec9441588ff0f0acbb62f938516916f8d7c7"}, {"checksum": "", "id": "54a8dd495ac4839e8f83ca4700ee2deb770c1b7613183f1eb581fbb5d8b6b967"}, {"checksum": "", "id": "7160a50be38392d9dd4ca705e6bc3dff013053f05f6332d1c0b3a5b6ea99ba26"}, {"checksum": "", "id": "b8139569b2c3372a1990404f376b6b444520924faaa834517551182dcb49faae"}, {"checksum": "", "id": "3ea89873333c601f74c0f74b2aa17a47c613230be564a2ecc16dbdcd35c9dfd6"}, {"checksum": "", "id": "63f6a566b01c62c7acb2711f8ba4dcbe46fb81aaa3850228f27c137ede0393e2"}, {"checksum": "", "id": "3736041ed2d5cb3072b7c0c6cdd00ddf17b8b6665b5948d85dc9722fd2d80eaa"}, {"checksum": "", "id": "6098fdd12961b0a3a2d604c49825de55c120ce6f3ec214eb99857356b0106ec7"}, {"checksum": "", "id": "82d285b93fd715bd135fe1940a9884eb6c42d83a640706f8ae0959cf2c122ba3"}, {"checksum": "", "id": "919f5eea81b501a5b8f3452835761dc0ff008ad40a7c6c1b283aae50ae394206"}, {"checksum": "", "id": "dc45890ba71612fcecebdceabe6edabb33dec2b1d8bbdeb93cad75a90e8a49f6"}, {"checksum": "", "id": "ffcb0b68b32831675579cd7f183fcbb5d80ef88ce9cc65d72307920d1f1c63ca"}, {"checksum": "", "id": "a110a7121ae27f89512e97dfce168d9a7cb9e214acb8f7a6a6ada696dccf2486"}, {"checksum": "", "id": "8eaf0328bb145b5f41b7dca658839b57a5ed3c9661c53c760c5d660b1feceb8f"}, {"checksum": "", "id": "c1f4c6506449b61abb32029a56151e0d0abe902bd273bfa4328d7ea805ca2cf1"}, {"checksum": "", "id": "ecceb23b82f73340d8fa1a4afecdad3ccdb4cb177e3e59e698c3699d23baa146"}]

**Comment by TeckniX** [comment]
Is this from a similar session? Do you have a proxy? It looks like the ip mapping was previously different and now resolves properly - Try perhaps the image install again?

**Comment by specialbrand** [comment]
No proxy. I just updated the app and now I can see the message from within the app.

![kitematic 2015-06-23 14-45-07](https://cloud.githubusercontent.com/assets/104973/8318056/87ca97aa-19b6-11e5-9ad4-7bdc3a1e6c35.png)

**Comment by jeffdm** [comment]
Duplciate of #718 with instructions on how to fix it [there](https://github.com/kitematic/kitematic/issues/718#issuecomment-115489049)

**Comment by specialbrand** [comment]
That worked for me. Thank you!

**Comment by jeffdm** [comment]
Great to hear. Thanks!
