### ISSUE TITLE
tag list in 'My Repositories' is not functioning correctly

### ISSUE THREAD

**Issue by bruneaud** [kitematic/kitematic#670]
I have a private git repo and I cannot list the tags when clicking the tag icon on the repo in My Repositories.  It returns 'no tags found' but I have many.

**Comment by mchiang0610** [comment]
Thanks for reporting this. May I ask for the exact error message you have? 

Did you get a 404 no latest tag found? Is this on Mac or Windows?

**Comment by bruneaud** [comment]
I'm not seeing any 404, it actually tries to download the latest tag if I download the repo(there is no latest tag in mine), This is on Mac

**Comment by mchiang0610** [comment]
Thanks. We are aware of this issue now. It's a problem with the communication between Kitematic and the Docker Hub API. We are working on a fix

**Comment by jeffdm** [comment]
This should be fixed as of 0.7
