### ISSUE TITLE
[Windows] Error contacting docker hub

### ISSUE THREAD

**Issue by JohnyDays** [kitematic/kitematic#676]
![image](https://cloud.githubusercontent.com/assets/4540763/8265021/ad1f6d7c-16e7-11e5-8cbd-427bf957ed8e.png)

Is there some log I can contribute to this issue? Just tell me where to fetch it from.
Thanks a lot! I used this on my mac at work and it was awesome, just trying to get the same awesome experience on windows.

I am on Windows 7

**Comment by jeffdm** [comment]
Hi @JohnyDays , thanks for the issue!

Try clicking on the recommended filter again (top right). It's possible it just failed to fetch because of the network, etc.

Logs would be visible by pressing `cmd+alt+i` and then seeing the `Console` tab. I'm not sure if you'll see anything, though, as this 'error' is properly handled. Maybe check the `Network` tab.

**Comment by JohnyDays** [comment]
I tried all the buttons :worried: 
Pressing ctrl+alt+i opened the devtools, on which i see 4 syntax errors(although they are probably unrelated)
After restarting a few times and re-logging (also a few times) it started working. Sorry if this doesn't help you solve the issue! If this happens to someone else, I can reinstall to try to reproduce the issue and find a fix. Just ping me here. For now I'll close this

**Comment by dandanknight** [comment]
I had the same. Logging out and back in again fixed it for me.

**Comment by kagningemma** [comment]
Hello guys.  I  can pull docker containers on windows 7 OS but I 'm having the same issue as JohnyDays. @dandanknight , I can't login in kitematic using my docker hub credentials (see images below). i don't know what is the problem. 
The env setting were done automatically when i installed docker (please see image). 
i'm having the same isse when i launch docker from
cd Kitematic
Kitematic.exe

@jeffdm, Pressing ctrl+alt+i and clicking console displays the following error message "Uncaught SyntaxError: Unexpected token u" (Please, see images below)

Besides, when i run the ngnx container and when go to the localhost, i have an error message,

![image](https://user-images.githubusercontent.com/7575126/28715960-9c015602-73d5-11e7-97f8-b33a508d0f90.png)

![image](https://user-images.githubusercontent.com/7575126/28717102-5f404cc2-73db-11e7-9739-f7f1bc11db66.png)



![image](https://user-images.githubusercontent.com/7575126/28717067-3d513540-73db-11e7-80cc-ae4c76456e02.png)


![image](https://user-images.githubusercontent.com/7575126/28716475-736b5212-73d8-11e7-8f23-9b1400c05d1c.png)

**Comment by FrenchBen** [comment]
@kagningemma 
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.

**Comment by kagningemma** [comment]
FrenchBen, thanks. i had to reconfigure proxies of both docker and kitematic. 
then i logged in as you mentionned. it works !
