### ISSUE TITLE
[win alpha] setting environment variables

### ISSUE THREAD

**Issue by erikrs** [kitematic/kitematic#682]
on panel Settings/General/Environment Variables:

a new filled in variable key/value is not saved. Tried adding deleting lines, multiple lines.

**Comment by david-guenault** [comment]
confirmed here. The save button is inactive.

**Comment by zedtux** [comment]
I confirm the button is missing but the handle function exists.

**Comment by zedtux** [comment]
Ha ! I've found the commit [0f3300f](https://github.com/kitematic/kitematic/commit/0f3300f992c2dd9433263b02e7f8bc8e14f72e15) which is adding the button again. It should solve this issue.

**Comment by jeffdm** [comment]
Fixed in 0.7.2. Download via kitematic.com/download or via the github release https://github.com/kitematic/kitematic/releases
