### ISSUE TITLE
How do I name and link images

### ISSUE THREAD

**Issue by mfkilgore** [kitematic/kitematic#683]
I would like to install 2 or more images, name each image and then link them?  I did not see an example in the docs but might have missed it.  

For example the docker command for this might look like - docker run -i -t --name hdfs sequenceiq/hadoop-docker:2.4.1 /etc/bootstrap.sh -bash

and then link to named image hdfs - docker run -i -t --name mfktest --link hdfs:hdfs mfkilgore/myimage1.0

myimage1.0 needs to resolve hdfs.

**Comment by mfkilgore** [comment]
I see that this is a feature request --- Feature request - support container linking #14 already and looks like it is not possible today.

**Comment by mchiang0610** [comment]
@mfkilgore You can manually use docker commands through Kitematic by pressing the Docker CLI button on the bottom left of the Kitematic interface for now.

**Comment by mfkilgore** [comment]
@mchiang0610 Thanks for the reminder, I keep forgetting that it is easy to open an integrated shell.  Of course if will be great when all of the options are in the GUI too...
