### ISSUE TITLE
Kitematic keeps waiting for downloading to finish - after sleep wake up 

### ISSUE THREAD

**Issue by mohdaliiqbal** [kitematic/kitematic#684]
My machine while downloading image went to sleep - after wake up Kitematic keeps saying downloading, i killed the process, shutdown vm restarted kitematic but still its saying -- connecting to dockerhub, or waiting for another download to finish and stays like this forever. Downloading tag next to my image stays as is but nothing is happening apparently. 

I had to delete the VM to make it go back to a workable state. This means downloading all my images all over again :cry: :disappointed:

**Comment by mchiang0610** [comment]
@mohdaliiqbal Sorry about this. Was this on Mac or Windows? 

Did your images finish downloading after deleting the VM and running it again?

**Comment by mohdaliiqbal** [comment]
MacOS X 10.9.5, yes it works fine after VM purging

**Comment by mchiang0610** [comment]
@mohdaliiqbal Thanks. Do you know which version of Kitematic this happened on? There was an earlier version that had a bug, and we fixed it in 0.7.2
