### ISSUE TITLE
[win alpha] timeout when behind proxy

### ISSUE THREAD

**Issue by ojacques** [kitematic/kitematic#685]
![image](https://cloud.githubusercontent.com/assets/5385290/8268463/8f75321c-173b-11e5-8995-211c5496e8d4.png)

I'm behind a corporate web proxy, with http_proxy and https_proxy variable set.
I get timeout errors when installing Kitematic.

**Comment by mchiang0610** [comment]
@ojacques Thanks for reporting. I believe the proxy issue is a known issue with Docker machine. 

cc @nathanleclaire @ehazlett

**Comment by childnode** [comment]
:information_desk_person: **partial Workaround**:

1. Clone your boot2docker machine to "kitematic" if available ;)
2. do
  * copy ssh keys from `%USERPROFILE%\.ssh\id_boot2docker` to `%USERPROFILE%\.docker\machine\machines\kitematic\id_rsa`
   * copy keys / certs from `%USERPROFILE%\.boot2docker\certs\boot2docker-vm` to `%USERPROFILE%\.docker\machine\certs`
   * make a second copy of them to `%USERPROFILE%\.docker\machine\machines\kitematic`
   * ~~delete corrupt machine config: `%USERPROFILE%\.docker\machine\machines\kitematic`~~
3. fix corrupt config: change ssh port from 0 to what is the forwarding local port for your NAT device in the cloned virtualBox device
(on clone, virtualbox will auto-remap this from boot2docker default 2022 to a new highport)
4. "retry setup"

you might test the connection yourself by
`%LOCALAPPDATA%\Kitematic\app-0.7.0\resources\resources>docker-machine ssh kitematic`

=> :warning: still not working, it's rebooting then hanging up at 99%.

:beetle:  not related to machine but on kitematic: => errorhandling
* not created / asked for id_rsa if machine is already available
* non-exisiting certificates might be auto-copied from default certs folder if missing in machine folder
* fixing SSH Port in config needed

:question:  **Related / perhaps same:** Kitematic has bundled boot2docker iso in `%LOCALAPPDATA%\Kitematic\app-0.7.0\resources\resources\boot2docker.iso` but above docker-machine command seems not to find this image, so on console you'll see the message ``

:beetle: :information_source:  corrupt machine config after failed init:
see: SSHPort:0
```
{
  "DriverName":"virtualbox",
  "Driver":{
    "IPAddress":"",
    "CPU":1,
    "MachineName":"kitematic",
    "SSHUser":"docker",
    "SSHPort":0,
    "Memory":2048,
    "DiskSize":20000,
    "Boot2DockerURL":"",
    "CaCertPath":"D:\\Users\\Marcel\\.docker\\machine\\certs\\ca.pem",
    "PrivateKeyPath":"D:\\Users\\Marcel\\.docker\\machine\\certs\\ca-key.pem",
    "SwarmMaster":false,
    "SwarmHost":"tcp://0.0.0.0:3376",
    "SwarmDiscovery":"",
    "Boot2DockerImportVM":""
  },
  "StorePath":"D:\\Users\\Marcel\\.docker\\machine\\machines\\kitematic",
  "HostOptions":{
    "Driver":"",
    "Memory":0,
    "Disk":0,
    "EngineOptions":{
      "ArbitraryFlags":[

      ],
      "Dns":null,
      "GraphDir":"",
      "Ipv6":false,
      "InsecureRegistry":[

      ],
      "Labels":[

      ],
      "LogLevel":"",
      "StorageDriver":"",
      "SelinuxEnabled":false,
      "TlsCaCert":"",
      "TlsCert":"",
      "TlsKey":"",
      "TlsVerify":true,
      "RegistryMirror":[

      ],
      "InstallURL":"https://get.docker.com"
    },
    "SwarmOptions":{
      "IsSwarm":false,
      "Address":"",
      "Discovery":"",
      "Master":false,
      "Host":"tcp://0.0.0.0:3376",
      "Image":"swarm:latest",
      "Strategy":"spread",
      "Heartbeat":0,
      "Overcommit":0,
      "TlsCaCert":"",
      "TlsCert":"",
      "TlsKey":"",
      "TlsVerify":false,
      "ArbitraryFlags":[

      ]
    },
    "AuthOptions":{
      "StorePath":"",
      "CaCertPath":"D:\\Users\\Marcel\\.docker\\machine\\certs\\ca.pem",
      "CaCertRemotePath":"",
      "ServerCertPath":"D:\\Users\\Marcel\\.docker\\machine\\machines\\kitematic\\server.pem",
      "ServerKeyPath":"D:\\Users\\Marcel\\.docker\\machine\\machines\\kitematic\\server-key.pem",
      "ClientKeyPath":"D:\\Users\\Marcel\\.docker\\machine\\certs\\key.pem",
      "ServerCertRemotePath":"",
      "ServerKeyRemotePath":"",
      "PrivateKeyPath":"D:\\Users\\Marcel\\.docker\\machine\\certs\\ca-key.pem",
      "ClientCertPath":"D:\\Users\\Marcel\\.docker\\machine\\certs\\cert.pem"
    }
  },
  "SwarmHost":"",
  "SwarmMaster":false,
  "SwarmDiscovery":"",
  "CaCertPath":"",
  "PrivateKeyPath":"",
  "ServerCertPath":"",
  "ServerKeyPath":"",
  "ClientCertPath":"",
  "ClientKeyPath":""
}
```

**Comment by hurtz** [comment]
Happy to report the workaround is working for me. I only had to complete steps 1, 2, 4, and 5.

Thanks!!

**Comment by ojacques** [comment]
@childnode - thanks for this greatly detailed answer. I wonder what a more permanent fix would look like. Any idea?

**Comment by arneluehrs** [comment]
Well, in this setting the problem is also fixable by explicitly setting http_proxy, https_proxy nad above all the no_proxy environment variable (tested with @ojacques setup)  The problem then moves to the next step. Inside the docker engine host we need to set the proxy again.
And that seems indeed like the problem mentioned in the docker-machine.

So you can use the docker-machine commands to get to your image.
docker-machine ssh kitematic
and by adding the env variables to /var/lib/docker/profile you get back to a fully working setup.

This however is unsatisfactory as you need to redo that setup at every time you destroy your docker engine (i.e. you rebuild your VM).

So passing the env variables from the hosting environment down to the Docker host machine is the best way to go.
It is to be tested if it would have to be propagated even furter into the containers (normally yes) or if that can be handled by an -e option in the docker run of the container.

**Comment by ofostier** [comment]
Yeaah !! You save my life !!
Thank you.

For information I don't have and I've not put this line in the profile file
>> EXTRA_ARGS=' --label provider=virtualbox --insecure-registry :443 ' 

Bye

**Comment by ehazlett** [comment]
@arneluehrs you no longer need to export those manually for the engine.  you can use the `--engine-env` command during create of machine which will set those for you.  for example `--engine-env HTTP_PROXY=http://1.2.3.4:8080`

**Comment by nickho** [comment]
What would be nice now that https://github.com/docker/machine/pull/1497 is in official release, is a screen to configure the proxy parameters in Kitematic when installing. Otherwise this issue will still exist, we just have better workarounds :D.

**Comment by ofostier** [comment]
@ehazlett , thanks for this. It's very helpfull.

@nickho Agree with you ... Just one week to find the right answer ...

**Comment by mchiang0610** [comment]
Merging with #1031 and #1029

**Comment by FugDev** [comment]
https://github.com/kitematic/kitematic/issues/1031#issuecomment-139749024

**Comment by mchiang0610** [comment]
If anyone still has problems with this on Mac or Windows 10+, please contact me at mchiang@docker.com.

We are working on something to help address this issue.

**Comment by byteshiva** [comment]
I'm still having the same issue. I'm unable to login to hub docker via kitematic BETA mac application

```
$docker-machine ssh default
$sudo vi /var/lib/boot2docker/profile

EXTRA_ARGS='
--label provider=virtualbox --insecure-registry :443

'
PROXY='http://proxt-server.com:8080'
export http_proxy=$PROXY
export HTTP_PROXY=$PROXY
export HTTPS_PROXY=$PROXY
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem

$docker-machine stop default
$docker-machine start default
Starting "default"...
(default) Check network to re-create if needed...
(default) Waiting for an IP...
Machine "default" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
$docker-machine env


```

![image](https://cloud.githubusercontent.com/assets/10637299/14008315/777dd43a-f1a5-11e5-8238-78eb1497bb4e.png)
