### ISSUE TITLE
Can't set environment variable (windows)

### ISSUE THREAD

**Issue by wdmtech** [kitematic/kitematic#689]
Trying to apply an environment variable (in this case) to official MySQL container fails when clicking save/changing tab:

1. Apply environment variable

![image](https://cloud.githubusercontent.com/assets/7282262/8271371/9cae4b96-180b-11e5-9808-6cf7d160d20a.png)

2. Save, change tab or leave the General tab by any other means
3. Go back to General tab
4. Environment variable is lost

**Comment by jeffdm** [comment]
@wdmtech thanks for the issue.

This should be fixed in 0.7.2 available at kitematic.com/download or on our releases page: https://github.com/kitematic/kitematic/releases
