### ISSUE TITLE
Version 0.27.2 shown when using one click upgrade (v0.6.3-Mac -> v0.7.2-Mac)

### ISSUE THREAD

**Issue by nooproblem** [kitematic/kitematic#691]
Hi,

I have just updated from Kitematic-0.6.3-Mac ->  Kitematic-0.7.2-Mac using the one click upgrade button.

The version now being reported is Version 0.27.2 when using the "About Kitematic" button.

I have not managed to reproduce this bug yet.

![screen shot 2015-06-21 at 20 57 01](https://cloud.githubusercontent.com/assets/12471443/8273193/f33c2b38-1859-11e5-84a6-5cd476d55b3d.png)

**Comment by TeckniX** [comment]
Yup the incorrect version was previously being displayed, where the version of the engine behind Kitematic (electron), was displayed instead of the proper Kitematic version.

**Comment by nooproblem** [comment]
Resolved in v0.7.4-Mac, thanks guys!
