### ISSUE TITLE
Issues and Enhancements with Kitematic Windows

### ISSUE THREAD

**Issue by smakam** [kitematic/kitematic#695]
hi
I recently tried out Kitematic Windows Alpha version. Thanks for the nice product. Overall, it worked well. 
Following are some issues I faced and some enhancement requests. Sorry for opening 1 issue for tracking multiple items. 

Installation issue:
I got the error "Error creating machine, parsing "128": value out of range". To workaround this, I had to remove host-only interface created in Virtualbox and retry the install. I had similar issues when I installed boot2docker earlier.

Issues:
Addition of environment variables not working. Even though I was able to add, I could not save them.
Minor point. To go back to home screen,  the only option I see is to select "New", good to have a Home button. 

Enhancements:
Not able to remap Container ports to host machine.
Container environment variables like ip address will be good to display
Will be good to give access to linux host where container is run like exec option where Container shell is given.
Creation of Multi-container application is not possible currently. Even a simple approach using environment variables, container linking is not working. 
Need an option to have multiple hosts where Containers can be deployed. Integration with Docker machine can achieve this.
Integrate with docker swarm and compose
Kitematic for Linux would be useful.

I have seen few other folks asking for similar enhancement requests. 

Thanks
Sreenivas

**Comment by kireevco** [comment]
@smakam I would suggest decomposing this ticket to multiple smaller ones.

**Comment by smakam** [comment]
@kireevco 
Do you see any duplicates for issues I reported from other issues reported earlier?
Any grouping I can do, otherwise, I need to open 8-9 issues...

**Comment by kireevco** [comment]
@smakam if you want these issues to be addressed you need to open an ticket for every issue. 
Otherwise it is just a blob that will never be worked on. IMHO.

**Comment by mchiang0610** [comment]
@smakam Are you still having problem with the install? Merging with #1029
