### ISSUE TITLE
Failed to start Kitematic in 0.7.2

### ISSUE THREAD

**Issue by wzymaster** [kitematic/kitematic#698]
I keep experiencing the failure or hanging of starting Kitematic 0.6.6 on my Mac. After upgrade to 0.7.2, it's still the same issue.  In fact, I am using VirtualBox 4.3.28r and tries a few times after clean all VMs, but get no luck.

**Comment by TeckniX** [comment]
If you user VirtualBox, do you see the image created there? Any screenshot of the error displayed by Kitematic

**Comment by wzymaster** [comment]
yes, I do see VM created and running and screenshots are attached.
![screen shot 2015-06-22 at 4 54 00 pm](https://cloud.githubusercontent.com/assets/2967108/8292735/42f933dc-18ff-11e5-8bf5-3bf986b4b809.png)
![screen shot 2015-06-22 at 4 54 07 pm](https://cloud.githubusercontent.com/assets/2967108/8292734/42f6f0cc-18ff-11e5-8e5a-7bcf091813a4.png)

**Comment by TeckniX** [comment]
If you stop the VM and start it, do you get the proper VM started and see the whale?

![dev](https://cloud.githubusercontent.com/assets/33699/8293002/98752590-18e7-11e5-9486-7f9a826a8e23.png)

**Comment by wzymaster** [comment]
Here is what I get .
![screen shot 2015-06-22 at 5 43 35 pm](https://cloud.githubusercontent.com/assets/2967108/8293832/2f7c4112-1906-11e5-860d-9deb8e6ca7ec.png)

**Comment by wzymaster** [comment]
Here is error from running Kitematic.
![screen shot 2015-06-22 at 5 44 50 pm](https://cloud.githubusercontent.com/assets/2967108/8293855/576bcaf8-1906-11e5-876c-f8e80402f377.png)

**Comment by TeckniX** [comment]
2 questions:
- How much memory (ram) do you have?
- Do you have enough free space on your device?

**Comment by wzymaster** [comment]
Unfortunately, I even tried Boot2Docker shell and IP isn't pingable ! The below is error from boot2docker :  

```An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/version: dial tcp 192.168.59.103:2376: i/o timeout```

In fact, I experienced the similar issue weeks ago however it's resolved itself by rebooting my Mac. For now, nothing works.

I have tried to totally remove vagrant and reinstall it. But it's still the same issue.

**Comment by wzymaster** [comment]
Hi, admin

     I have 16 GB RAM on my Mac + 500 GB HD.  I doubt if the available space or memory is the cause.  In fact, I ever experienced such Vagrant VM issue while running Boot2docker or Kinematic . Here is error which I get :

bash-3.2$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/version: dial tcp 192.168.59.103:2376: i/o timeout

  Your earliest response is highly appreciated !


best regards,
Leo Wu

==============================================================
"Minds are like parachutes, they only function when open."  by Thomas R. Dewar

**Comment by erwin16** [comment]
same issue as wzymaster ...

**Comment by mchiang0610** [comment]
Should be fixed in Docker Toolbox. Please give it a try, if problem persists, it may be a docker machine problem .
