### ISSUE TITLE
[OSX] No obvious way to upgrade docker server in VM

### ISSUE THREAD

**Issue by doxxx** [kitematic/kitematic#701]
I just upgraded Kitematic to v0.27.2 and apparently this included a new version of docker. When I tried to run docker comands from the terminal started by Kitematic, it gave me an error:

    Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)

I had to run VirtualBox, delete the VM and restart Kitematic to get it to recreate the VM with the right version of docker server.

**Comment by MrOrz** [comment]
Just bumped into this issue and deleting the VM works. This issue saved my day! Thanks @doxxx .

Just to note that all previously installed images would be removed as well, which is fine for me since those images are just for tryout purpose.
