### ISSUE TITLE
trying to pull repository library/oraclelinux: "Account is not Active"

### ISSUE THREAD

**Issue by jonay1** [kitematic/kitematic#703]
trying to pull repository library/oraclelinux: "Account is not Active"

**Comment by TeckniX** [comment]
Not logged in, I was able to pull the image and get it up and running.

![oraclelinux](https://cloud.githubusercontent.com/assets/33699/8314153/74d86740-199c-11e5-84f3-1c52582182b8.png)

**Comment by jeffdm** [comment]
@jonay1 are you logged in to DockerHub via Kitematic?

**Comment by jeffdm** [comment]
Closing in favor of #789 as the discussion is continuing there. Stay tuned!
