### ISSUE TITLE
Failed to download my docker image in Kitematic 0.7.2

### ISSUE THREAD

**Issue by wzymaster** [kitematic/kitematic#704]
I am trying to create a new Docker container from my docker image in Docker hub,  "bigdatauniversity/spark:latest".  However it failed with downloading image , and error like the following :  

```Error pulling image (latest) from bigdatauniversity/spark, Untar re-exec error: exit status 1: output: unexpected EOF```

Can you help with it ?

**Comment by patrick-mota** [comment]
Same with jenkins
`Error pulling image (latest) from jenkins, Untar re-exec error: exit status 1: output: unexpected EOF`

**Comment by mchiang0610** [comment]
should be fixed in latest versions of Kitematic (installed through Docker toolbox)
