### ISSUE TITLE
proxy settings

### ISSUE THREAD

**Issue by elofland** [kitematic/kitematic#705]
app doesn't seem to honor system wide proxy settings

**Comment by JrCs** [comment]
+1

**Comment by TempleCloud** [comment]
+1

**Comment by rmusiy** [comment]
+1

**Comment by fezfez** [comment]
+1

**Comment by thebignet** [comment]
+1

**Comment by gvlx** [comment]
Release [v0.8.0-rc1](https://github.com/kitematic/kitematic/releases/tag/v0.8.0-rc1) already includes latest release of docker-machine for windows [v0.4.0-rc1](https://github.com/docker/machine/releases/tag/v0.4.0-rc1), however, there is no way to configure the proxy to be used.

**Comment by rafiq-ahmed** [comment]
+1

**Comment by todorez** [comment]
+1

**Comment by doronl** [comment]
+1

**Comment by sl2** [comment]
+1

**Comment by CL0SeY** [comment]
+1

**Comment by gvlx** [comment]
Issue still remains in [v0.8.3](https://github.com/kitematic/kitematic/releases/tag/v0.8.3).

I have been able to directly create a boot2docker instance which can use the system proxy settings without problems.

Issues [685](https://github.com/kitematic/kitematic/issues/685) and [872](https://github.com/kitematic/kitematic/issues/872) still apply.

**Comment by stritti** [comment]
+1

**Comment by mchiang0610** [comment]
Merging with #1031

**Comment by agsola** [comment]
same problem here.

**Comment by mchiang0610** [comment]
If anyone still has problems with this on Mac or Windows 10+, please contact me at mchiang@docker.com.

We are working on something to help address this issue.
