### ISSUE TITLE
Kitematic 0.7.2 for Windows - can not install

### ISSUE THREAD

**Issue by Spirit328** [kitematic/kitematic#706]
Hey Guys,

I was just trying to install the kitematic version 0.7.2 for Windows on Windows 8.1.

It started, but failes at about 22% with the following error message:
Setup Error
We're Sorry!
There seems to have been an unexpected error with Kitematic (+1)
C:\Users\tmichels\AppData\Local\Kitematic\app-0.7.2\resources\resources\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 kitematic returned non zero exit code. Stderr: Error creating machine. Machine kitematic already exists. You will want to check the  provider to make sure the machine and associated resources were properly removed.

Although the virtualbox is defently NOT present, because I deleted it manually. 100% defently positivly sure.

**Comment by leafmulch** [comment]
I just fixed same issue by removing kitematic directory out of ~\.docker\machine\machines\kitematic

**Comment by Spirit328** [comment]
Thanks to leafmulch's comment, I was able to bring up kitematic on my windoze box.
It is working fine and smoothly. Great job and thanks a lot.
I wouldn't have guessed to search in that corner for a solution. 

We can close this issue now!

**Comment by mattjonesorg** [comment]
I ran into this issue too.  I had this issue also.  Finding a github comment is not the resolution that is best for the product.  When you click retry, it should remove this directory.

**Comment by Spirit328** [comment]
Hi Matt,

unfortunately it didn't help to click on "retry". I tried this .... many
times ;-)

But now, with the version Kitematic 0.7.4 for Windows this issue seems
to be solved.

Cheers
Thorsten

Am 10.07.2015 um 04:26 schrieb Matt Jones:

**Comment by mattjonesorg** [comment]
I'm having the same issue with 0.7.4, and I've deleted the folder ~.docker\machine\machines\kitematic.  I think this issue should be reopened.

**Comment by leafmulch** [comment]
Matt do you have other machines and certs already under ~/.docker?

It might be worth just moving the whole .docker directory to one side and try again. I sense that boot2docker, docker-machine, old kitematic and current kitematic aren't working well together.
