### ISSUE TITLE
A failed docker build doesn't show the image in the container until a new container is added.

### ISSUE THREAD

**Issue by JefStat** [kitematic/kitematic#708]
From the Kitematic docker cli 
- Build a container that will fail ie. add a copy cmd that is point to a file that doesn't exist.
- Run `docker ps -a` and notice  there is a container not running that is not listed in kitematic.

**Comment by TeckniX** [comment]
If the container failed to build, then it simply doesn't get created.

**Comment by JefStat** [comment]
Ah in my script to build and run it ignores the failure follows through and still tries to run. Where I end up with a stopped container not reflected in kitematic.

**Comment by jeffdm** [comment]
Kitematic shows a list of _containers_, not images. If the image failed to build then no container will be displayed in either `docker ps` or Kitematic.

For images, see the `docker images` command. Closing this for now
