### ISSUE TITLE
Impossible download

### ISSUE THREAD

**Issue by TemoKun** [kitematic/kitematic#712]
Hello Docker.
First of all, I'm a new-comer to your Docker and tried out Kitematic just a few minutes ago.
I've noticed when trying to download images that it stops and it doesn't allow me, confirming an error .
Here's what the error pointed:
"Error pulling image (latest) from kitematic/hello-world-nginx, Mktemp failed: mkdir /mnt/sda1/var/lib/docker/graph/_tmp/69980e5074aa82d3329fadaaea51ccc38141f379d2aca21f55e75d97cb09c365: read-only file system"

**Comment by jeffdm** [comment]
Thanks for the issue! Closing in favor of #714
