### ISSUE TITLE
Kitematic 0.7.3, DNS Unable to resolve and download image

### ISSUE THREAD

**Issue by schrepfler** [kitematic/kitematic#713]
Get https://index.docker.io/v1/repositories/itszero/zipkin-web/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects

**Comment by karcaw** [comment]
same for me.  0.7.2 works fine..

**Comment by jeffdm** [comment]
This is a duplicate of #718, merging. There are instructions on how to fix it manually [there](https://github.com/kitematic/kitematic/issues/718#issuecomment-115489049)
