### ISSUE TITLE
Mktemp failed: read-only file system

### ISSUE THREAD

**Issue by 2urn** [kitematic/kitematic#714]
Hello,

I am new to docker. When I try to install WordPress I get this error:

Error pulling image (latest) from wordpress, Mktemp failed: mkdir /mnt/sda1/var/lib/docker/graph/_tmp/11a47324cabe999bd089bb6e5277db87fcd5ffd6b3aa2824cfda52e3a81c82ce: read-only file system

**Comment by jeffdm** [comment]
Does this work on CLI? Click on the `Docker CLI` button and then type:

```
docker run -dP wordpress
```
