### ISSUE TITLE
fails if latest is not used as the tag

### ISSUE THREAD

**Issue by zevmo** [kitematic/kitematic#715]
On images that don't have a "latest" tag, the create function fails.

**Comment by psychemedia** [comment]
I just noticed this too.

I also tried explicitly searching for an image with the :TAGNAME qualifier and this failed to find the parent image? (that may be a dockerhub search issue though?)

**Comment by mchiang0610** [comment]
@zevmo That is the current behavior of Kitematic. I totally agree that this needs to be changed.

**Comment by mchiang0610** [comment]
closing this in favor of the older feature request. https://github.com/kitematic/kitematic/issues/572
