### ISSUE TITLE
Kitematic can't see docker images from Boot2Docker

### ISSUE THREAD

**Issue by commanderfun** [kitematic/kitematic#719]
Does Kitematic play well with Boot2Docker?  Kitematic can't find the images that I previously pulled or built with Boot2Docker.

**Comment by mchiang0610** [comment]
@commanderfun Hi, Kitematic uses the new Docker-machine instead of boot2docker. This is the reason why Kitematic can't find the images you've previously pulled. 

Thanks! 
mchiang@docker.com

**Comment by commanderfun** [comment]
@mchiang0610 Thanks for the info.  Here's a few helpful links if others have this issue:

https://github.com/boot2docker/boot2docker-cli#pending-deprecation

http://www.reddit.com/r/docker/comments/38l5as/osx_tip_using_dockermachine_vs_boot2docker/
