### ISSUE TITLE
gluu

### ISSUE THREAD

**Issue by rashidniazi** [kitematic/kitematic#720]
Hi 

I was interested in checking out the Gluu Docker cluster. However, when downloading it I recieve this error message. We're Sorry. There seem to be an error: Tag latest not found in repository nekbab/gluu. 

Not sure if this is expected or not...

**Comment by mchiang0610** [comment]
@rashidniazi Which exact docker hub image is this? Does it have the latest tag?

**Comment by rashidniazi** [comment]
Ouf not sure how to answer this. The image name when searching is "gluu" nekbab.

**Comment by jeffdm** [comment]
This seems to be a duplicate of #720

Closing for now

**Comment by fcjbispo** [comment]
inspectig the existing tags in https://hub.docker.com/r/nekbab/gluu/tags/ i have pulled the v6 tag by issuing  docker pull nekbab/gluu:v6

But it provides no service when the image is started. It seems to be an empty centOS 6.5 image...
