### ISSUE TITLE
Can't configure ports in Kitematic 0.7.2

### ISSUE THREAD

**Issue by wzymaster** [kitematic/kitematic#723]
After download and update to 0.7.2 , I can't configure ports in Settings tab. In fact, the 'Configuring Port' page isn't editable at all.

Please advise it and screenshot is attached.
![screen shot 2015-06-25 at 6 04 47 pm](https://cloud.githubusercontent.com/assets/2967108/8366630/94d921a0-1b64-11e5-9089-695ef643e613.png)

**Comment by mchiang0610** [comment]
@wzymaster Thanks for this issue. We have a PR open for this feature that we are reviewing right now with this feature. Will let you know when it's merged

**Comment by jeffdm** [comment]
This was a bug in 0.7.3 that occurred after restarting a container. It's been fixed in 0.7.4.

Closing for now

**Comment by jeffdm** [comment]
Also, for the editing part, we're tracking that feature in issue #344.

Thanks again!
