### ISSUE TITLE
Pull Private repository is failing

### ISSUE THREAD

**Issue by sanaras** [kitematic/kitematic#724]

**Comment by mchiang0610** [comment]
@sanaras Thanks for reporting. I will look into this

**Comment by mchiang0610** [comment]
@sanaras It's working on my side. May I ask what error(s) you are seeing? 

Thanks

**Comment by sanaras** [comment]
I'm getting
No such container 404
no such id: spautobots

**Comment by mchiang0610** [comment]
@sanaras Thanks. Is this on Windows or Mac?

**Comment by sanaras** [comment]
Its on Mac OS X Yosemite v10.10.3

**Comment by jeffdm** [comment]
Are you running the latest version of Kitematic?

**Comment by mchiang0610** [comment]
Merging with #1030
