### ISSUE TITLE
i need root permissions to changing mirror..

### ISSUE THREAD

**Issue by jik1992** [kitematic/kitematic#725]
Hi,  i can't link official registry.hub.  because of GFW..
and i own one mirror link to replace it. 
but  in docker cli ,     don't know password..

```
echo "DOCKER_OPTS=\"\$DOCKER_OPTS --registry-mirror=http://xxxx.m.daocloud.io\"" | sudo tee -a /etc/default/docker
sudo service docker restart
```
i need  sudo permissions ..  so where i can know vm password on root

**Comment by leafmulch** [comment]
If you already have access to the kitematic vm then all you need to do is type sudo su for a root shell and it doesn't prompt for a password.

docker@kitematic:/etc/default$ echo "DOCKER_OPTS=\"\$DOCKER_OPTS --registry-mirror=http://xxxx.m.daocloud.io\"" | sudo tee -a /etc/default/docker
DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=http://xxxx.m.daocloud.io"
docker@kitematic:/etc/default$ ls -l docker
-rw-r--r--    1 root     root            71 Jun 26 08:54 docker
docker@kitematic:/etc/default$ cat docker
DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=http://xxxx.m.daocloud.io"
docker@kitematic:/etc/default$

**Comment by jik1992** [comment]
you are right.. be careless,  we need  docker-machine ssh dev  to link boot2docker.

😅

**Comment by leafmulch** [comment]
Sorry - I don't understand if that helped or... You can list the kitematic vm if you go to the docker cli (bottom left) and run docker-machine ls. I had some headaches myself when I installed kitematic, as I already had boot2docker and docker-machine installed the latter of which seemed to conflict.

**Comment by jeffdm** [comment]
This is a `boot2docker` issue not Kitematic, so I'm closing this for now :smiley: 

The vm password should be `tcuser` as per [this](https://github.com/boot2docker/boot2docker/blob/master/README.md).

**Comment by yank1** [comment]
HI @jik1992 . I'm DaoCloud's enginner. Very glad to see you are using DaoCloud Mirror.
Now, we has a solution to config mirror in kitematic at [DaoCloud Dashboard](http://https://dashboard.daocloud.io/mirror)

Or. You can use this script to config mirror.

	docker-machine ssh dev
	sudo sed -i "s|EXTRA_ARGS='|EXTRA_ARGS='--registry-mirror=http://[your-mirror].m.daocloud.io |g" /var/lib/boot2docker/profile
	exit
	docker-machine restart dev

**Comment by mckelvin** [comment]
@yank1 :+1:
