### ISSUE TITLE
Can't access local file in virtual machine

### ISSUE THREAD

**Issue by tobegit3hub** [kitematic/kitematic#726]
We want to access the `/var/run/docker.sock` in kitematic cli. All these files are in virtual machine from virtualbox but how can we access them?

**Comment by leafmulch** [comment]
You need to login to the VM. docker-machine ssh kitematic and access via there. Other docker client queries from the host client should just go over tcp with the certs created at installation time.

**Comment by TeckniX** [comment]
@leafmulch has almost the proper command - The VM created is actually labelled `dev` so the proper command is: `docker-machine ssh dev`

**Comment by leafmulch** [comment]
for vanilla docker-machine setups maybe, but I got a kitematic out of the box here:-

PS C:\Users\xxxxx\AppData\Local\Kitematic\app-0.7.3> docker-machine ls
NAME        ACTIVE   DRIVER       STATE     URL                         SWARM
kitematic   *        virtualbox   Running   tcp://192.168.99.103:2376

**Comment by TeckniX** [comment]
@leafmulch Yup in Windows, the VM created is labelled 'kitematic' otherwise it's 'dev'. 
I guess we were both right :P 

@tobegit3hub - To SSH into the proper machine:
`docker-machine ls`
Should return Either `kitematic` or `dev`
`docker-machine ssh <above-name>`

**Comment by leafmulch** [comment]
There's no like/favourite on your comment, so...

Ah - didn't think that mac would be different! Good to know.

**Comment by jeffdm** [comment]
Seems like this issue is ready to be closed :), but feel free to re-open if otherwise.

**Comment by tobegit3hub** [comment]
Yes, it works. Thanks all @leafmulch and @TeckniX :+1:
