### ISSUE TITLE
Docker client cannot connect after Kitematic installation (mac)

### ISSUE THREAD

**Issue by shaunc** [kitematic/kitematic#730]
I had an older docker installation. I upgraded it via boot2docker upgrade.

I then installed Kitematic. I could run the Kitematic nginx-hello-world example. However, when I do "docker ps" I get the error:

> An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/version: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103

I tried to regenerate config via:

    boot2docker shellinit
    boot2docker restart

But still the same error. What has happened and how should I correct? 

Thanks!

**EDIT**: the docker cli installed by kitematic in

> /Volumes/Macintosh_HD/Users/shauncutts/Downloads/Kitematic (Beta) 2.app/Contents/Resources/resources

works... however the one in /usr/local/bin/docker doesn't work. However, they both list the same build (0baf609) and seem to have same environment - vis:

bash-3.2$ env | grep DOCKER
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/shauncutts/.docker/machine/machines/dev

(NB -- in fact, "usr/local version" had 

> DOCKER_CERT_PATH=/Users/shauncutts/.boot2docker/certs/boot2docker-vm

 but changing didn't effect error.) 
Is there some other config I'm missing? Also, why didn't "global"  boot2docker shellinit rewrite the certificates so that then the Kitematic version would break not the /usr/local version?

**Comment by Chekote** [comment]
This is a boot2docker issue. It usually occurs whenever the boot2docker VM is restarted. There's no official fix for it yet, but you can work around the issue by adding the following file to your boot2docker VM:

/var/lib/boot2docker/profile
```bash
waitForEth1() {
  COUNT=0
  until ip a show eth1 | grep -q UP
  do
    [ $((COUNT++)) -gt 60 ] && break || sleep 1
  done
  sleep 1
}
waitForEth1
```

**Comment by shaunc** [comment]
@Chekote -- thanks! -- that sounds promising... only, /var/lib/boot2docker does not exist. (checked e.g. /usr/local/var/lib as well...) Is there an alternate location? ... or if I create it there with just that in it, will it work? In general, what rule(s) does boot2docker use to find this profile?

If this is useful:

bash-3.2$ boot2docker info
{
	"Name": "boot2docker-vm",
	"UUID": "632dc5f1-5d05-4f0c-9605-ddf4c5973bc1",
	"Iso": "/Users/shauncutts/.boot2docker/boot2docker.iso",
	"State": "running",
	"CPUs": 8,
	"Memory": 2048,
	"VRAM": 8,
	"CfgFile": "/Users/shauncutts/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox",
	"BaseFolder": "/Users/shauncutts/VirtualBox VMs/boot2docker-vm",
	"OSType": "",
	"Flag": 0,
	"BootOrder": null,
	"DockerPort": 0,
	"SSHPort": 2022,
	"SerialFile": "/Users/shauncutts/.boot2docker/boot2docker-vm.sock"

**Comment by shaunc** [comment]
Another related fact:

   sudo DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/Users/shauncutts/.docker/machine/machines/dev docker info

works... perhaps there is something in my ~/.boot2docker or ~/.docker directories that conflicts, which is somehow overridden by the Kitematic resource files? I don't have global docker_machine installed.

**Comment by Chekote** [comment]
I only just started messing with kitematic, and I'm also not using docker machine. I've just experienced this same issue with boot2docker before.

I've had trouble with the boot2docker instance starting up with the .100 IP address too. Whenever that happens I just stop and start it and it typically picks up the expected .103 address.

In regards to the missing directory, I'm not sure why it's not on your system. `/var/lib/boot2docker` is a symbolic link. This is what `/var/lib` looks like on my boot2docker VM:

```
docker@boot2docker:~$ ls -lah /var/lib/
total 0
drwxrwxr-x    3 root     staff        100 Jun 29 13:39 ./
drwxrwxr-x    9 root     staff        200 Jun 29 13:39 ../
lrwxrwxrwx    1 root     root          29 Jun 29 13:39 boot2docker -> /mnt/sda1/var/lib/boot2docker/
lrwxrwxrwx    1 root     root          24 Jun 29 13:39 docker -> /mnt/sda1/var/lib/docker/
drwxr-xr-x    4 root     root         160 Jun 29 13:39 nfs/
```

**Comment by TeckniX** [comment]
@shaunc it sounds like you have both boot2docker and the kitematic VM setup - You're probably looking at the previous `.bashrc` setup which conflicts with your current VM setup.

Here are a couple of tips to get you back on your feet:
* Edit your local `.bashrc` or `.zshrc` and comment out (add `#`) for each `DOCKER` env variable
* Confirm that your shell no longer has `DOCKER` like env via:
`env | grep "DOCKER"`
If any `DOCKER` variable exist, you can remove them via `unset`, like so:
```bash
$ env | grep "DOCKER"                                                                                                                                DOCKER_HOST=tcp://192.168.59.103:2376
$ unset DOCKER_HOST
$ env | grep "DOCKER" 
```

Now to user docker with your boot2docker vm, do the following:
```bash
$ eval "$(docker-machine env boot2docker)"
```
If you wanted to use the 'dev' VM as created by Kitematic:
```bash
$ eval "$(docker-machine env dev)"
```


The issue with shared Volumes, is that by default the VM created will mount the `/Users` directory - You can modify this with the VirtualBox app to point to any folder you like.

**Comment by shaunc** [comment]
@TeckniX Thanks .. this looks promising. On first attempt:

----

Shauns-MacBook-Pro:xquery-rest shauncutts$ env | grep "DOCKER"
DOCKER_HOST=tcp://192.168.59.103:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/shauncutts/.docker/machine/machines/dev
Shauns-MacBook-Pro:xquery-rest shauncutts$ unset DOCKER_HOST
Shauns-MacBook-Pro:xquery-rest shauncutts$ unset DOCKER_TLS_VERIFY
Shauns-MacBook-Pro:xquery-rest shauncutts$ unset DOCKER_CERT_PATH
Shauns-MacBook-Pro:xquery-rest shauncutts$ env | grep "DOCKER"
Shauns-MacBook-Pro:xquery-rest shauncutts$ eval "$(boot2docker shellinit)"
Writing /Users/shauncutts/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/shauncutts/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/shauncutts/.boot2docker/certs/boot2docker-vm/key.pem
Shauns-MacBook-Pro:xquery-rest shauncutts$ docker info
An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/info: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103

----

However, the other suggestion works:

---

Shauns-MacBook-Pro:xquery-rest shauncutts$ unset DOCKER_HOST
Shauns-MacBook-Pro:xquery-rest shauncutts$ unset DOCKER_TLS_VERIFY
Shauns-MacBook-Pro:xquery-rest shauncutts$ unset DOCKER_CERT_PATH
Shauns-MacBook-Pro:xquery-rest shauncutts$ eval "$(docker-machine env dev)"
-bash: docker-machine: command not found
Shauns-MacBook-Pro:xquery-rest shauncutts$ eval "$(/Volumes/Macintosh_HD/Users/shauncutts/Downloads/Kitematic\ \(Beta\)\ 2.app/Contents/Resources/resources/docker-machine env dev)"
Shauns-MacBook-Pro:xquery-rest shauncutts$ docker info

 {works}

---

I am still confused why the first way doesn't work. Perhaps a conflict in ~/.boot2docker ?

**Comment by TeckniX** [comment]
Nope what you see there is a version issue - If you look at the version of docker within the boot2docker, I'm guessing it's different than the one on your Mac. 

Getting them both to the latest version should fix this issue.

**Comment by jeffdm** [comment]
To install the global command line binaries that Kitematic uses do the following:

![](https://cloud.githubusercontent.com/assets/3325447/8246881/fa5f1ee0-15fa-11e5-936b-147bd53ec5a0.png)

After this, calling eval `"$(docker-machine env dev)"` should work for the `dev` VM.

As @TeckniX mentioned, updating should fix this - the same menu command in the above image will also update your docker CLI version.
