### ISSUE TITLE
Uninstall Kitematic

### ISSUE THREAD

**Issue by shaunc** [kitematic/kitematic#733]
Due to other issues, (https://github.com/kitematic/kitematic/issues/730, https://github.com/kitematic/kitematic/issues/731), I cannot currently use Kitematic. How can I uninstall it so that I can continue using the globally-installed command-line client?

**Comment by TeckniX** [comment]
@shaunc Please see my comment in your previous issues - To uninstall Kitematic, simply drag the app to your trashcan and remove the VM via docker-machine:
`docker-machine rm dev`

**Comment by jeffdm** [comment]
@TeckniX thanks! Closing this for now.

**Comment by shaunc** [comment]
@TechniX -- your comments all issues were very helpful --thanks! ... however... (see reply in #730) -- global docker still not working without docker-machine. I am worried that if I do `docker-machine rm dev` then the solution you gave of using the dev environment will no longer work.

... in general (perhaps this is a feature request, not a bug) kitematic is packaged as a standalone alternative to docker-cli -- another use case (which I tried unsuccessfully) would be to add a gui to an existing installation. (NB -- IMHO fine would be to detect existing and stop install unless versions X Y and Z of docker, docker-compose and docker-machine were installed).

**Comment by kandekar** [comment]
removed kitematic from app folder, os x. kitematic did not get removed completely. it still opens. but unsuccesfully creating virtual linux on my mac.
then i read this thread told to run docker-machine rm dev, which i did, the output said, INFO[0000] machine does not exist, assuming it has been removed already 

but when i run docker -v, i still see Docker version 1.5.0, build a8a31ef

which means docker is still not removed from my machine, how to successfully delete it.
