### ISSUE TITLE
Trying to install hello-world-nginx - timeout

### ISSUE THREAD

**Issue by bjorngranvik** [kitematic/kitematic#735]
I'm trying to install hello-world-nginx. I get a timeout error:
Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout

Using Kitematic 0.7.4 on a Mac (latest OS). 
/Björn

**Comment by TeckniX** [comment]
Are you behind a proxy? It seems to be a recurring issue when dealing with these types of timeout

**Comment by bjorngranvik** [comment]
Hi,

No proxy. 
I followed the lab instructions in the doc section which worked fine (using commands). Then I switched back to kitematic and it worked fine. 

I tried downloading tomcat component. It seemed to work, however I didn't get a chance to test it (lack of time).

I'll give it another go and get back to you.
/Björn

Written on a mobile. Please excuse brevity and errrs

**Comment by TeckniX** [comment]
Thanks for the feedback - Please report back if any other issue come up.

**Comment by jeffdm** [comment]
Merging with #718 since it seems to be the same issue. There's a solution [there](https://github.com/kitematic/kitematic/issues/718#issuecomment-115489049)
