### ISSUE TITLE
Unable to access boot2docker from Kinematic CLI shell

### ISSUE THREAD

**Issue by mmc41** [kitematic/kitematic#738]
New user: Just installed newest Kinematic with Docker and boot2docker for the first time. When I open the shell by selecting "Docker CLI" the shell recognises the "docker" command but not the "boot2docker" command. It is used in several tutorials so I would expect it to be there.

**Comment by jeffdm** [comment]
@mmc41 thanks for the issue

Kitematic only currently includes `docker-machine`, similar to the `boot2docker` command. More info on that [here](https://docs.docker.com/machine/).

Lookout for some better docs around this soon! Closing for now.
