### ISSUE TITLE
Cannot delete stopped containers

### ISSUE THREAD

**Issue by bfirsh** [kitematic/kitematic#739]
I click the "X" in the list of containers on the left, then:

![screenshot 2015-06-29 12 46 50](https://cloud.githubusercontent.com/assets/40906/8416833/4898dde6-1ea0-11e5-84b7-045869723a65.png)

**Comment by TeckniX** [comment]
@bfirsh can you issue in the Docker CLI  `docker ps -a` so we can see what is running on your system and list it here?

Thanks

**Comment by bfirsh** [comment]
It happens with any container.

I realise this might make a difference:

```
$ docker version
Client version: 1.8.0-dev
Client API version: 1.20
Go version (client): go1.4.2
Git commit (client): f39b9a0
OS/Arch (client): darwin/amd64
Experimental (client): true
Server version: 1.8.0-dev
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): f39b9a0
OS/Arch (server): linux/amd64
Experimental (server): true
```

**Comment by bfirsh** [comment]
Hm, it's working now. Not sure what caused that - sorry. :(
