### ISSUE TITLE
Failed to download my docker image in Kitematic 0.7.4

### ISSUE THREAD

**Issue by wzymaster** [kitematic/kitematic#741]
I got error while downloading and running my docker image :

Error pulling image (latest) from bigdatauniversity/spark, Untar re-exec error: exit status 1: output: unexpected EOF

Any advice ?

**Comment by mchiang0610** [comment]
Please remove Kitematic, open virtualbox and remove the dev VM. (delete all files) 

Install Docker Toolbox which includes Kitematic.  https://docker.com/toolbox 

Thanks!
