### ISSUE TITLE
Windows without HW virtualization doesn't work

### ISSUE THREAD

**Issue by kireevco** [kitematic/kitematic#742]
Is there a way to set docker-machine to be 32 bit by default instead of 64bit? It fails silently on Kitematic initial startup.

**Comment by psychemedia** [comment]
+1

I'm looking at using kitematic as a containerised app launcher for distance education use, which means that we're always for looking to be able to configure s/ware distributions for lowest common denominator, naive user, use.

**Comment by jeffdm** [comment]
KM needs to check for VT-X, and in the bigger picture, `docker-machine` may need to allow creating VMs with VT-X disabled.

Thanks

**Comment by mchiang0610** [comment]
some type of virtualization is needed at this time. Sorry.
