### ISSUE TITLE
[Windows] Can't docker login from docker cli

### ISSUE THREAD

**Issue by crouillon** [kitematic/kitematic#744]
Using windows alpha version, the login prompt in powershell doesn't accept char typing

**Comment by jeffdm** [comment]
I've opened an issue on `docker/docker` as https://github.com/docker/docker/issues/14336 since this is an issue with the docker cli itself.

A short-term alternative is to do:

```
docker-machine ssh kitematic
docker login
```

Closing for now! Keep an eye on https://github.com/docker/docker/issues/14336 for updates

**Comment by crouillon** [comment]
thank you i'll do it

**Comment by ssmith15** [comment]
just to clarify, I can't do this inside of the boot2docker client, I have to do this in cmd? Or should I be able to run docker-machine commands in the boot2docker command line? I'm having the same issue (can't input username on windows) and am trying this but just want to clarify how to use this and how to get docker-machine to run from the boot2docker client
