### ISSUE TITLE
Cant download and install sming (kireevco / sming-docker)

### ISSUE THREAD

**Issue by MrZANE42** [kitematic/kitematic#745]
Hi
I get this error:
Error: Status 403 trying to pull repository kireevco/sming-docker: "Account is not Active"
when trying to download kireevco / sming-docker.

my account used is mrzane
Kitematic version is 0.7.4 (Alpha)

PS. Later when trying again i can't get passed the login screen but if I enter bad credentials it's informs me of it.

**Comment by jeffdm** [comment]
Can't reproduce, as it pulls okay for me.

Are you logged in? It's possible you're logged into Kitematic, and changed your Docker Hub password. Try logging out of KM and logging back in and try this again. If it doesn't work then feel free to reopen :smiley:
