### ISSUE TITLE
unable t download docker images in Kitematic

### ISSUE THREAD

**Issue by gdischner** [kitematic/kitematic#747]
When I go download a docker image it tells me that the repository does not exist. I can be reached at 716-649-0337 or gary.dischner@txmq.com

The repository that it is complaining about is registry-1.docker.io. If  you can help it would be much appreciated

**Comment by TeckniX** [comment]
@gdischner Do you have the exact error? What version of kitematic are you using?

This could be a possible DNS issue, see this post about a fix: https://github.com/kitematic/kitematic/issues/718#issuecomment-115489049

**Comment by jeffdm** [comment]
Closing as a dupe, see @TeckniX 's answer (thanks!)
