### ISSUE TITLE
too many redirects

### ISSUE THREAD

**Issue by sputnik62** [kitematic/kitematic#748]
I was trying to download bigdatauniversity/spark image and I keep getting this message:
Get https://index.docker.io/v1/repositories/bigdatauniversity/spark/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects 

I checked the status of Docker Hub at https://status.docker.com/ and it shows as operational with reasonable response times except for Docker Registry Response Time which has spiked to 663ms from about 336ms.

**Comment by jeffdm** [comment]
Thanks for the issue.

This is a duplicate of #718. There are instructions on how to fix it manually [there](https://github.com/kitematic/kitematic/issues/718#issuecomment-115489049)
