### ISSUE TITLE
i'm getting https://192.168.99.101:2376/v1.19/images/json error forbidden from the docker cli

### ISSUE THREAD

**Issue by toddspurlockw** [kitematic/kitematic#749]
It looks like the certs are bad.

**Comment by TeckniX** [comment]
@toddspurlockw What version of docker are you using? 
See the following comment to re-install the docker commands:
[Install Docker Commands](https://github.com/kitematic/kitematic/issues/730#issuecomment-117866619)

**Comment by mchiang0610** [comment]
@toddspurlockw most likely the same bug with machine #1029. 
Merging

**Comment by goodtune** [comment]
If anyone else is having issues, I just came across [docker-machine regenerate-certs](https://docs.docker.com/machine/reference/regenerate-certs/) command and it saved my bacon.
