### ISSUE TITLE
Show errors in log window when I screw up my Dockerfile

### ISSUE THREAD

**Issue by mkempster** [kitematic/kitematic#75]
If I make a stupid mistake in a Dockerfile, the Log window shows the Step that it was trying to run but nothing further. If I run boot2docker on the same Dockerfile, it tells me how stupid I was.

eg. Dockerfile with one incorrect line

    from tianon:apache2

running boot2docker from a terminal tells me 

    Sending build context to Docker daemon 69.63 kB
    Sending build context to Docker daemon
    Step 0 : from tianon:apache2
    Pulling repository tianon
    2014/09/12 23:14:09 Error: image tianon not found 

the same Dockerfile processed by Kitematic only shows me

    Step 0 : from tianon:apache2

For the testers out there, the corrected line should be

    from tianon/apache2

**Comment by jeffdm** [comment]
Thanks for the input!

Fixed in 0.5 with building being a future feature.
