### ISSUE TITLE
Error pulling image (latest) from kitematic/minecraft

### ISSUE THREAD

**Issue by ayalam** [kitematic/kitematic#750]
Error pulling image (latest) from kitematic/minecraft, Server error: Status 0 while fetching image layer (104de4492b991d7f23b0cfa0e8715c3f5501b9962a9cf8745600386c63659b77)

**Comment by ayalam** [comment]
I am a MAC user

**Comment by mchiang0610** [comment]
Hub might be down during that time. Please try again.
