### ISSUE TITLE
Error message while trying to install https://registry.hub.docker.com/u/jberkus/postgres95-test/

### ISSUE THREAD

**Issue by andywenk** [kitematic/kitematic#753]
Version 0.7.4

I tried to install https://registry.hub.docker.com/u/jberkus/postgres95-test/ but received the following error:   https://drive.google.com/open?id=0B2xXhdpvuHcGRnoxMFN0bHpQLVk 

More info here about PostgreSQL image: https://wiki.postgresql.org/wiki/PostgreSQLTestDockerImage

**Comment by mchiang0610** [comment]
Merging with #572

**Comment by andywenk** [comment]
thanks ;-)
