### ISSUE TITLE
Windows - "google/nodejs-runtime" throwing npm errors

### ISSUE THREAD

**Issue by williamkehl** [kitematic/kitematic#756]
I attempted to create the "google/nodejs-runtime" container and received the following errors:

![image](https://cloud.githubusercontent.com/assets/998904/8503280/b5f52d92-2182-11e5-976f-879d9ba47aa6.png)

0mnpm ERR! Error: ENOENT, open '/app/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.0.5-boot2docker
npm ERR! command "/nodejs/bin/node" "/nodejs/bin/npm" "start"
npm ERR! cwd /app
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /app/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /app/npm-debug.log
npm ERR! not ok code 0

I'm on Win7 x64.

Also note, I was able to install hello-world-nginx properly.

I also tried to create "google/nodejs" container and I received a 500 error (as has been reported in other issues. Didn't want to open a new ticket for that.

**Comment by mchiang0610** [comment]
@williamkehl Are you still having this issue with this with new version of Toolbox / Kitematic?

**Comment by ssharifi02** [comment]
so what happened as i still have this problem
