### ISSUE TITLE
No way to use different docker-machine than "dev"

### ISSUE THREAD

**Issue by lox5773** [kitematic/kitematic#759]
I am mac user and wanted a way to use different docker-machine than dev
or to allow more than one instances of kitematic where each is pointing to different docker-machine

**Comment by mchiang0610** [comment]
Changed to be called - default.

**Comment by sbusso** [comment]
The issue may remain. It would be nice to be able to choose name of machine used by Kitematic. Especially when having everything working on - dev - already

**Comment by mchiang0610** [comment]
+1 on @sbusso 's suggestion. We are working on this; no definite timeline at this moment yet.
