### ISSUE TITLE
Error 500 while changing Volume

### ISSUE THREAD

**Issue by lmartins** [kitematic/kitematic#762]
Hi,

Im trying to set a local volume for a container as visible here:
<img width="1317" alt="screenshot 2015-07-05 11 52 46" src="https://cloud.githubusercontent.com/assets/151981/8511412/99534170-230c-11e5-9a17-a75b9887cb21.png">

Problem is once I do it, I get the following error and it never saves:
```
server error
500
Cannot find child for /compose_wordpress_1/compose_wordpress_1
```

<img width="1317" alt="screenshot 2015-07-05 11 54 09" src="https://cloud.githubusercontent.com/assets/151981/8511413/9f368d86-230c-11e5-8f26-2e9a5a130775.png">

**Comment by TeckniX** [comment]
@lmartins Is this using the regular wordpress image? I'd like to replicate the issue. 
Can you also share your 'General' and 'Advance' tab settings? Did you create the container from command line?
Finally can you provide the output of the inspect for your docker container?

To get the info on your container, click the 'DOCKER CLI' bottom left of Kitematic, then at the command prompt:
`docker inspect compose_wordpress_1`

**Comment by mchiang0610** [comment]
@lmartins Can you open up virtualbox, and remove the dev VM. 

visit docker.com/toolbox and install the latest version of Toolbox. It includes Kitematic. 

If the issue persists, please let us know. 

Hope this helps!

**Comment by lmartins** [comment]
Sorry @TeckniX I missed your message.
I have since found a different way to achieve what I was after, with docker compose, so I haven't seen this issue since.
Thank you both for the support.
