### ISSUE TITLE
Kitematic 0.7.4 doesn't contain the latest version of docker-machine

### ISSUE THREAD

**Issue by ssreekanth** [kitematic/kitematic#763]
Updated Kitematic to 0.7.4 version. However, it didn't have the updated version of docker-machine. It still has the 0.3.0-rc2 version.

```bash
bash-3.2$ which docker-machine
/Applications/Kitematic (Beta).app/Contents/Resources/resources/docker-machine

bash-3.2$ docker-machine -v
docker-machine version 0.3.0-rc2 (6f939a8)
```

Could you please package the stable version of docker-machine in the next release of Kitematic?

**Comment by mchiang0610** [comment]
updated
