### ISSUE TITLE
Instable

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kitematic/kitematic#765]
I'm surprise that you make difficult to copy the error message require to send you a picture: <img width="380" alt="screen shot 2015-07-05 at 6 51 14 pm" src="https://cloud.githubusercontent.com/assets/8209940/8514555/e008146c-2346-11e5-804d-b08d4177faae.png">
Usability issue plus crashing too often when you try to remove dead docker from the GUI or try to run two in parallel.

**Comment by VelizarVESSELINOV** [comment]
"Cannot connect to the Docker daemon. Is 'docker -d' running on this host?" Looking in the settings of running container without doing any change make me lose the running container
<img width="408" alt="screen shot 2015-07-05 at 7 15 50 pm" src="https://cloud.githubusercontent.com/assets/8209940/8514716/4c4ab17c-234a-11e5-84db-e023b119fd5b.png">

**Comment by TeckniX** [comment]
@VelizarVESSELINOV Why the need to run 2 Kitematic apps in parallel? Or did you mean 2 container apps?
Can you provide the output of the following commands:
`docker-machine ls`
`docker-machine env dev` (unless the above ls command showed `kitematic`)
`eval "$(docker-machine env dev)" | docker version`

Thanks

**Comment by VelizarVESSELINOV** [comment]
2 Docker containers running in parallel, not 2 Kinematic apps.

I will give you theres details next time I'm playing with Kitematic. The version was downloaded last Friday afternoon, if this help you about the version identification.

**Comment by TeckniX** [comment]
Yup I suspect a couple of things - Can you provide the output of the different docker versions too?
`docker version`
`docker-machine version`
And if you login to your VM, the docker version there too? Thanks!

**Comment by VelizarVESSELINOV** [comment]
Please find the requested information:
*docker version:*
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

*docker-machine --version:*
docker-machine version 0.3.0-rc2 (6f939a8)

*docker-machine ls*
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM
dev    *        virtualbox   Running   tcp://192.168.99.100:2376

*docker-machine env dev*
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/VV/.docker/machine/machines/dev"
export DOCKER_MACHINE_NAME="dev"

Thanks

**Comment by TeckniX** [comment]
Can you verify that the docker version within the VM is the same as the one on your Mac?

I was sort of expecting a x509 certificate error, but this doesn't seem to be the case

**Comment by mchiang0610** [comment]
labelling as a docker-machine issue for when we troubleshoot

**Comment by mchiang0610** [comment]
Is this happening on Kitematic 0.8 as well? Installed through Docker Toolbox

**Comment by VelizarVESSELINOV** [comment]
I just installed Docker Toolbox, thank you for the post, Kinematics didn't give me notification that a new version is available. I will test again at let you know.

**Comment by VelizarVESSELINOV** [comment]
Looks like working better, I have other UX and docker stability issues but I will close this one
