### ISSUE TITLE
Kitematic (7.0.4) changed NODE_PATH on Mac OSX Yosemite (10.10.3)

### ISSUE THREAD

**Issue by janviehweger** [kitematic/kitematic#766]
For some reasons my `NODE_PATH` is pointing to `/Applications/Kitematic (Beta).app/Contents/Resources/app.asar/node_modules`. This happened right after installation of Kitematic (7.0.4) and broke my Node environment ;(

**Comment by TeckniX** [comment]
@janviehweger You should be able to overwrite it using the  Kitematic Container 'Settings > General' tab under 'Environment Variables'.

**Comment by janviehweger** [comment]
@TeckniX  Maybe my first explanation was not that clear. I'm talking about the `NODE_PATH` on my dev machine - which is not the Host (i'm on OSX) which was somehow taken over by Kiteamatic. That means, i'dont have access to my standard Node environment.

**Comment by TeckniX** [comment]
@janviehweger odd, I have the same Kitematic version and didn't see any node_path override. 
What shell do you use? Maybe check the  `.*rc` for that shell to see what's inside? If an entry was added, it surely can be removed and shouldn't have removed any previous export.

**Comment by mchiang0610** [comment]
@janviehweger Sorry about that. We have updated Kitematic to fit with Toolbox. Future versions should be more stable.

**Comment by NodeGuy** [comment]
I have the same problem and just installed the latest version of Toolbox but the problem isn't fixed.  How do I fix it?
