### ISSUE TITLE
Kitematic pops up other semi-random containers when starting from PS

### ISSUE THREAD

**Issue by MrZANE42** [kitematic/kitematic#780]
Hi.
After installing 0.7.4 and downloading kireevcos sming-docker I started it and it worked fine but with no USB. After that I ran the following from PS (Started from kitematic):
docker run -it -d -p 8181:80 -p 8122:22 -p 4075:4075 --device=//dev/ttyUSB0 -v /c/Users/$env:username/sming/:/root/workspace/ kireevco/sming-docker
And suddenly I had a container called silly_bardeen/sming-docker, what gives?
I've had other ones suddenly appear also(sad_feynamn, sick_ritchie, boring_torvalds. All owious bogus containers). Bug, maybe something left behind by the developers?
Kind regards
Jimmy

**Comment by MrZANE42** [comment]
OK. So I found the code in docker that generates these names:
https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go
Funny for sure but why are the popping up in kitematic when I tell it to start "kireevco/sming-docker" ?

**Comment by TeckniX** [comment]
@MrZANE42 What you're missing here is the `--name ` option passed to the `docker run` command - the `kireevco/sming-docker` part is simply the image to use. When no name is passed, the name generator is triggered to ensure that you have separate containers.

**Comment by MrZANE42** [comment]
Ok. Thanks, that explains it. And thank's for a VERY quick answer.
