### ISSUE TITLE
Can't load any images

### ISSUE THREAD

**Issue by davesag** [kitematic/kitematic#782]
Just installed `Kitematic` (having given up on `boot2docker`) and trying to get one of the standard images to install.

I get this message for any image I try (in this case `mongo`)

    Get https://index.docker.io/v1/repositories/library/mongo/images: dial tcp: lookup index.docker.io: no such host

From the `docker cli` I can do the following

    bash-3.2$ host images.docker.io
    images.docker.io is an alias for images.docker.io.s3-website-us-east-1.amazonaws.com.
    images.docker.io.s3-website-us-east-1.amazonaws.com is an alias for s3-website-us-east-1.amazonaws.com.
    s3-website-us-east-1.amazonaws.com has address 54.231.80.210

Is there some config I need to do first to get this to work? (Running OS X 10.10.4)

**Comment by jeffdm** [comment]
Thanks for the issue!

Please see https://github.com/kitematic/kitematic/issues/718#issuecomment-115489049 for the duplicate issue (and a fix!)
