### ISSUE TITLE
ETIMEDOUT error

### ISSUE THREAD

**Issue by sirdigglesb** [kitematic/kitematic#786]
I've been trying to use Kitematic for the deepdream container. At first I got to 100% on the first one I tried but then it just sat there for ages so I restarted the programme. Now no matter what I try and make a container it tries to connect then says ETIMEDOUT connect 192.168.99.100   2376

Not the most familiar with these things but quite good with computers so any help would be appreciated, thanks!

**Comment by jeffdm** [comment]
Are you running a VPN that might be blocking connection to the VM running Docker?

**Comment by mchiang0610** [comment]
closing due to no response. Please reopen if necessary
