### ISSUE TITLE
Cant pull images...

### ISSUE THREAD

**Issue by projectdocker** [kitematic/kitematic#788]

**Comment by TeckniX** [comment]
Could be an issue with your connection/dns, see a possible solution here:
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes

**Comment by projectdocker** [comment]
trying the line " docker-machine ssh dev " outputs:
" Error : Host does not exist: dev

**Comment by TeckniX** [comment]
What is the output of:
`docker-machine ls` ?

**Comment by TeckniX** [comment]
It'll probably have a line with the word 'kitematic' in it - If that's the case, then do `docker-machine ssh kitematic` instead of the dev

**Comment by projectdocker** [comment]
docker-machine ls outputs the docker logo with the current version. I tried
creating the image from my repo at my personal wifi connection and seems to
work perfectly. Thank you for the help!

**Comment by TeckniX** [comment]
Glad to hear you were able to resolve this - Would you mind closing the issue if it no longer applies.

Thanks!
