### ISSUE TITLE
New user 403s - Check if account is active BEFORE downloading image!

### ISSUE THREAD

**Issue by Miserlou** [kitematic/kitematic#789]
This is an annoying one that might affect a lot of first time users, but will be hidden to active Kitematic users and devs!

Here's the problem flow. 

So, I just got KM installed - awesome - now I want to take it out for a spin. I've signed up for Dockerhub with the internal KM flow, but I haven't verified my email address yet, because who cares about that right now, I just want to try it out! So, I type in my favorite tools and see if there are available images. And there are! Awesome, let's start downloading some. Click, click click.. three on the way. Great! 

Now, because I'm a slow corporate network, each of these downloads takes about 30 minutes. Boo! Okay.. 98.. 99.. WHAT!

    Error: Status 403 trying to pull repository nagev / tor: "Account is not Active" when trying to download nagev / tor.

Ahh! Dammit! What the hell does that mean? Who's account isn't active? Nagev's? Mine? I don't know! All of my downloads just 403'd at 99%.. crap! I just wasted half an hour and I still can't Kitematic - so sexy, but doesn't actually work!

Of course, the solution here is really obvious - check if a user has verified their email address on Dockerhub __before__ downloading an image! This would save new users a lot of time, bandwidth and headache. And, while you're at it, you can make the error message an instructional one (ex, "403 - have you verified your Dockerhub email address?") rather than a baffling one.

That's it! Should make the onboarding process _a lot_ smoother.

Thanks!

ps - Kitematic is freaking amazing, you guys rock.

**Comment by TeckniX** [comment]
:+1: to have that added as a feature.

**Comment by Miserlou** [comment]
Status?

**Comment by jeffdm** [comment]
Looking now - sorry for the late response

**Comment by jeffdm** [comment]
Thanks for the issue.

I'm trying to reproduce this with `nagev/tor`, but am having some trouble seeing the same issue:

1. Create a new Hub account via kitematic sign up flow
2. Create container from `nagev/tor`

Am I missing a step?

**Comment by mchiang0610** [comment]
Merging with #1030
