### ISSUE TITLE
Installed Docker Commands don't work immediately

### ISSUE THREAD

**Issue by Miserlou** [kitematic/kitematic#790]
(This one could be on me, but I think this might be a KM bug. Feel free to close if I'm just being stupid.)

I just used KM's 'Install Docker Commands' feature to get docker and friends into my /usr/local/bin. Great!

    $ docker
    Usage: docker [OPTIONS] COMMAND [arg...]
    A self-sufficient runtime for linux containers.

Sweet. Okay, let's try it out.

    $ docker ps
    Get http:///var/run/docker.sock/v1.19/containers/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

Oh no! This happens for everything.

What's wrong here? If this requires a restart or some kind of configuration, please make this either a) happen automatically or b) be explained by the Install Docker Commands feature.

Thanks!

**Comment by Miserlou** [comment]
Ah, so it looks like the appropriate variables need to be set, ex:

    export PATH='/Applications/Kitematic (Beta).app/Contents/Resources/resources:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' && DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_CERT_PATH=/Users/myusername/.docker/machine/machines/dev DOCKER_TLS_VERIFY=1 docker

I added an alias to my bash profile to handle this automatically. I suggest that the Install Docker Commands button handle this aliasing automatically somehow, or provide some educational information about these variables to the user. The default behavior as it stands is quite confusing.

**Comment by TeckniX** [comment]
I believe the proper workflow would be as follow:

1. Click "Install Docker Commands"
2. Click "DOCKER CLI"

**Comment by jeffdm** [comment]
Going to close this for now since it's not an issue with KM per-say, more so with the docker CLI experience.

Thanks for the issue!
