### ISSUE TITLE
Show all Information from within Kitematic

### ISSUE THREAD

**Issue by Miserlou** [kitematic/kitematic#791]
This is just a small enhancement.

It's frustrating that all of the descriptions are truncated with ellipsises within KM. To view any actually useful information for a given container, I always have to go out to the Dockerhub website.

It'd be nice if I clicked on an item, it would expand to show the entire description. Ideally, this feature would persist for downloaded containers as well as another panel alongside IP/Ports, Web Preview, etc.

Thanks!

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by mchiang0610** [comment]
Merging with #1032
