### ISSUE TITLE
Docker CLI button should respect default system shell

### ISSUE THREAD

**Issue by Miserlou** [kitematic/kitematic#792]
When I use the Docker CLI button to get to my KM Docker, this command is executed:

    bash -c "export PATH='/Applications/Kitematic (Beta).app/Contents/Resources/resources:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' && clear && DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_CERT_PATH=/Users/myusername/.docker/machine/machines/dev DOCKER_TLS_VERIFY=1 /bin/sh"

Could we change that final /bin/sh to respect the default system shell? Some people like bash, some like zsh, etc.. then we can get our lovely bash profiles and other dotfile niceties.

Thanks!

**Comment by TeckniX** [comment]
What version of Kitematic are you running?
If you look at the code:
https://github.com/kitematic/kitematic/blob/master/src/utils/DockerMachineUtil.js#L170

Kitematic looks up the Env shell - I use ZSH and always get zsh. On Ubuntu, I get a proper BASH shell too. 
Maybe your env SHELL variable isn't set properly?

**Comment by Miserlou** [comment]
Ah, you're correct. I assumed that Terminal.app default shell and $SHELL were the same - I guess not.

**Comment by TeckniX** [comment]
no problem - the Terminal.app settings can be confusing at times. Could you close this issue if it is no longer valid?
