### ISSUE TITLE
Retina UI Bug (Name Hovering)

### ISSUE THREAD

**Issue by Miserlou** [kitematic/kitematic#793]
<img width="671" alt="screen shot 2015-07-08 at 12 47 56 pm" src="https://cloud.githubusercontent.com/assets/139987/8580457/a70192bc-256f-11e5-8fd3-a90627fd2887.png">

Minor visual defect - looks like there's a hard limit on the background size for container name hovers. My hunch is that this is a "retina" thing.

**Comment by TeckniX** [comment]
Our of curiosity and also to replicate the issue, what's the image name that your 'hopeful_yonath' container used?

**Comment by Miserlou** [comment]
That stuff must have just been auto generated during 'docker build'. This is what it eventually came out as (just a test) - https://registry.hub.docker.com/u/richjones/nx-trust/ Built on ubuntu:14.04

**Comment by TeckniX** [comment]
it's possible if you didn't give the image a name - then the md5 looking string ends up being used.
If I used the above link, the name below 'hopeful_yonath' would just be 'nx-trust:latest'.

**Comment by Miserlou** [comment]
I mean, that is absolutely the situation (I tagged it after I built it) - but that doesn't change the UI bug. You could get the same thing by tagging your repo 'julian/ACollectionOfHistorySince_1966_ToThePresentDay', etc etc etc

**Comment by TeckniX** [comment]
totally understand, was easier to replicate your exact setup/build steps then creating my own (in case you did something different).

**Comment by mchiang0610** [comment]
merging with #1032

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (124/100 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:36222 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYsS-002bf7-Qb
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:41:14 -0500
Date: Fri, 11 Sep 2015 17:41:16 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442018476;
	bh=MbkPIfBTP4quLMrXUUxeUudGQG2mjJhU7n7/hyo2bAg=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=lUI8rTgR7XtkNVNyjlQLXheAU7rV0pih/S131OaLLy+2xArc9l5+LfJ6204GpQov0
	 rUVmT3E/IFKltBXOaRrb2+TeCOXs1Fa2nWXDiY4f7aQH0MJy4Tsaa4hatVa6FwuwQR
	 y3xJlH1wvZqz1CbD12eustrZuQkjC86C+UDiK9m0=
