### ISSUE TITLE
cannt load the image for fundamental of spark

### ISSUE THREAD

**Issue by IvyC** [kitematic/kitematic#794]
it said the account is not active

**Comment by mchiang0610** [comment]
@IvyC 

Sorry about that. Can you provide more details on the error that you are seeing? Which image are you having trouble on? (Can you provide that exact name / owner)? 

Thanks!

**Comment by Miserlou** [comment]
This is related to https://github.com/kitematic/kitematic/issues/789 which I just opened and described in more detail.

In fact, I imagine that some, if not all, of these are related:
https://github.com/kitematic/kitematic/issues/788
https://github.com/kitematic/kitematic/issues/782
https://github.com/kitematic/kitematic/issues/758
https://github.com/kitematic/kitematic/issues/750
https://github.com/kitematic/kitematic/issues/745
https://github.com/kitematic/kitematic/issues/703
etc etc

I think #789 should be given serious priority for this reason. It seems to happen to nearly every new user.

**Comment by TeckniX** [comment]
@Miserlou interestingly enough we do have a check in place for active/inactive accounts, see:
https://github.com/kitematic/kitematic/blob/master/src/utils/HubUtil.js#L126

It looks like it needs to be debugged to ensure that we can prompt the user to activate their account, if not active.

**Comment by jeffdm** [comment]
Closing in favor of #789, thanks all. See the discussion there!
