### ISSUE TITLE
How can I access the Remote API's ? 

### ISSUE THREAD

**Issue by krckumar** [kitematic/kitematic#795]
Can you guide me on how to access the remote APIs ?
It would be great if you could provide me with info on remote API's... the boot2docker way of things seems not working.. may be the URL path matters...

Thank you.

**Comment by TeckniX** [comment]
This doesn't seem to be specific to Kitematic, but falls more under the 'docker' request - Please refer to the docker.com website:
https://docs.docker.com/registry/spec/api/

**Comment by jeffdm** [comment]
@TeckniX thanks! Closing since this is unrelated to KM. 

@krckumar also see https://docs.docker.com/reference/api/docker_remote_api_v1.19/ for the full, latest remote api docs.
