### ISSUE TITLE
I/O timeout on new container

### ISSUE THREAD

**Issue by donert** [kitematic/kitematic#797]
Trying to download Cassandra and get the following error repeatedly.

error message
Get https://index.docker.io/v1/repositories/library/cassandra/images: dial tcp: lookup index.docker.io on 172.20.10.1:53: read udp 172.20.10.1:53: i/o timeout

docker info

Containers: 2
Images: 88
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 92
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-boot2docker
Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: dev
ID: ZZMP:PQMI:FTL6:3OYK:BQNS:XUYX:HO3Y:TR6X:GCCO:ABPS:OHXZ:Z4LK
Debug mode (server): true
File Descriptors: 33
Goroutines: 84
System Time: 2015-07-09T02:52:18.704924962Z
EventsListeners: 1
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**Comment by tforssander** [comment]
I get same error message when trying to create the "hello-world-ngnix" container.

```
Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp: lookup index.docker.io on 172.20.10.1:53: read udp 172.20.10.1:53: i/o timeout
```

**Comment by TeckniX** [comment]
Could be an issue with your connection/dns, see a possible solution here:
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes

Are you logged in to the DockerHub? Did you activate/validate your email?

**Comment by donert** [comment]
Yes, I am signed in and email verified.

it does appear to be a nameserver problem. it seems odd that I previously had been able to install 2 docker images successfully and then all I have tried return similar errors. 

I corrected resolv.conf and container download now works again.

**Comment by TeckniX** [comment]
@donert Glad to hear the wiki link helped! :+1:  

Would you mind closing the issue since it's been resolved?

**Comment by ambled** [comment]
@donert have you needed to fix resolv.conf multiple times?

**Comment by mchiang0610** [comment]
This should be fixed in the new Toolbox. Closing for now.
