### ISSUE TITLE
Allow the user to turn off auto-updates

### ISSUE THREAD

**Issue by runasand** [kitematic/kitematic#798]
According to [this blog post](http://blog.kitematic.com/post/104164806039/kitematic-0-4-released) Kitematic ships with an auto-update feature. Please consider giving users the ability to turn this off/on.

**Comment by jeffdm** [comment]
@runasand Thanks for the issue!

**Comment by mchiang0610** [comment]
@runasand The auto-update will not self update. It will prompt the user and at that time the user will have the option to say no. 

Thanks!

**Comment by runasand** [comment]
Thanks, @mchiang0610! Will Kitematic connect to another server to check for an update before prompting the user? If yes, then that's the type of behavior I would like to be able to disable.

**Comment by vesper8** [comment]
would be nice to have a menu item to 'check for updates' 

there was a new version available and it never offered me to install it, had to download it manually
