### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by projectdocker** [kitematic/kitematic#799]
according to the container logs on kitematic, mysql spawns and exits with error code 1. Any ideas how to fix it? my wordpress container was working fine earlier.

**Comment by jeffdm** [comment]
Hi there,

For now you need to set an extra environment variable for MYSQL, for example:

![screen shot 2015-07-09 at 5 54 05 pm](https://cloud.githubusercontent.com/assets/251292/8610165/8cc704dc-2663-11e5-8dfe-473e8c300d7d.png)

**Comment by projectdocker** [comment]
How do I got about this? I am new to docker.

**Comment by jeffdm** [comment]
@projectdocker sorry for the delay!

1. Start a `mysql` container
2. Click on `Settings`
3. You'll see environment variables you can modify as in the image above. Add
`MYSQL_ROOT_PASSWORD` and `examplepassword` to the last line.
4. Press Save
