### ISSUE TITLE
add docker pull equivalent?

### ISSUE THREAD

**Issue by bortels** [kitematic/kitematic#80]
I was kind of surprised when I found the only way (so far as I can see) to get an image in is to build it from scratch in a Dockerfile. 

I could cheat, I guess, and make a dockerfile with a single FROM line (and mess with CMD and so on) - but it would be nice if we could simply do a docker "pull" command and be done with it. Even better would be to search against the Docker hub...

**Comment by jeffdm** [comment]
Added in 0.5! :smiley_cat:
