### ISSUE TITLE
Add a Retry Button

### ISSUE THREAD

**Issue by Miserlou** [kitematic/kitematic#800]
So, because Kitematic is still in kind of an early state, my downloads fail a lot. That's fine. Shit happens.

<img width="893" alt="screen shot 2015-07-09 at 11 19 55 am" src="https://cloud.githubusercontent.com/assets/139987/8603400/b38fd1d4-262c-11e5-8b47-f6b9690e1119.png">

The problem is that there is no 'Retry' button. I have to remember which thing I'm trying to download, then go back to the Search page.  This is annoying. You have a File Ticket button right there.. it'd be nice if you'd also add a Retry Download button.

Also, if you leave the search page, and click back on the container (perhaps if you want to see the user that created it, which is quite often), the search resets and you have to re-type it in. That's also annoying.

I've started filing enough tickets that I feel like I should be working on some of these things myself. Do you guys accept pull requests? Do you hire consultants?

**Comment by mchiang0610** [comment]
@Miserlou This seems like a network issue. 

We do accept pull requests. As the nature of this project is open source, we are open to PRs, suggestions, request, and more. 

Docker is always hiring. Please check out our career page. 

Closing this issue for now. 

Thanks!
