### ISSUE TITLE
Kitematic.app becomes unresponsive if container CPU >= 100% while updating container logs

### ISSUE THREAD

**Issue by Miserlou** [kitematic/kitematic#801]
<img width="1474" alt="screen shot 2015-07-09 at 12 17 30 pm" src="https://cloud.githubusercontent.com/assets/139987/8604617/9e8953f2-2634-11e5-880e-331f417a75c8.png">

When running a beastly job in a Container, Kitematic.app becomes unresponsive. 

This has something to do with the logging. If I try the same thing but I don't have the logs going, Kitematic remains responsive.

**Comment by Miserlou** [comment]
Steps to reproduce:

Download 'deepdream' container.
Put any input.png file in /data volume and start container.
Wait 5s for it to get started.
Click on the 'container logs'

Now, clicking anywhere else in Kitematic won't work.

**Comment by jeffdm** [comment]
Thanks for the issue!

Is the docker daemon unresponsive? In either case, the UI's responsiveness should always be good.

**Comment by Miserlou** [comment]
The daemon continues, it's just Kite that's the problem.

**Comment by jeffdm** [comment]
Thanks for the update.

**Comment by mchiang0610** [comment]
Merging with #867
