### ISSUE TITLE
Stopping a container

### ISSUE THREAD

**Issue by projectdocker** [kitematic/kitematic#802]
Hi,

I created a container from the wordpress image found on eugeneware's github. It runs perfectly fine up until the point I stop the container or shut down the computer where I am working on my environment on. When I try viewing the webpage, I get "Error in connecting to database server" or "no DNS servers".

**Comment by jeffdm** [comment]
When you try to view the webpage again, is the container running?

It's possible restarting the container breaks something with how the database starts. Which image are you trying?

**Comment by projectdocker** [comment]
Hi,

Yes the container is running. I deduced that the problem occurs whenever
the container stops and I try starting the container up again -- MySQL
starts having problems connect.

I forked this repo: https://github.com/eugeneware/docker-wordpress-nginx

**Comment by jeffdm** [comment]
@projectdocker this seems to be specific to that container - does it occur with any others?

**Comment by mchiang0610** [comment]
Closing for now.
