### ISSUE TITLE
Cannot Remove Container After 404

### ISSUE THREAD

**Issue by Miserlou** [kitematic/kitematic#803]
Shown below:

<img width="893" alt="screen shot 2015-07-09 at 11 19 55 am" src="https://cloud.githubusercontent.com/assets/139987/8607564/96b9105e-2648-11e5-8299-ae6f3abad2fb.png">
<img width="783" alt="screen shot 2015-07-09 at 2 40 53 pm" src="https://cloud.githubusercontent.com/assets/139987/8607571/a5838056-2648-11e5-8a14-435c8f60458c.png">
<img width="893" alt="screen shot 2015-07-09 at 2 40 33 pm" src="https://cloud.githubusercontent.com/assets/139987/8607574/ab0a0e96-2648-11e5-94ca-629b5f96d5eb.png">

**Comment by jeffdm** [comment]
Thanks for the issue, what steps did you take to reproduce?

Just deleting a downloading container doesn't seem to reproduce this, but I think I've seen this another time in the wild.

**Comment by nconnor** [comment]
Also seeing this with urelx/centos6-epel

**Comment by mchiang0610** [comment]
Merging with #1030
