### ISSUE TITLE
Could it support show images below containers tabbar

### ISSUE THREAD

**Issue by jsvisa** [kitematic/kitematic#805]
It only shows the containers, if I want to see the images, I have goto Terminal, and then typing 

```bash
docker images
```

Could Kitematic support showing images in TabBar below containters TabBar?

**Comment by TeckniX** [comment]
@jsvisa If you look at the container name, you will see the image name used underneath it - 

It seems you're wanting a way to list the existing images within your own environment, which is independent of all containers, is that correct?

**Comment by FrenchBen** [comment]
Possible ##feature##

* Show list of images
* Allow delete of images

**Comment by jeffdm** [comment]
Merging with #787
