### ISSUE TITLE
gocd/gocd-agent throws 500 error creating aufs mount

### ISSUE THREAD

**Issue by JorritSalverda** [kitematic/kitematic#807]
server error
500
error creating aufs mount to /mnt/sda1/var/lib/docker/aufs/mnt/c21a5bc51f4043b6e4676ea16ea8723d01d87d0d089b85dc7680e05a671a60a0-init: invalid argument

**Comment by TeckniX** [comment]
Not sure if this is the exact same issue, but see this docker issue:
https://github.com/docker/docker/issues/13742

Can you provide specs of your docker environment? (docker version, VM version, OS, etc)

**Comment by bawigga** [comment]
Same here:

```
Docker version 1.7.1, build 786b29d
VirtualBox 5.0.0
Mac OSX 10.4.4
```

**Comment by jeffdm** [comment]
Thanks!

**Comment by mchiang0610** [comment]
Merging with #1030
