### ISSUE TITLE
Kitematic UI going to blank screen

### ISSUE THREAD

**Issue by Jared-Prime** [kitematic/kitematic#810]
<img width="1364" alt="screen shot 2015-07-10 at 3 22 48 pm" src="https://cloud.githubusercontent.com/assets/1060000/8628331/a7935694-2717-11e5-9e92-fd99177552c6.png">

Not sure what additional info to provide at this time.

**Comment by FrenchBen** [comment]
What OS? Kitematic Version?
Did you previously have docker tools installed?
Any VirtualBox versions previously installed?

Thanks

**Comment by Jared-Prime** [comment]
OSX Yosemite 10.10.3
Kitematic 0.7.4
VirtualBox 4.3.28 r100309 (from previous install)

Is there a log or something I can grab if and when this happens again?

**Comment by FrenchBen** [comment]
With the window open and the Kitematic menu shown, you can toggle the dev tools, by going to 'View > Toggle DevTools" (looks like chrome dev tools), but will not always have information about the error. 

In your case it looks like the app failed to initialize, it's possible that an error could've been generated.

**Comment by mchiang0610** [comment]
Can you try installing with Docker Toolbox?  docker.com/toolbox

**Comment by Jared-Prime** [comment]
Hi @FrenchBen and @mchiang0610 ! I have not experienced this issue within the last month or so. I do share @FrenchBen suspicion that the app failed to initialize. I will close this issue until I or someone else is able to provide useful information.

Thanks!

**Comment by hpez** [comment]
I'm experiencing the same issue on Ubuntu 18.04. When running Kitematic, it goes to a blank screen and gets stuck.

**Comment by BookOfGreg** [comment]
Also having this issue
Ubuntu 18.04
Kitematic 0.17.6-1
in Hyper-V

**Comment by cracki** [comment]
Also having this issue
Kitematic-0.17.6-Windows

**Comment by lucaspanik** [comment]
I'm experiencing the same issue on Ubuntu 18.04.

Also having this issue
Ubuntu 18.04
Kitematic 0.17.7 amd64

**Comment by otaphsf** [comment]
Same problem here, Ubuntu 18.04, Kitematic v1.8.8. It starts for every user attempting the first time quickly and without problems.
But restarting it will result in a white screen, after logout/login, shutdown/restart etc. (persistently). I've been looking for some .(dot)<kitematic related hidden dir or file> with settings that creates the problem after first successful startup?
Has anybody found a solution for this?

**Comment by lucaspanik** [comment]
I had to change my ubuntu UI to Unity instead of Gnome, and apparently Kitematic is working normally.

I believe it is relative to GNOME.

**Comment by otaphsf** [comment]
Ah, thank you, i will try that : )

**Comment by dwervin** [comment]
How did you all solve this?  I'm still having this problem with Ubuntu 18.04.

How is this closed if people are still having the issue.  There is no note indicating the resolution.

**Comment by ALiangLiang** [comment]
same issue here
ubuntu 18.04

**Comment by dwervin** [comment]
How did you all solve this? I'm still having this problem with Ubuntu 18.04.

How is this closed if people are still having the issue? There is no note indicating the resolution.

**Comment by ALiangLiang** [comment]
@dwervin I just re-install the kitematic. And  it's works.

**Comment by dwervin** [comment]
> 
> 
> @dwervin I just re-install the kitematic. And it's works.

Did you take any different steps from the first time it was installed?  I ask because I tried reinstall as well back in March, but no luck.

Maybe they fixed something since then.
