### ISSUE TITLE
Error running new wordpress container

### ISSUE THREAD

**Issue by crewshin** [kitematic/kitematic#811]
![screen shot 2015-07-10 at 8 06 38 pm](https://cloud.githubusercontent.com/assets/273809/8632055/34aec924-273f-11e5-837d-b14d35136544.png)

**Comment by FrenchBen** [comment]
What versions of docker are you running?
Can you run the following from a command line (click 'Docker CLI' button on the bottom left corner)
`docker version`
`docker-machine version`

**Comment by crewshin** [comment]
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64


docker-machine: 'version' is not a docker-machine command. See
'docker-machine --help'.



~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Gene Crucean
www.genecrucean.com
@GeneCrucean <https://twitter.com/#!/GeneCrucean>

Crucean Photography
www.cruceanphotography.com
@CruceanPhoto <https://twitter.com/cruceanphoto>
Instagram <https://instagram.com/crucean_photography>

On Mon, Jul 13, 2015 at 12:22 PM, FrenchBen <notifications@github.com>
wrote:

> What versions of docker are you running?
> Can you run the following from a command line (click 'Docker CLI' button
> on the bottom left corner)
> docker version
> docker-machine version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/issues/811#issuecomment-121029290>
> .
>

**Comment by GaryJones** [comment]
@crewshin Do `docker-machine -v` to get the version info.

**Comment by crewshin** [comment]
Sorry about that. I'm completely new to Docker, and now I've apparently
upgraded this thing. New (and probably irrelevant info)...

Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): darwin/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

docker-machine version 0.3.1-rc1 (993f2db)

I'll post back here if it happens with this version. Thanks for the help
and sorry about the crap bug reporting. Sheesh.

>

**Comment by FrenchBen** [comment]
Thanks for the update - Do you mind closing the issue if it's currently resolved?
