### ISSUE TITLE
command line terminal ENV

### ISSUE THREAD

**Issue by carljmosca** [kitematic/kitematic#812]
There may already be a way to do this but so far I have not found it.  I would like to do my Java maven builds in the kitematic command line environment and wondered if there's a way to have it set up my environment.

BTW...kitematic rocks!!

**Comment by FrenchBen** [comment]
@carljmosca You can do setup your docker environment in 2 ways:
* Click the 'Docker CLI' button on the bottom left of Kitematic
* From a terminal window, with the docker command tools installed, run: `eval "$(docker-machine env dev)"` 
You may need to verify that 'dev' is the proper name for your Virtualbox Machine via `docker-machine ls`

**Comment by carljmosca** [comment]
I am sorry but I think I am missing something in your second bullet.  What I am after is not having to do a "source ~/.bash_profile" or the like each time I go the the command line.

**Comment by FrenchBen** [comment]
The `eval "$(docker-machine env dev)"` actually does this for you - you do not need to do the `source ...`

**Comment by carljmosca** [comment]
I thought you might say that but it does not seem to be the case for me.  I am guessing I am coming at this differently.  Will play around some more and make something work.

**Comment by FrenchBen** [comment]
@carljmosca can you provide me with the output of the following commands:
* `docker-machine ls`
* `env | grep DOCKER`
* `docker-machine env dev`

**Comment by ForNeVeR** [comment]
What about Windows support? It does not seem that Kitematic installs docker-machine etc. somewhere into PATH. So all I have is

    > docker-machine
    Command 'docker-machine' cannot be found.

`docker-machine` and `docker` are perfectly available in the terminal started by Docker CLI button in the Kitematic UI. Could I have such effect without starting GUI?

**Comment by carljmosca** [comment]
I am using another solution for the time being and have not been able to get back to this.

**Comment by jeffdm** [comment]
For the Windows Alpha you need to click on `Docker CLI` to open a shell with `docker` & `docker-machine` available.

**Comment by ForNeVeR** [comment]
Okay, I think what I need is #697; thanks.
