### ISSUE TITLE
Issue install on Mac OS X

### ISSUE THREAD

**Issue by webdevapi** [kitematic/kitematic#813]
Error pulling image (latest) from mariadb, Mktemp failed: mkdir /mnt/sda1/var/lib/docker/graph: read-only file system.

Even when i create the full directory path and apply a chmod -R 777 /mnt.

Any ideas ?

**Comment by FrenchBen** [comment]
What versions of docker are you running?
Can you run the following from a command line (click 'Docker CLI' button on the bottom left corner)
`docker version`
`docker-machine version`

**Comment by mchiang0610** [comment]
closing. no response. please reopen if necessary
