### ISSUE TITLE
No drop shadow on Kitematic window

### ISSUE THREAD

**Issue by doxxx** [kitematic/kitematic#814]
The flat white styling of the Kitematic window doesn't include a drop shadow around the window border on Windows 7. The result is that when the window is overlapping another window with a lot of white in it, it's impossible to see the border of the Kitematic window.

As an example, here is the Kitematic window overlapping the browser window where I'm composing this issue:

![image](https://cloud.githubusercontent.com/assets/677940/8651433/c90b5656-2946-11e5-9891-5097ec294ac0.png)

**Comment by FrenchBen** [comment]
Do you have a special theme in place? Windows 7?

**Comment by jeffdm** [comment]
This seems to happen if the app loses focus - maybe in that case we can somehow add a border.

**Comment by doxxx** [comment]
@FrenchBen Standard Windows Aero theme.

@jeffdm It looks like this regardless of whether the app has focus.

**Comment by jeffdm** [comment]
Thanks!

**Comment by doxxx** [comment]
It looks like this only occurs when using Remote Desktop.

**Comment by mchiang0610** [comment]
Merging with #1032

**Comment by tohagan** [comment]
I have the issue in normal use for win7 (not just drop remote desktop). 
I have a standard default windows theme.

**Comment by ssatguru** [comment]
On windows 7 , drop shadow only occurs when using Aero Theme. No drop shadow when using window 7 basic or high contrast theme, making the app irritatingly  hard to use.
