### ISSUE TITLE
Website: missing word in Managing Volumes article

### ISSUE THREAD

**Issue by charleswhchan** [kitematic/kitematic#822]
https://kitematic.com/docs/managing-volumes/

(Last sentence before image)
... Quick ___ to this ...

If someone can point me to the code for this page, I can update it. Thanks.

**Comment by mchiang0610** [comment]
@charleswhchan Thanks for reporting Charles. We are in the process of removing our docs page in favor of having our docs on Docker.com

**Comment by charleswhchan** [comment]
Thanks @mchiang0610, sounds good.
