### ISSUE TITLE
heroku cedar with latest tag not available through kitematic

### ISSUE THREAD

**Issue by mordtech** [kitematic/kitematic#823]
The docker image is searchable and allows me to select create. But, when I select it, I'm informed that no heroku cedar with the latest tag is available

**Comment by mchiang0610** [comment]
@mordtech This is the correct behavior as the heroku cedar image does not have the latest tag. 

To choose a tag, please click on " ... " inside kitematic, and select "14" as that is the only tag heroku has provided. 

Hope this helps. Closing this issue for now. Please reopen this if you have more related questions! 

Thanks!
