### ISSUE TITLE
sometimes  can't run 'docker info' in the command line terminal

### ISSUE THREAD

**Issue by iamcrzay** [kitematic/kitematic#824]
Get http:///var/run/docker.sock/v1.19/info: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

**Comment by cclauss** [comment]
Do you install kitematic from the installer or do you install it via [`brew cask install kitematic](http://brew.sh)?  I installed via the brew cask method and I am seeing the same thing as you.

**Comment by jeffdm** [comment]
Did you open a new shell from Terminal.app or was your terminal created via the `Docker CLI` button in Kinematic?

If this is from Terminal.app - which isn't a Kitematic issue per say but more so with the docker cli & VM set up experience.

I'll close this for now but please re-open if it's from the `Docker CLI` button in Kitematic
