### ISSUE TITLE
Need a way to tell if I am running the current version.

### ISSUE THREAD

**Issue by cclauss** [kitematic/kitematic#826]
`About Kitematic` on my Mac tells me that I am running 0.7.4.  I want to know if that is the latest and greatest so I go to https://kitematic.com which does not tell me what the current version is so I go to https://kitematic.com/download/ which does not tell me what the current version so I go to https://github.com/kitematic/kitematic which does not tell me what the current version is.  The only way to tell what the current version is is to download the files first.

**Comment by mchiang0610** [comment]
Hi @cclauss the latest version are on our latest releases. https://github.com/kitematic/kitematic/releases

Thanks!
