### ISSUE TITLE
Terminal commands don't work in Kitematic's Docker CLI

### ISSUE THREAD

**Issue by jsvisa** [kitematic/kitematic#828]
After goto docker CLI from 
![here](https://cloud.githubusercontent.com/assets/3627395/8739193/4ecee7cc-2c6b-11e5-8e21-65714fffea27.png) 

the terminal simple commands like `ls` becomes illegel
![image](https://cloud.githubusercontent.com/assets/3627395/8739208/73861f18-2c6b-11e5-8d9c-2b87deafeea6.png)

**Comment by mchiang0610** [comment]
@jsvisa Is this on Mac or Windows, and which version of Kitematic are you using? 

I'm currently unable to reproduce it on Windows / Mac

**Comment by jsvisa** [comment]
@mchiang0610 Thanks for your quick reply. Seems it's my falut, I put `$(docker-machine env dev)` in my *~/.bash_profile`, 
But seems ` $(docker-machine env dev)` may eval failed, I just replaced it with `eval "$(docker-machine env dev)"`, then all got well
