### ISSUE TITLE
About Kitematic should also show docker version, docker-machine version, and virtualbox version

### ISSUE THREAD

**Issue by cclauss** [kitematic/kitematic#829]
Current docker version is v1.7.1 but the current Kitematic ships v1.7.  It would be easier to debug incompatibility issues if version numbers for all components were shown in one place.

**Comment by mchiang0610** [comment]
@cclauss Thanks for this feature request. This is definitely useful.

**Comment by FrenchBen** [comment]
Please take a look at this PR and provide feedback
https://github.com/kitematic/kitematic/pull/843

**Comment by jeffdm** [comment]
Merged
