### ISSUE TITLE
Documentation on Managing Volumes talks about a missing option

### ISSUE THREAD

**Issue by cclauss** [kitematic/kitematic#833]
https://docs.docker.com/kitematic/userguide/#managing-volumes mentions an `"Enable all volumes to edit files in Finder"` option that I was unable to find in the current version of Kitematic.  If I create from the official Django image which does not EXPOSE any volumes, then I can not edit files in the Finder.

**Comment by FrenchBen** [comment]
The 'Enable all volumes' shows up when you click the folder  - If no volume was defined in the dockerfile/image then Kitematic can't assume any mounting point. 
There's a current discussion on custom volume mapping:
https://github.com/kitematic/kitematic/pull/722

Once that PR has been updated with the latest changes you'll be able to map your custom volumes

**Comment by mchiang0610** [comment]
Docs will completely change. 

Thanks for the update !
