### ISSUE TITLE
No Tags

### ISSUE THREAD

**Issue by dlamblin** [kitematic/kitematic#835]
Maybe I'm missing something obvious, but I search for debian, I see the Official Debian repository first, and I click the … button where it says the selected tag is "latest" that's fine, but there's 26 other tags on the page right? So I click selected tag, and the "Please select an image tag." box says "No Tags". Not even latest is in there. And this seems to be true of ANY image, even the front page ones.

V 0.7.6

**Comment by FrenchBen** [comment]
Thanks for the bug report - it seems that the docker hub changed their response format slightly which broke the tags selection- I've pushed a fix here:
https://github.com/kitematic/kitematic/pull/840

**Comment by dlamblin** [comment]
Thanks; I'm surprised issues don't get linked with pulls like this. I hope they do get linked to tags/releases. I would love to see when this is closed by an available & built release.

**Comment by jeffdm** [comment]
I had made some changes to KM in wake of Hub API changes, but too early, temporarily breaking the tag code.

Things should be working correctly in 0.7.6 as of this morning. Sorry for having tags unavailable for that time.

Jeff
