### ISSUE TITLE
Not able to download httpd:latest docker image

### ISSUE THREAD

**Issue by vikranttelkar** [kitematic/kitematic#836]
We're sorry. There seem to be an error:
ETIMEDOUT
ETIMEDOUT
connect
192.168.99.100
2376

I tried to download 3-4 official images but I am getting this error for all images using kitematic.

**Comment by FrenchBen** [comment]
Please see the wiki about possible fix:
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#cannot-download-imageconnect

**Comment by RoySchoep** [comment]
Adding the nameserver to ```resolv.conf``` solved the problem for me.
