### ISSUE TITLE
docker.sock issue after docker run OS X 10.10.2

### ISSUE THREAD

**Issue by coltonoscopy** [kitematic/kitematic#841]
Hello,

In trying to operate the docker CLI with Kitematic on Mac OS 10.10.2, running just a "docker run x", where x is any image, I'm getting the following error:

Post http:///var/run/docker.sock/v1.19/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

I wasn't having this issue before with boot2docker; is it an issue related to boot2docker being installed simultaneously? It happens after I start using Kitematic and stopped once after I did a clean wipe of boot2docker. 

Thanks!

**Comment by mchiang0610** [comment]
@coltonoscopy Kitematic runs Docker-machine underneath. We've seen a few cases of machine not fully working alongside boot2docker. 

boot2docker CLI will go into deprecation soon. 

Usually this problem can be solved by removing the dev VM created in Virtualbox by Kitematic, and then running Kitematic again. 

Please let me know if you are still seeing problems with using Kitematic. 

Thanks!

**Comment by coltonoscopy** [comment]
Hi Michael,

Thanks so much for the help; that fixed it!

Best,
Colton
