### ISSUE TITLE
default Docker parameters

### ISSUE THREAD

**Issue by coltonoscopy** [kitematic/kitematic#842]
Hello,

Is there any way to modify the run string of a container through the GUI without going through the CLI? Context is deploying a container to students who aren't technically savvy and having them use Kitematic for this. I tried searching through Docker docs to see if maybe this could be done on the build end, but it seems everything related to RUN, CMD, ENTRYPOINT, etc. wasn't capable of doing something like mapping ports? The string we would want to run is this:

docker run -e "OFFLINE_IP=$(IP)" -e "OFFLINE_PORT=8080" \
		   --name $(CON_OFF) -d \
		   -p 5050:5050 -p 8080:8080 $(IMG_OFF) 2>/dev/null

Thanks for the help!

Best,
Colton

**Comment by FrenchBen** [comment]
@coltonoscopy Does the image have the above ports declared in the Dockerfile via 'EXPOSE' ?
All of the `-e` parameters can be set within the container's General tab, under Environment variables. 

Custom port editing/mapping is still a work in progress. If you have them created during the initial `docker run` they should be retained after changes to the general settings (environment)

**Comment by coltonoscopy** [comment]
@FrenchBen Thank you for the reply; the ports are indeed exposed via EXPOSE, but I was hoping there was a way to configure it in such a way that we could get a 1:1 mapping (i.e., 5050:5050 and 8080:8080 as in the above string). As best I can tell, EXPOSEing the ports only makes them outwardly available from within the image but doesn't let the host access them except via default port mapping?

**Comment by FrenchBen** [comment]
The 'random' default port mapping in Kitematic is in place to prevent port conflicts. If you map them during the initial creation, they should remain mapped afterwards.

Perhaps you could create a compose file for your student to use as a base, then use Kitematic to do the rest of the config?

**Comment by coltonoscopy** [comment]
@FrenchBen Thank you for the reply! We would ideally like to avoid having the students build their images and instead have everything happen from within Kitematic. Can an image built with compose, for example one with ports mapped within it, be uploaded to the Docker Hub and then run from within Kitematic without it remapping the ports?

**Comment by FrenchBen** [comment]
@coltonoscopy I don't think you can force the port-mapping of the images. Compose is simply to organize all images that would be built/linked on the system along with port maps, see:
https://docs.docker.com/compose/

**Comment by coltonoscopy** [comment]
@FrenchBen Ah I see... thank you for your help!

**Comment by FrenchBen** [comment]
You're welcome :+1: 
Port mapping/editing should be added soon to Kitematic, so keep an eye on the release details
