### ISSUE TITLE
can not downlaod scipyserver

### ISSUE THREAD

**Issue by estheryou** [kitematic/kitematic#844]

**Comment by estheryou** [comment]
can not download scipyserver

**Comment by mchiang0610** [comment]
@estheryou May I ask what error message you were seeing? Also, which repo are you downloading this from?  

Thanks,
Michael

**Comment by estheryou** [comment]
Hi,Michael, thanks for the prompt reply, just downloaded the scipyserver ,I
guess it requires some strong web connection ,failed many times before that
single success.

The message was GET to an address ending in timeout , sorry it is too long
and when I copy that address and it turned out to be nothing  .

Thank you so much !

estheryou

**Comment by mchiang0610** [comment]
@estheryou Thanks for letting me know. 

Just to confirm you have it working now? 

Closing this issue for now if it's working. If not, please respond and we will try to help as much as we can.
