### ISSUE TITLE
Make set-up error messages selectable for easier copy past research

### ISSUE THREAD

**Issue by D1no** [kitematic/kitematic#846]
Would be great if one would not have to type out the 14 line error message by turning the error stdouts into selectable text-areas.
![image](https://cloud.githubusercontent.com/assets/2397125/8828748/0361716a-3094-11e5-9eda-c1043f1cd1b2.png)

**Comment by nathanleclaire** [comment]
+1

**Comment by FrenchBen** [comment]
:+1: 
Fixed by https://github.com/kitematic/kitematic/pull/853

**Comment by D1no** [comment]
Perfect!
