### ISSUE TITLE
MYSQL_ROOT_PASSWORD not set by default.

### ISSUE THREAD

**Issue by krishnazure** [kitematic/kitematic#850]
I came across this issue , when setting up MySQL Docker image. The issue is easily resolved by adding the  MYSQL_ROOT_PASSWORD in the "Settings".

![mysql_root_password not set by default](https://cloud.githubusercontent.com/assets/5904129/8840260/b8967b9e-30ac-11e5-8d28-f756de26d2fc.jpg)

**Comment by FrenchBen** [comment]
Per the docs, this is normal:
https://registry.hub.docker.com/_/mysql/

**Comment by mchiang0610** [comment]
This is normal behavior. Will relay the issue to Official images team
