### ISSUE TITLE
Broken links in FAQ on docs.docker.com

### ISSUE THREAD

**Issue by rtrauntvein** [kitematic/kitematic#857]
https://docs.docker.com/kitematic/faq/ 

Links to CONTRIBUTING and ROADMAP are not working right on the docs page. Works fine in the GitHub display of the page, as well as in my markdown previewer. Not sure why it is broken.

Example link showing as: 
`https://docs.docker.com/kitematic/https://github.com/kitematic/kitematic/blob/master/CONTRIBUTING` instead of just `https://github.com/kitematic/kitematic/blob/master/CONTRIBUTING`

**Comment by mchiang0610** [comment]
Fixed thanks.
