### ISSUE TITLE
Ports not working

### ISSUE THREAD

**Issue by fgarcia** [kitematic/kitematic#858]
I am having problems with my container ports on OSX. I have seen posts by manually editing the Virtualbox machine, but I thought it was already solved with the Host only adapter

The port configuration according `docker ps` is this:

    CONTAINER ID        IMAGE                 PORTS                      NAMES
    a066b6fdcbef        mongo:latest          0.0.0.0:32769->27017/tcp   mongo

Looking at my `$DOCKER_HOST` ip I noticed that although 32769 is open and working properly, port 27017 is closed. Do I still need to manually edit the host-only-adapter (vboxnet1) to forward each port?

**Comment by FrenchBen** [comment]
Although it seems confusing at first, what you're seeing here `0.0.0.0:32769->27017/tcp` is that your port 32769 is mapped to the 27017 port within the container. Which is what the port 32769 is shown as open.

Therefore, you should be able to connect to your mongo db via: `192.168.99.100:32769`
