### ISSUE TITLE
VirtualBox download URL wrong

### ISSUE THREAD

**Issue by ngreatorex** [kitematic/kitematic#861]
Trying to install Kitematic v0.7.6 on a Mac that doesn't have VirtualBox installed gives this error:
<img width="800" alt="kitematic-error" src="https://cloud.githubusercontent.com/assets/1928433/8884798/a4cbfcdc-3251-11e5-9702-b255d63e6bf1.png">

On setting a breakpoint with the Developer Tools I can see the URL it's trying is:
    https://github.com/kitematic/virtualbox/releases/download/5.0.0/VirtualBox-5.0.0.pkg

This URL gives a 404. The correct URL should be:
    https://github.com/kitematic/virtualbox/releases/download/v5.0.0/VirtualBox-5.0.0.pkg

<img width="1151" alt="kitematic-vbox-url" src="https://cloud.githubusercontent.com/assets/1928433/8884812/bef95456-3251-11e5-8b2d-8c8774f99bf5.png">

Downloading and installing VirtualBox manually allows the setup to proceed.

**Comment by FrenchBen** [comment]
Thanks for the issue - The link in the app is correct, just the release package link is incorrect. 
If you look at 'older' releases, it shows the same url format as:
https://github.com/kitematic/virtualbox/releases/download/5.0.0/VirtualBox-5.0.0.pkg

**Comment by jeffdm** [comment]
Fixed, thanks!
