### ISSUE TITLE
Unexpected error starting up Kitematic (windows 7)

### ISSUE THREAD

**Issue by rmorrise** [kitematic/kitematic#862]
I was able to install Boot2Docker and run 'hello world' successfully. I noticed Kitematic mentioned on the docker site and decided to try it out, since it seemed like it might be easier to work with.

After running the installer, I got this error from Kitematic:
    `C:\Users\<redacted>\"" } You may be getting rate limited by GitHub. You will want to check the provider and make sure the machine and associated resources were properly removed.`

![image](https://cloud.githubusercontent.com/assets/8999824/8886252/67bd2da0-3235-11e5-8487-f9c63e5f6f0f.png)

I only just installed the tool, and haven't told it to do anything yet. I'm not sure what it's asking me to do here. I don't seem to have any problem accessing GitHub.

I tried both buttons, but neither one fixes the issue.

**Comment by mchiang0610** [comment]
@rmorrise Are you installing this through a company network? It seems like you are getting rate limited by GitHub.

**Comment by mchiang0610** [comment]
Closing to merge with #1029
