### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by calphool** [kitematic/kitematic#863]
I can't get Kitematic to install on my Mac (10.9.5).

I get this screen:

![image](https://cloud.githubusercontent.com/assets/4335553/8886804/2a340200-3236-11e5-8eec-c55e28248bb7.png)

I don't really know what the error means.  I used to have VirtualBox on this Mac, but I removed it a long time ago.

Thoughts?

**Comment by calphool** [comment]
Nevermind.  I installed VirtualBox again, and the Kitematic install started working... I think the installer needs some way to make sure VirtualBox is installed properly rather than blowing up with a weird error like that.... apparently it saw something left over from my ancient install of VirtualBox (I couldn't even find it on the hard drive, but there must have been something left over).

**Comment by timfallmk** [comment]
@calphool Unfortunately Virtual Box can be a bit cryptic in why and when it doesn't want to do something. It also likes to leave messy bits of itself everywhere. Hopefully this problem should be improved when we refactor the use of `docker-machine` to provision machines.

FYI. There is an uninstall script that will wipe out any components left by Virtual Box. If you think there might be something interfering with the install, it might be a good idea to run that. The instructions are in the main docs.

**Comment by mchiang0610** [comment]
Closing to merge with #1029
