### ISSUE TITLE
Error install Postgres official

### ISSUE THREAD

**Issue by leoromanovsky** [kitematic/kitematic#864]
server error
500
error creating aufs mount to /mnt/sda1/var/lib/docker/aufs/mnt/13ed5ebaf267aa2ee347b7dc8c6293d3e1f66ec0689e7a6bb7b0ec885a936869-init: invalid argument

**Comment by timfallmk** [comment]
@leoromanovsky Could you give some more info on what you're trying to do? Are you running the `postgresql` container, or something else?

**Comment by fortytw2** [comment]
same issue here - happens on a brand new install, just trying to launch the official postgres image.

**Comment by FrenchBen** [comment]
Just downloaded the latest kitematic, allowed it to create a brand new `docker-vm` and selected postgres from the recommended containers. 
No problem installing/running it. 

![postgres](https://cloud.githubusercontent.com/assets/3965324/8937606/abcaf65e-3527-11e5-98f3-335331ed4c74.png)

**Comment by leoromanovsky** [comment]
Fixed by upgrading my version of Virtualbox.

**Comment by FrenchBen** [comment]
:+1: Good to hear - Can you go ahead and close this issue since it was resolved?

**Comment by fortytw2** [comment]
Fixed here by upgrading virtualbox too :+1:
