### ISSUE TITLE
Getting Celery Image

### ISSUE THREAD

**Issue by mcspud** [kitematic/kitematic#868]
server error
500
error creating aufs mount to /mnt/sda1/var/lib/docker/aufs/mnt/a32e2579e7fedc3a74aee6ce4385d29884444a7f10cddd6dc85afcce06560f18-init: invalid argument

**Comment by FrenchBen** [comment]
Can you provide the following:
* kitematic version
* docker version
* docker-machine version

Are you trying to use a specific tag for the Celery image?

**Comment by mchiang0610** [comment]
@mcspud closing this due to no reply. Please reopen this issue if you are still having problems. 

Thanks!

**Comment by nguyentam2211** [comment]
Hi there,

I have the same issue. I had an other issue about couldn't start docker with Kitematic (0.8.3). Then I updated my Virtualbox to a test build (5.0.3).
I installed Mysql container and it works ok.
Then I try to install Wordpress container (https://hub.docker.com/_/wordpress/) and get this error:
```server error
500
error creating aufs mount to /mnt/sda1/var/lib/docker/aufs/mnt/451d78e8bd5041554167318df18f5d0efbcdd5e68ebc1491307173fa99aa8308-init: invalid argument```
About my Kitematic:
- kitematic version: 0.8.3
- docker version: 1.8.1
- docker-machine version: 0.4.1

Please let me know your comments.
Thank you!

**Comment by nguyentam2211** [comment]
Nevermind, I remove the Wordpress container -> reset Virtual machine -> re-install Wordpress container -> it works!
