### ISSUE TITLE
"grunt-retro": "0.7.0" add this in package.json

### ISSUE THREAD

**Issue by lipangit** [kitematic/kitematic#871]
In this way , we can use cnpm install in china, otherwise 
![image](https://cloud.githubusercontent.com/assets/2038071/8923097/eb98dcfa-351e-11e5-88f3-61cd2fc84fc9.png)

**Comment by timfallmk** [comment]
@lipangit It looks like the problem is that `cnpm` is out of date. Is there a way to get an updated version with updated dependencies?

**Comment by timfallmk** [comment]
Obviously I haven' tried this before, but have you tried `s3-cnpm`? https://github.com/QubitProducts/s3-cnpm

**Comment by jeffdm** [comment]
This seems to be unrelated to KM itself. As @timfallmk mentioned, there's probably a way to access these `npm` modules

Feel free to re-open
