### ISSUE TITLE
Docker Image Create - Error

### ISSUE THREAD

**Issue by aravindsastry** [kitematic/kitematic#873]
Following error occurred while trying to create Docker Image:

ETIMEDOUT
ETIMEDOUT
connect
192.168.99.100
2376

**Comment by FrenchBen** [comment]
What docker image where you using? Do you have a link to its details on the docker hub?

**Comment by aravindsastry** [comment]
I just used official Java official repo pull. I tried another helloworld-nginx image pull. Both resulted in same same error.

**Comment by aravindsastry** [comment]
I did this in Kitematic.

**Comment by FrenchBen** [comment]
Do you have the docker commands installed? If so, could you issue the following and post the results here:
`docker-machine --version`
`docker-machine ls`
`docker version`

**Comment by mchiang0610** [comment]
Merging with #1030
