### ISSUE TITLE
v0.8.0-rc2: client is newer than server (client API version: 1.20, server API version: 1.19)

### ISSUE THREAD

**Issue by commanderfun** [kitematic/kitematic#875]
When running v0.8.0-rc2 on Mac OS X 10.10.4.

I started a container from: hello-world-nginx:latest, clicked the EXEC button and got this error:

Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)

**Comment by FrenchBen** [comment]
but the 'hello-world-nginx' container was created properly?

**Comment by commanderfun** [comment]
@FrenchBen I'm not sure what you mean by "properly" but I think yes it was created by clicking the "create" button in the Kitematic GUI.

**Comment by FrenchBen** [comment]
I was able to replicate this #bug looks like the docker variables aren't being set properly.
In the meantime, you can fix this by running:
`eval "$(docker-machin env docker-vm)"`
then to exec into the container:
`docker exec -it hello-world-nginx sh`

**Comment by miguelqvd** [comment]
Hi,

I've installed Kitematic v0.8.0-rc3 completely new and I have this issue:

PS C:\Users\xxx\AppData\Local\Kitematic\app-0.8.0> docker images
Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)

I don't have any other docker daemon or docker exe anywhere.

Thanks in advance for your support and your great work!

**Comment by liangchaob** [comment]
I got the same issue on Mac like this!
It seems like the version of coreos in virtualbox can't match the client
I didn't solve this by running
<code>eval  "$(docker-machin env docker-vm)"<code>
PS:I run it on OSX, it's that right?
Or should I update my docker version in coreos?

**Comment by FrenchBen** [comment]
@liangchaob @miguelqvd can you guys share your ENV vars after clicking on the 'Docker CLI' button from Kitematic and then after running the `eval "$(docker-machine env docker-vm)"` 

Thanks

**Comment by liangchaob** [comment]
Thanks for you respond!

after running the <code>eval "$(docker-machine env docker-vm)"</code>
I just got nothing


<pre><code>Last login: Sat Aug  1 00:35:22 on ttys003
bogon:~ alan$ bash -c "export PATH='/Applications/Kitematic (Beta).app/Contents/Resources/resources:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' && clear && DOCKER_HOST=tcp://192.168.99.100:2376 DOCKER_CERT_PATH=/Users/alan/.docker/machine/machines/docker-vm DOCKER_TLS_VERIFY=1 /bin/bash"
bash-3.2$ eval "$(docker-machine env docker-vm)"

bash-3.2$
bash-3.2$</code></pre>

Nothing return!
And the issue continue

And then I try <code>set</code>,and got a lot thing seems like GO language
finally,I try <code>set | env</code>

<pre><code>
bash-3.2$ set |env
TERM_PROGRAM=iTerm.app
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/nx/0d0tjzmd7nl2rq6z_wjpmfsc0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Y1GvirTIL6/Render
DOCKER_HOST=tcp://192.168.99.100:2376
USER=alan
COMMAND_MODE=unix2003
DOCKER_MACHINE_NAME=docker-vm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.KYhad9bL0F/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34
DOCKER_TLS_VERIFY=1
PATH=/System/Library/Frameworks/Python.framework/Versions/3.4/bin:/System/Library/Frameworks/Python.framework/Versions/3.4/bin:/Applications/Kitematic (Beta).app/Contents/Resources/resources:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/alan
LANG=zh_CN.UTF-8
ITERM_PROFILE=Default
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=3
HOME=/Users/alan
COLORFGBG=7;0
DOCKER_CERT_PATH=/Users/alan/.docker/machine/machines/docker-vm
ITERM_SESSION_ID=w0t4p0
LOGNAME=alan
SECURITYSESSIONID=186a5
_=/usr/bin/env
bash-3.2$ set |grep env
bash-3.2$ set |grep ENV
bash-3.2$ set |env
TERM_PROGRAM=iTerm.app
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/nx/0d0tjzmd7nl2rq6z_wjpmfsc0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Y1GvirTIL6/Render
DOCKER_HOST=tcp://192.168.99.100:2376
USER=alan
COMMAND_MODE=unix2003
DOCKER_MACHINE_NAME=docker-vm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.KYhad9bL0F/Listeners
</code></pre>

**Comment by FrenchBen** [comment]
@liangchaob `set` is the same as `env` (or similar) - If you look at the ENV output, you have the proper variables setup after `eval "$(docker-machine env docker-vm)"` (it's normal that it doesn't output anything).
But you can check that everything went well via: `env | grep -i "docker"`
You'll see these, as you have posted above:
```bash
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME=docker-vm
DOCKER_CERT_PATH=/Users/alan/.docker/machine/machines/docker-vm
DOCKER_TLS_VERIFY=1
```

Since all of your Docker vars are now setup, you can list all running containers via: `docker ps` or `docker images` to see all downloaded images.

**Comment by liangchaob** [comment]
@FrenchBen 
But I can't run any command about docker
<pre><code>
bash-3.2$ docker ps -a
Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)
bash-3.2$ docker exec -it hello-world-nginx sh
Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)
</code></pre>

I can get the right return in vitrual box, I think there must be something wrong with my docker-client in OSX,it's that right?

**Comment by FrenchBen** [comment]
@liangchaob If your env is setup correctly (aka you ran the docker-machine command above) you should be fine. Unless you installed different version manually?

**Comment by mchiang0610** [comment]
Should be fixed in latest build.

**Comment by mbonaci** [comment]
Posting for other people that stumble upon the same error:
I was also getting: "Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)"

__The situation:__ 
 - OS X 10.10.4
 - boot2docker was installed.
 - Then, without touching boot2docker, I installed Docker Toolbox 1.8.1.
 - Machine `dev` was automatically created (previous VM was called `default` - named by boot2docker without my intervention, so the name `boot2docker-vm` that is mentioned in the docs is news to me).
 - Machine `dev` was made "active".
 - Env vars set OK with `eval "$(docker-machine env dev)"`.
```sh
$ env | grep -i "docker"
DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_CERT_PATH=/Users/mbo/.docker/machine/machines/dev
DOCKER_MACHINE_NAME=dev
```
Still, the error was there. See for yourself:
![image](https://cloud.githubusercontent.com/assets/497926/9285255/5577f354-42e4-11e5-81ab-f8dbc62c6a86.png)

First time I tried running `docker-machine upgrade dev` I got timeout while downloading boot2docker 1.8.1 image.
Second time the upgrade succeeded and from then on `docker` command started to work as expected, i.e. version discrepancy vanished.

It would be nice if someone would explain what exactly happened there.
Thanks

**Comment by garystafford** [comment]
I had similar errors after upgrading to latest version of Docker and other tools, on Ubuntu 15.04. Running the ```docker-machine upgrade ...``` command on all three of my newly created Docker Swarm nodes also fixed this error:
```bash
gstafford@gstafford-X555LA:~$ docker run swarm list token://$scid
Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)
gstafford@gstafford-X555LA:~$ docker-machine upgrade swarm-node-01
Stopping machine to do the upgrade...
Upgrading machine swarm-node-01...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.8.1/boot2docker.iso to /home/gstafford/.docker/machine/cache/boot2docker.iso...
Starting machine back up...

# repeat for each swarm node...

gstafford@gstafford-X555LA:~$ docker run swarm list token://$scid # should list (4) nodes...
192.168.99.101:2376
192.168.99.100:2376
192.168.99.102:2376
```

**Comment by funkytaco** [comment]
Just an FYI, I tried this:

`brew upgrade docker`
`brew upgrade docker-machine`
`docker-machine upgrade dev`

For the last one, I got this:

    docker-machine upgrade dev

    Stopping machine to do the upgrade...

    exit status 1

I had to reboot my laptop before I was able to upgrade.

**Comment by rockaja** [comment]
Temp fix for windows
client is newer than server (client API version: 1.20, server API version: 1.19) 
If you have the above  error message when you try to run docker on windows after installing docker-toolbox try this

Right click on the default server on virtual-box and select power off now go to 
https://github.com/boot2docker/boot2docker/releases and download the latest boot2docker iso

Now back to your machine go to 
C:\Users\<USER>\.docker\machine\machines\default and replace the boot2docker.iso with the new one

The old one is 27MB the new one is 29MB

Then go back to Virtualbox default server and click on start.. This will force it to use the new iso image.

This is a temp fix because if you shutdown and restart the default virtual server it will download the 27MB iso image again and you will loose the one you downloaded.

As noted this is a quick fix - and there should be a better way to persist the latest iso image.

Thanks

**Comment by Mahmoudz** [comment]
**I solved it** after 3 days of debugging, and I wrote the answer on StackOverflow, you MUST check it http://stackoverflow.com/questions/24586573/docker-error-client-and-server-dont-have-same-version/36298911#36298911

**Comment by funkytaco** [comment]
I just use Docker Toolbox now instead of homebrew.
