### ISSUE TITLE
Update the installation for Toolbox

### ISSUE THREAD

**Issue by moxiegirl** [kitematic/kitematic#877]
Beginning in 1.8 Kitematic is installed with toolbox rather than from the download page. Need to rewrite the install with this in mind.

ping @jeffdm @mchiang0610

**Comment by FrenchBen** [comment]
:+1:

**Comment by moxiegirl** [comment]
@FrenchBen quoi? Is this name because of the beard?

**Comment by mchiang0610** [comment]
PR LGTM.

**Comment by FrenchBen** [comment]
@moxiegirl Or all the frenchness that surrounds me!
