### ISSUE TITLE
Golang container

### ISSUE THREAD

**Issue by kostonstyle** [kitematic/kitematic#883]
Hi all,
I installed Golang container via kitematic as you can see on the picture
<img width="804" alt="screen shot 2015-08-01 at 23 21 04" src="https://cloud.githubusercontent.com/assets/701611/9023626/185e2d48-38a4-11e5-978a-caa22f19b0bf.png">

Usually, I run my application with statement go run main.go, but with kitematic where I have to put my application to run? In which folder?

When I started golang container in exec mode and type go env, it shows me:
<img width="675" alt="screen shot 2015-08-02 at 13 23 57" src="https://cloud.githubusercontent.com/assets/701611/9025926/0a75240e-391a-11e5-998b-27ab2a6466fe.png">
As you can see GOPATH, where can I find /go directory? 

Thanks

**Comment by FrenchBen** [comment]
@kostonstyle If you look at the image information, found here:
https://registry.hub.docker.com/_/golang/
You can see that you can run your golang project under the `/go` folder as seen above in the `GOPATH` environment variable.

**Comment by mchiang0610** [comment]
Assuming resolved? Closing
