### ISSUE TITLE
server error 500 No command specified

### ISSUE THREAD

**Issue by edwardIshaq** [kitematic/kitematic#884]
i got this error while downloading the docker-ios-notificaiton.
any idea what happened ?

**Comment by FrenchBen** [comment]
As the error suggests, there are 'no command specified' in the Dockerfile:
https://registry.hub.docker.com/u/cloudspace/docker-ios-notification/dockerfile/

If you look at the registry information a command is required before the container can be created:
https://registry.hub.docker.com/u/cloudspace/docker-ios-notification/

Unfortunately there isn't an easy way for Kitematic to detect this, but it's something on the feature request.

**Comment by mchiang0610** [comment]
@edwardIshaq It could also be because a network connection timed out.
