### ISSUE TITLE
Switching network makes my docker environment not working

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kitematic/kitematic#885]
Requires VM re-start outside Kitematic to make it works again in new network environment. Please make it more stable (working with different networks) and easy to restart VM.

**Comment by FrenchBen** [comment]
What do you mean by 'Switching network'?
I've gone from a coffee shop to my house to my office and never have any network issues (I keep the VM running at all times)

**Comment by VelizarVESSELINOV** [comment]
Moving from one Wi-Fi to another Wi-Fi I got the issue below, if I'm working on docker container that is using local resources (like parsing local files) the switching network is not creating me problems, but if I'm working with urllib and accessing files on the web, I have more issues:
```
  File "/usr/local/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/local/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
```
And another issue I got was with ``docker build`` was giving tcp errors not able to download python docker image, but l doesn't have a log of the error message.

**Comment by FrenchBen** [comment]
Looks like you're having some connection issues are you behind a proxy?

**Comment by VelizarVESSELINOV** [comment]
No proxy, that I'm aware of.
From the error ``lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout`` I assume that the network interface of the VM is still with the old 10.0.x.x address and now is no more valid with 163.185.x.x address.

The same Python code is working very well on my terminal interface without docker, but somehow docker VM is not updated with the change of internet address/DHCP, etc.

**Comment by FrenchBen** [comment]
the `10.0.2.3` simply isn't a proper ip - see:
https://github.com/kitematic/kitematic/issues/718#issuecomment-115489049

**Comment by VelizarVESSELINOV** [comment]
Not "so simple", **10.0.2.3** is a proper private network setup with NAT DNS router (in one wi-fi environment) and I agree is very close to the problem that you listed.

I suspect that moving from coffee shop (with NAT DNS setup) to house (with NAT DNS setup) is working, but moving from coffee shop to enterprise (with public address without NAT, etc.) is creating problem for docker VM.

Reboot the VM it is solving the problem, but the solution is far to be **simple** (elegant) and **proper** (user friendly). If you can propose a better solution to solve this problem, the users will be happier.

**Comment by FrenchBen** [comment]
The issue seems to be with the Virtualbox DHCP - Not the first time I've seen it cause issue. Hopefully they'll get this fixed soon!
Thanks for the feedback

**Comment by damienstanton** [comment]
I can confirm there are some issues with VirtualBox DHCP... Moving between networks caused me numerous `network timeout` and `no such repository` errors when trying to pull images.

Resetting the VirtualBox default VM manually and then opening Kitematic did the trick.

**Comment by mchiang0610** [comment]
Thanks for the report. Unfortunately we cannot control how VirtualBox does DHCP. We are looking into alternatives though. 

Thanks!

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (114/100 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:1798)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaYoP-002H1E-Gw
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:37:02 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=CktomyE3PKAtOrIncxtx9JCKr/Q=; b=us9JW/Rs3U9p4GcO
	BJ4qsYRsjZ0dPZH9I8EQ3+0GxeImJhv1kHabDgcDOICoRZK3SHoF7D6d3M9ySHn3
	nJ6G37AqqH/VhTSgDQTwSpHGweSaiWTcFxgGNtvx9zNmaczxv9m0JUNpLIo+HQM+
	36OTQj7JrjmdMDXRn1ak+qobW2M=
Received: by filter0448p1mdw1.sendgrid.net with SMTP id filter0448p1mdw1.11755.55F373AE12
        2015-09-12 00:37:02.452723556 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id b7i50txQQamtRMAWr6CwPA
	for <greg@biomassiv.es>; Sat, 12 Sep 2015 00:37:02.439 +0000 (UTC)
Date: Fri, 11 Sep 2015 17:37:02 -0700

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (113/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:48351)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaYoP-002H2u-C9
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:37:02 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=lfYFOezJmibdiW+4+ROk3p4zcfY=; b=vICvXXvWS2Xy18VO
	7+YV7yS2oDjV20+zJ2QXLB63WhBGT8V/An46302X3/fqpfLDftcpxhUf8rZo2Szi
	dkdHSYCxABt0dFXZcpmJO2DpFX93lpEF+NHTCok/7sTn6mBo7aJaUiGd36yYxCra
	3miUmb+7TBn0IL0DOftF9a8o1dk=
Received: by filter0823p1mdw1.sendgrid.net with SMTP id filter0823p1mdw1.23789.55F373AFA
        2015-09-12 00:37:03.290793314 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id QC8x-fhTQvSL_8V_jv7IYQ
	for <greg@biomassiv.es>; Sat, 12 Sep 2015 00:37:03.293 +0000 (UTC)
Date: Fri, 11 Sep 2015 17:37:03 -0700
