### ISSUE TITLE
UI enhancement suggestion: remove all (or multi-selection of) containers

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kitematic/kitematic#887]
I'm running a lot of containers per day and my list is becoming very often full. Removing one by one is painful user experience.

I would suggest that you can select multiple containers and remove them, or magic button close all (stopped or running or both).

**Comment by mchiang0610** [comment]
@VelizarVESSELINOV Thanks for this request. We are looking into how to deal with this in the new Kitematic design. It won't be ready as part of the Docker 1.8 (kitematic 0.8) release that's going out next week, but you can bet that we are working on this for our everyday Kitematic users.

**Comment by mchiang0610** [comment]
Merging with #1032

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (104/100 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:55561 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYl2-001zqi-Ms
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:33:33 -0500
Date: Fri, 11 Sep 2015 17:33:35 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442018015;
	bh=gTB54dH1uel6tHgVfwymFr4Y5UyS2HK3q1BVY5BhTyk=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=tRG8G22E8sGsg0fN7kMb+5kHtzTpMLHDrKXXTvbBbkT7AEo4N/yuyWWcp/XQSaX4j
	 h+z3WADvmCmaIWQhBKFK+yCV8eIOJBc7yW6twdFFMLWTVAxRJ45yGFo7ijD07r/B4e
	 9mrZgz8DiXLJYEpK/yM7mY5M8SL2xn1yd3vEOaXs=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (105/100 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:20615)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaYl5-00201r-9N
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:33:36 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=JzBkp4uQO/MD7IOm6taA8hmPPKw=; b=GsaZQqB+RiBVZ3E6
	YH0skHy0irRHwQ7z80cX8ZIAgVXEQ+WKxGoyz5gsZiSELD/eQWqLSAXrwGlBeRcn
	iF9dEVtRGOzlycTn6wWRzEvB9i/LQrYbkRCe+msGbsx6v8r2IDopFehiDJ0V+lSB
	v7wVKm1+Vhsfy8KlMUgsmgFcKPc=
Received: by filter0481p1mdw1.sendgrid.net with SMTP id filter0481p1mdw1.19750.55F372E021
        2015-09-12 00:33:36.994933421 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id xz_48Xs4R3-6ImyvW5WAEg
	for <greg@biomassiv.es>; Sat, 12 Sep 2015 00:33:36.977 +0000 (UTC)
Date: Fri, 11 Sep 2015 17:33:36 -0700
