### ISSUE TITLE
Organization private repos only available to Owner group

### ISSUE THREAD

**Issue by wnthompson78** [kitematic/kitematic#888]
Members of an organization must be part of the owners group in order to see the private repositories. User defined groups can not access private repositories even with admin permissions defined. Not all users should be part of the owners group in order to access

**Comment by mchiang0610** [comment]
@wnthompson78 Hi Nick, thanks for reporting this. 

This is a feature that we will need.

**Comment by wnthompson78** [comment]
:+1:

**Comment by bradgessler** [comment]
:+1:

I'd like to deploy Docker containers to people on our team who are less technical. I won't be able to do that until this feature is built. I'd like to propose that having a `read` permission in a group should be enough for the image to be visible from the "My Repos" list.

**Comment by michaelwilde** [comment]
Same deal.  I'd assume this won't be an issue with Trusted Registry, but if using Hub.. this is needed, as the private repo's are available on the web.

**Comment by michaelwilde** [comment]
You might be able to close this out soon..   @FrenchBen tackled it over here:  https://github.com/kitematic/kitematic/issues/1024

**Comment by FrenchBen** [comment]
thanks for the rep @michaelwilde :+1:

**Comment by jeffdm** [comment]
This should be fixed in 0.8.5. Thanks to @FrenchBen for the awesome fix.
