### ISSUE TITLE
can not find scipyserver

### ISSUE THREAD

**Issue by estheryou** [kitematic/kitematic#889]

**Comment by mchiang0610** [comment]
Hi @estheryou Can you give me more information on this? 

You should be able to search within Kitematic, and get to it. 

Closing this issue for now. If you are still having trouble please reopen this issue. Thank you!

**Comment by estheryou** [comment]
Hi Michael,
     If I want to use the jupyter is it tu search for Jupyterhub ,and what
is the account for that ?Maybe I need to sign in the jupyer first?

Thank you

**Comment by FrenchBen** [comment]
@estheryou All jupyter images should be available from the Docker hub, see:
https://registry.hub.docker.com/repos/jupyter/

You can search for them via kitematic

**Comment by estheryou** [comment]
Hi, actually I have jupyterhub downloaded and when I go to the port ,it
needs username and password to sign in ,which I do not know which account
to use ,the docker hub?But it did not work
