### ISSUE TITLE
can not find scipyserver

### ISSUE THREAD

**Issue by estheryou** [kitematic/kitematic#890]
it seems like there is no such container with id spicyserver and by the way how to sign in jupyterhub to use jupyter ,what is a valid username looks like?

**Comment by mchiang0610** [comment]
Hi @estheryou 

It's a public repo. Please go into Kitematic: 
![image](https://cloud.githubusercontent.com/assets/3325447/9077767/d96c708c-3ae6-11e5-9996-e0504b9f68cb.png)

Hopefully this helps! 

If you have more questions regarding Docker Hub, please do not hesitate to contact support@docker.com, where we can help you more! 

Thanks,
Michael Chiang

**Comment by estheryou** [comment]
I have downloaded that but do not know how to sign in ,always invalid
username,where to get the valid user name then?
