### ISSUE TITLE
can not use the spicyserver 

### ISSUE THREAD

**Issue by estheryou** [kitematic/kitematic#891]
invalid ID or something and could anyone tell me how to use jupyterhub ,there is some username and password which I don't know how to get .I tried the dockerhub account ,didn't work .
Thank you for your time

**Comment by FrenchBen** [comment]
jupyterhub isn't a project that we support - Please see their github:
https://github.com/jupyter/jupyterhub

**Comment by estheryou** [comment]
Thanks

**Comment by FrenchBen** [comment]
Since these issues are unrelated to kitematic, can you close it and https://github.com/kitematic/kitematic/issues/892 also?

Thanks

**Comment by estheryou** [comment]
Sorry ,but no, the issue that leads to this is actually the failure of
access scipyserver .I can not use scipyserver through kitematic now.By the
way , do you think a stronger internet access can help?

**Comment by mchiang0610** [comment]
@estheryou does Kitematic show it as running? That server may require you to set the username and password for the specific server.  In this case you can find the settings within Kitematic's environment variable settings. 

Unfortunately, I cannot help further as it's a problem with the way that particular repo is set up. Please try contacting the creators of that project. 

Thanks! 
Michael
