### ISSUE TITLE
can not download scipyserver or something

### ISSUE THREAD

**Issue by estheryou** [kitematic/kitematic#892]
Get https://index.docker.io/v1/repositories/ipython/scipyserver/images: dial tcp: lookup index.docker.io on 75.75.76.76:53: server misbehaving

**Comment by FrenchBen** [comment]
Do you get the same issue when you do:
`docker pull ipython/scipyserver`

**Comment by estheryou** [comment]
hi, I  use kitematic ,almost the same thing happen all last night and now I
can not even delete the container scipyserver.
Or there is some other way to use jupyterhub? But I don't know how to sign
in ,which username and password should I use?
T

**Comment by mchiang0610** [comment]
@estheryou Can you go into virtualbox and fully delete the VM, and then try again? 

Thanks

**Comment by estheryou** [comment]
I will try that~thanks
