### ISSUE TITLE
Creating dynamic image with size (20000MB) Error creating machine: exit status 1 

### ISSUE THREAD

**Issue by phuongtailtranminh** [kitematic/kitematic#894]
Hi. I'm running on Windows 10, Kitematic 0.7.1 and VirtualBox v 4.3.28 and stucked when start Kitematic.

![kitematic_error](https://cloud.githubusercontent.com/assets/12473996/9094849/517882b2-3bde-11e5-8b9c-457d81315ac1.png)

**Comment by mchiang0610** [comment]
@phuongtailtranminh Does using "delete VM and retry setup" help? Or do you get back to this page? 

Can you also open virtualbox, and screenshot its state? 

Thanks! 
Michael

**Comment by phuongtailtranminh** [comment]
'Delete VM and Retry setup' doesn't help me!

This is VirtualBox state

![kitematic_error2](https://cloud.githubusercontent.com/assets/12473996/9095174/04f8a71c-3be0-11e5-986e-f5e2dde97bca.png)

**Comment by thecolorblue** [comment]
I am having the same issue. Not sure if this is related, but I have previously had issues with hyper-v and virtual box installed at the same time (I removed virtual box, and reinstalled when installing kitematic).

**Comment by phuongtailtranminh** [comment]
@thecolorblue , I've faced with same problem with you. My solution is: turn off Hyper-V on Windows Features

![kitematic_solution](https://cloud.githubusercontent.com/assets/12473996/9096019/d86a4eb2-3be4-11e5-8cd0-2598dd25262e.png)

**Comment by solthoth** [comment]
I mentioned this is another thread, but I noticed that VB is actually preventing the image from running because it is using 50% or more of the host memory.

Pretty much if you computer has only 4GB of RAM and the docker image in VB needs 2GB, VB will not let you run it. Upgrading to 6GB+ does the trick, at least it did for me in all instances where I ran into this (OSX, Win7, Win8, haven't tried it on win10 yet).

**Comment by phuongtailtranminh** [comment]
@solthoth , My computer has 16GB RAM. I don't think that is reason

**Comment by mchiang0610** [comment]
@phuongtailtranminh sorry. Just noticed that you are on Windows 10. 

Unfortunately VirtualBox does not currently support Windows 10. They are currently working on a fix. 

Thanks,
Michael

**Comment by phuongtailtranminh** [comment]
@mchiang0610 , Thank you. You've saved my day!

**Comment by mchiang0610** [comment]
This means boot2docker / docker machine / kitematic that use Virtualbox will not currently work with Windows 10.

**Comment by FrenchBen** [comment]
You can try and apply the patch currently available within the VB forum and linked to here:
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#kitematic-vm-stuck-at-99

**Comment by phuongtailtranminh** [comment]
@FrenchBen , Thank you. But those thing doesn't work for me :"(

**Comment by mchiang0610** [comment]
@phuongtailtranminh I will post here when VirtualBox has a bug fix regarding Windows 10 support. 

Thanks

**Comment by phuongtailtranminh** [comment]
@mchiang0610 , Thank you my friend!

**Comment by bpetersen** [comment]
@phuongtailtranminh  @mchiang0610  I was able to get this to work by installing VB separately (just regular 5.0.0, not the special Windows 10 build) and then making it run in compatibility mode for windows 8.  Then run the Kitematic installer and everything worked fine.

**Comment by barhun** [comment]
the latest version of docker toolbox comes with virtualbox v5.0.2 which fixes the aforementioned issues. try and install it, but you still need to do one more thing: disabling hyper-v. windows 10 has hyper-v enabled by default, so virtualbox becomes, in the case, unable to operate in x64 virtualization mode.

if you don't want to uninstall hyper-v, you can follow the steps, about which scott hanselman has a blog post, to create a boot configuration with hypervisorlaunchtype set to off.

http://www.hanselman.com/blog/SwitchEasilyBetweenVirtualBoxAndHyperVWithABCDEditBootEntryInWindows81.aspx

**Comment by FrenchBen** [comment]
@barhun Thanks for the link - There's actually a few steps laid out within the wiki:
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#kitematic-vm-stuck-at-99-or-cannot-pull-images under 'Windows 10'

**Comment by mchiang0610** [comment]
Merging with #1029
