### ISSUE TITLE
Docker CLI discards aliases defined in ~/.bash_profile

### ISSUE THREAD

**Issue by birdonfire** [kitematic/kitematic#896]
~~When I launch Kitematic's Docker CLI, it doesn't source my `~/.bash_profile`. It would be jolly if either it did or there were a separate rc (e.g. `~/.dockerclirc`) file loaded automatically when the CLI starts.~~

When I launch Kitematic's Docker CLI, it appears to source my `~/.bash_profile`, evidenced by env vars being set, but does not preserve any of the aliases defined therein.

**Comment by FrenchBen** [comment]
The CLI should be loading your default shell - How did you assert that the `.bash_profile` wasn't loaded?

**Comment by birdonfire** [comment]
Hrm. It appears you're correct. I do see my env vars set. However, the CLI seems to have discarded all of my aliases (which is what I originally noticed).

**Comment by FrenchBen** [comment]
@birdonfire If the env is set, then aliases should follow too - Are they all set within your `.bash_profile` or `.bashrc`?

See: http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

**Comment by FrenchBen** [comment]
Closing this due to lack of feedback. Please re-open if needed.

**Comment by Aliance** [comment]
I have the same issue. There is my `Dockerfile`:
```
# https://hub.docker.com/_/php/
FROM php:5.5.23-fpm

LABEL maintainer "Lesnykh Ilia"

USER www-data

ADD .bash_profile /var/www/.bash_profile

SHELL ["/bin/bash", "-c"]

RUN source /var/www/.bash_profile
```

Then after container built I run `docker exec -it CONTAINER_NAME bash` I did not see my aliases defined into `/var/www/.bash_profile`. But if I execute `source /var/www/.bash_profile` manually – everything is ok.

**Comment by FrenchBen** [comment]
@Aliance sourcing during build, does nothing.
Run it as part of your `CMD` or simply move it to a location BASH is looking for.
