### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by rabarar** [kitematic/kitematic#897]
Unexpected error - either button fails to recover...

![kitematic-error](https://cloud.githubusercontent.com/assets/4433144/9146574/d6187e52-3d2b-11e5-9e33-d17cf7b5030e.jpg)

**Comment by rabarar** [comment]
to recover you need to manually delete ~/.docker/machine/machines/dev

**Comment by FrenchBen** [comment]
Can you provide us with the following:
* Current OS & Version
* Kitematic Version

Is this on a new setup/install or update to existing?

**Comment by rabarar** [comment]
Current OS is Mac OS X 10.10.4
Kitematic (Beta) Version 0.7.6

**Comment by rabarar** [comment]
Hit send too soon - It was an existing install - there was a failed download on an image due to bandwidth dropout (on the train). And when I attempted to re-establish the download I found myself in this state.

**Comment by FrenchBen** [comment]
@rabarar You may want to download the latest [Kitematic release](https://github.com/kitematic/kitematic/releases/tag/v0.8.0-rc5) and see if you still experience the same issues.

**Comment by mchiang0610** [comment]
Merging with #1029
