### ISSUE TITLE
Ability to clear the logs

### ISSUE THREAD

**Issue by innovia** [kitematic/kitematic#90]
currently i don't see a way to clear the logs 

would be good to have a way to clear the logs

**Comment by DominicBoettger** [comment]
This has a massive performance impact on applications which creates a log of log data in the terminal. Kitematic will become unresponsive after a while. My favorited option is to disable the interactive logging until it's enabled.

We are using it on several Developer workstations at the moment.

**Comment by AvivLander** [comment]
+1 @DominicBoettger

**Comment by jeffdm** [comment]
This should be fixed in the next release, by #372 

Closing for now :-) Thanks!

**Comment by b-long** [comment]
I understand that this has been in kitematic since [v0.5.14](https://github.com/docker/kitematic/releases/tag/v0.5.14) , but I'm unclear on the usage.  Is there a command or button to press and clear the logs?

**Comment by FrenchBen** [comment]
@b-long I believe we only get the last `x` lines of logs instead of everything.

**Comment by b-long** [comment]
Ah, I see.  Thanks @FrenchBen ! Might be worth a feature request, but I'll workaround this for the time being 👍
