### ISSUE TITLE
Unable to connect to docker hub

### ISSUE THREAD

**Issue by tryggth** [kitematic/kitematic#900]
From Kitematic the message is:
Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp: lookup index.docker.io on 10.8.8.20:53: read udp 10.8.8.20:53: i/o timeout

Email address for account is tryggth2009@gmail.com

**Comment by FrenchBen** [comment]
@tryggth Checkout a possible solution as described in the wiki
https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#cannot-download-imageconnect

**Comment by rwatts3** [comment]
Getting the same error. Docker images even from supported images are now connecting to the docker site. Simply fails. I have not changed any settings since the last time I used Kitematic.

**Comment by FrenchBen** [comment]
@rwatts3 What version of Kitematic are you using?

**Comment by FrenchBen** [comment]
Just to qa this, I downloaded the latest kitematic 0.8.0-rc5 allowed it to create a new virtualbox and verified that I could download the following recommended images:
* hello-world-nginx
* minecraft

Both downloaded and started up fine.

**Comment by rwatts3** [comment]
Thank you I believe aws servers were down

**Comment by mchiang0610** [comment]
@rwatts3  we were switching to Hub 2.0, had some downtime. Should be fixed now. Please reopen if you are still having issues.
