### ISSUE TITLE
Error when tried to pull and run image

### ISSUE THREAD

**Issue by iBobik** [kitematic/kitematic#901]
I run Kitematic firstly and tried to pull php:5.6-fpm. It downloaded image and then it retuned error:

server error
500
error creating aufs mount to /mnt/sda1/var/lib/docker/aufs/mnt/c13f9be471fe54694a68bddd55142b4bd261896c79e8dd469014db85bca0a9e9-init: invalid argument

**Comment by FrenchBen** [comment]
@iBobik Is this on a brand new VM/Kitematic install?
What are the versions of:
* VirtualBox
* Kitematic
* OS

**Comment by iBobik** [comment]
VB 4.3.26 r98988
Kitematic 0.7.6
OS X 10.10.4



Jan Pobořil

2015-08-10 19:09 GMT+02:00 FrenchBen <notifications@github.com>:

**Comment by mchiang0610** [comment]
@iBobik Hub had slight downtown for switching to 2.0. Please try again. 
Thanks
