### ISSUE TITLE
Install Docker to PATH in ~/.bash_profile

### ISSUE THREAD

**Issue by iBobik** [kitematic/kitematic#907]
Kitematic should add line to ~/.bash_profile to allow people intuitively use Docker without need to start Terminal from Kitematic.

**Comment by FrenchBen** [comment]
@iBobik I believe an installer is in the works which should do exactly that - stay tuned!

**Comment by iBobik** [comment]
No, please, don’t break simplicity of just moving .app into Applications
folders. Why not just install this one line on first run?



Jan Pobořil

2015-08-11 0:13 GMT+02:00 FrenchBen <notifications@github.com>:

**Comment by FrenchBen** [comment]
Maybe I'm missing what you'd like to see in the `.bash_profile`?

**Comment by iBobik** [comment]
Somethink like this what is called in custom terminal opened from Kitematic
(i am not sure what is possible and good idea):

bash -c "export PATH='/Applications/Kitematic
(Beta).app/Contents/Resources/resources:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
&& clear && DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_CERT_PATH=/Users/Bobik/.docker/machine/machines/dev
DOCKER_TLS_VERIFY=1 /bin/bash"


Jan Pobořil

2015-08-11 0:27 GMT+02:00 FrenchBen <notifications@github.com>:

**Comment by kriswill** [comment]
I use this in my `.bash_profile`:

```sh
  # set Docker environment variables using docker-machine
  test -f /usr/local/bin/docker-machine && eval $($_ env default)
```

This gives my bash full access to the docker host running in virtualbox by default in my shell.

**Comment by mchiang0610** [comment]
This should be solve with Docker toolbox - through the Docker quickstart terminal.
