### ISSUE TITLE
New Kitematic Version 0.8.0 -rc6 Does not contain .exe files

### ISSUE THREAD

**Issue by rwatts3** [kitematic/kitematic#908]
I am trying to use the Newest rc for kitematic, and noticed there are no .exe files. Will these come later or should we run this via build ? 
@jeffdm

**Comment by mchiang0610** [comment]
@rwatts3 Sorry about that. In the future, Kitematic will be installed from Docker Toolbox. (Alternatively you can build it) 

It can be found here: https://github.com/docker/toolbox/releases

**Comment by rwatts3** [comment]
No Worries,

Thank you .

On Monday, August 10, 2015, Michael Chiang <notifications@github.com> wrote:

> @rwatts3 <https://github.com/rwatts3> Sorry about that. In the future,
> Kitematic will be installed from Docker Toolbox. (Alternatively you can
> build it)
>
> It can be found here: https://github.com/docker/toolbox/releases
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/issues/908#issuecomment-129655439>
> .
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts
