### ISSUE TITLE
Volumes Not Displaying When Using Docker Toolbox

### ISSUE THREAD

**Issue by rwatts3** [kitematic/kitematic#910]
When using the Docker Toolbox, even though a volume is displayed, for some reason it's not allowing me to change, or even see the mapping. I navigate to the kitematic folder and the container's path is  never rendered either.

**Comment by rwatts3** [comment]
Is there any status on this @jeffdm , Containers that have a valid Volume and Binding are not showing in Kitematic.

**Comment by jeffdm** [comment]
Thanks for this!

Working on a fix now, this must be a bug with how Kitematic connects to the Docker 1.8 Remote API

**Comment by rwatts3** [comment]
Thank you

**Comment by rwatts3** [comment]
Also my apologies for the duplicate entry I was intending to post one to Docker Tool and one here. Still getting used to the organization of Kitematic & how it relates to Docker Tool

**Comment by jeffdm** [comment]
No worries! Fixed in Kitematic `0.8.1` and Toolbox `1.8.0a`
