### ISSUE TITLE
Error creating virtual machine

### ISSUE THREAD

**Issue by meyera** [kitematic/kitematic#911]
Dear Kitematic Team,
right after install when I try to start kitematic I am persistently getting an error message (see attached screenshoot). On my hard drive is > 24gb free space available. I am using Windows 10.

![image](https://cloud.githubusercontent.com/assets/2930867/9195956/092bb3ce-4027-11e5-9b7f-3b7c9e2c1f13.png)

Thank you very much.
Alexander

**Comment by FrenchBen** [comment]
@meyera Can you run the following from a command prompt?
`vboxmanage --version`

**Comment by beniboy87** [comment]
Same thing happened to me with Windows 10 Pro and VirtualBox 5.0.0 r101573 already installed before Kitematic.

**Comment by meyera** [comment]
Thanks for the reply. No I cannot. Even when I go into the folder C:\Program Files\Oracle\VirtualBox

@beniboy87 Indeed I had VirtualBox installed before. Do you recommend uninstall, and try install Kitematic again?

Thanks for the help,
Alex

**Comment by FrenchBen** [comment]
@beniboy87 @meyera 
I've added a possible fix for Win 10 in the wiki: https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#kitematic-vm-stuck-at-99
Look for the windows 10 section.

**Comment by dqmota** [comment]
I'm using Docker Toolbox 1.8.0a and it seens there's a bug on Windows version.

When I run the command `docker-machine -D ip default`

I could see the port forwarding rule for ssh service inside docker vm as `Forwarding(0)="ssh,tcp,127.0.0.1,49533,,22"`

However, the ssh command (I had to put `C:\Program Files\Docker Toolbox\kitematic\resources\resources` in PATH env) ignores that config and tries to connect allways using port 22. Mac OS version works as expected.

    STDERR:
    Using SSH client type: external
    About to run SSH command:
    ip addr show dev eth1
    &{C:\Program Files\Docker Toolbox\kitematic\resources\resources\ssh.exe [C:\Program Files\Docker Toolbox\kitematic\resources\resources\ssh.exe -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i C:\Users\Fnac\.docker\machine\machines\default\id_rsa -p 22 docker@localhost ip addr show dev   eth1] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
    SSH cmd err, output: exit status 255:
    exit status 255

Anyone know how to workaround this issue?

**Comment by mchiang0610** [comment]
Thanks! Merging with #1029
