### ISSUE TITLE
Using Kitematic with existing Docker installation

### ISSUE THREAD

**Issue by granthbr** [kitematic/kitematic#913]
I used to be able to use the UI from Kitematic with my existing docker configuration. No longer. When I initiate Kitematic, it attempts to create the VM again. Is there a way around this?

**Comment by FrenchBen** [comment]
@granthbr What was the name of your previous VM?
The latest build will look for a VM labeled 'default' - Allowing the user to select the VM is part of the future improvements, see:
https://github.com/kitematic/kitematic/wiki/Machine-Management

**Comment by abritinthebay** [comment]
Should probably look for `dev` too. That seems pretty common.

**Comment by jeffdm** [comment]
As of 0.8.0 it looks for `dev`. Before we auto update all of the 0.7.x users we may try and add auto migration support.

**Comment by granthbr** [comment]
@FrenchBen Existing VM is dev created with docker-machine. I don't want to over write my dev VM. I want to be able to see it. It looks like I need to wait for a future release to choose which VM to view. I will leave the issue open in case someone wants to comment or advise. What is strange is that it used to work. Then just stopped working. More specifically, I could display, create, destroy, and change my images.
Message says 'Machine Dev already exists. I should check to see that the machine was properly removed'.

**Comment by FrenchBen** [comment]
@granthbr if you rename the VM to the name expected by Kitematic, it should work properly.

**Comment by oliverhr** [comment]
Renaming vm did not work kitematic show error and ask to delete vm.

VM name should be asked by the installer or a at least I think that a better name is "kitematic" instead of "default".

**Comment by granthbr** [comment]
I'm still in the same boat at @oliverhr . Still no resolution..

**Comment by oliverhr** [comment]
I see two solutions here:

- Kitematic let us set VM name
- Kitematic let us to choose the VM to use from those available on docker-machine
- Or wait to docker-machine lets us change vm name.

**Comment by FrenchBen** [comment]
@oliverhr A lot of this is part of the on-going [Machine Management] (https://github.com/kitematic/kitematic/wiki/Machine-Management) task. 
It's all features we'd like to see happen sooner than later; if you'd like to get started on the implementation of the VM selection, feel free to look through the link above :)

**Comment by granthbr** [comment]
By the way, this ended up working after i combined some of the suggestions from previous comments and an update of docker, docker-machine,boot2docker and Kitematic. A OSX restart was required. It works fine now. 
Steps were: 
1. Rename VM (from dev to something else)
2. Updated Docker, Docker-Machine, Boot2docker with Homebrew 
3. Restarted OS. 

Closing the issue because following the steps from above resolved it.
