### ISSUE TITLE
Toolbox hanging

### ISSUE THREAD

**Issue by vraman0601** [kitematic/kitematic#914]
Unable to download Virtual Box on proxy.

**Comment by FrenchBen** [comment]
What OS and Kitematic version are you using?

**Comment by vraman0601** [comment]
Kenematic-.7.6-Mac.zip

On the Mac.

Proxy URL Discovery is being used.

On Tue, Aug 11, 2015 at 12:30 PM, FrenchBen <notifications@github.com>
wrote:

> What OS and Kitematic version are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/issues/914#issuecomment-130031640>
> .
>



-- 
He who never made a mistake never learnt!!
http://feeds.feedburner.com/mrvivekr

**Comment by FrenchBen** [comment]
Can you download Virtualbox Manually?

**Comment by vraman0601** [comment]
Yup

**Comment by FrenchBen** [comment]
Please see the new toolbox tool to install it all :)
https://www.docker.com/toolbox

**Comment by mchiang0610** [comment]
@vraman0601 hopefully it worked. Closing this issue for now.

**Comment by vraman0601** [comment]
Downloaded the Toolbox 1.8.0.a version for mac. It asks me to continue then it hangs...
<img width="616" alt="screen shot 2015-08-12 at 3 25 49 pm" src="https://cloud.githubusercontent.com/assets/7082789/9238342/748e39c2-4106-11e5-98c6-e2fe73e11760.png">

**Comment by vraman0601** [comment]
@mchiang0610  Please reopen. This is not fixed.

**Comment by vraman0601** [comment]
Installer Log

Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: LSExceptions [0x7fb153423dd0] loaded
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: @(#)PROGRAM:Install  PROJECT:Install-922
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: @(#)PROGRAM:Installer  PROJECT:Installer-815
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Hardware: MacBookPro11,5 @ 2.80 GHz (x 8), 16384 MB RAM
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Running OS Build: Mac OS X 10.10.4 (14E46)
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: __CF_USER_TEXT_ENCODING=0x4A18E634:0x0:0x0
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: TMPDIR=/var/folders/s8/cfcd6l5509x6cjxwb2cv6yy551jsjm/T/
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: HOME=/Users/x3it
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: SHELL=/bin/bash
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.enHiMXDEC9/Listeners
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.XMclSEDIeJ/Render
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: LOGNAME=x3it
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: XPC_SERVICE_NAME=com.apple.xpc.launchd.oneshot.0x10000006.Installer
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: COMMAND_MODE=unix2003
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: USER=x3it
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Env: XPC_FLAGS=0x0
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Docker Toolbox %INSTALLER_VERSION% Installation Log
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Opened from: /Users/x3it/Downloads/DockerToolbox-1.8.0a.pkg
Aug 12 15:24:23 M00973492.nordstrom.net Installer[3291]: Product archive /Users/x3it/Downloads/DockerToolbox-1.8.0a.pkg trustLevel=202
Aug 12 15:24:33 M00973492.nordstrom.net Installer[3291]: LSExceptions [0x7fb153423dd0] unloaded

**Comment by mchiang0610** [comment]
Submitting this to Toolbox github.  https://github.com/docker/toolbox

**Comment by mchiang0610** [comment]
@vraman0601 Can you comment on this thread? Sorry just want to make sure the toolbox issues are in that thread instead of Kitematic. 

https://github.com/docker/toolbox/issues/65 

Thanks!!!
