### ISSUE TITLE
Question: How to access container without dynamic port

### ISSUE THREAD

**Issue by rwatts3** [kitematic/kitematic#916]
How would one access a container directly without the :28080 random port each time the container starts. 

For example I am using a lucee/lucee-tomcat container where it runs a coldfusion application. The default port for coldfusion is 80. I would like to have my container's port which is 8080 , to resolve to 80, without kitematic automatically assigning it a random port. 

This is possible on Tutum , by publishing the port, but i'm not sure how to do this within Kitematic. 

Any help will be greatly appreciated. 

Thank you , 

Ryan .

**Comment by Quetzacoalt91** [comment]
Hi,

I'm also looking for this feature. You should watch the PR #598 to know when it could be released.

**Comment by rwatts3** [comment]
Thank you i'll keep an eye out.

**Comment by mchiang0610** [comment]
Thanks. We are working on this issue through that PR. #598 

Closing this issue here to move the discussion over. Thanks!
