### ISSUE TITLE
Adding volumes in settings?

### ISSUE THREAD

**Issue by dvichris** [kitematic/kitematic#917]
I don't know if I'm missing something or if I'm just supposed to be doing this via the CLI but shouldn't there be an option to add a volume to a container?

Example: Creating a new httpd container and adding ~/Users/username/Projects to the volumes.

**Comment by mchiang0610** [comment]
@dvichris We currently require you to add volumes through your dockerfile / compose file. 

We are definitely looking to improve this experience in the future, but for now it's through dockerfile or compose. 

Thanks!
