### ISSUE TITLE
Windows ask for VBoxNetAdp.sys

### ISSUE THREAD

**Issue by Filirom1** [kitematic/kitematic#918]
I can't use Kitematic on Windows.

It fails and asks for the network driver "VBoxNetAdp.sys".

Unfortunately, only the netadp6 driver is available on my machine.

Virtualbox was installed with Kitematic. It upgrades my previous Vagrant Virtualbox.

![docker](https://cloud.githubusercontent.com/assets/295554/9230410/64031750-4122-11e5-8966-c2c1a2d7c317.PNG)

**Comment by mchiang0610** [comment]
@Filirom1 May I ask which version of Windows you are on? Can you try manually uninstalling virtualbox and installing it again? 

https://www.virtualbox.org/

**Comment by Filirom1** [comment]
It is Windows 7. I uninstall virtualbox, reboot my machine and reinstall virtualbox. I do not have this error anymore but I am now stucked with https://github.com/docker/machine/issues/1521
