### ISSUE TITLE
Cannot log into Docker Hub from Kitematic

### ISSUE THREAD

**Issue by alantech21** [kitematic/kitematic#919]
The password for my dockerhub account contains uppercase characters, yet kitematic will not allow me to log in because of those.

**Comment by mchiang0610** [comment]
Hi, Kitematic can support uppercase characters. I just tried again. 

Are you able to log into Docker Hub fine?

**Comment by alantech21** [comment]
No. It does not progress when I press the login button. Plus, it
re-downloaded VirtualBox three times and destroyed the VM that the docker
toolkit had converted from boot2docker, which had all my development images.

On Wed, Aug 12, 2015 at 12:16 PM, Michael Chiang <notifications@github.com>
wrote:

> Closed #919 <https://github.com/kitematic/kitematic/issues/919>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/issues/919#event-380685260>.
>



-- 
Alan Townsend

Good enough never is.

**Comment by mchiang0610** [comment]
@alantech21 is this on Mac or Windows?

**Comment by alantech21** [comment]
Mac. OS is 10.10.3 & 10.10.4. The new docker toolkit containing docker 1.8 was just freshly installed this morning.

Alan Townsend

**Comment by mchiang0610** [comment]
Just to make sure. 

Toolbox is installed correctly, and both Kitematic and the quickstart app works?  (They both use Docker Machine underneath - if that fails nothing will work)

**Comment by alantech21** [comment]
Was working, until I tried starting Kitematic. Now, everything fails.

Alan Townsend

**Comment by mchiang0610** [comment]
Sorry, I don't quite understand. To get to the login menu in Kitematic, it would mean that Kitematic was set up correctly. 

Are you unable to see the login screen anymore?

**Comment by alantech21** [comment]
Correct. Plus, the command line tools are timing out now. I'm going to try a reinstall.

Alan Townsend

**Comment by mchiang0610** [comment]
Can you open Virtualbox: 
1. Remove the `default` VM (make sure to select delete all files - otherwise, it will fail) 
2. remove the .docker folder by running `rm -rf .docker` 
3. Rerun the Toolbox installer

**Comment by alantech21** [comment]
Finally, have everything reinstalled and the command line tools are working again. Any precautions or backup actions I should take before trying Kitematic?

Alan Townsend

**Comment by mchiang0610** [comment]
@alantech21 No, Kitematic just uses Docker machine like the command line tool.

**Comment by mchiang0610** [comment]
Glad it's resolved. Thanks!
