### ISSUE TITLE
Kitematic web preview executes arbitrary JavaScript

### ISSUE THREAD

**Issue by jvoorhis** [kitematic/kitematic#920]
EZ steps to reproduce:

1. Install and run official Drupal image
2. Create a page with "Unfiltered HTML" and the following code: <script>alert("Hello script execution!")</script>
3. Load the container's web preview in Kitematic and your script will run within Kitematic

Screenshot:
![screen shot 2015-08-12 at 3 20 09 pm](https://cloud.githubusercontent.com/assets/9054/9238238/b330cef2-4105-11e5-94bd-bb73fe0437db.png)

**Comment by jeffdm** [comment]
Thanks for the issue.

Kitematic is an electron app (powered by chromium embedded framework), and in this case, renders the preview in a [webview](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md). Calls to `alert` will be handled by chromium and show a dialog window (like the image you showed).

It does execute arbitrary Javascript as a browser window. But this javascript is contained and should absolutely **not** have access to node libraries such as `fs`, `net`, etc.

**Comment by jeffdm** [comment]
Going to close this for now, and thanks again for the issue (and screen shot!)

By all means please re-open if you feel this should stay open or if there are any other webview-related security issues!
