### ISSUE TITLE
https://docs.docker.com/kitematic/ has links pointing to localhost

### ISSUE THREAD

**Issue by wjimenez5271** [kitematic/kitematic#921]
Not sure where they should be pointing to but it probably isn't that

**Comment by thaJeztah** [comment]
Thanks for reporting, looking at that file; https://raw.githubusercontent.com/kitematic/kitematic/master/docs/index.md, it looks like `thebaseurl` wasn't set properly when the docs were generated.

ping @moxiegirl

**Comment by thaJeztah** [comment]
@moxiegirl looking at this; https://github.com/docker/docs-base/blob/0f43fd98de1f91961e924f4f2b855a0e8fbd2c82/config.toml#L1 thar config file is set to localhost; is that overwritten somewhere during the release?

**Comment by moxiegirl** [comment]
@wjimenez5271 Thanks for the catch. @thaJeztah This is my bad. I tend to experiment on different build functionality on smaller projects. I was testing out a Go template and I checked in an experiment.  I'll fix it.

```
See the [Mac OS X installation guide]({{% thebaseurl %}}mac) or the [Windows installation guide]({{% thebaseurl %}}installation/windows) for details on installing with Docker Toolbox.
```
