### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by 66beta** [kitematic/kitematic#923]
Excuse for my poor English (T..T)

**ENV:**
- KiteMatic 0.8.2
- Windows 10 enterprise

Can't open app on Windows 10, nothing in the Task Manager.
No error shows, nothing happends.

**Comment by 66beta** [comment]
KiteMatic 0.8.3 still not working

**Comment by bpetersen** [comment]
@66beta Virtual Box does not support windows 10 yet.  Try running VB in Windows 8 compatibility mode.

**Comment by 66beta** [comment]
Thanks @bpetersen , Already running under Windows 8 compatibility mode
I think its kitematics's issue, not VirtualBox's.
I can run docker vm in "Docker Quickstart Terminal"

**Comment by bpetersen** [comment]
@66beta  Interesting, I'm running on Windows 10 with that as the only fix in place.  Have you tried reinstalling Kitematic after setting VirtualBox to run in Compatibility mode?  Maybe remove the VM and have Kitematic reinstall that also.  I can't think of anything else I've done to make this work...

**Comment by 66beta** [comment]
@bpetersen Both Virtualbox & docker-toolbox have reinstalled.
Where can I find Kitematic's error log? Empty in C:\Users\***\AppData\Roaming\Kitematic.

**Comment by bpetersen** [comment]
@66beta I don't know the answer to that.  Sorry.
Did you look at this thread?  https://github.com/kitematic/kitematic/issues/894
There's something about turning off Hyper-V also.

**Comment by 66beta** [comment]
Still not working after install **docker-toolbox 1.8.1c**

**Kitematic** never show it self, just not working width Windows 10.

I suggest a log file to trace issues.
