### ISSUE TITLE
Docker Toolbox Install - Pre Check takes too much time

### ISSUE THREAD

**Issue by vraman0601** [kitematic/kitematic#928]
Docker Toolbox - Version 1.8.1a
Mac OSx.
The pre-check message pops-up, then it takes nearly 5 minutes for the continue button to show up.

Aug 13 11:15:42 M00973492.nordstrom.net Installer[1106]: Docker Toolbox %INSTALLER_VERSION% Installation Log
Aug 13 11:15:42 M00973492.nordstrom.net Installer[1106]: Opened from: /Users/x3it/Downloads/DockerToolbox-1.8.1a.pkg
Aug 13 11:15:42 M00973492.nordstrom.net Installer[1106]: Product archive /Users/x3it/Downloads/DockerToolbox-1.8.1a.pkg trustLevel=202
Aug 13 11:15:52 M00973492.nordstrom.net Installer[1106]: LSExceptions [0x7fa058c05d10] unloaded
Aug 13 11:20:45 M00973492.nordstrom.net Installer[1106]: JS: Hardware architecture detected: x86_64
Aug 13 11:20:45 M00973492.nordstrom.net Installer[1106]: JS: OS version detected: 10.10.4
Aug 13 11:20:45 M00973492.nordstrom.net Installer[1106]: JS: TypeError: null is not an object (evaluating 'vboxplist.CFBundleVersion')
Aug 13 11:20:45 M00973492.nordstrom.net Installer[1106]: JS: result:true
Aug 13 11:21:32 M00973492.nordstrom.net Installer[1106]: InstallerStatusNotifications plugin loaded
Aug 13 11:21:53 M00973492.nordstrom.net runner[1128]: Administrator authorization granted.

**Comment by mchiang0610** [comment]
@vraman0601 This is odd. It should take no more than 10 seconds. 

Closing this for now. Please provide reproduction steps if you can reproduce on other computers. Thank you so much!

**Comment by vraman0601** [comment]
Well steps for re-production  : Just run it on a mac. Logs are also proved for you.

**Comment by mchiang0610** [comment]
@vraman0601 May I ask which Mac hardware you are running this on? 

From our users and our testing here, it should take seconds.

**Comment by vraman0601** [comment]
Macbook Pro on Intel 2015 model...
