### ISSUE TITLE
Tag latest not found in repository aspgems/ibm-db2

### ISSUE THREAD

**Issue by bbelgodere** [kitematic/kitematic#929]
Tag latest not found in repository aspgems/ibm-db2 error received when deploying aspgems/ibm-db2.

**Comment by thaJeztah** [comment]
Looks like that repository doesn't *have* a `:latest` tag, only a `:v1.0` tag; https://hub.docker.com/r/aspgems/ibm-db2/tags/

So this is an issue with that repository. To work around this, explicitly specify the `:v1.0` tag

**Comment by mchiang0610** [comment]
Merging with #572

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:55310 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaY7U-004BK3-JO
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:52:41 -0500
Date: Fri, 11 Sep 2015 16:52:44 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442015564;
	bh=CwaBGnUX1ME+mbIIVVX25V7aw49PMlt1zBdGRrRbsUU=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=pqmRDKCGnXK31BPDa6UApotu328bzT9B1pPC+voSNHU2X0KlyLsVISAXIAI4s1sDo
	 BVJLTb1V07Xl0Bo1ElKENmJrRcY4J8jxMBK6a1btS2ai6gF9PTTfmoYGh4pPCoIbDF
	 5QHM0l0PdjFHtGfpfYVH/7atCDi/dTZDMWfEb0XM=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (111/100 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:37283)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaY7V-004BKa-Iw
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:52:43 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=3tTZufa4Yswuid4GW4zm73DTyLk=; b=i6wf0yb9pt+SFh4M
	I6KoU8JcdsPLvpbMi7IjxY8C/N1FumTNN7c9VBT1pBzBo5Nl0uA1yGmwjpLId5//
	I+Y2SmAth2INA3gFpstoR+OeYKQlUKB10qhUhMU4Eo4rvxZ1Awm/sUXnNE/ftmT2
	W57k3hfK09UQ1icQDJUN7zub2zI=
Received: by filter0580p1mdw1.sendgrid.net with SMTP id filter0580p1mdw1.31376.55F3694B1D
        2015-09-11 23:52:43.798664832 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id BjW0pT3HRtGLzkLQ0yWe7w
	for <greg@biomassiv.es>; Fri, 11 Sep 2015 23:52:43.980 +0000 (UTC)
Date: Fri, 11 Sep 2015 16:52:43 -0700
