### ISSUE TITLE
Help with this error

### ISSUE THREAD

**Issue by wmgeorge** [kitematic/kitematic#930]
Docker Toolbox install

![screen shot 2015-08-13 at 1 01 23 pm](https://cloud.githubusercontent.com/assets/5324563/9260262/8b3caf4a-41bb-11e5-83c6-522033d24849.png)

When kitematic closed, machine stopped get this on restart also this error. Have recreated many times, any help would be appreciated.

![screen shot 2015-08-13 at 2 43 20 pm](https://cloud.githubusercontent.com/assets/5324563/9262491/19d90c04-41ca-11e5-83ea-83a6021ad1ec.png)

**Comment by mchiang0610** [comment]
Merging with #1029
