### ISSUE TITLE
Organization team members cannot see private repos under My Repos in Kitematic.

### ISSUE THREAD

**Issue by commanderfun** [kitematic/kitematic#931]
I created an organization account via the new Docker Hub web interface and then created a few private repos.  I am able to see these repos by clicking the "My Repos" button in Kitematic.  (as I should because I created them)

However, I added some of my co-workers to the "owners" team and they CANNOT see these private repos under "My Repos" in Kitematic.  

We found a workaround:  They can click the DOCKER CLI button to open the command line and run a: docker login ... then pull the repos manually and run them. 

However, the workaround is not ideal.   We'd love to see them in the GUI and just "click to create" ...

P.S.  We're all using Kitematic Version 0.7.6

**Comment by nritholtz** [comment]
+1

**Comment by mchiang0610** [comment]
Merging with #360

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (115/100 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:54411 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYpF-002LLl-Mw
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:37:54 -0500
Date: Fri, 11 Sep 2015 17:37:57 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442018277;
	bh=WkXzXkOZj4ocRTUoue1SxrYZ/h+5K6KGuZcZ3IA/5/Q=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=KYv0RdgWVrY+cjMz2N9I3C3dG3xqw15UeSfjoa81+iC0sYg9qZrYKNzTFPmetBNoQ
	 BN1b8/kX4pvupQQDykDu6OLUQPDXNGUEAgxX9wS5bkU8h+lAT72i8fBJQI+eq6JQ9S
	 AHC/CW+svSyyErR68DcQT5gtSqZ7HF0l5aOtp9YQ=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (116/100 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:54579 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYpH-002LUi-Hk
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:37:56 -0500
Date: Fri, 11 Sep 2015 17:37:58 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442018278;
	bh=WHbJiZm7YLo1/3Pdar1BetREXuBFLUOSA0724ANDnnQ=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=RZz2+ZrXwdcj9Fz72elPvH/5qrjo479CR4IEFwlBvyJoBierNmGbf7fvIwp0WxYcY
	 8sFclB0oBucAtyh6iTvV8gVc99hBqpP4tVGEmfEqab71TFYVoBFRp3xcavioyqDhHq
	 5cPEfqTwg8klpv3vHI9pso+XyfCugESXgupzUrqA=
