### ISSUE TITLE
Cannot use latest VirtualBox

### ISSUE THREAD

**Issue by lexxpavlov** [kitematic/kitematic#932]
I have Win10 and have some troubles with install docker with Kitematic (and with Boot2Docker too). 

I installed latest Virtualbox (5.0.1r102010), then try to run Kitematic. Kitematic first removes this my Virtualbox and installs 5.0.0r101573 instead. If I setup Virtualbox via Kitematic, then I have several troubles with it. 
I can't run Kitematic with new Virtualbox (r102010) without reinstall to previous Virtualbox, but this latest version of VIrtualBox may solve Win10 troubles. 

How I can use Kitematic without reinstall latest VirtualBox?

**Comment by FrenchBen** [comment]
#close - looks like your issue has been explained in the docker/toolbox#77

**Comment by jeffdm** [comment]
This should be fixed in the latest toolbox version for Windows
