### ISSUE TITLE
error creating dockers image

### ISSUE THREAD

**Issue by pradhyu** [kitematic/kitematic#933]
Error pulling image (latest) from docker.io/kriation/centos7, Get https://registry-1.docker.io/v1/images/0af989cd52ff4a9808a839a0871d90e3e849edea40d257be17c689a8052e0386/ancestry: net/http: TLS handshake timeout

**Comment by FrenchBen** [comment]
@pradhyu Are you behind a proxy?

**Comment by mchiang0610** [comment]
Merging with #1030
