### ISSUE TITLE
Table view of containers

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kitematic/kitematic#937]
Now if you search the smaller container that do something, you need to open several extrernal web pages. Or filter by labels, maintainer, etc.

**Comment by FrenchBen** [comment]
@VelizarVESSELINOV Can you provide a bit more detail, I'm not sure if I follow what you mean

**Comment by VelizarVESSELINOV** [comment]
Docker containers listing propose very basic search and 3 basic filters.

Use case #1:
Imagine that you are looking for smaller Python or Linux container, today is not possible for sort by size or ranking like basic file explorer like Finder, iTunes, Mail on Mac.

Use cases #2:
I labeled my containers and I want to filter all the containers with label "status" = "final".

Any hidden hidden option to do this kind of container "exploration"?

I hope it is more clear now.

**Comment by FrenchBen** [comment]
#feature - Add advance filtering on images

**Comment by mchiang0610** [comment]
Merging with #1032

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (109/100 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:56590 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYmU-0027CF-3t
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:35:03 -0500
Date: Fri, 11 Sep 2015 17:35:05 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442018105;
	bh=rnFsphIAX0VCiBxxbz/cLpYe7gjfcn9ig55jd5GG9+M=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=jp8KUojW6pm7IExjkfiazh9r4s1grxhnb4tvL7HqIxHdhYOtsx9xRGxX5VyEvy6Bg
	 hgF2qdeMG2JSSFULQ0rq9MrT8fFsZqCNKRSBD7m/NEGREt9kk4hhi5u4OBjV6vaJEf
	 iX84yEcboJhWCEDLopyBnL6oNARJi6Uu7zvkmVgs=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:29708)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaYmW-0027HJ-3p
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:35:05 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=E6WPXdy1B5IWek+BrHGer2xjCMY=; b=DdaAouHB943xyKOW
	6vZGgZ1D8Elxn+sJoMX/0iouxqgUm7fRC9SCKJH4sJjr9qaLMG/c+rpuRXq44JaA
	2VTZOtc0U2o3ECluobTv/1Audl9MnUkgem+SmDwY06dHE30QKJhB8xlWrzZAw116
	GYUq0FJV0P74GZpPhyVkfNtgN+0=
Received: by filter0882p1mdw1.sendgrid.net with SMTP id filter0882p1mdw1.16409.55F373393E
        2015-09-12 00:35:05.634220695 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id qBGuxea6Sc-tPOgMH1QIXg
	for <greg@biomassiv.es>; Sat, 12 Sep 2015 00:35:05.997 +0000 (UTC)
Date: Fri, 11 Sep 2015 17:35:05 -0700
