### ISSUE TITLE
forgot password link returns 404

### ISSUE THREAD

**Issue by wjimenez5271** [kitematic/kitematic#940]
on the docker hub login view, the forgot password link yields 404:
![screen shot 2015-08-14 at 3 45 34 pm](https://cloud.githubusercontent.com/assets/322834/9285541/a3c668ae-429b-11e5-9f55-d1771cf56c4e.png)

the link is https://hub.docker.com/account/forgot-password/

**Comment by scalopus** [comment]
Fixed in https://github.com/kitematic/kitematic/pull/935 . Code Merged.

**Comment by wjimenez5271** [comment]
yay, thanks!
