### ISSUE TITLE
unable to login, unable to "boot2docker up", and various issues

### ISSUE THREAD

**Issue by gurlinthewurld** [kitematic/kitematic#941]
I received an email about the Aug 6th, site deployment, but it indicated there would be no down time, et al. 

However, I am unable to "boot2docker up" on the command line, and I am unable to connect to the hub (docker site). 

While I am able to connect via Kitematic app, I can't create a container. 

I don't know if this is related to the new deployment. I will reply via the email I received, as well.

**Comment by FrenchBen** [comment]
@gurlinthewurld `boot2docker` has been retired in favor of `docker-machine`.
Did you do a fresh install via the Docker Toolbox?
docker.com/toolbox

**Comment by gurlinthewurld** [comment]
@FrenchBen thanks, I've already uninstalled boot2docker, and I've installed the new toolbox - The trouble is I seem to have an unverified account on the site https://hub.docker.com/login/ -- I am in limbo: I can neither login, nor register as a new account because my email and info is in the database -- I'm not sure if this is the forum to address the issue. I've been emailing docker support, but there's not been any solution yet.

**Comment by FrenchBen** [comment]
@gurlinthewurld Did you try to simple reset the password on the account? https://hub.docker.com/reset-password/

**Comment by gurlinthewurld** [comment]
@FrenchBen - Well, I'm certain the password I used was the right one (I auto saved it upon creating it), but I just submitted a request - it takes 24 hrs? :( In any case, I have nothing to lose ...

**Comment by FrenchBen** [comment]
I think the 'up to 24hrs' is just the industry standard - I'm hoping that the reset will force an email to be kicked out for both the reset and then an acknowledgement of your account being valid :)

**Comment by mchiang0610** [comment]
@gurlinthewurld For Docker Hub problems you should be able to email support@docker.com directly for help! 

Sorry about this.

**Comment by gurlinthewurld** [comment]
Hey, @mchiang0610 @FrenchBen and all, this issue was resolved. I uninstalled boot2docker, and did an install of toolbox. Thanks for your attention to this!

**Comment by FrenchBen** [comment]
@gurlinthewurld :+1: Glad to hear this was resolved. Thanks for the feedback.
