### ISSUE TITLE
Modifying stock containers

### ISSUE THREAD

**Issue by janvladimirmostert** [kitematic/kitematic#942]
Hi, I was wondering if it's possible to modify stock containers ...

Let me explain: So in Kitematic, I select `New+`, select RabbitMQ and a stock installation of RabbitMQ is now running. I try to access the RabbitMQ management UI and see that it's not running.
I click Exec, type in `bash`, followed by `rabbitmq_plugins install rabbitmq_management`.
RabbitMQ Management plugin is now running, I restart the container and can see in the logs that the management pugin is being loaded.

Now how do I access it? The Managemenet plugin runs on port 15672 and only port 5672 is mapped, I don't see any way in Kitematic to now also map port 15672 in the container.

So my question, how do I map extra ports and is it possible to mount extra volumes on containers I don't control?
If this is not possible, consider this a feature request.

**Comment by FrenchBen** [comment]
@janvladimirmostert Port editing as well as Volume editing is an upcoming feature but is currently in Kitematic. 
If you're familiar with the docker command line, you can create your own image, based on the current container setup and re-create the container with the added ports and volume mapping.

**Comment by janvladimirmostert** [comment]
I've been using Docker command line exclusively since I started using Docker. 
Kitematic is awesome, it's just missing those two features before it's a one-stop place for managing dev environments - looking forward to Port / Volume editing feature!

**Comment by Tolsi** [comment]
+1

**Comment by FrenchBen** [comment]
Port editing is part of the latest Kitematic - Closing this as the Volume management PR is also pending.

**Comment by janvladimirmostert** [comment]
Yay, thanks guys!
