### ISSUE TITLE
create mysql container error (404)

### ISSUE THREAD

**Issue by samuelchen** [kitematic/kitematic#943]
I was creating 4 containers in kitematic (rabbitmq, celery, django, mysql). They all are official images.

The other 3 succesfully downloaded but 'mysql'. error as below.

no such container
404
open /mnt/sda1/var/lib/docker/repositories-aufs: no such file or directory

AND 

`docker ps`  returns no images. It returns several images just seconds ago.

**Comment by samuelchen** [comment]
latest docker tools (just downloaded & installed yesterday). 
docker host is default.
mac os 10.9.5.

**Comment by FrenchBen** [comment]
Looks like an issue with the VM setup - I just create a MySQL container without any issues. Can you retry?

**Comment by mchiang0610** [comment]
Merging with #1030
