### ISSUE TITLE
Pull error on OS X with DNSCrypt

### ISSUE THREAD

**Issue by prusayn** [kitematic/kitematic#944]
"Error while pulling image: Get https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images: dial tcp: lookup index.docker.io on 127.0.0.54:53: read udp 127.0.0.54:53: connection refused"

Kitematic on OS X, installed DNSCrypt. When I disabled DNSCrypt everything is working fine.

**Comment by FrenchBen** [comment]
Are you behind a proxy? It looks like the docker.io site is mapping to a localhost IP which shouldn't be the case.

**Comment by moloch--** [comment]
I have the same problem

```
➜  docker run nginx
Unable to find image 'nginx:latest' locally
Pulling repository docker.io/library/nginx
Error while pulling image: Get https://index.docker.io/v1/repositories/library/nginx/images: dial tcp: lookup index.docker.io on 127.0.0.54:53: read udp 127.0.0.54:53: connection refused


➜  nslookup docker.io
Server:		127.0.0.54
Address:	127.0.0.54#53

Non-authoritative answer:
Name:	docker.io
Address: 162.242.195.84

➜  curl https://index.docker.io/v1/repositories/library/nginx/images
[{"checksum": "", "id": "6886fb5a9b8d73b12d842bab8f9a6941c36094c2974abddb685d54c9d99e37da"},
...removed...
```

My guess is Docker doesn't use standard DNS resolution for some odd reason?

**Comment by FrenchBen** [comment]
@moloch-- It should, but the DNS lookup happens in the VM first. If you happen to be behind a proxy or have some slightly customized routing, it seems that Virtualbox looses connectivity. 
If you look in the wiki, there's a quick [how-to DNS](https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#cannot-download-imageconnect) to make sure that your resolve settings allow the images to be downloaded.

**Comment by moloch--** [comment]
Ahh okay, thank you.

**Comment by mchiang0610** [comment]
Merging with #1030
