### ISSUE TITLE
Dockerfile build is failing on COPY command

### ISSUE THREAD

**Issue by AnalogJ** [kitematic/kitematic#945]
Hi,

I have a simple application that I'm trying to build with docker. My dockerfile contains a COPY command, but when it attempts to copy my application code into the Docker image, only the Dockerfile gets added. This kinda makes sense as docker runs inside a VM, but if the Dockerfile gets copied into the VM, why how can I make sure the rest of my project files do as well?

Here's the relevant Dockerfile:

	from ruby:2.1
	maintainer Jason Kulatunga <jk17@ualberta.ca>

	run gem install bundler

	# copy the application files to the image
	workdir /srv/capsulecd
	copy . /srv/capsulecd

	run pwd && ls -alt
	run bundle install --path vendor/bundle

	cmd ["bundle","exec","ruby","test.rb"]

Here's the run log. As you can see, only the Dockerfile exists in the current working directory, while the application actually has may other files

	Deploying 'Deployment: Dockerfile: Dockerfile'...
	Building image...
	Step 0 : FROM ruby:2.1

	.. snip ..
	 
	Step 3 : WORKDIR /srv/capsulecd

	 ---> Using cache

	 ---> 5b1be6ee1aba

	Step 4 : COPY . /srv/capsulecd

	 ---> 05471a157c93

	Removing intermediate container 1bff59b4b257

	Step 5 : RUN pwd && ls -alt

	 ---> Running in 3d8d06205d36

	/srv/capsulecd

	total 12
	-rw-r--r-- 1 root root  274 Aug 16  2015 Dockerfile
	drwxr-xr-x 2 root root 4096 Aug 16 09:45 .
	drwxr-xr-x 3 root root 4096 Aug 16 09:45 ..

	 ---> 7612ef3fdc60

	Removing intermediate container 3d8d06205d36

	Step 6 : RUN bundle install --path vendor/bundle

	.. snip ..

I'm not sure how to fix this.

**Comment by FrenchBen** [comment]
#close - This seems to be a Dockerfile/Docker issue. Please only create issues for Kitematic here.

**Comment by AnalogJ** [comment]
uh. This is definitely related to Kitematic and not a docker/dockerfile specific problem. If i build the image manually on a linux machine (without using kitematic) everything works fine, its a fairly simple command. 

If anything this is a problem with the way that kitematic interacts with boot2docker, and however the current Dockerfile is being copied/mounted into the VM, the current folder should be as well.

**Comment by FrenchBen** [comment]
How are you 'making' kitematic build this image?

Is there a github repo with the entire project files? If I made a copy of your Dockerfile in a local dir, only the Dockerfile would be copied, since that's the only thing that exists in that dir.

**Comment by mchiang0610** [comment]
@AnalogJ Thanks for reporting. Are you using docker build through Kitematic's open in CLI? Kitematic uses Docker Machine (which uses boot2docker).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (112/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:40868 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYnX-002CYN-1U
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:36:08 -0500
Date: Fri, 11 Sep 2015 17:36:10 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442018170;
	bh=8yTDVzCNZ+wn7fvN94ysRYJtt/Rs2wCREUUAqn4DFV0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=RpTCnU3aD3xXqBMTGACk/EkhufIbsmHCs0sj+qMR/qQwRhFXJ2ebTdswGuSOKAwJf
	 CerMTRq+0L8dj5aXqoWFR17EPs8OzjbKM7pkXmdDXgBkzl8t6M/CvQWnpWI8C23+Mj
	 bW/1rmx3YaSGxC0rn6H5pi4d/DhiLOh6gRHL8UgA=
