### ISSUE TITLE
Failed to install Wordpress with kitematic

### ISSUE THREAD

**Issue by wkoszek** [kitematic/kitematic#946]
I got rid of boot2docker. I installed DockerToolbox-1.8.1b.pkg. The Docker Terminal seems to work OK. I went and gave the Kitematic the try however. Installing Ghost was flawless and I was able to access it from the browser. Then I tried Wordpress. It failed. Errors are below.

issing WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP environment variables
  Did you forget to --link some_mysql_container:mysql or set an external db
  with -e WORDPRESS_DB_HOST=hostname:port?
error: missing WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP environment variables
  Did you forget to --link some_mysql_container:mysql or set an external db
  with -e WORDPRESS_DB_HOST=hostname:port?
error: missing WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP environment variables
  Did you forget to --link some_mysql_container:mysql or set an external db
  with -e WORDPRESS_DB_HOST=hostname:port?

**Comment by FrenchBen** [comment]
#close - duplicate of https://github.com/kitematic/kitematic/issues/947

**Comment by wkoszek** [comment]
My understanding is that this is a different problem: Wordpress has a dependency, but Kitematic can't figure it out, so it errors out. Since Wordpress needs MySQL, on "Create", I'd expect Kitematic to ask me to install MySQL automatically and get these environment variables right.

In other words: Kitematic experience isn't complete if I have to be jumping back and forth between GUI and the command line to bootstrap it.

**Comment by FrenchBen** [comment]
Same as #947; it is assumed that the developer will read the documentation associated with the container and that all requirements will be met. 

As you can see on the hub there are countless images and ways to set something up, relying on Kitematic to determine the dependencies is difficult.

**Comment by FrenchBen** [comment]
For example, you could determine that this image is a better setup for you, as it has everything built-in:
https://hub.docker.com/r/tlongren/docker-wordpress-nginx-ssh/

**Comment by wkoszek** [comment]
Just letting you know about my experiences: Wordpress was a random choice of something I knew has dependencies.

I think the summary of the problem is: Kitematic just wraps Docker command line, not Docker Compose, and thus it's unaware of further needs of the container.

Would be nice to see us wrapping and presenting Docker Compose recipes instead of raw images.

**Comment by FrenchBen** [comment]
I see what you're saying, and you are correct that there is no 'magic' behind Kitematic, just a helper for docker command line. 
Docker Compose is a feature requested often - I actually created a PR to make this happen:
https://github.com/kitematic/kitematic/pull/898

**Comment by wkoszek** [comment]
Talked to @FrenchBen and we discussed technical problems. Looks like there's no good way to solve this problem with Docker metadata, so I guess it makes sense to close this as "never fix"

**Comment by wkoszek** [comment]
.
