### ISSUE TITLE
Failed to install mysql with kitematic

### ISSUE THREAD

**Issue by wkoszek** [kitematic/kitematic#947]
I tried to spin containers based on some of the kitematic's images after I installed DockerToolbox-1.8.1b.pkg today. PostgresSQL installation was fine. MySQL failed. Same with MariaDB. Errors:

atabase is uninitialized and MYSQL_ROOT_PASSWORD not set
  Did you forget to add -e MYSQL_ROOT_PASSWORD=... ?

**Comment by FrenchBen** [comment]
As indicated by the logs and shown in the documentation (https://hub.docker.com/_/mysql/), you need to create an environment variable of `MYSQL_ROOT_PASSWORD` - This can be done in Kitematic under the 'Settings > General' tab. 

ps: the title of your issue is misleading as the install worked since you can see the logs - Starting it is where you're experiencing issues, which the above will fix.

**Comment by wkoszek** [comment]
This looks like a problem in Kitematic. If there's any requirement to get stuff set, I'd expect Kitematic to ask me to input it. Could we throw a popup so that I can configure this environment variable at container setup time (maybe after hitting "Create")?

If not, can you at least throw a warning "footer" with a link to documentation of the image?

**Comment by FrenchBen** [comment]
@wkoszek I would normally agree with providing some feedback, but there is no way Kitematic can account for any requirements detailed in the documentation. 

IMHO It's assumed that a user will read the documentation pertaining to the container they are trying to create/use and that the software shouldn't be in charge of these requirements. 

It's similar to opening/starting a car without a key; the vehicle doesn't tell you that a key is missing, you have learnt that to open/start a car you need a key. (although new keyless start message to be better at this)

**Comment by wkoszek** [comment]
@FrenchBen so basically you're saying you don't know upfront what to ask for? I've looked at the mysql Dockerfile and I feel like you don't have enough metadata?

I like the car analogy :-) But to me it's like I ordered a TV and it got shipped to me, but without necessary cables.

**Comment by wkoszek** [comment]
@FrenchBen So translating it to your view: you're saying that you have no metadata in Dockerfile

**Comment by FrenchBen** [comment]
@wkoszek if you want to join Gitter, I'd be happy to chat :) - As you mentioned there isn't much in the Dockerfile that explains that MySQL is required for this image to work. 

Additionally Kitematic just hands off the workload to the docker client (aka similar to you running docker pull manually in a terminal) - As mentioned before I've opened up the discussion to have that be part of the Dockerfile, which may help Kitematic connect all the dots. 

To your TV analogy, you would still need to know that the TV cables need to be plugged in - How would you know to do that?

**Comment by wkoszek** [comment]
We talked about adding a help screen to overcome the problems with the parameters. Similar to other issues: Docker doesn't provide enough metadata to give the UI enough feedback on what to ask for, so I guess we should close it as "never fixed"
