### ISSUE TITLE
New Install of Toolbox on Mac OS 10.10.5 unable to launch VM

### ISSUE THREAD

**Issue by simphoukham** [kitematic/kitematic#948]
Hi Everyone,  

I recently installed the new Docker Toolbox 1.8.1b.pkg on my Mac.  After running the installation I get this error.  I assume others have seen this issue.  I did not find a similar issue when googling for it.

/Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users/<redacted>/.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed.

Machine default already exists in VirtualBox.
Starting machine default...
exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


host is not running
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com

default is not running. Please start this with docker-machine start default
bash-3.2$ 

Has anyone seen and solved this problem?  I cannot start the default.vm in VirtualBox either. I get the following error message.

Failed to open a session for the virtual machine default.

Failed to load VMMR0.r0 (VERR_VMM_SMAP_BUT_AC_CLEAR).

Result Code: NS_ERROR_FAILURE (0x80004005)
Component: ConsoleWrap
Interface: IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

**Comment by mchiang0610** [comment]
@simphoukham Thanks for reporting. It seems like there may already be a virtual machine called "default" in your virtualbox. 

If it's possible to remove, can you try removing that VM by doing "delete all files" within Virtualbox, and then restarting either quickstart app or Kitematic. 

Thanks!

**Comment by simphoukham** [comment]
Thank you for the response.  I thought that was the case.  However, I see only one “default” vm in my virtual box.  I’ve deleted the VM and reinstalled the toolbox and get the same error message.

**Comment by simphoukham** [comment]
Hi Kitematic Team,

I found the error to be with the new VirtualBox 5.0.2 update for Mac.  I reverted back to 5.0 and it works.

Thank you

**Comment by mchiang0610** [comment]
@simphoukham Thanks for that data point. We are still unsure whether or not it was an error with 5.0.2 because some times if you just reinstall VirtualBox again, it works. (Need to get more data points on this). 

I'm glad it's working for you now though! Appreciate it! 

Thanks,
Michael Chiang
