### ISSUE TITLE
Unable to remove containers in Kitematic

### ISSUE THREAD

**Issue by sabuva** [kitematic/kitematic#952]
Unable to remove container. Please help removing the container.

Error:

ETIMEDOUT
ETIMEDOUT
connect
192.168.99.100
2376

**Comment by FrenchBen** [comment]
@sabuva How are you trying to remove the container?

**Comment by sabuva** [comment]
Hi,

I was able to remove the containers after I re-started my mac computer and
re-tried the operation. Thanks. You may close the ticket now.

Regards

*Sabu Nair** | IT  Mgr*
W ☎ (510) 713-4798 | M ☎: (510) 224-7927

**Comment by FrenchBen** [comment]
@sabuva Thanks for the feedback - This you opened this issue, you can actually hit the 'Close' button below :+1:
