### ISSUE TITLE
Local volumes are missing

### ISSUE THREAD

**Issue by bettyjunod** [kitematic/kitematic#953]
<img width="968" alt="screenshot 2015-08-18 14 21 05" src="https://cloud.githubusercontent.com/assets/10804749/9343065/7d1e9fde-45b4-11e5-8d85-4e911eb0f8a9.png">

**Comment by FrenchBen** [comment]
Just created one from the latest and got the volumes - What did you do differently then clicking 'Create'?
![hello-world](https://cloud.githubusercontent.com/assets/3965324/9360538/cabce6aa-4664-11e5-9764-70a31df0b395.png)

**Comment by mchiang0610** [comment]
@bettyjunod @FrenchBen There was a version of Kitematic that had this bug. It was fixed.
