### ISSUE TITLE
Kitematic cannot connect to VirtualBox during install / setup

### ISSUE THREAD

**Issue by bettyjunod** [kitematic/kitematic#954]
<img width="974" alt="screenshot 2015-08-18 14 36 04" src="https://cloud.githubusercontent.com/assets/10804749/9343390/871f153e-45b6-11e5-94d9-41a653fd589c.png">

**Comment by Regner** [comment]
I had this issue the first time I installed from the new Docker toolbox. My problem was I already had VirtualBox installed but didn't tell Docker toolbox NOT to install VirtualBox. Easiest thing for me was just to remove both VirtualBox and the toolbox and reinstall.

**Comment by bettyjunod** [comment]
Yeah I removed everything and tried reinstalling - that's when I got this issue :(

**Comment by wmgeorge** [comment]
Having same problem, same error. Seems when machine restarts if gets new IP address and certs are all goofed up, mine keeps changing from IP:192.168.99.100 to .101

**Comment by FrenchBen** [comment]
@wmgeorge @bettyjunod Can you both try to remove any existing VMs prior to re-trying the setup?
`which docker-machine`   (confirm it's installed in the `/usr/local/bin/docker-machine` so all commands below work)
```bash
docker-machine ls
docker-machine rm <machine name from above>
```
example:
`docker-machine rm default`

Then try to run kitematic again and let it setup the machine.

**Comment by mchiang0610** [comment]
Merging with #1029
