### ISSUE TITLE
BUG:  Kitematic 0.8.2 (BETA) - pane for centos:5 throws 500 error

### ISSUE THREAD

**Issue by ectopunk** [kitematic/kitematic#955]
While trying to start centos:5 with Kitematic 0.8.2.

![screen shot 2015-08-18 at 5 14 27 pm](https://cloud.githubusercontent.com/assets/8877641/9346060/a2ca086e-45cc-11e5-9101-71a622874590.png)

**Comment by FrenchBen** [comment]
The container seems to have been 'updating' - What parameters did you change that caused this issue?
Also what image did you use? I can't seem to find a matching 'centos:5' image - Kitematic only shows 'centos:5.11'.

**Comment by mchiang0610** [comment]
Merging with #1030
