### ISSUE TITLE
Kitematic fails to start with "Segmentation Fault: 11"

### ISSUE THREAD

**Issue by thomasshanks** [kitematic/kitematic#956]
When I attempt to run Kitematic from Finder, the icon bounces for one second and disappears.  When I attempt to start it from the terminal, I get:

myhostname:MacOS tshanks$ ./Electron 
Segmentation fault: 11
myhostname:MacOS tshanks$ 

In the log, I have-

8/18/15 9:30:34.039 PM ReportCrash[4697]: Saved crash report for ReportCrash[4696] version 418 to /Users/myusername/Library/Logs/DiagnosticReports/ReportCrash_2015-08-18-213034_myhostname.crash

That crash report contains:

Process:         ReportCrash [4696]
Path:            /System/Library/CoreServices/ReportCrash
Identifier:      ReportCrash
Version:         418
Code Type:       X86-64 (Native)
Parent Process:  launchd [154]
User ID:         501

Date/Time:       2015-08-18 21:30:33.688 -0700
OS Version:      Mac OS X 10.8.5 (12F2560)
Report Version:  10
Sleep/Wake UUID: 48513EEE-BCF8-4E30-B774-8FEFAA928582

Crashed Thread:  7

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007ffab6400000

VM Regions Near 0x7ffab6400000:
    MALLOC_TINY            00007ffab4800000-00007ffab6400000 [ 28.0M] rw-/rwx SM=PRV  
--> 
    STACK GUARD            00007fff58c71000-00007fff5c471000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0

Application Specific Information:
Analyzing process: Electron[4695], path: /Applications/Docker/Kitematic (Beta).app/Contents/MacOS/Electron; parent process: bash[4646], path: /bin/bash
 
Thread 7 Crashed:
0   libsystem_c.dylib             	0x00007fff8e229408 strcpy + 104
1   com.apple.CoreSymbolication   	0x00007fff882e6c00 0x7fff8828b000 + 375808
2   com.apple.CoreSymbolication   	0x00007fff88294154 0x7fff8828b000 + 37204
3   com.apple.CoreSymbolication   	0x00007fff882c601f 0x7fff8828b000 + 241695
4   com.apple.CoreSymbolication   	0x00007fff882922ad 0x7fff8828b000 + 29357
5   com.apple.CoreSymbolication   	0x00007fff88291d4c 0x7fff8828b000 + 27980
6   com.apple.CoreSymbolication   	0x00007fff882bdc88 0x7fff8828b000 + 208008
7   com.apple.CoreSymbolication   	0x00007fff8828dfbe 0x7fff8828b000 + 12222
8   com.apple.CoreSymbolication   	0x00007fff8828df3e 0x7fff8828b000 + 12094
9   libsystem_c.dylib             	0x00007fff8e23b772 _pthread_start + 327
10  libsystem_c.dylib             	0x00007fff8e2281a1 thread_start + 13

I just installed it today, so I should have the latest version.  I'm running on Mac OS X 10.8.5.

**Comment by FrenchBen** [comment]
Was this installed from the Toolbox?
I was able to start both without issues using the Toolbox intaller

**Comment by thomasshanks** [comment]
Yes, I used the latest toolbox installer.

**Comment by mmickelson** [comment]
I have this same issue, also using Mac OSX 10.8.5. I don't know the exact steps to start it from the terminal but this sounds like the same thing. I also downloaded the toolbox today and installed normally.

Is there any requirement to stop any existing docker-machines? I played with some tutorials prior to trying to open Kitematic.

**Comment by thomasshanks** [comment]
In my case, this was the first installation of VirtualBox and of docker-machines on this machine.

**Comment by mchiang0610** [comment]
Merging with #1029
