### ISSUE TITLE
Can't remove containers which failed to install

### ISSUE THREAD

**Issue by wkoszek** [kitematic/kitematic#958]
I got #957, and afterwards I went and removed old containers. My MySQL I can't remove, but it's present in the GUI:

![image](https://cloud.githubusercontent.com/assets/483344/9361830/2eb191e6-4652-11e5-8d2d-8825f824900a.png)

**Comment by mchiang0610** [comment]
@wkoszek Thanks for reporting. Does this happen after you have restarted Kitematic? I'm having trouble reproducing this on my end.

**Comment by mchiang0610** [comment]
Merging with #952
