### ISSUE TITLE
postgreSQL local folder

### ISSUE THREAD

**Issue by solisoft** [kitematic/kitematic#963]
Hi,

I have this error while linking data folder to a local folder on my windows 10.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
LOG:  could not link file "pg_xlog/xlogtemp.19" to "pg_xlog/000000010000000000000001" (initialization of log file): Operation not permitted
FATAL:  could not open file "pg_xlog/000000010000000000000001": No such file or directory
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
creating template1 database in /var/lib/postgresql/data/base/1 ... 

Any idea? MariaDB and Redis works fine though !

**Comment by FrenchBen** [comment]
Are you mounting the Volume to a local folder for the postgre container? 
Windows should allow full read/write on the folder, unless windows 10 does something different?

**Comment by mchiang0610** [comment]
seems like a particular problem with the image.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (102/100 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:52249 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYkU-001x0e-VV
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:33:00 -0500
Date: Fri, 11 Sep 2015 17:33:02 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442017982;
	bh=qVPXE0i0k1S5FHAvZ8iPJeZ5zFuTaF1OfizU9YfvHcU=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=tjnhV2IwBkP2086yrR9hEJVuyrZzBNiXBE1qaGX6I8b6mXP4vpmTTI2iM3tbhf1No
	 eMs7FrOpw6UgVHRwdtlyOqJIfrSrhcqBE2hk6w0xbrpUELptcad0ok6Jha7C/ffWzP
	 H5+L5qwfP/gtgeJDYUpjkYPQT5wb26+pkPk5H5GI=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (103/100 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:28923)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaYkW-001x93-Ne
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:33:02 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Ba7vpHLp5+0v38Z+XtGA2I7wBwE=; b=JFeASoyslPZE13aQ
	G66jh0wfqUGktj4NW7SOa4/66l0R4GbUwOD/Ud+cy0jCrQ0smwZ0L8PYR2EMmuZd
	nJkiqzE5aM3tbGW8wLWNnliX0aF5D0KVam01CXqKYOnez8+P0pX2HiNcyGNGiDaC
	eXRqFeFvkwdBJNcDJSnRkPn4QnA=
Received: by filter0663p1mdw1.sendgrid.net with SMTP id filter0663p1mdw1.10090.55F372BE16
        2015-09-12 00:33:02.484893778 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id uFc4ThLyQQGrkgHmfEo6Sw
	for <greg@biomassiv.es>; Sat, 12 Sep 2015 00:33:02.475 +0000 (UTC)
Date: Fri, 11 Sep 2015 17:33:02 -0700

**Comment by vandamon** [comment]
I have the same problem on Windows 10, trying to mount a Windows directory to /var/lib/postgresql/data.

`
creating template1 database in /var/lib/postgresql/data/base/1 ... LOG:  could not link file "pg_xlog/xlogtemp.22" to "pg_xlog/000000010000000000000001": Operation not permitted
FATAL:  could not open file "pg_xlog/000000010000000000000001": No such file or directory
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
`

I am trying this with the latest [Postgres image](https://hub.docker.com/_/postgres/)  and my Docker version is: ```1.9.1```

I have given read/write permission to 'Everyone' on the Windows directory that I am trying to mount.

**Comment by FrenchBen** [comment]
@vandamon I believe this is an issue with the way volumes are mapped in Virtualbox and their ownership. 
For a possible solution, checkout the Docker for Windows Beta here: beta.docker.com

**Comment by stanpalatnik** [comment]
@FrenchBen It's invite only, so "possible solution" feels like a strong word :>

**Comment by FrenchBen** [comment]
@stanpalatnik who says I can't invite you? :P

**Comment by stanpalatnik** [comment]
@FrenchBen I'd take that

**Comment by robvelor** [comment]
This is also happens on windows 7 with the official postgres image (9.5.2).

**Comment by kadrach** [comment]
And the docker beta is win10 only, not a solution :(

**Comment by oerd** [comment]
Having the same exact problem on Win8 x64 with Kitematic & docker 1.11.2

**Comment by derMart** [comment]
same here on win7 + docker 1.11.2
