### ISSUE TITLE
kinematic latest no run to mac OS X 

### ISSUE THREAD

**Issue by fusengine** [kitematic/kitematic#966]
to run ton mac OS X sur download https://www.virtualbox.org/wiki/Testbuilds virtual box 5.0.3 is good run  :+1:

**Comment by FrenchBen** [comment]
@fusengine 
Tu peux donner si possible (pour aider les autres):
* OSX Version:
* Kitematic Version:
* Docker Version:

Merci!

**Comment by mchiang0610** [comment]
@fusengine @FrenchBen Thanks for the notice. We will test with 5.0.3, and will update to it if it's good.
