### ISSUE TITLE
cannot connect to hello-nginx

### ISSUE THREAD

**Issue by wwkoon007** [kitematic/kitematic#967]
cannot connect to hello-nginx

**Comment by FrenchBen** [comment]
@wwkoon007 Can you take a screenshot of the issue you're having?
Did you try to [update your DNS](https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes#cannot-download-imageconnect) settings?

**Comment by mchiang0610** [comment]
Merging with #1030

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (124/100 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:44597 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYDS-0003oF-BG
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:58:51 -0500
Date: Fri, 11 Sep 2015 16:58:53 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442015933;
	bh=c1eNmpLjRqpNz+O/9KrOa96m98BJr1+9H93FYL6XnKI=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=RN3jNDWzCNDB1LVlER2zsZ+VY4Gd6ljzTCtaP34YHAv+9l7vS4Kif3l6F2rJZguCb
	 cd8Cf8KqEQtTcm50MZQbBY4XYXlgf8Z1SkOu0bf9GgdXaei1ZpXeP0HLjkHSVXCAI8
	 sfOFP2WjQCIS37MGIczPiZB+N7pYWDofXyP87oKA=
