### ISSUE TITLE
container name appears in the right panel, but can not be deleted

### ISSUE THREAD

**Issue by casraz** [kitematic/kitematic#969]
container name appears in the right panel, but can not be deleted. When press the `X` button as an attempt to remove the container name, the following msg is displayed:

no such container
404
no such id: sleepy_bhabha

**Comment by mchiang0610** [comment]
@casraz Thanks for reporting. Does this still happen if you restart Kitematic?

**Comment by mchiang0610** [comment]
This appears to be the same issue as #958. Merging the issue. Please comment there. Thank you!
