### ISSUE TITLE
ETIMEDOUT error when downloading images 

### ISSUE THREAD

**Issue by AlexCollin** [kitematic/kitematic#970]
Looking for my screenshot 
![2015-08-23 18 47 16](https://cloud.githubusercontent.com/assets/2717621/9428928/8c65bc0e-49c7-11e5-969a-f5a92c13c891.png)

**Comment by mchiang0610** [comment]
@AlexCollin This seems like a network issue. Are you currently connected through a proxy? Please check your internet connection as well. 

Thanks!

**Comment by csrui** [comment]
I'm having the same type of issues and there's nothing wrong with my network.

I specifically get the following (although I can open the url by hand).

```
Network timed out while trying to connect to https://index.docker.io/v1/repositories/eboraas/laravel/images. You may want to check your internet connection or if you are behind a proxy.
```

**Comment by AlexCollin** [comment]
Ok ok. Im then know

**Comment by AlexCollin** [comment]
Try this again after switching-on you internet connection or successfully resolve dns names

**Comment by mwillerich** [comment]
same here, a minute ago. Both Kitematic and the CLI give me this error, but I can `curl` the same url successfully in the CLI. Weird.

**Comment by mwillerich** [comment]
Ah magic. An hour later and it works. Another example of not learning at all what went wrong.

**Comment by anggun-indra** [comment]
i still getting the error

**Comment by FrenchBen** [comment]
@anggun-indra what version of Kitematic are you using?
