### ISSUE TITLE
create new container nginx-php error

### ISSUE THREAD

**Issue by kirillus** [kitematic/kitematic#972]
server error
500
error creating aufs mount to /mnt/sda1/var/lib/docker/aufs/mnt/7fb694a78220f99f2c72c328a61df21be04e5423ec02eccb22fab64c5ca2bf8a-init: invalid argument

**Comment by kirillus** [comment]
![kitematic](https://cloud.githubusercontent.com/assets/5607779/9472930/151b6a94-4b26-11e5-98f1-642f72f393c1.png)

**Comment by FrenchBen** [comment]
Can you share the 'About' screen so that we know the version of software you have.

**Comment by kirillus** [comment]
<img width="660" alt="kitematic" src="https://cloud.githubusercontent.com/assets/5607779/9477425/35d00924-4b40-11e5-870d-0cb95e3da36e.png">

**Comment by FrenchBen** [comment]
It looks like your rails container was created without any issues, correct?
Can you delete the nginx-php container and see if you can re-create it?

Also can you share your logs? `.docker/machine/machines/default/default/Logs/Vbox.log`

**Comment by kirillus** [comment]
ok, figured out. I have deleted all machines from .docker/machine/machines/ (defaults/  ,  dev/) and downloaded again. Thanks

**Comment by FrenchBen** [comment]
Glad you were able to solve this, although it's unfortunate you had to remove all of your VMs for that to happen. 
From your description it sounds like you had previous versions installed, which may have caused some of those issues. 

In the future, you can always check the VMs installed or remove them via:
`docker-machine ls`
`docker-machine rm <vm-name>`

**Comment by mchiang0610** [comment]
Merging with #1030

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (122/100 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:43518 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYDF-00039B-6W
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:58:38 -0500
Date: Fri, 11 Sep 2015 16:58:40 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442015920;
	bh=M2+U/nAFPt8IywzygcVHs9wYrNX9tZZuh+FeNJJyOM0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=iMU2bwk6+/sh20gjEngghvpGs3dUMX4yb9zBlqd3sejgD+hmO+pwPp74+Y/KWmUWG
	 ZD9Im/KzY7ICNBIqOrVelkk6hkJlYt8enoUT99VUsTjMBpF+V+znGeRzBrGyD1yncF
	 2+RmJn4J+sfBX/6h4NudalR3N43mp25HPYUw/9S4=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (123/100 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:51905)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaYDG-0003CW-Dk
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:58:39 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=ulMn/1H5hpQXOjtQx3F5SLrQWbc=; b=VbDV0vSJCItFPMSh
	zLczjPAZM5bGvEHc9funvR+pYEwDTJ8GGd2OCRg2KeBPPuLRl52PJ0u4B9LQeJJT
	999IBVooOd/RcIqXJZTHynmcta1Z66bf/5cYFTOnZyRL+4dRixwgjMGKRawc3eBP
	V51MugqZfLibJfo4QHDLFT7EZM0=
Received: by filter0858p1mdw1.sendgrid.net with SMTP id filter0858p1mdw1.16042.55F36AB01A
        2015-09-11 23:58:40.481969608 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id I3rQ8ioqQ92ziCF8axSwJA
	for <greg@biomassiv.es>; Fri, 11 Sep 2015 23:58:40.596 +0000 (UTC)
Date: Fri, 11 Sep 2015 16:58:40 -0700
