### ISSUE TITLE
Tag latest not found

### ISSUE THREAD

**Issue by gsimpson1130** [kitematic/kitematic#973]
Tag latest not found in repository docker.io/dnvriend/fuse

**Comment by FrenchBen** [comment]
#close - this is a known issue if you try to pull an image where the 'latest' tag doesn't exist. 
If you look at the docs, link under tags, you'll see it doesn't exist:
https://hub.docker.com/r/dnvriend/fuse/tags/

as a side note, the same thing would happen if you ran a `docker pull dnvriend/fuse`

**Comment by mchiang0610** [comment]
Merging with #572

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (107/100 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:48416 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaY6n-0049D5-3y
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:51:58 -0500
Date: Fri, 11 Sep 2015 16:52:00 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442015520;
	bh=tjxlWf0hGnUs0GGXPAvbNAwC5VVnM/aJIkduoQA21i4=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=icgI6TI8ubPsNtsaQClPHI91oRgw4qLTTEHA0ZQoK2YwdgmslAEskA0fL/sUPT/MF
	 NUe8HncoE3OqlTDZOSGM+2icQwFHmsoSDLbliUXuZrKgxG52fK+9ymMU6qaDe1+CBt
	 yTjby9lU9uX6Qb1+rBrFje5RhSYyd3FnXM1vcss8=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (106/100 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:20593)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaY6m-0049AD-KN
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:51:58 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=/Eg1Wq3/kR/K5uffZe699ht10G0=; b=Kj3nqtnIDGx61nLD
	TOUnqnswJXAuMQmcwb/RsGeTVw03D6L3pTREM1jqeJHVVpz19BVZlFxIBM9QyL2r
	KFVuwpDA9DGq7XQimNyPLjYwkalEpo6RFKCSp1NSrhDmdoDU2uB+lEkRKivlCoiP
	Zlc1xS0G8Plbw2xRki4q/zvGYQo=
Received: by filter0467p1mdw1.sendgrid.net with SMTP id filter0467p1mdw1.27475.55F3691F3
        2015-09-11 23:51:59.166567689 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id bYO-z8HcQxqEN8NBqsBRTA
	for <greg@biomassiv.es>; Fri, 11 Sep 2015 23:51:59.249 +0000 (UTC)
Date: Fri, 11 Sep 2015 16:51:59 -0700
