### ISSUE TITLE
Invalid Header

### ISSUE THREAD

**Issue by gsimpson1130** [kitematic/kitematic#974]
Error pulling image (latest) from docker.io/jazinner/fuse, Untar re-exec error: gzip: invalid header: output:

**Comment by FrenchBen** [comment]
can you provide the full error output, it looks like your message was truncated.

**Comment by mchiang0610** [comment]
@gsimpson1130 seems like an issue with that particular docker image.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (108/100 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:51648 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaY79-004AKJ-Sb
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:52:21 -0500
Date: Fri, 11 Sep 2015 16:52:23 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442015543;
	bh=1fdhWTLklMjqB99GQ7H4bMVrCsRJCEjIHRFZAEqqCi0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=R+tm2rtP27lLPbKjTI08xk+/1HcXpDvcJTcWJWsE6VQ3wAH/u4QGSMdIkHMjTs52B
	 KPl8mk7k3AEwTSF9IDK5ijlCaRQDREU4aCUT1NPrUmHFSF5E2Cy6psOnO4fnMmZpKR
	 JBz+yIYM4XkSiaen3QDZ4JZxGhxkgcMTB6e0FqbA=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (109/100 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:17728)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaY7B-004AMR-8S
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:52:22 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=0/Cx261fCQ9m5B1uVLiACl2jsIM=; b=xKMXs7eCmFd+9iZK
	7bbiQkOezsQL6n0tgah1p4IfV0VplUwxnWhQPf1uHW165JpN8pQJsvm0pODxPO9t
	7iHCzBJ9apzIAi/6Y4VI/nE3GcVh5jicE51+Kqoxw29NoqxfHD5vK7HIlITEGrbF
	d8Tli8Wxwa9KokabJhHqM5j7MMA=
Received: by filter0853p1mdw1.sendgrid.net with SMTP id filter0853p1mdw1.32379.55F3693715
        2015-09-11 23:52:23.349312105 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id 7icJS8fnT-iqzaPs8-7aLg
	for <greg@biomassiv.es>; Fri, 11 Sep 2015 23:52:23.421 +0000 (UTC)
Date: Fri, 11 Sep 2015 16:52:23 -0700
