### ISSUE TITLE
server error 500

### ISSUE THREAD

**Issue by fusengine** [kitematic/kitematic#975]
but i go to run my container this is not run and print this =>

<img width="565" alt="capture d ecran 2015-08-26 a 23 39 58" src="https://cloud.githubusercontent.com/assets/7295655/9507038/cde96064-4c4b-11e5-89f7-65a6d61233d4.png">

**Comment by FrenchBen** [comment]
Did you create 2 containers with the same 2 ports bind? Kitematic uses random ports to prevent this from happening - Port 88 wouldn't be one of them.

**Comment by fusengine** [comment]
no sure
but i stop this and i start this container print this error j'allucine

**Comment by fusengine** [comment]
@FrenchBen kitematic est très nul

**Comment by FrenchBen** [comment]
@fusengine Si tu veux te mettre sur Gitter on peut discuter tes problèmes. Tu es un des premiers a avoir autant de soucis. 

As-tu customisé qqchose de special?

**Comment by fusengine** [comment]
non rien mais je pense faire de mauvaise manipulation excuse moi j'ai résolut mon problème.

**Comment by FrenchBen** [comment]
De rien - Par curiosité pourrais-tu partager tes mauvaises manip et la manière dont tu as résolu le problème?
Ca peut sans doute aider qq'un d'autres?

**Comment by fusengine** [comment]
c'était des erreur de port que j'avais fais j'avais supprimer un conteneur et remis le meme port du coup interférence @FrenchBen

**Comment by FrenchBen** [comment]
:+1: En effet ca peut creer qq problemes. Peux-tu fermer l'issue?

**Comment by fusengine** [comment]
Oui chef

**Comment by FrenchBen** [comment]
Merci!
