### ISSUE TITLE
Cannot kill container golang 

### ISSUE THREAD

**Issue by jy03189211** [kitematic/kitematic#982]
Container cede1903123d07d2b9d709103cdbc5f07bd2ecf91905c55ccb629b198e1c799a is not running

**Comment by FrenchBen** [comment]
@jy03189211 
* What did you try?
* What happened?
* What did you expect?

**Comment by jy03189211** [comment]
I uninstalled the kitematic. But I cannot run it properly after reinstalling it for warning as follows:
 "You will want to check the provider to make sure the machine and associated resources were properly removed."

**Comment by FrenchBen** [comment]
Did you install it via toolbox?
If you need to reset the setup, there's a pretty handy script found here:
https://github.com/kitematic/kitematic/blob/master/util/reset

**Comment by jy03189211** [comment]
when I run the program like "./reset.sh" it gave me"command not found" error for the final line of the script
is "$DIR/VirtualBox_Uninstall.tool" in  a runnable command? I think it's only a path

**Comment by FrenchBen** [comment]
The reset was part of the util directory - If you look at that directory 'https://github.com/kitematic/kitematic/tree/master/util' you'll see that the VBox uninstall tool is there. 

I don't think that step is needed, since your VBox should be up to date. I would simply re-install it using the [Docker Toolbox](https://www.docker.com/toolbox)

**Comment by jy03189211** [comment]
Yes, I did. But after installing. When I run kitematic during setup, it gives me error all the time "You will want to check the  provider  to make  sure  the machine and associated resources  properly removed"

**Comment by FrenchBen** [comment]
@jy03189211 to clean that up, try:
`docker-machine ls` (should list existing machines, 'default' is more likely in there)
`docker-machine rm default` (if the above didn't return default, but something like dev, just replace it in the command line)

**Comment by mchiang0610** [comment]
@jy03189211 seems like an issue with machine #1029

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (118/100 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:37595 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYCU-00011u-RL
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:57:52 -0500
Date: Fri, 11 Sep 2015 16:57:53 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442015873;
	bh=tNMFGoCNKswG61hvQaZOwqaEjTvHLkSfNkEzPbPwJks=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=uDmWl0tnlshXg69Q0vUBORUJBNOw1+ATVLt6T1T3uUsPXnRTy6wiAr9iw6Xejzaie
	 ZGqgUONIhXrlMSEoOswjwjhLBFwfXSwbKRPBgcxZehxkP0Q+q+zlZTDzxttIc2xonW
	 5yKxlKc49cMq69gK6TBNA+oYS7uYQrM7/3B/c6ss=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (119/100 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:58012)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaYCV-00013J-Pp
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:57:53 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=AS5YdQg8KNc+FQ/63QcRn6lTetI=; b=Qo9v2REfb0Mvn7VY
	HN+F7vNvn56dC+veF2IUArc9IKaDtOWaNo5wHXfp4IFw3+5yf1E6krRLhSWQuE1F
	XR91GoUBQx2xyc7yD2FNltA4ijtwvsXyC2MF0Idr1Nh0Up6shaqNpsJtt/lgTYWF
	06fPdapnEF+1VrxOyX5ajBWjczw=
Received: by filter0806p1mdw1.sendgrid.net with SMTP id filter0806p1mdw1.32688.55F36A812B
        2015-09-11 23:57:53.849758503 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id KLPoyQ7kSnOXMLL1oWUEUQ
	for <greg@biomassiv.es>; Fri, 11 Sep 2015 23:57:53.942 +0000 (UTC)
Date: Fri, 11 Sep 2015 16:57:53 -0700
