### ISSUE TITLE
[Question] Kitematic no longer looks at dev but now default

### ISSUE THREAD

**Issue by rizowski** [kitematic/kitematic#984]
Hi,

I recently installed the docker toolbox. Previously I had kitematic installed. I am fairly new to docker but I can't find any information on this. How can I changed what VM kitematic looks at? I have two VM images currently. `dev` which was installed a few months ago when I installed kitematic by itself. Then there is `default` which was installed today with the new docker toolbox installation.

I read over this #777 Which looks like what I am needing, but I don't want to install a nightly build of kitematic. Now I know before today kitematic used to look at dev, but now it is looking at default. Is there a way to change this with an environment variable or something of the sort?

Thanks

**Comment by mchiang0610** [comment]
@rizowski Hi, sorry about this. 

We made the decision to change to default because it was causing a lot of issues for many Docker users. 

Would it be possible for you to rerun the containers by pulling the images again through the new version? 

Thanks! Again, sorry about what you have to go through.

**Comment by rizowski** [comment]
Well I understand that #777 is being constructed but why isn't VMname property overwritable? Do you know if there are plans to make it overwritable in the future?

In the mean time I might switch back to the older version of kitematic.

**Comment by FrenchBen** [comment]
@rizowski Would the following help if it was merged?
https://github.com/kitematic/kitematic/pull/992

**Comment by rizowski** [comment]
@FrenchBen Yes that looks like it would.

**Comment by FrenchBen** [comment]
Are you familiar with the kitematic build process @rizowski ? If you are, would you mind doing some QA on this PR to confirm it working as expected for you?

**Comment by rizowski** [comment]
I am not, but I assume that it is described in the [Contributing guidelines](https://github.com/kitematic/kitematic/blob/master/CONTRIBUTING.md#testing)?

**Comment by FrenchBen** [comment]
Guidelines are just that, not an actual how-to. I'll get someone from the team to check it out!

**Comment by rizowski** [comment]
Hey @FrenchBen I am just checking up on this issue and hoping for a status on where this is at. :smile:

**Comment by FrenchBen** [comment]
@rizowski It's more than just a QA of the changes - It's also the pro/con on the need to have this and the support that it entails. I'll see if there are any updates.

**Comment by mchiang0610** [comment]
@rizowski sorry about what you have to go through.  Does rerunning the images not work? The reason why we made the decision to change to default is that the impact should be relatively low. 

One major benefit of Docker is its portability, where you should be able to recreate what you had in seconds.
