### ISSUE TITLE
NaN Error while downloading image.

### ISSUE THREAD

**Issue by bizoru** [kitematic/kitematic#987]
![screen shot 2015-08-27 at 7 05 58 pm](https://cloud.githubusercontent.com/assets/417759/9536182/acb17c3a-4cee-11e5-9226-3d047b35e596.png)

Tried to downlad a postgres image and this happened. I've got internet conection, that's a weird issue.

**Comment by mchiang0610** [comment]
@bizoru Thanks for reporting this. Can you try it again? We had some down time today with Hub. 

Closing this for now because this is most likely due to downtime. Please reopen if you are still seeing this issue. 

Thanks,
Michael
