### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by lianghongle** [kitematic/kitematic#988]
Get https://registry-1.docker.io/v1/repositories/library/ubuntu/tags/latest: net/http: TLS handshake timeout.
If this error is invalid, please file a ticket on our Github repo.

**Comment by mchiang0610** [comment]
@lianghongle thanks for filing this. It seems like you are having network issues connecting to Docker Hub. Can you please try again? 

Thanks! 
Michael
