### ISSUE TITLE
Centos Base image error

### ISSUE THREAD

**Issue by hqinnus** [kitematic/kitematic#990]
I was installing a centos bare-metal image to my docker. I encountered error as follows.
Any idea why?

![capture](https://cloud.githubusercontent.com/assets/692001/9542117/a3727040-4da0-11e5-8050-7ca09dcfe196.JPG)

**Comment by mchiang0610** [comment]
@hqinnus this seems like a network issue. Are you connected through VPN / proxy? If not can you try again? 

Thanks!

**Comment by mchiang0610** [comment]
merging with #1030

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (116/100 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:56854 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYBZ-004N6Z-IP
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:56:54 -0500
Date: Fri, 11 Sep 2015 16:56:57 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442015817;
	bh=V/zUqSA0Q/GqelXXJxUpfoajGBjWQX24Uo58NGCvZbU=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=HRkgf7c7cJ+HhbIzJXI3Y+vvojM8A2ruye4OLaAoOyulyqsI7e8yoQlDDM0l0qwAY
	 eM1LWMLySChdQ0ybl3sFFxg5opNG6VzIqJTfE2XpWw/SAv/J3ku3yUR8ABXFsIcsua
	 SLq9gxy9nE77N/u+VFZI3aQvkR9lnAPnZbDfhhow=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (117/100 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:13895)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaYBa-004N6o-Va
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:56:56 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=6iWMSFBQ54RWKG0pUu6RXb8ZX4k=; b=BpQj9goSvy2W99ZJ
	f9+3goXyhlyd8uDoBueXkmC/iYUBKUNzz4xG3KP3XY4VW9ExbPfcYBcmxh5cvCoa
	iLxXJAOJSrlHaLY007HQJ0IELbVpYED/WFETtmQjcoU7lGLoCV7cwrHR946Vzn6k
	iqlRKw+Svdyq2/0mNR+/e2Suc7g=
Received: by filter0414p1mdw1.sendgrid.net with SMTP id filter0414p1mdw1.11711.55F36A488
        2015-09-11 23:56:56.587709854 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id D9XweTPlRxWYVSALhOmyzg
	for <greg@biomassiv.es>; Fri, 11 Sep 2015 23:56:56.780 +0000 (UTC)
Date: Fri, 11 Sep 2015 16:56:56 -0700
