### ISSUE TITLE
Error creating volumes on windows if the user has a space in its username.

### ISSUE THREAD

**Issue by ehvattum** [kitematic/kitematic#991]
When adding a local volume on  windows, one is forced to add one under the users folder. If the user has a space in its username, this causes
```server error
500
Cannot start container nginx: mkdir /c/Users/My\ Name: protocol error```

The username issue is caused on Windows 10 64bit. It is likely this will happen often, as the Windows installation procedure promts you for your Microsoft account, and creates user forlders based on it.

**Comment by mchiang0610** [comment]
@ehvattum Thanks for reporting this.

**Comment by alexandrev** [comment]
Is this still happening? I've been looking at the code last night, and it doesn't seem too dificult to get rid of that error.

**Comment by FrenchBen** [comment]
@alexandrev This is an old issue which has since then been fixed. It is also different from your previous issue, as it deals with spaces in the actual name of the user folder.

**Comment by alexandrev** [comment]
Ok, I only want to know if I could help in that :)
