### ISSUE TITLE
Trying to delete jenkins container

### ISSUE THREAD

**Issue by WieseServices** [kitematic/kitematic#995]
server error
500
Cannot kill container jenkins: Container 46342b0a1c0f9393512f331863437db6470ac48daeca7371f83f7647c8987a3f is not running

**Comment by FrenchBen** [comment]
Is your VM running? I would try to close down the application and try this again.

**Comment by marceldiass** [comment]
It's happen for me too.
I'm using the Mac Version 0.7.6.
I need to start the container and then I can remove it. 

<img width="668" alt="kitematic-error" src="https://cloud.githubusercontent.com/assets/233598/9724651/69f9e62c-55b1-11e5-85a7-bd7579a8931f.png">

**Comment by FrenchBen** [comment]
@marceldiass Kitematic is now up to 0.8.3 which fixes many bugs. I would recommend upgrading via the toolbox: [Docker Toolbox](https://www.docker.com/toolbox)

**Comment by mchiang0610** [comment]
Merging with #1030

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (120/100 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:39492 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZaYCh-0001e7-K1
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:58:04 -0500
Date: Fri, 11 Sep 2015 16:58:06 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1442015887;
	bh=Vp3m/yIV6hXrxrL2iUaOtY7rPnoQ/DeLFDVHUsmKGpc=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=esYblUvOxPapmdmLrRTa+lfWdVG7IdcGuJ5PwiPh0CfUk8ag5akoBnXc1jb0qdC+J
	 Tg9EOy2lWaEkAWjy5W+c2gHSCoimv9LxMqi/rzsmpb961c933tQcf5l6smKVazreTb
	 4Jjq+jdNHJZj13DmwK1raTM9qPi/BYz0jVDw+YBo=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (121/100 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:26490)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaYCi-0001fB-Qc
	for greg@biomassiv.es; Fri, 11 Sep 2015 18:58:06 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=vakoc0WznJkNnfTSwR2N+AFSfGY=; b=MRd8/QvFdiBW7KZY
	aBo1vsBnST/j1B+O8jyPsFbT2LUGhZhobVo/Pf6Cwk28wx4/IY2zUv68Q48IZv+/
	xRzgefH/wnYDdADMhv0zKJA7zvtbmC8hTo/fsLqdK44AXzbUmuiGWVz0BvjqIeYx
	lsaNgigrtIZ7Ab9D9Y8rStacsNE=
Received: by filter0808p1mdw1.sendgrid.net with SMTP id filter0808p1mdw1.31382.55F36A8E25
        2015-09-11 23:58:06.93011544 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id xsWI7A9qQqmfMzYcEyGXAw
	for <greg@biomassiv.es>; Fri, 11 Sep 2015 23:58:06.988 +0000 (UTC)
Date: Fri, 11 Sep 2015 16:58:06 -0700
