### ISSUE TITLE
Downloading image: NaN %

### ISSUE THREAD

**Issue by dnozay** [kitematic/kitematic#996]
* installed Kitematic
* did not login
* try to create (from neo4j:latest if that matters)

<img width="1066" alt="nan" src="https://cloud.githubusercontent.com/assets/205466/9572490/4807be56-4f65-11e5-8166-f2aa5761a243.png">

**Comment by dnozay** [comment]
<img width="1066" alt="version" src="https://cloud.githubusercontent.com/assets/205466/9572568/0bb16e9c-4f66-11e5-915d-c5fd9f2d60ec.png">

**Comment by FrenchBen** [comment]
If there is a loss of connectivity (or hub cannot be reached) it's possible that the download percentage cannot be determined; although it should probably say 0 instead of NaN. #bug

**Comment by dnozay** [comment]
probably connectivity - VM was originally created behind corp network, and I only tried once at home

**Comment by FrenchBen** [comment]
Sounds like it - Unfortunately the VM is a bit tricky with it's DHCP settings, and doesn't do a good job at reconnecting. 
A restart of the VM usually does the trick. Can you close this issue if you haven't had an issue since?
