### ISSUE TITLE
Kitematic won't download image - spinning while trying to connect to dockerhub - which I skipped setup

### ISSUE THREAD

**Issue by dnozay** [kitematic/kitematic#997]
* I do not want to sign in - initially skipped account setup
* I have no intention to sign in (read, I will use private registry)
* quit kitematic (read, closed the application once)
* kitematic will not let me create a container: keeps spinning while "trying to connect"

<img width="1066" alt="connecting to dockerhub" src="https://cloud.githubusercontent.com/assets/205466/9572677/71c05f26-4f67-11e5-8104-444c34b871b2.png">

<img width="1066" alt="version" src="https://cloud.githubusercontent.com/assets/205466/9572680/781cc1b6-4f67-11e5-8711-b77188687b51.png">

**Comment by FrenchBen** [comment]
Are you behind a proxy or changed connection settings while having the VM running? Virtualbox seems to have some connectivity issues if you let it run and go from one network location to another. (aka it can't reconnect properly)

To make sure that kitematic and the VM are reset, within the Preferences, make sure that you have 'Shutdown Linux VM on closing Kitematic' selected and quit the application. (Cmd+Q on a Mac)

**Comment by dnozay** [comment]
yes, the VM gets shutdown when closing Kitematic; I did change locations.

**Comment by mchiang0610** [comment]
@dnozay Are you behind a proxy or VPN? If so it might fail to contact Hub. 

We don't force users to create / sign into hub.

**Comment by mchiang0610** [comment]
Closing by default, please reopen on reply.
