### ISSUE TITLE
When docker-machine use env variable MACHINE_STORAGE_PATH

### ISSUE THREAD

**Issue by skywit** [kitematic/kitematic#998]
Kitematic 初始化项目时无法识环境变MACHINE_STORAGE_PATH，并与docker-machine生成的vms冲突

**Comment by FrenchBen** [comment]
What OS are you on?
docker-machine and Kitematic use the same machine storage location; Kitematic actually uses docker-machine behind the scene.

**Comment by skywit** [comment]
win10

**Comment by mchiang0610** [comment]
@skywit seems like a docker machine problem. Please check out github.com/docker/machine/issues

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (100/100 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:7072)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaYjs-001tmY-Ok
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:32:22 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=e3UCOeFgg7aSt6DMP7ClBT1uqjg=; b=G5A+Nk4ahs/Q+oaz
	jcWjijVcqt/cAw+/63XuVwHiiJwbM2W4O99LGcQ3Z+HcnBcOdbPoNAsM+0F0QPzT
	L247OkiRjajn4xtnIkZI1UiNBaWwMUEy1WgJZVk1zKlxoIdpfWZcJRWct6QnFi3m
	BXQ2+drPPCalkVOSeYhkElsUwGM=
Received: by filter0430p1mdw1.sendgrid.net with SMTP id filter0430p1mdw1.4914.55F372976
        2015-09-12 00:32:23.178148527 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id pNWPke4mRiebfNJ5gnBOqQ
	for <greg@biomassiv.es>; Sat, 12 Sep 2015 00:32:23.157 +0000 (UTC)
Date: Fri, 11 Sep 2015 17:32:23 -0700

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (101/100 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:55282)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZaYjt-001tng-CP
	for greg@biomassiv.es; Fri, 11 Sep 2015 19:32:22 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=+vcUwLNcaWNeJ9FNVCo5Oz//mTs=; b=VeJY1eVdmJJz8NN3
	IrKIsEUMUIJEr0S6rmg+yF1s2eW18AzTk5WpOfLNCY7KJU+8y5mizC/ce+ThjtF4
	iJC4muXSFb36yuM5lNNTjRvc+5sPc7Y9J1sb5qIHBssWZscyLT1n9HgZm77b1MEj
	mOxVtjX4zclSX/WgF+e/nAqvurA=
Received: by filter0523p1mdw1.sendgrid.net with SMTP id filter0523p1mdw1.11250.55F37297E
        2015-09-12 00:32:23.235380867 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id z0OJ9mn9QaeSiq6OVE5Spw
	for <greg@biomassiv.es>; Sat, 12 Sep 2015 00:32:23.228 +0000 (UTC)
Date: Fri, 11 Sep 2015 17:32:23 -0700
